### ISSUE TITLE
[docs] Caveats issue clarification

### ISSUE THREAD

**Issue by DarkGhostHunter** [laravel/octane#101]
I don't think the caveat sections is entirely clear, at least for first comers, when dealing with `register()` and `boot()`, but the examples only use `boot()` and the PHPDoc says "Register any application services.", which should be done in the `register()` method.

Assuming these caveats affect both `register()` and `boot()` methods equally, shouldn't be better to move the examples to the `register()` method? Or the examples are as intended, meaning, registering singletons at booting?

**Comment by themsaid** [comment]
Updated the docs.
