### ISSUE TITLE
http_plugin_serve_http: cannot enable TCP_DEFER_ACCEPT

### ISSUE THREAD

**Issue by NiZerin** [laravel/octane#102]
- Octane Version: 0.1.0
- Laravel Version: 8.36.1
- PHP Version: 8.0.3
- Database Driver & Version: none

### Description:
i use WSL test octane, but it don't work
### Steps To Reproduce:
execute `php artisan octane:start`:
```

   INFO  Server running…

  Local: http://127.0.0.1:8000

  Use Ctrl+C to stop the server


   INFO  error occurred: http_plugin_serve_http: cannot enable TCP_DEFER_ACCEPT: protocol not available, plugin: http.Plugin

   ERROR  2021-04-07T10:37:01.292+0800  ERROR   container/poller.go:16  vertex got an error     {"vertex id": "http.Plugin", "error": "http_plugin_serve_http: cannot enable TCP_DEFER_ACCEPT: protocol not available"}

   ERROR  github.com/spiral/endure/pkg/container.(*Endure).poll.func1

   ERROR        github.com/spiral/endure@v1.0.1/pkg/container/poller.go:16

   ERROR  handle_serve_command: http_plugin_serve_http: cannot enable TCP_DEFER_ACCEPT: protocol not available; fsm_recognizer: can't transition from state: Stopped by event Stop
```

**Comment by aftabnaveed** [comment]
Try it with Swoole instead of roadrunner.  `php artisan octane:start --server=swoole`   make sure swoole php extension is installed prior to that.

**Comment by NiZerin** [comment]
> Try it with Swoole instead of roadrunner. `php artisan octane:start --server=swoole` make sure swoole php extension is installed prior to that.

ok, i try this

**Comment by NiZerin** [comment]
> Try it with Swoole instead of roadrunner. `php artisan octane:start --server=swoole` make sure swoole php extension is installed prior to that.

it work, thank you.

**Comment by woodongwong** [comment]
Try to delete the `.rr.yaml` file
