### ISSUE TITLE
Watching For File Changes Server Reloading Crash

### ISSUE THREAD

**Issue by bdlogicalerror** [laravel/octane#105]
- Octane Version: 0.1.0
- Laravel Version: 8.12
- PHP Version: 8.0.3
- Database Driver & Version:

### Description:

After changes any file Server Crash And  **Too few arguments to function Laravel\Octane\RoadRunner\ServerProcessInspector::reloadServer(), 0 passed**

i figure out the solution octane/src/Commands/Concerns/InteractsWithServers.php on line 54 need to pass any slug.

` while ($server->isRunning()) {
                $this->writeServerOutput($server);

                if ($watcher->isRunning() &&
                    $watcher->getIncrementalOutput()) {
                    $this->info('Application change detected. Restarting workers…');

                    $inspector->reloadServer('/');
                }

                usleep(500 * 1000);
            }`

**Comment by driesvints** [comment]
Let's see how the pr goes

**Comment by barryvdh** [comment]
Can you test https://github.com/laravel/octane/pull/177 ?
