### ISSUE TITLE
http_plugin_serve_http: cannot bind to "0.0.0.0:80": permission denied, plugin: http.Plugin

### ISSUE THREAD

**Issue by thyseus** [laravel/octane#111]
### Description:
I have followed the instructions using `laravel sail` to 100%, also did `sail build --no-cache` but i get this error when trying to run `sail up`:

```
 INFO  Server running…
laravel.test_1       | 
laravel.test_1       |   Local: http://0.0.0.0:80 
laravel.test_1       | 
laravel.test_1       |   Use Ctrl+C to stop the server
laravel.test_1       | 
laravel.test_1       | 2021-04-07 08:23:15,094 INFO success: php entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
laravel.test_1       | 
laravel.test_1       |    INFO  error occurred: http_plugin_serve_http: cannot bind to "0.0.0.0:80": permission denied, plugin: http.Plugin
laravel.test_1       | 
laravel.test_1       |    ERROR  2021-04-07T08:23:14.616Z       ERROR   container/poller.go:16  vertex got an error     {"vertex id": "http.Plugin", "error": "http_plugin_serve_http: cannot bind to \"0.0.0.0:80\": permission denied"}
```
Any ideas on what i have done wrong / what step is missing in the tutorial?

**Comment by gregorip02** [comment]
It seems you have a host level restriction to use port `80`. Try changing the port to access your application to one without restrictions, e.g `8080` or run` sail` with root permissions.

**Comment by thyseus** [comment]
@gregorip02 thanks a lot for your reply.

running `sail` as root unfortunately gives me the same error message.
I also ensured that port 80 is free on my host by using `sudo lsof -i -P -n | grep LISTEN`.
The php development server that is preconfigured by `sail` also uses port 80 and this one is running fine on my system.

**Comment by gregorip02** [comment]
Try running `php artisan sail:publish`, then, change the host-port of your app.

```yaml
# docker-compose.yml

# More configurations...
services:
  laravel.test:
    ports:
      - '8080:80'
```

**Comment by thyseus** [comment]
This is my `docker-compose.yml`:
```
services:
  laravel.test:
    ports:
       - '${APP_PORT:-80}:80'
```
which should read the environment variable `APP_PORT` which is set to 8080.
No luck.

Also removing this line and 'hardcode' the `- '8080:80'` line has no effect.
Are you sure this is due a port limitation on my host ?

**Comment by thyseus** [comment]
I have found a solution !

My assumption was right. Roadrunner (running inside the `laravel_test` container) was not able to open a port _outside_ of the container to the outer world. No idea why. Setting the port from `80` to `8080` in `docker/8.0/supervisord.conf` _and_ setting the right part of the colon(:) in `docker-compose.yml` to `8080` like: `            - '${APP_PORT:-80}:8080'` fixes the issue for me. 

I want to keep this issue open for some `sail` expert to determine if the `80` configured as default should be changed to `8080` and maybe for someone to explain the real cause of the problem :)

Thanks a lot for your efforts!

**Comment by JackN-code** [comment]
Hi @thyseus, thanks for the solution, it makes octane works on port 80, but somehow the performance goes down a lot. Do you encounter the same issue? Leaving at port 8000 and with 2000 requests, average response time is about 50ms, but port 80 is about 100 ms.

Using vapor with aws lambda, it means x2 cost
