### ISSUE TITLE
Swoole\Process::kill(): swKill(xxxx, 15) failed, Error: No such process[3]

### ISSUE THREAD

**Issue by nicoorfi** [laravel/octane#114]
- Octane Version: v0.1.0
- Laravel Version: v8.36.0
- PHP Version: 8.0.3
- Database Driver & Version: Not Related
- Distro: debian:buster (Docker)

** NOT USING LARAVEL SAIL **

### Description:

When using `Ctrl+C` to stop the server the following exception is thrown:
```
 ErrorException

  Swoole\Process::kill(): swKill(7127, 15) failed, Error: No such process[3]

  at vendor/laravel/octane/src/Swoole/SwooleExtension.php:18
     14▕      * @return bool
     15▕      */
     16▕     public function dispatchProcessSignal(int $processId, string $signal): bool
     17▕     {
➜  18▕         return Process::kill($processId, $signal);
     19▕     }
     20▕
     21▕     /**
     22▕      * Set the current process name.

      +45 vendor frames
  46  artisan:37
      Illuminate\Foundation\Console\Kernel::handle()
```

Afterwards the `octane-server-state.json` is still present and it's impossible to start the server again because of:
```
 ERROR  Server is already running.
```

After some research found out that in `Laravel\Octane\Swoole\ServerProcessInspector::stopServer()` if i remove the:
```
$this->dispatcher->terminate($masterProcessId, 15)
```

the server terminates without problems and the `octane-server-state.json` is missing like it's supposed to, and after when checking with `htop` both processes (master & manager) are gone.

### Steps To Reproduce:

I guess trying with a fresh laravel installation within a debian:buster container to run:
```
/usr/bin/php -d variables_order=EGPCS /var/www/app/artisan octane:start --server=swoole --host=0.0.0.0 --port=8080 --workers=1
```

and stop it with `Ctrl+C`.

Happy to help with anything.

**Comment by driesvints** [comment]
We don't provide Docker support other than Sail, sorry.
