### ISSUE TITLE
Option to ignore some watched directories?

### ISSUE THREAD

**Issue by myckhel** [laravel/octane#118]
During watch mode and when media files are created the server detects the changes and reload the server each time.
would it be a good idea to specify directories to be ignored during watch mode?
so that server don't reload when uncared files changes.

**Comment by Namoshek** [comment]
https://github.com/laravel/octane/blob/984c9a870c97b51b49e9d32638dfef16d0889d89/bin/file-watcher.js#L5-L20

Since `/storage` is not watched, media files should not cause a reload. Did I miss something?

**Comment by Namoshek** [comment]
It would make sense to allow adding additional directories to watch though. I think there are applications with multiple modules in different root directories similar to `/app`.

**Comment by myckhel** [comment]
This pull request didn't solve the unnecessary server reload issue.

For example i have linked some folders into the `public` dir (`public/images`)
when new images are added the watcher detects changes from `public/images` dir and reloads the server.

With the pull request created there is still no option to ignore some nested folders.

I will try to make a pull request for unwatch config.

i hope the pull request will be considere.
