### ISSUE TITLE
Broadcast routes responds with 403 when using octane:swoole server

### ISSUE THREAD

**Issue by myckhel** [laravel/octane#120]
- Octane Version: v0.1.0
- Laravel Version: v8.35.1
- PHP Version: v8.0.2
- Database Driver & Version: mysql
- Broadcast Driver & Version: pusher:v4.1.5

### Description:
when using `octane:swoole` server, Broadcast routes always return 403 error.
`[GET]: {{url}}/broadcasting/auth?channel_name=User.1` `403`

when using `artisan serve` everything works fine
`[GET]: {{url}}/broadcasting/auth?channel_name=User.1` `200`

### Steps To Reproduce:
1. `php artisan octane:start`
2.  `[GET]: {{url}}/broadcasting/auth?channel_name=User.1`

**Comment by fridzema** [comment]
Can confirm this, looks like a CORS issue as my xhr requests also fails and gives CORS errors. 

<img width="1893" alt="Screen Shot 2021-04-07 at 14 12 47" src="https://user-images.githubusercontent.com/8180660/113864634-6b47c700-97ab-11eb-92e6-d730f9ad89be.png">

**Comment by barryvdh** [comment]
@fridzema Isn't that a different issue? Shouldn't the request also be to port 8000?

**Comment by barryvdh** [comment]
Oh nevermind, the first 3 errors are not related..
But similar issue on Twitter; https://twitter.com/tonysmdev/status/1379587360812306437 where Taylor is looking into.

**Comment by barryvdh** [comment]
Probably fixed with the latest release.

**Comment by myckhel** [comment]
sounds nice will try out.
