### ISSUE TITLE
Freeze

### ISSUE THREAD

**Issue by jihadismail8** [laravel/octane#122]
- Octane Version: v1
- Laravel Version: 8.36..1
- PHP Version: 8.0.3
- Database Driver & Version: mysql8
-  php --ri swoole
Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.6.4
Built => Mar 29 2021 10:46:54
coroutine => enabled with boost asm context
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
sockets => enabled
openssl => OpenSSL 1.1.1f  31 Mar 2020
dtls => enabled
http2 => enabled
json => enabled
curl-native => enabled
pcre => enabled
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
mysqlnd => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 8388608 => 8388608

### Description:
i can only get to login page , and after the login page , the home page loads and only some elements are visible , then the page freezes  and never receives any response .

what i noticed is that the livewire components or the ones that have alpine.js in them  are not being loaded   .
to reproduce , install by composer  mediconesystems/livewire-datatables  , and just make a datatable .

**Comment by Namoshek** [comment]
Are you missing an Nginx/Apache in front which serves static assets like the `.js` files required for Alpine.js?

**Comment by jihadismail8** [comment]
Well i am on local development,  so i just start the octane server as in the docs , no apache and no nginx .

**Comment by themsaid** [comment]
Stick to the default swoole configurations and try again. There are known issues with coroutines and that's why they are disabled.

**Comment by jihadismail8** [comment]
> Stick to the default swoole configurations and try again. There are known issues with coroutines and that's why they are disabled.

But thats exactly what i did !! I changed absolutely nothing in configs and sticked to the docs . The app i tested it on is also minimalist  just a boilerplate with tailwind and livewire+alpine , with a home page of a datatable . But as i mentioned in the description the table loads only half of it (visually) the other half  down (even the pagination) doesn't load . And the browser just keeps waiting for the response.  Any idea of at least how to debug it ?

**Comment by jihadismail8** [comment]
ok now iam tried to switch to RoadRunner : but am getting another error .

 Unable to locate RoadRunner binary. Should Octane download the binary for your operating system? (yes/no) [yes]:
 > y


 Environment:
   - Version:          2.*
   - Stability:        stable
   - Operating System: linux
   - Architecture:     amd64

  - spiral/roadrunner-binary (2.0.4): Downloading...
RoadRunner (2.0.4) has been installed into /mnt/c/Users/jihad/PhpstormProjects/datatable-php8-octane/rr


 [OK] Your project is now ready in
      /mnt/c/Users/jihad/PhpstormProjects/datatable-php8-octane


Whats Next?
===========

 * For more detailed documentation, see the https://roadrunner.dev
 * To run the application, use the following command: $ rr serve



   INFO  Server running…

  Local: http://127.0.0.1:8000

  Use Ctrl+C to stop the server


   INFO  error occurred: http_plugin_serve_http: cannot enable TCP_DEFER_ACCEPT: protocol not available, plugin: http.Plugin

   ERROR  2021-04-07T14:40:20.461+0300  ERROR   container/poller.go:16  vertex got an error     {"vertex id": "http.Plugin", "error": "http_plugin_serve_http: cannot enable TCP_DEFER_ACCEPT: protocol not available"}

   ERROR  github.com/spiral/endure/pkg/container.(*Endure).poll.func1

   ERROR        github.com/spiral/endure@v1.0.1/pkg/container/poller.go:16

   ERROR  handle_serve_command: http_plugin_serve_http: cannot enable TCP_DEFER_ACCEPT: protocol not available; fsm_recognizer: can't transition from state: Stopped by event Stop

**Comment by aftabnaveed** [comment]
Are you using WSL?

**Comment by themsaid** [comment]
Well if a response is received that means Octane server is working. Don't have experience with livewire tho so maybe it's something related to how it works.

**Comment by jihadismail8** [comment]
> Are you using WSL?

Yea  WSL2

**Comment by jihadismail8** [comment]
> Well if a response is received that means Octane server is working. Don't have experience with livewire tho so maybe it's something related to how it works.

Yea thats what i don't understand  , so is it an issue in livewire? Or octane?  The pages with no livewire (pure blade ) are working  fine .

**Comment by jihadismail8** [comment]
> Stick to the default swoole configurations and try again. There are known issues with coroutines and that's why they are disabled.

when i installed octane/swoole i answered all the questions by NO , but still in  php --ri swoole as we can see above , everything is enabled ( json , coroutine , sockets ..etc ) does not make sense . i uninstalled swoole , and  installed it again  and made sure i pressed NO on all the questions . but it still says everything is enabled . so it could be an issue in swoole installation on WSL2 .

**Comment by jihadismail8** [comment]
@driesvints   can you please drop something to debug , some ways or  at least from where to start ?? as this is some how new to the community !! which info i can provide more ?

**Comment by driesvints** [comment]
Please try a support channel:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks
