### ISSUE TITLE
  The "--with-all-dependencies" option does not exist.

### ISSUE THREAD

**Issue by genesiscz** [laravel/octane#124]
- Octane Version: 0.1.0
- Laravel Version: 8.35
- PHP Version: 8.0

### Description:
![image](https://user-images.githubusercontent.com/1512353/113866523-b82c9d00-97ad-11eb-8edf-b7c4bd05e288.png)
![image](https://user-images.githubusercontent.com/1512353/113866664-df836a00-97ad-11eb-9a5f-386e2f9d9611.png)

### Steps To Reproduce:
- Install laravel/octane without RR
- php artisan octane:start

**Comment by barryvdh** [comment]
Are you using Composer version 1? Can you upgrade to composer v2? (Or require spiral/roadrunner manually with Composer)

**Comment by crynobone** [comment]
`spiral/roadrunner` 2 does require Composer 2 actually. You can require it manually but still need to upgrade to Composer 2

**Comment by genesiscz** [comment]
I actually am on 2.0.7, v1 didn't ask if you want to continue as root

**Comment by genesiscz** [comment]
Ah, I see, it didn't ask. That means it was v1 probably, but isn't the package somehow envoking its own composer and not using my system one?
