### ISSUE TITLE
Failed to open stream: Too many open files in /vendor/composer/ClassLoader.php:478

### ISSUE THREAD

**Issue by z-golly** [laravel/octane#127]
- Octane Version: 0.1.0
- Laravel Version: 8.35.1
- PHP Version: 8.0.3
- Database Driver & Version: mysql:5.7 & elasticsearch:7.10.1
- System：MacOS Big Sur

### Description:
wrk -c20 -d5s http://127.0.0.1:8000/api/companies

```bash
  200    GET /api/companies ......................................................................................................... 14.77 ms
  200    GET /api/companies ......................................................................................................... 10.31 ms
  200    GET /api/companies ......................................................................................................... 21.90 ms

   ERROR  PHP Fatal error:  Uncaught ErrorException: include(/Users/jonathan/Laravel/m-api/vendor/laravel/octane/src/Events/WorkerErrorOccurred.php): Failed to open stream: Too many open files in /Users/jonathan/Laravel/m-api/vendor/composer/ClassLoader.php:478

  ↑   72 similar errors were reported.

   ERROR  Stack trace:

  ↑   74 similar errors were reported.

   ERROR  #0 /Users/jonathan/Laravel/m-api/vendor/composer/ClassLoader.php(478): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'include(/Users/...', '/Users/jonathan...', 478)

  ↑   74 similar errors were reported.
```
log is 
```bash
[2021-04-07 22:28:33 $5548.0]	WARNING	check_worker_exit_status: worker#2[pid=6016] abnormal exit, status=0, signal=9
[2021-04-07 22:28:33 $5548.0]	WARNING	check_worker_exit_status: worker#1[pid=6017] abnormal exit, status=0, signal=9
[2021-04-07 22:28:33 $5548.0]	WARNING	check_worker_exit_status: worker#3[pid=6015] abnormal exit, status=0, signal=9
[2021-04-07 22:28:33 $5548.0]	WARNING	check_worker_exit_status: worker#0[pid=6014] abnormal exit, status=0, signal=9

```

**Comment by albertcht** [comment]
Hi @z-golly ,

I think it's related to number limit of `file descriptors` on your Linux kernel.

Try to run `ulimit -n` to see the number. You can run `sudo ulimit -n 10240` to change the config temporarily to see if it works.

**Comment by z-golly** [comment]
@albertcht 
I have tried to set it, but the error still occurs

**Comment by aftabnaveed** [comment]
@z-golly  may be give this a try

Increase the limit by editing `/etc/sysctl.conf` and add this line to the end of the file: 
`fs.inotify.max_user_watches=524288`

And then run `sudo sysctl -p`

**Comment by z-golly** [comment]
@taylorotwell  @aftabnaveed @albertcht  I didn't find this problem when I used it in the Windows Docker environment.

**Comment by z-golly** [comment]
When there is a database query, there is no performance improvement. This makes me feel very puzzled.

### laravel version
#### code
```php
    /**
     * @return JsonResponse
     */
    public function version()
    {
       return response()->json(['version' => app()->version()]);
    }
```
#### nginx+fpm
![1617845426(1)](https://user-images.githubusercontent.com/18160974/113960358-f762f880-9856-11eb-97bf-9d4ae18422fe.png)
#### octane
![1617845383(1)](https://user-images.githubusercontent.com/18160974/113960504-309b6880-9857-11eb-8e6a-060d649f28f0.png)

### query
#### code
```php
      /**
     * @param Request $request
     * @param $id
     * @return JsonResponse
     */
    public function show(Request $request, $id)
    {
        $request->query->set(
            'with',
            'jds.addresses.province,jds.addresses.city,jds.educationName,typeName,scaleName,industries,province,city'
        );
        $company = (new Company())->filter($request->query())->findOrFail($id);

        return (new CompanyShowResource($company))->response();
    }
```
#### nginx+fpm
![1617845556(1)](https://user-images.githubusercontent.com/18160974/113960693-6ccec900-9857-11eb-9d65-49fd2597e665.png)
#### octane
![1617845706(1)](https://user-images.githubusercontent.com/18160974/113960720-76f0c780-9857-11eb-8545-5acff7e876f9.png)

**Comment by aftabnaveed** [comment]
For database queries you need to execute it through `Octane::concurrently`

```
use App\User;
use App\Server;
use Laravel\Octane\Facades\Octane;

[$users, $servers] = Octane::concurrently([
    fn () => User::all(),
    fn () => Server::all(),
]);
```

**Comment by albertcht** [comment]
All of I/O operations now in Laravel Octane should still be blocking I/O. `Octane::concurrently` seems using SwooleTaskDispatcher by default. That means `concurrently` now can only help you decrease total waiting time of multiple I/O operations. These I/O operations still block Swoole's task workers. It won't help your qps significantly.

Unless coroutine feature is fully supported in Laravel, otherwise contexts between different coroutines may lead unexpected results.

**Comment by aftabnaveed** [comment]
@albertcht does that mean we won't be able to use `go` functions with `octane` ? I am thinking if Laravel does not provide it then why not use Swoole's utility functions directly?

**Comment by z-golly** [comment]
A little disappointed with this.

**Comment by Namoshek** [comment]
`Swoole::concurrently(...)` uses `go()` (or actually the long version of it, see #100) under the hood. It allows you to execute multiple commands in parallel, but not in a fully asynchronous style we know from other languages like C#.

Whether Octane has an impact on request times depends on the tasks performed on the server. The more I/O is involved, the less noticeable it will be in the end. But for high traffic sites with content that can be cached easily, Octane is a great plus nonetheless.

What I'm not sure about is the Coroutine MySql Extension provided by Swoole. The documentation is lacking in my opinion, but maybe it can improve performance of queries further.

**Comment by themsaid** [comment]
Coroutines are currently disabled when using Octane. We're planning to work on adapting the framework and first party packages for it first.

**Comment by faytekin** [comment]
> Coroutines are currently disabled when using Octane. We're planning to work on adapting the framework and first party packages for it first.

I came across this response from 2021, but it's now 2025 and there still appears to be no progress on this issue.

Currently, with coroutines disabled in Laravel, external API calls are blocking my workers, which is putting me in a very difficult position. My system needs to make requests to multiple APIs, and these APIs sometimes respond slowly. When workers are waiting for API responses, they can't handle new incoming requests, causing everything to time out at once.

If coroutines were enabled in Octane, we could potentially offload these API calls to task workers and solve this problem. However, Laravel doesn't seem to be configured appropriately for this.

Is there any update on when coroutines might be enabled in Laravel Octane? This would be tremendously helpful for applications that need to handle multiple external API calls without blocking the main request processing.​​​​​​​​​​​​​​​​
