### ISSUE TITLE
RR handles requests slow at start, then very fast randomly

### ISSUE THREAD

**Issue by genesiscz** [laravel/octane#129]
- Octane Version: 0.1.0
- Laravel Version: 8.35
- PHP Version: 8.0
- Database Driver & Version: MariaDB

### Description:
![image](https://user-images.githubusercontent.com/1512353/113907453-abbc3a80-97d5-11eb-9c47-59ea23dae67a.png)

Slow request:
![image](https://user-images.githubusercontent.com/1512353/113908159-854acf00-97d6-11eb-82bc-acdbba12243c.png)

Fast request:
![image](https://user-images.githubusercontent.com/1512353/113908099-7532ef80-97d6-11eb-81ea-da7750069352.png)

### Steps To Reproduce:
I am not sure, this always happens on start. They were literally a second apart from each other. I just spammed cmd + R & it randomly starts being fast. Headers, models, events, cache & redis tabs show literally the same thing, they differ only about a few points of a millisecond.

**Comment by genesiscz** [comment]
Looks like swoole made it in 153ms in the first request & 36ms in all other requests.

**Comment by taylorotwell** [comment]
The first time you hit a worker it loads the whole framework.

**Comment by genesiscz** [comment]
Yeah, true. I didn't expect it to rotate the worker one by one each request. Thanks!

**Comment by wolfy-j** [comment]
RR uses round-robin balancing, so it takes a bit to warm up all the workers.

**Comment by genesiscz** [comment]
Perfect answer, wolfy-j, thanks for explanation!
