### ISSUE TITLE
Problem with `php://input`

### ISSUE THREAD

**Issue by foremtehan** [laravel/octane#143]
- Octane Version: 0.1.1
- Laravel Version: 8
- PHP Version: 8
- Server: Swoole 

### Description:
I want to interact with [Telegram](https://core.telegram.org/bots/api) API, I have to receive data from telegram hook via `php://input`, The issue is the `file_get_contents` always return empty string:

```php
use Symfony\Component\HttpFoundation\Response;

Octane::route('POST', '/hook', function () {
    $data = file_get_contents('php://input');
    
    $url = "https://api.telegram.org/botTOKEN/sendMessage?chat_id=chatId&text=".empty($data) ? 'Empty' : $data;
    
    Http::get($url); // test if we received data but it always says 'Empty'

    return new Response('Ok');
});
```

But it working with traditional : `Route::post(..)`

**Comment by barryvdh** [comment]
Is `$request->getContent();` also empty?

```php
use Illuminate\Http\Request;
use Symfony\Component\HttpFoundation\Response;

Octane::route('POST', '/hook', function (Request $request) {
    $data = $request->getContent();

    $url = "https://api.telegram.org/botTOKEN/sendMessage?chat_id=chatId&text=".empty($data) ? 'Empty' : $data;

    Http::get($url); // send data from telegram hook but it always is 'Empty'

    return new Response('Ok');
});

```

**Comment by foremtehan** [comment]
@barryvdh it workings now, I dont know if this issue can be closed but problem with 'php://input' still exists

**Comment by themsaid** [comment]
You should use the illuminate request object.
