### ISSUE TITLE
`__destruct` not being called when binding in controller

### ISSUE THREAD

**Issue by foremtehan** [laravel/octane#154]
- Octane Version: 0.1.1
- Laravel Version: 8
- PHP Version: 8
- Server: Swoole 

In my app i have to bind something inside of controller's method but today i realised when i do this the `__destruct` never called:

```php
use Illuminate\Support\Facades\App;
use App\Http\Controllers\MyController;
use Symfony\Component\HttpFoundation\Response;

Octane::route('GET', '/index', function () {
    $result = App::make(MyController::class)->index();

    return new Response($result);
});
```

```php
<?php

namespace App\Http\Controllers;

use Illuminate\Support\Facades\App;
use Illuminate\Support\Facades\Log;

class MyController extends Controller
{
    public function index()
    {
        App::bind('foo', fn() => 'bar');

        //
    }

    public function __destruct()
    {
        Log::info('Here');

        // not being called
    }
}
```

**Comment by driesvints** [comment]
Destruct cannot be called because objects are never destruct. Octane serves a long running process.

**Comment by foremtehan** [comment]
@driesvints If so, When i remove the binding line it would work actually..., You can test it by yourself

**Comment by themsaid** [comment]
Don't use __destruct() inside a controller. Not sure what you're doing with it but I'm sure there's a better way. 

Also don't bind things to the container inside a controller, bindings should be in a service provider.
