### ISSUE TITLE
Warming up workers when using RoadRunner

### ISSUE THREAD

**Issue by Namoshek** [laravel/octane#163]
This is more of a design question. Is there any particular reason why we cannot move lines 41-49 outside the request handling loop to boot the framework before accepting requests?

https://github.com/laravel/octane/blob/15093197bae652e434e304753b3dcf47796272d5/bin/roadrunner-worker#L31-L62

**Comment by taylorotwell** [comment]
Yes - @nunomaduro can answer that.

**Comment by nunomaduro** [comment]
When using roadrunner, if you place the boot of the framework outside that `while` condition, the `boot` exceptions/errors do get properly propagated.
