### ISSUE TITLE
Support for SOA ecosystem

### ISSUE THREAD

**Issue by nonetallt** [laravel/octane#164]
I know this is still very early in the development but I'm curious if there are plans to eventually support components necessary for service oriented architecture? Such features are quite common in most frameworks that utilize the underlying techonologies like Swoole. So far the pitch seems to be to simply enable faster laravel applications, but I'm specifically interested in the possibility of adding features like:

- Service discovery (Consul etc.)
- RPC
- Circuit breakers
- Message queues (Kafka, Perhaps integrated with the underlying event system?)

Is this something that might be within the scope of Octane in the future or should we just assume that if such support is ever integrated, it would be done using 3rd party unofficial packages?

**Comment by DarkGhostHunter** [comment]
I think that, considering the scope of Laravel Octane and the features you require, it will be totally in another package:

- [Consul SDK](https://packagist.org/packages/sensiolabs/consul-php-sdk)
- [gRPC for PHP](https://cloud.google.com/php/grpc)
- Circuit Breaker will depend on the architecture itself IMHO
- [Some packages for RabbitMQ](https://www.rabbitmq.com/devtools.html#php-dev)

**Comment by taylorotwell** [comment]
Maybe someday.
