### ISSUE TITLE
unserialize(): Error at offset 10000 of 10000 bytes

### ISSUE THREAD

**Issue by foremtehan** [laravel/octane#173]
- Octane Version: 0.1.1
- Laravel Version: 8
- PHP Version: 8
- Server: Swoole 

### Description:
I just changed my default cache driver to octane and i got the following error:

```
unserialize(): Error at offset 10000 of 10000 bytes#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError()
#1 /app/vendor/laravel/octane/src/Cache/OctaneStore.php(37): unserialize()
#2 /app/vendor/laravel/framework/src/Illuminate/Cache/Repository.php(97): Laravel\Octane\Cache\OctaneStore->get()
#3 /app/vendor/laravel/framework/src/Illuminate/Cache/Repository.php(376): Illuminate\Cache\Repository->get()
#4 /app/vendor/laravel/framework/src/Illuminate/Cache/CacheManager.php(392): Illuminate\Cache\Repository->remember()
#5 /app/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(261): Illuminate\Cache\CacheManager->__call()
#8 /app/vendor/laravel/framework/src/Illuminate/Collections/Traits/EnumeratesValues.php(234):
#13 [internal function]: Illuminate\Routing\RouteFileRegistrar->{closure}()
#14 /app/vendor/laravel/octane/src/Concerns/ProvidesRouting.php(53): call_user_func()
#15 /app/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(261): Laravel\Octane\Octane->invokeRoute()
#16 /app/vendor/laravel/octane/src/ApplicationGateway.php(33): Illuminate\Support\Facades\Facade::__callStatic()
#17 /app/vendor/laravel/octane/src/Worker.php(94): Laravel\Octane\ApplicationGateway->handle()
#18 /app/vendor/laravel/octane/bin/swoole-server(119): Laravel\Octane\Worker->handle()
#19 [internal function]: {closure}()
#20 /app/vendor/laravel/octane/bin/swoole-server(169): Swoole\Server->start()
#21 {main}
```

Looks like it have problem with Eloquent\Collection, if the data is big, it cannot cache it:

```php
Cache::store('octane')->rememberForever('key', fn() => Thread::query()->latest()->take(100)->get());
```

**Comment by foremtehan** [comment]
Looks like it have problem with Eloquent\Collection, it cannot cache it:

```php
Cache::rememberForever('key', fn() => Thread::query()->where(/**/)->get());
```

**Comment by Namoshek** [comment]
The Octane cache is based on a Swoole Table, in case you are using the Swoole server. The cache is limited to 1000 rows with 10.000 bytes each by default:
https://github.com/laravel/octane/blob/9faedfb8f3a7d6477738ab95148ca8c570ddef5d/config/octane.php#L125-L139

For larger items, you might want to:
- consider using a different type of cache
- increase the default size of the Octane cache per item
- define and use a separate Swoole Table for the larger items

**Comment by foremtehan** [comment]
I changed it to `'bytes' => 200000000` but it says : 

```
ERROR  PHP Fatal error:  Swoole\Table::create(): unable to allocate memory in /app/vendor/laravel/octane/bin/createSwooleCacheTable.php on line 11
```

I actually need 200mb of ram for my keys, What did i wrong ? should i reduce rows ?

**Comment by wimil** [comment]
I have the same problem, how can I fix it ?, I tried to increase the bytes and row but it doesn't work.

**Comment by haught** [comment]
This is an issue that needs to be worked around. You can set an entry to the swoole table that is larger the it can contain and we don't get a false back from $this->table->set() in the **put** method. It thinks it added it correctly. This would probably be something that swoole needs to address.

The problem on the octane side is that we are failing to handle the unserialize error on the **get** method. The data is corrupted, it should be handled in some way. Report the error (maybe a more friendly message...) and return null as if the record was not found would seem like a logical workaround for the **get** method.

```
            try {
                return unserialize($record['value']);
            } catch (Throwable $e) {
                report($e);
                return null;
            }
```

**Comment by nunomaduro** [comment]
This will be fixed on the next release, next week.
