### ISSUE TITLE
Developers can't know that the process is killed when it exceeds the maximum execution time.

### ISSUE THREAD

**Issue by eleven26** [laravel/octane#183]
https://github.com/laravel/octane/blob/6054cc9893bb4c0b860f0e7f8835920b27abbb55/src/Swoole/Actions/EnsureRequestsDontExceedMaxExecutionTime.php#L27

`SIGKILL` will kill the process directly, but we don't know it at all, but it's very helpful for us to improve the application if we know this situation.

**Comment by driesvints** [comment]
Send in a PR if you like
