### ISSUE TITLE
getRequestUri differers

### ISSUE THREAD

**Issue by elsuterino** [laravel/octane#188]
- Octane Version: 0.1.0
- Laravel Version: 8.36.2
- PHP Version: 8.0.3
- Server: Swoole
- Database Driver & Version:

### Description:
```request()->getRequestUri();```
provides different results for serve/php-fpm vs octane swoole/nginx proxy

here is normal artisan serve
![image](https://user-images.githubusercontent.com/5807399/114562181-f24ae280-9c76-11eb-9254-b089b62f3c03.png)

and here is with swoole
![image](https://user-images.githubusercontent.com/5807399/114562302-0d1d5700-9c77-11eb-854b-fd2fc0d949d1.png)

as you can see its missing query params

### Steps To Reproduce:
return `request()->getRequestUri()` with query params under normal setup and under swoole octane

**Comment by driesvints** [comment]
Does this also happens on Octane 0.1.1?

**Comment by elsuterino** [comment]
yes

**Comment by barryvdh** [comment]
Can you try this? https://github.com/laravel/octane/pull/196

**Comment by elsuterino** [comment]
yes that fixed it, thanks
