### ISSUE TITLE
Octane::concurrently may cause requests to be unresponsive

### ISSUE THREAD

**Issue by eleven26** [laravel/octane#190]
- Octane Version: v0.1.1
- Laravel Version:  v8.36.2
- PHP Version:  8.0.3
- Server: Swoole 
- Swoole Version: 4.6.5
- Database Driver & Version: MySQL 5.7.26

### Description:

When multiple MySQL queries are launched in `Octane:: concurrently`, the worker process may not respond.

#### Two tasks can respond normally

I'd like to try to run multiple MySQL queries at the same time, and then use `Octane:: concurrently` to test. The test code is as follows:

```PHP
Route::get('/', function () {
    $result = Octane::concurrently([
        function() {
            return DB::select(DB::raw('select sleep(1);'));
        },
        function() {
            return DB::select(DB::raw('select sleep(1);'));
        },
    ]);

    var_dump($result);

    return view('welcome');
});
```

When requested, two MySQL query tasks are initiated. When I made the request, the server returned normally.

#### More MySQL queries are unresponsive

Then I increased the number of tasks by one, modified the query statement, and monitored the `TaskTerminated` event：

```PHP
Event::listen(TaskTerminated::class, function () {
    echo "Task terminated";
});

Route::get('/', function () {
    $result = Octane::concurrently([
        function() {
            return DB::select(DB::raw('select sleep(1);'));
        },
        function() {
            return DB::select(DB::raw('select sleep(2);'));
        },
        function() {
            return DB::select(DB::raw('select sleep(3);'));
        },
]);

    var_dump($result);

    return view('welcome');
});

```

But when I started the request, the server didn't respond at all. It was always in the pending state. But you can see that the console outputs three `Task terminated`.

I used laravel sail to test. I went in and used `ps -ef` to look at the process status. I found that there are two manager processes, but normally there should be only one.

```
sail        26    19  0 16:14 ?        00:00:00 swoole_http_server: master process for Laravel
sail        27    26  0 16:14 ?        00:00:00 swoole_http_server: manager process for Laravel
sail        30    27  0 16:14 ?        00:00:00 /usr/bin/php8.0 swoole-server /var/www/html/storage/logs/octane-server-state.json
sail        31    27  0 16:14 ?        00:00:00 /usr/bin/php8.0 swoole-server /var/www/html/storage/logs/octane-server-state.json
sail        32    27  0 16:14 ?        00:00:00 /usr/bin/php8.0 swoole-server /var/www/html/storage/logs/octane-server-state.json
sail        34    27  0 16:14 ?        00:00:00 swoole_http_server: manager process for Laravel
```

At the same time, the worker process is one less than normal.

#### Other information

`swoole_ http.log` shows that the process exited abnormally, and the signal is 9, which should be killed when the maximum execution time is exceeded.

```
[2021-04-13 16:22:23 $26.0]	WARNING	check_worker_exit_status: worker#1[pid=32] abnormal exit, status=0, signal=9
```

**Comment by driesvints** [comment]
Can you try again on v0.2.0?

**Comment by eleven26** [comment]
> Can you try again on v0.2.0?

I tried 0.2.0 today, when I use the old code to test (the code below), the request can be responded normally.

```PHP
Event::listen(TaskTerminated::class, function () {
    echo "Task terminated";
});

Route::get('/', function () {
    $result = Octane::concurrently([
        function() {
            return DB::select(DB::raw('select sleep(1);'));
        },
        function() {
            return DB::select(DB::raw('select sleep(2);'));
        },
        function() {
            return DB::select(DB::raw('select sleep(3);'));
        },
]);

    var_dump($result);

    return view('welcome');
});
```

But I still reproduced the situation, and there is a way to reproduce it is to make the task execution time greater than the default maximum request time (max_execution_time):

```PHP
Route::get('/', function () {
    $result = Octane::concurrently([
        function() {
            sleep(config('octane.max_execution_time') + 1);
            return 1;
        },
    ]);

    var_dump($result);

    return view('welcome');
});
```

This will cause the worker process to be killed, and then the request will become unresponsive. At this time, a new manager process will appear, and the number of worker processes will be one less. In this case, `TaskTerminated` event can still be triggered, but it cannot respond.

**Comment by themsaid** [comment]
The process will be terminated after `config('octane.max_execution_time')` passes. With Swoole, there's no way we can send a response so yes the request will hang. I reached out to the Swoole team and there's currently no way around this.

**Comment by Spittal** [comment]
Hey just wanna chime in here that we have independently confirmed that this is the case with Swoole. That max execution time will be hit, and it will send the swoole worker a signal 9 killing the worker, and your HTTP request will hang indefinitely. 

The current work-around we have is to set our proxy HTTP server to the same timeout as our max execution time.
