### ISSUE TITLE
Server reloads unnecessarily when linked files to public dir changes

### ISSUE THREAD

**Issue by myckhel** [laravel/octane#202]
- Octane Version: 0.2.0
- Laravel Version: ^8.37
- PHP Version: 8.0.2
- Server: Swoole

### Description:
based on the previously closed issue https://github.com/laravel/octane/issues/118
> During watch mode and when media files are created the server detects the changes and reload the server each time.
would it be a good idea to specify directories to be ignored during watch mode?
so that server don't reload when uncared files changes.

and later comment https://github.com/laravel/octane/issues/118#issuecomment-820330865
> This pull request didn't solve the unnecessary server reload issue.
>
> For example i have linked some folders into the public dir (public/images)
when new images are added the watcher detects changes from public/images dir and reloads the server.
>
> With the pull request created there is still no option to ignore some nested folders.
>
> I will try to make a pull request for unwatch config.
>
> i hope the pull request will be considered.

Tried a pull request https://github.com/laravel/octane/pull/201
but unfortunately it was closed with no clear reason.

I hope someone can see this issue and try to solve it.

I have tried and my effort have not  been considered.

**Comment by driesvints** [comment]
It seems like Taylor doesn't wants to change this atm.
