### ISSUE TITLE
[Doucment Request] Didn't find information about database connection pool in laravel octane

### ISSUE THREAD

**Issue by diyism** [laravel/octane#223]
I didn't find information about database connection pool in laravel octane,
Wish someone add some decsription about this

For example, shadowfax laravel framework have supported db_pools and redis_pools: https://github.com/huang-yi/shadowfax

**Comment by themsaid** [comment]
Octane doesn't include support for connection pooling as we disable coroutines completely for now. Once we start supporting coroutines, we'll introduce connection pooling.
