### ISSUE TITLE
Wrong record added in sessions table

### ISSUE THREAD

**Issue by Donkfather** [laravel/octane#230]
- Octane Version: 0.2.0
- Laravel Version: 8.38.0
- PHP Version: 8.0.3
- Server: Swoole
- Database Driver & Version: sqlite

### Description:
Created a new application with Jetstream (Livewire) with Teams
When I gave the url to a friend I could see in my account in the Browser Sessions panel a record from his request.
Also tested it with Incognito.

To note that the other user/session is redirected to Login page.

### Steps To Reproduce:
1. Insall Laravel Octane on a fresh Laravel app
2. Install Jetstream and select Livewire and also activate Teams
3. Setup a server with swoole
4. Register a new user
5. While logged in go to Profile
6. Copy the url and open it in an Incognito Session or on another computer and you will be redirect to login
7. Go back to the previous browser
8. Refresh and see a new record in Browser Sessions panel

**Comment by driesvints** [comment]
Please try the latest version first, thanks!
