### ISSUE TITLE
A non-numeric value encountered

### ISSUE THREAD

**Issue by netbounty** [laravel/octane#231]
Hey, I have just installed a fresh laravel app with docker and laravel sail. I installed octane too and I've chosen RoadRunner. It is giving me an error:
![Unbenannt](https://user-images.githubusercontent.com/65421448/115626734-3173d600-a2fe-11eb-8bb1-fe3aaaf13132.PNG)

Help me please

**Comment by netbounty** [comment]
This appeared after hitting the page. The first visit is fine, then the second is crashing

**Comment by nunomaduro** [comment]
Already fixed here: https://github.com/laravel/octane/commit/7e55e9b556b08aa6d010c2603d6107c9e61529b6. We will releasing a fix soon.

**Comment by netbounty** [comment]
Oh thank you for the fast response
