### ISSUE TITLE
Weird problem with `shell_exec` in 0.3.2

### ISSUE THREAD

**Issue by foremtehan** [laravel/octane#234]
- Octane Version: 0.3.2
- PHP Version: 8.03
- Server: Swoole

### Description:
It sounds ridiculous but after i updated from 0.3.1 to 0.3.2 `shell_exec` doesn't find my python's module (in heroku server) But when downgrade to 0.3.1 it works fine! I tested it 3time i dont know what cause the problem here's my codes:

```php
$output = shell_exec("python script.py 2>&1");
```
the python script uses chardet module and i get this error :

```
Traceback (most recent call last):\n
  File "/app/script.py", line 1, in <module>\n
    import chardet, sys\n
ModuleNotFoundError: No module named 'chardet'\n
```

**Comment by themsaid** [comment]
That's a python error. How is this related to Octane?

**Comment by foremtehan** [comment]
The exact code working in 0.3.1 , nevermind i stick with this version for now sorry
