### ISSUE TITLE
memory leak

### ISSUE THREAD

**Issue by KTMRules** [laravel/octane#236]
- Octane Version: latest
- Laravel Version:latest
- PHP Version: latest
- Server: Swoole 
- Database Driver & Version:

### Description:

Fresh install Octane and Laravel, create a test get route with: 

```
<?php


namespace App\Http\Controllers;


class TestController extends Controller
{
    public function index()
    {
        return memory_get_usage()/1024/1204;
    }
}`
```

And you saw memory just goes up an never down..

**Comment by shinguweb96** [comment]
same problem

**Comment by themsaid** [comment]
Using a fresh Laravel installation, there's no memory leak. The leak seems to be coming from your application code or one of the packages you are using.
