### ISSUE TITLE
octane:start --watch is not watching for modified files

### ISSUE THREAD

**Issue by netbounty** [laravel/octane#237]
- Octane Version: 0.3.2
- Laravel Version: 8.12
- PHP Version: 8.0
- Server: RoadRunner

### Description:
Hey, I've implemented Octane in my current project I'm working on. Everything works perfect. BUT:

When I start:
php artisan octane:start --watch

it's not listening for changed files.

![image](https://user-images.githubusercontent.com/65421448/115792930-6e59ce80-a3cb-11eb-96bb-7bbfb9a59401.png)

Take a look at the terminal at the bottom and the Route::get('/test' ...)

![image](https://user-images.githubusercontent.com/65421448/115793009-a19c5d80-a3cb-11eb-97c1-6a656488b5a4.png)

Here I have changed now the return of the /api/test route but nothing happened.
I have also installed chokidar by using:
npm install --save-dev chokidar
in the docs.

The route does not work too, and I've tried to octane:reload the workers but nothing happened and I can't access my localhost:8000/api/test route.

![image](https://user-images.githubusercontent.com/65421448/115793290-25eee080-a3cc-11eb-9ff5-918699300c76.png)

Help me please..

**Comment by netbounty** [comment]
By the way: I have Windows installed and I'm using the app via Laravel Sail through WSL on an Ubuntu-20.04 distribution

**Comment by netbounty** [comment]
Anyone having the same issue?

**Comment by netbounty** [comment]
For any reason it's working now.

**Comment by xmoney** [comment]
> For any reason it's working now.

how did you resolve it? I have the same issue on WSL2.

**Comment by thetuyen** [comment]
> > For any reason it's working now.
> 
> how did you resolve it? I have the same issue on WSL2.

 I have the same issue on WSL2. I did not found any solution. Then, I had to edit file vendor\laravel\octane\bin\file-watcher.js (see attach image) to enable watching.
![Screenshot 2021-05-17 200113](https://user-images.githubusercontent.com/11868366/118492857-aa721c00-b74a-11eb-8c02-f16c49313f64.png)
Maybe There will  have config for this option in future.

**Comment by erfantkerfan** [comment]
I have the same problem on WSL2 but on my Ubuntu system there is no problem

chokidar: 2.1.8

also editing vendor like so fixes the problem:
usePolling: true,

please re-open issue

**Comment by erfantkerfan** [comment]
@taylorotwell

**Comment by krissss** [comment]
Add environment `CHOKIDAR_USEPOLLING: 'true'` to docker-compose.yml can solve this

[wsl2 issue](https://github.com/microsoft/WSL/issues/4739)

**Comment by alignwebs** [comment]
Thanks @krissss
