### ISSUE TITLE
Could the CurrentApplication set method be concurrently unsafe?

### ISSUE THREAD

**Issue by godruoyi** [laravel/octane#241]
When a request comes in, we use CurrentApplication::set to set the current container. But is this concurrency safe?

[Worker.php#L83](https://github.com/laravel/octane/blob/master/src/Worker.php#L83)

```php
public function handle(Request $request, RequestContext $context): void
{
    CurrentApplication::set($sandbox = clone $this->app);

    try {
        // process...
    } catch (Throwable $e) {
    } finally {
        CurrentApplication::set($this->app);
    }
}
```

For example:

```
                                                worker1

                    request1                                                    request2
                       |                                                            |
                       |                                                            |
                       V                                                            |
CurrentApplication::set($sandbox1 = clone $this->app);                              |
                       |                                                            |
                       |                                                            |
                       |                                                            V
                       |                                     CurrentApplication::set($sandbox2 = clone $this->app);
                       |
                       V
                    app()->make(x) // ? use sandbox1 container or sandbox2 container.
                       |                                                            |
                       |                                                            |
                       V                                                            V
                      end                                                          end
```

When I use Container::getInstance in request 1, I'm probably getting the sandbox2 in request 2 set.

So, Is this allowed?

- Octane Version: ^0.3.2
- Laravel Version: ^8.12
- PHP Version: 8.0.3
- Server: Swoole

**Comment by albertcht** [comment]
Unless you use Swoole's coroutine feature, otherwise your worker can only serve one request at the same time.
The `concurrently` feature provided in Octane uses `SwooleHttpTaskDispatcher` by default, which means you can still get the correct sandbox instance in this case.

**Comment by godruoyi** [comment]
if I don't use the concurrently feature, the above problem still exists?  Because by default, we may not need to use the concurrently feature.

And thank you for your answer.

**Comment by albertcht** [comment]
If you don't use Swoole's coroutine, then it's safe.

**Comment by godruoyi** [comment]
Sorry, I don't understand what you mean.

In Laravel Octane, when the request comes in, the framework will use the same worker to process it.

This worker is `Laravel\Octane\Worker` not swoole `worker process`. 

```php
$server->on('request', function ($request, $response) {
    // ...

    $workerState->worker->handle(...$workerState->client->marshalRequest(new RequestContext([
        'swooleRequest' => $request,
        'swooleResponse' => $response,
        'publicPath' => $serverState['publicPath'],
        'octaneConfig' => $serverState['octaneConfig'],
    ])));
    
    // ...
}
```

The `Laravel\Octane\Worker` will handle request and set application container.

 ```php
public function handle(Request $request, RequestContext $context): void
{
    CurrentApplication::set($sandbox = clone $this->app);

   // ...
}
```

But if we dont use Swoole's coroutine, the `CurrentApplication::set` method should be unsafe (look the questions above). 

why `If you don't use Swoole's coroutine, then it's safe`.

**Comment by albertcht** [comment]
Each worker can only serve one request at the same time, so the situation described in your diagram doesn't exist.
The coroutine feature is now disabled in Octane package, therefore you can always get correct sandbox container in your request cycle.

**Comment by godruoyi** [comment]
Read the swoole documentation again, I understand, thanks again for your answer.
