### ISSUE TITLE
A non-numeric value encountered

### ISSUE THREAD

**Issue by tmdevlet** [laravel/octane#242]
- Octane Version: 0.3.2
- Laravel Version: 8.38
- PHP Version: 8.0.1
- Server: RoadRunner
- Database Driver & Version: PGSQL (12)

### Description:

When script runs long time (f.e. 5s)

A non-numeric value encountered

  at vendor/laravel/octane/src/Commands/StartRoadRunnerCommand.php:211
    207▕             return $elapsed * 0.001;
    208▕         }
    209▕ 
    210▕         if (Str::endsWith($elapsed, 's')) {
  ➜ 211▕             return $elapsed * 1000000;
    212▕         }
    213▕ 
    214▕         return $elapsed * 1000;
    215▕     }

      +31 vendor frames 
  32  artisan:37

### Steps To Reproduce:

Call any router (/api/long_api/) witch runs long time (f.e. 5s)

### Possible fix:

  at vendor/laravel/octane/src/Commands/StartRoadRunnerCommand.php:211

line: 213 
if (Str::endsWith($elapsed, 's')) {
    return substr($elapsed, 0, -1) * 1000;
}

**Comment by nunomaduro** [comment]
Already fixed here: 7e55e9b. We will be tagging a new version soon.
