### ISSUE TITLE
the possibility of memory leaks

### ISSUE THREAD

**Issue by kiroto123** [laravel/octane#243]
- Octane Version: 0.3.2
- Laravel Version: 8.38.0
- PHP Version: 8.0.3
- Server: Swoole
- Database Driver & Version:

### Description:

fresh install Octane and Laravel, create a test route with:

```php

<?php

namespace App\Http\Controllers;

class TestController extends Controller
{
    public function index()
    {
        $dispatcher = app()->make('events');
        $dispatcher->listen('foo', function () {
            return 'foo';
        });
        return event('foo');
    }
}
```

And you saw that...

- first
  ```json
  ["foo"]
  ```
- second

  ```json
  ["foo","foo"]
  ```

### Steps To Reproduce:

Extend `\Fruitcake\Cors\HandleCors` and make method `shouldRun` always true.

```php
<?php

namespace App\Http\Middleware;

use Illuminate\Http\Request;

class HandleCors extends \Fruitcake\Cors\HandleCors
{
    protected function shouldRun(Request $request): bool
    {
        return true;
    }
}
```

change `\App\Http\Kernel` middleware from `\Fruitcake\Cors\HandleCors::class` to ` \App\Http\Middleware::class`

and make controller

```php

<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Http\Events\RequestHandled;

class TestController extends Controller
{
    public function test()
    {
        $dispatcher = app()->make('events');
        $ref = new \ReflectionObject($dispatcher);
        $listenersProperty = $ref->getProperty('listeners');
        $listenersProperty->setAccessible(true);
        $listeners = $listenersProperty->getValue($dispatcher);
        $listener = $listeners[\Illuminate\Foundation\Http\Events\RequestHandled::class] ?? [];
        return [
            'count' => count($listener),
        ];
    }
}

```

request and you saw count increasing

```json
{"count":4}
```

**Comment by themsaid** [comment]
Why would you register a listener from inside a controller? Listeners should be registered inside the `boot` method of a service provider.

**Comment by kiroto123** [comment]
When I install a fresh app, in global middleware `\Fruitcake\Cors\HandleCors`, it register A `Illuminate\Foundation\Http\Events\RequestHandled` in `handle` method. Maybe some patch should be apply to it.

https://github.com/laravel/laravel/blob/a6ffdbdf416d60c38443725807a260a84dca5045/composer.json#L10
https://github.com/fruitcake/laravel-cors/blob/5781ffce1f68cb003a36ddd1c66fcf70bae3c07d/src/HandleCors.php#L51

@themsaid

**Comment by themsaid** [comment]
@kiroto123 yes this is wrong and I'm going to report it to the package maintainers.

**Comment by kiroto123** [comment]
barryvdh/laravel-debugbar#1172

**Comment by barryvdh** [comment]
I fixed and released laravel-cors; https://github.com/fruitcake/laravel-cors/releases/tag/v2.0.4
Could you try that out?

I'll look into debugbar, that might be a bit more complex.

**Comment by kiroto123** [comment]
Yes, v2.0.4 works well now.
