### ISSUE TITLE
The system environment variables got overrided by the .env

### ISSUE THREAD

**Issue by litan1106** [laravel/octane#244]
- Octane Version: v0.4.2
- Laravel Version: v8.38.0
- PHP Version: 8.0.3
- Server: Swoole / RoadRunner (Same issue with both runtime)
- Database Driver & Version: Mysql 8.0

### Description:
The system environment variables got override by the .env in Octane but not php-fpm or php-cli.
**The system environment variables shouldn't be override by the .env in Octane.**

### Steps To Reproduce: (max and linux)

1. Test the laravel/octane in composer.json to v0.2.0

```
"laravel/octane": "~0.2.0",
```

2. Add a test route to web.php

```php
Route::get('test-sys-vars', function() {
    var_dump($_ENV['DB_USERNAME']);
    var_dump(config('database.connections.mysql.username'));
    var_dump(getenv('DB_USERNAME'));
    var_dump(getenv('DB_USERNAME', true));
    dd(env('DB_USERNAME'));
});
```

3. Run command in the current Laravel project directory.
```bash
export DB_USERNAME=example-app && php -dvariables_order=EGPCS artisan octane:start --server=roadrunner --host=0.0.0.0 --port=8000
```

4. Make sure DB_USERNAME exists in the .env
```
DB_USERNAME=homestead
```

5. Browse http://localhost:8000/test-sys-vars and see result

Then repeat 1 - 5 again with another version
```
"laravel/octane": "^0.4.0",
```

![image](https://user-images.githubusercontent.com/1310539/116454434-d6b60f00-a814-11eb-81aa-af14d15494ff.png)

**Comment by nunomaduro** [comment]
I wasn't able to reproduce this issue locally. Do you also face the issue when **not** using sail?

**Comment by anopier** [comment]
I also have the same problem and I'm not using sail.

**Comment by litan1106** [comment]
> I also have the same problem and I'm not using sail - I had to switch back to 0.2.0 to get it working.

Thanks for the confirmation.

**Comment by litan1106** [comment]
@nunomaduro maybe caused by these changes? (I compared v0.3.2 vs v0.2.0)

![image](https://user-images.githubusercontent.com/1310539/116281991-1f02fd80-a73f-11eb-8fee-60b3ddfb28d1.png)

https://github.com/laravel/octane/compare/v0.2.0...v0.3.2#diff-d86e0d58256c86388b8241b36f32171f8b2156aa131e205ddd18b13d7afb5825L82-R866

**Comment by L3o-pold** [comment]
I can confirm seeing this issue with v0.3.2+ using Kubernetes. Rolling back to v0.3.1 fixed it. But an important note is that we don't have any .env file (only environment variables var) and Octane are not seing them.

```bash
   WARN  Laravel Octane is within a beta period. It should only be used for local development and testing in order to improve the quality of the library and resolve any existing bugs.

   INFO  Server running…

  Local: http://0.0.0.0:8080 

  Press Ctrl+C to stop the server


   Illuminate\Encryption\MissingAppKeyException  No application encryption key has been specified.
```

**Comment by nunomaduro** [comment]
Currently investigating this...

**Comment by L3o-pold** [comment]
I prepared a sample Dockerfile for you if needed.

```bash
FROM php:8.0.3-cli-buster

RUN apt-get update && apt-get install -y \
	git \
	unzip \
	libzip-dev \
	&& rm -rf /var/lib/apt/lists/*

RUN pecl install swoole

RUN docker-php-ext-install pcntl zip \
	&& docker-php-ext-enable swoole.so pcntl.so zip.so

RUN curl -sS https://getcomposer.org/installer | php -- --$COMPOSER && mv composer.phar /usr/bin/composer

WORKDIR /var/www/html

RUN composer create-project laravel/laravel example-app

WORKDIR /var/www/html/example-app

RUN composer require laravel/octane \
	&& php artisan octane:install --server=swoole

RUN rm /var/www/html/example-app/.env

# dummy APP_KEY env var
ENV APP_KEY=vvVmYOwJCBY5k0Kr5ykVGe1qYbNNCGJL

EXPOSE 80

CMD ["php", "artisan", "octane:start", "--server=swoole", "--host=0.0.0.0", "--port=80"]
```

```bash
docker build -t test . && docker run test:latest
```

```bash
WARN  Laravel Octane is within a beta period. It should only be used for local development and testing in order to improve the quality of the library and resolve any existing bugs.

   INFO  Server running…

  Local: http://0.0.0.0:80 

  Press Ctrl+C to stop the server


   Illuminate\Encryption\MissingAppKeyException 

  No application encryption key has been specified.

  at vendor/laravel/framework/src/Illuminate/Encryption/EncryptionServiceProvider.php:79
     75▕     protected function key(array $config)
     76▕     {
     77▕         return tap($config['key'], function ($key) {
     78▕             if (empty($key)) {
  ➜  79▕                 throw new MissingAppKeyException;
     80▕             }
     81▕         });
     82▕     }
     83▕ }
```

**Comment by foremtehan** [comment]
Do you think this also affect this issue ? https://github.com/laravel/octane/issues/234

the `python` keyword as system env didnt work in 0.3.2+ but it work in 0.3.1

**Comment by litan1106** [comment]
> Do you think this also affect this issue ? #234
> 
> the `python` keyword as system env didnt work in 0.3.2+ but it work in 0.3.1

Nope. I am sure that was caused by this change. ( I already tested it. )

![image](https://user-images.githubusercontent.com/1310539/116567424-75e21180-a8bc-11eb-9a2d-e2b03464b9fb.png)

https://github.com/laravel/octane/compare/v0.3.1...v0.3.2#diff-d86e0d58256c86388b8241b36f32171f8b2156aa131e205ddd18b13d7afb5825L86

**Comment by zolotov88** [comment]
Same issue

**Comment by nunomaduro** [comment]
@zolotov88 @litan1106 @foremtehan @L3o-pold @anopier Can you all test this branch? https://github.com/laravel/octane/pull/257.

**Comment by L3o-pold** [comment]
@nunomaduro from my test case here https://github.com/laravel/octane/issues/244#issuecomment-829188654 the issue seems fixed 👍

**Comment by litan1106** [comment]
@nunomaduro This PR fixed my system env issue as well. Thanks again.
