### ISSUE TITLE
When can coroutines be supported?

### ISSUE THREAD

**Issue by codingheping** [laravel/octane#256]
Want to see laravel and coroutines used in combination

**Comment by nunomaduro** [comment]
It is in our backlog, but we are not sure yet if we will tackle it.

**Comment by jobsssss** [comment]
Can you explain why coroutines are not supported? If you don't support coroutines, it doesn't make much sense to use Octane, or is it convenient to tell you what the difficulties are in supporting coroutines? Or when do you plan to start supporting coroutines?

**Comment by Ekion-1** [comment]
I agree; it seems a bit short sighted. Don't get me wrong, I appreciate the work you guys have put into Octane but without coroutines I don't understand the real-world benefit.

@nunomaduro do you have an update from the team regarding if this will be tackled?

**Comment by foremtehan** [comment]
Does the use of `Swoole\Runtime::enableCoroutine();` alone suffice to transform an octane application into an asynchronous one?

**Comment by AuroraYolo** [comment]
Not good, laravel has too many global variables

> 单独使用是否`Swoole\Runtime::enableCoroutine();`足以将 Octane 应用程序转换为异步应用程序？
