### ISSUE TITLE
[Doc]: NGINX configuration atleast.

### ISSUE THREAD

**Issue by myckhel** [laravel/octane#268]
Now that octane stable version is about to be released, can we atleast see some example configurations?

I feel it will be good to add a deployment section to the docs stating how to deploy to production.

I think must of us doesn't know how to go about using the server in a production environment and since maybe this is the first time using laravel app as a server in production.

**Comment by flc1125** [comment]
- supervisor：`php artisan octane:start`
- nginx：`proxy_pass`

**Comment by joaovitorp** [comment]
```
server {
    root /data/wwwroot/;
    server_name teste.com;

    location / {
        proxy_http_version 1.1;
        proxy_set_header Connection "keep-alive";
        proxy_set_header X-Real-IP $remote_addr;
        if (!-e $request_filename) {
             proxy_pass http://127.0.0.1:8080;
        }
    }
}
```

**Comment by n3m3s7s** [comment]
check [https://github.com/laravel/octane/issues/254](url)
