### ISSUE TITLE
octane:status does not see the server process 

### ISSUE THREAD

**Issue by tsparksh** [laravel/octane#269]
- Octane Version: 0.5.0
- Laravel Version: 8.0
- PHP Version: 8.0
- Server & Version: Swoole 4.6.6
- Database Driver & Version: N/A

### Description:
`php artisan octane:status` in docker container tells that octane is not running, while it actually is.
`php artisan octane:start` does nothing, because port is already in use.

It reproduced two times with my config, on Windows and Os X host machines.

### Steps To Reproduce:
Not sure about the steps to reproduce. In my case: 
1) Start octane via `php artisan octane:start` in docker container
2) Close the shell window
3) Wait ??? minutes/hours
4) `php artisan octane:status` tells that octane is not running, while `ps -a` tells the opposite

```
/srv/app # php artisan octane:status

   INFO  Octane server is not running.
/srv/app # ps -a
PID   USER     TIME  COMMAND
    1 root      0:40 php-fpm: master process (/usr/local/etc/php-fpm.conf)
   23 root      0:08 crond
   26 root      3:17 {supervisord} /usr/bin/python3 /usr/bin/supervisord --configuration /etc/supervisord.conf
   27 1000      0:08 php-fpm: pool www
   28 1000      0:08 php-fpm: pool www
  267 root      0:00 sh
  324 root      3:37 php artisan octane:start --host=0.0.0.0 -q
  328 root      2:01 {php} swoole_http_server: master process for Laravel
  329 root      0:01 {php} swoole_http_server: manager process for Laravel
  334 root      0:00 {php} swoole_http_server: worker process for Laravel
  335 root      0:01 {php} swoole_http_server: worker process for Laravel
  380 1000      0:06 php-fpm: pool www
  591 root      0:00 sh
 1700 root      0:00 sh
153564 root      0:00 sh
153572 root      0:03 /usr/local/bin/php /srv/app/artisan rabbitmq:consume --tries --queue=*************
153573 root      0:03 /usr/local/bin/php /srv/app/artisan rabbitmq:consume --tries --queue=*************
153574 root      0:04 /usr/local/bin/php /srv/app/artisan rabbitmq:consume --tries --queue=*************
153575 root      0:03 /usr/local/bin/php /srv/app/artisan rabbitmq:consume --tries --queue=*************
160116 root      0:00 {php} swoole_http_server: task worker process for Laravel
160161 root      0:00 {php} swoole_http_server: task worker process for Laravel
160360 root      0:00 sh
160366 root      0:00 [php]
160392 root      0:00 ps -a
```

**Comment by bing15** [comment]
Laravel octane did not start in docker, there may be a problem with your steps

**Comment by tsparksh** [comment]
> Laravel octane did not start in docker, there may be a problem with your steps

I started it with `php artisan octane:start --host=0.0.0.0` (pid  324) and it's running

**Comment by nunomaduro** [comment]
At this point, we've multiple users that have followed **[this guide](https://laravel.com/docs/8.x/octane#swoole-via-laravel-sail)**, and didn't had issues running Octane in Docker containers. So this must be an issue with the way you've setup Octane in your Docker container.

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!

**Comment by sjsiam** [comment]
did you solve this issue? I am facing the same.

**Comment by halfstring** [comment]
The same issue, but I think I have fixed the cause.

After running the octane service, we modified storage/, for example, by pushing new code, and then attempted to execute octane:reload... However, storage/logs/octane-server-state.json had already been modified.

If we exclude folder storage/ when redeploying the code, this issue will not occur....

Record the solution here for future reference！
