### ISSUE TITLE
Issues with hook structure (apply_filters, add_action ...)

### ISSUE THREAD

**Issue by abdullahtekin** [laravel/octane#270]
- Octane Version: 1.0
- Laravel Version: 8.12
- PHP Version: 8.0.6
- Server & Version: Swoole / RoadRunner 4.6.6
- Database Driver & Version: mysql 5.7

### Description:
My laravel cms structure is usually coded hook (Look like Wordpress). When i use hook the Octane ignore this process. But Laravel serve is running correct. How can you help me this about?

### Steps To Reproduce:

Sample:
`$result = apply_filters(BASE_FILTER_PUBLIC_SINGLE_DATA, $slug);`

```
#doesn't work hooks
add_action('ThemeAfterBody', function () {
    echo "test";
});
```

This code lines ignore Octane and continue.

**Comment by themsaid** [comment]
Please elaborate. I don't understand your issue.
