### ISSUE TITLE
Wrong label for `INFO` and `WARNING` logs in terminal

### ISSUE THREAD

**Issue by seyed-me** [laravel/octane#272]
- Octane Version: 1.0.0
- Laravel Version: 8.41.0
- PHP Version: 8.0.6
- Server & Version: Swoole 4.6.6

### Description:
Octane labels `Log::info()`, `Log::warning('bar')` and `logger()`  as ERROR in terminal.

### Steps To Reproduce:
- serve Laravel via Octane
- use `Log::info('foo')` or `Log::warning('foo')` to log `foo` in terminal.

**Comment by DanCharousek** [comment]
@seyed-me 

I thought that I had a similar problem so I looked into it.
It seems this is not an issue with Octane itself. If you server freshly installed Laravel app with Octane and try to `Log::debug`, `Log::info` or `Log::warn` you will probably find out that it does not do anything. The default `LOG_CHANNEL` is `stack`. If you check the `config/logging.php` you'll see that the `stack` includes only channel `single` by default.

In my case, the "issue" was, that besides `single` I had also `stderr` included in the channel list of the stack (`'channels' => ['single', 'stderr']`. **This caused all output from the logger to appear in the console with ERROR label**.

If you look closer into https://github.com/laravel/octane/blob/1.x/src/Commands/Concerns/InteractsWithIO.php you'll see that Octane logs are being sent to the stdout. I do not thing you are able to output custom log levels into Octane's terminal output at the moment (although I might be wrong).

Try this simple demo:

```php
Route::get('/', function () {
    fwrite(STDERR, 'Lorem ipsum!');
    fwrite(STDOUT, 'Hello world!' . PHP_EOL);

    return view('welcome');
});
```

And you should see something similar in the terminal after hitting localhost:8000:

![image](https://user-images.githubusercontent.com/10319511/118545743-499d1080-b757-11eb-9dc4-f1798453380f.png)

Hope this helps.

**Comment by nunomaduro** [comment]
@DanCharousek is correct.
