### ISSUE TITLE
Fresh install laravel with Sail and RoadRunner

### ISSUE THREAD

**Issue by goszowski** [laravel/octane#275]
- Octane Version: ^1.0
- Laravel Version: ^8.40
- PHP Version: 8.0.5 (Sail)
- Server & Version: RoadRunner ^2.2

### Description:
After fresh installation i have the errors:
 INFO  Server running…
laravel.test_1  |
laravel.test_1  |   Local: http://0.0.0.0:80
laravel.test_1  |
laravel.test_1  |   Press Ctrl+C to stop the server
laravel.test_1  |
laravel.test_1  |
laravel.test_1  |    ERROR  2021-05-17T10:58:06.423Z	ERROR	container/poller.go:16	vertex got an error	{"vertex id": "service.Plugin", "error": "processor_start: exec: \"binary\": executable file not found in $PATH"}
laravel.test_1  |
laravel.test_1  |    ERROR  github.com/spiral/endure/pkg/container.(*Endure).poll.func1
laravel.test_1  |
laravel.test_1  |    ERROR  	github.com/spiral/endure@v1.0.1/pkg/container/poller.go:16
laravel.test_1  |
laravel.test_1  |    ERROR  panic: runtime error: invalid memory address or nil pointer dereference
laravel.test_1  |
laravel.test_1  |    ERROR  [signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xb32885]
laravel.test_1  |
laravel.test_1  |    ERROR  goroutine 61 [running]:
laravel.test_1  |
laravel.test_1  |    ERROR  github.com/spiral/roadrunner/v2/plugins/http.applyMiddlewares(0x0, 0xc00028c7e0, 0xc0004f5ba0, 0x1, 0x1, 0x1586b20, 0xc0000a1198)
laravel.test_1  |
laravel.test_1  |    ERROR  	github.com/spiral/roadrunner/v2@v2.2.1/plugins/http/serve.go:252 +0x225
laravel.test_1  |
laravel.test_1  |    ERROR  github.com/spiral/roadrunner/v2/plugins/http.(*Plugin).serveFCGI(0xc00019ae00, 0xc000091e00)
laravel.test_1  |
laravel.test_1  |    ERROR  	github.com/spiral/roadrunner/v2@v2.2.1/plugins/http/serve.go:76 +0x2ef
laravel.test_1  |
laravel.test_1  |    ERROR  github.com/spiral/roadrunner/v2/plugins/http.(*Plugin).serve.func3(0xc00019ae00, 0xc000091e00)
laravel.test_1  |
laravel.test_1  |    ERROR  	github.com/spiral/roadrunner/v2@v2.2.1/plugins/http/plugin.go:205 +0x35
laravel.test_1  |
laravel.test_1  |    ERROR  created by github.com/spiral/roadrunner/v2/plugins/http.(*Plugin).serve
laravel.test_1  |
laravel.test_1  |    ERROR  	github.com/spiral/roadrunner/v2@v2.2.1/plugins/http/plugin.go:204 +0x6f8
laravel.test_1  | 2021-05-17 10:58:07,868 INFO exited: php (exit status 2; not expected)
laravel.test_1  | 2021-05-17 10:58:08,872 INFO spawned: 'php' with pid 118

### Steps To Reproduce:
All default steps from documentation

**Comment by 48d90782** [comment]
The issue is from the `service` plugin: https://github.com/spiral/roadrunner-binary/blob/master/.rr.yaml#L314
It seems that the default config was used.

**Comment by goszowski** [comment]
> The issue is from the `service` plugin: https://github.com/spiral/roadrunner-binary/blob/master/.rr.yaml#L314
> It seems that the default config was used.

Where I can get non-default, laravel/ssail based .rr.yaml config?

**Comment by 48d90782** [comment]
I guess that it's better to wait for @nunomaduro answer 😃 I guess that for some reason, octane did not remove part of the config related to the default `service` plugin section.

**Comment by goszowski** [comment]
.rr.yaml must be empty.
