### ISSUE TITLE
Add missing property and return types

### ISSUE THREAD

**Issue by DanCharousek** [laravel/octane#281]
As I walk through the Octane's source code I notice there are inconsistencies in type definitions in properties, methods return types and parameter types (see attached screenshot for an example). I am willing to submit PR with filling those missing information as I believe that strict types can prevent possible errors. Is this something wanted by the project?

![image](https://user-images.githubusercontent.com/10319511/118546632-81f11e80-b758-11eb-9cc2-828e7747d8cd.png)

**Comment by themsaid** [comment]
Feel free to submit a PR.

**Comment by DanCharousek** [comment]
> Feel free to submit a PR.

Will do. Thank you.
