### ISSUE TITLE
Bug/Get Help: Octane:install and octane:start not working in Windows environment

### ISSUE THREAD

**Issue by francsiswanto** [laravel/octane#282]
- Octane Version: 1.0.0
- Laravel Version: 8.41.0
- PHP Version: 8.0.6
- Server & Version: RoadRunner 2.0.0
- Database Driver & Version: MySQL 8.0.23
- O/S: Windows 10 Pro

### Description 1:
Command of "artisan octane:install" not working properly and force me to download rr binary manually at https://github.com/spiral/roadrunner-binary/releases, this is the error messages:
```
E:\WebOnline\Apps\NSA\api\testoct>php artisan octane:install

 Which application server you would like to use?:
  [0] roadrunner
  [1] swoole
 > 0
0K

 Unable to locate RoadRunner binary. Should Octane download the binary for your operating system? (yes/no) [yes]:
 > yes
  Symfony\Component\Process\Exception\ProcessFailedException 
  The command "D:\PHP\php80nts\php.exe "./vendor/bin/rr" get-binary -n --ansi" failed.

Exit Code: 255(Unknown error)

Working directory: E:\WebOnline\Apps\NSA\api\testoct
Output:
================

Error Output:
================
  at E:\WebOnline\Apps\NSA\api\testoct\vendor\symfony\process\Process.php:267
    263      */
    264     public function mustRun(callable $callback = null, array $env = []): self
    265     {
    266         if (0 !== $this->run($callback, $env)) {
    267             throw new ProcessFailedException($this);
    268         }
    269
    270         return $this;
    271     }

  1   E:\WebOnline\Apps\NSA\api\testoct\vendor\laravel\framework\src\Illuminate\Support\HigherOrderTapProxy.php:34
      Symfony\Component\Process\Process::mustRun(Object(Closure))

      E:\WebOnline\Apps\NSA\api\testoct\vendor\laravel\octane\src\Commands\Concerns\InstallsRoadRunnerDependencies.php:175
      Illuminate\Support\HigherOrderTapProxy::__call("mustRun")
```

### Description 2:
Command of "artisan octane:start" also not working with this error messages:
```
E:\WebOnline\Apps\NSA\api\testoct>php artisan octane:start

  Unable to subscribe to signal events. Make sure that the `pcntl` extension is installed and that "pcntl_*" function
  s are not disabled by your php.ini's "disable_functions" directive.
```

### Comparing to other package:
Since laravel/octane does not working on my laptop, I've tried other package, https://github.com/spiral/roadrunner-laravel with brand new installation of Laravel 8 and it is working, and also working on my existing Laravel 8 project without major problem.

Please help, how do I fix this problem?

Thank you.

**Comment by woodspire** [comment]
Laravel Octane will not work on Windows.

The pcntl extension is required and it is not available on windows.

https://www.php.net/manual/en/pcntl.installation.php

**Comment by themsaid** [comment]
Use Sail https://github.com/laravel/sail

**Comment by francsiswanto** [comment]
> Laravel Octane will not work on Windows.
> 
> The pcntl extension is required and it is not available on windows.
> 
> https://www.php.net/manual/en/pcntl.installation.php

Thank you for this info, it would be way better if documentation in https://laravel.com/docs/8.x/octane mention about this fact.

**Comment by iVampireSP** [comment]
I found a magic way to run roadrunner on windows.

```powershell
php artisan make:command StartOctane
```

```php
<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;

class StartOctane extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'app:start-octane {--host=127.0.0.1} {--port=8000} {--workers=1}';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Command description';

    /**
     * Execute the console command.
     */
    public function handle()
    {
        $path = storage_path('logs/octane-server-state.json');
        if (file_exists($path)) {
            unlink($path);
        }

        $this->call('octane:start', [
            '--host' => $this->option('host'),
            '--port' => $this->option('port'),
            '--workers' => $this->option('workers'),
        ]);
    }
}

```

then run
```powershell
php .\artisan app:start-octane
```

You will see it works!!!

direct run octane:start on windows
![image](https://github.com/laravel/octane/assets/32544186/9ee14494-c270-4ab7-b0c9-2411781c6a04)

use command
![image](https://github.com/laravel/octane/assets/32544186/dcb5cce4-3b7e-4446-bcd5-d0caf94998af)

**Comment by HassanDomeDenea** [comment]
@iVampireSP 
I tried your code, I downloaded road-runner as stated here:
https://roadrunner.dev/docs/intro-config/current/en
by using the following commands:

`composer require spiral/roadrunner-cli
`
`./vendor/bin/rr get-binary
`

and I got the file `rr.exe` in the root of my project.


then copied your command, but got the following error:
![image](https://github.com/laravel/octane/assets/41169617/71d0a728-98f2-4a5a-8d4a-059e0152e856)

Although when I run the regular octane:start I get the usual error:
![image](https://github.com/laravel/octane/assets/41169617/36555f8b-aec0-4701-a150-53687807d0b2)

Any ideas ?

**Comment by ezalorpro** [comment]
> @iVampireSP I tried your code, I downloaded road-runner as stated here: https://roadrunner.dev/docs/intro-config/current/en by using the following commands:
> 
> `composer require spiral/roadrunner-cli ` `./vendor/bin/rr get-binary `
> 
> and I got the file `rr.exe` in the root of my project.
> 
> then copied your command, but got the following error: ![image](https://private-user-images.githubusercontent.com/41169617/301288586-71d0a728-98f2-4a5a-8d4a-059e0152e856.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgwNDA5NzksIm5iZiI6MTcwODA0MDY3OSwicGF0aCI6Ii80MTE2OTYxNy8zMDEyODg1ODYtNzFkMGE3MjgtOThmMi00YTVhLThkNGEtMDU5ZTAxNTJlODU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE1VDIzNDQzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY0MjcxMWNkOGE3Yzc3ZGEyNzYxMjI0ZmRlZTBmMjAyY2Y4Njc1YWQyMzg3MjM2MWE3MzhjMWFiMjY4ZjEyMzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.iB4zAiNQOZzjmzb0B8vzdTypq5mqFCJ4f7hdS7J-4qI)
> 
> Although when I run the regular octane:start I get the usual error: ![image](https://private-user-images.githubusercontent.com/41169617/301288914-36555f8b-aec0-4701-a150-53687807d0b2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgwNDA5NzksIm5iZiI6MTcwODA0MDY3OSwicGF0aCI6Ii80MTE2OTYxNy8zMDEyODg5MTQtMzY1NTVmOGItYWVjMC00NzAxLWExNTAtNTM2ODc4MDdkMGIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE1VDIzNDQzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg1OTBjMGNiMTk2OGMzMzZlM2FmNWU0NThmNDc0NWEyZTU1NDY2MGU4MDVhMmEzYmExNjQyMTRmNGFlNGQ0YjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BX__IQd0S8yiEOUYls_NpXopVn8HnjmYYkRHMhrqVcw)
> 
> Any ideas ?

I encountered the same issue after runing the custom command suggested by @iVampireSP . The solution was to install `spiral/roadrunner-http:^3.3.0`, after that, the command suggested by @iVampireSP works. 

Explanation:

Octane checks for Roadrunner installation using the `isRoadRunnerInstalled()` function, which verifies the existence of the PSR7Worker::class. This class is part of the roadrunner-http package. 

If you want to know where i got the roadrunner-http, you can check the function `ensureRoadRunnerPackageIsInstalled()` function inside `Laravel\Octane\Commands\Concerns\InstallsRoadRunnerDependencies`, in there you have this:

![image](https://github.com/laravel/octane/assets/37134637/3848aa52-9e2c-4da6-9f0d-e7ad87e8625e)

Oh and sorry for commenting on a closed issue. Cheers!
