### ISSUE TITLE
artisan octane:install cannot update the .env file on Lumen

### ISSUE THREAD

**Issue by FrontEndCoffee** [laravel/octane#284]
- Octane Version: 1.0.1
- Laravel Version: Lumen 8.2.3
- PHP Version: 8.0.6
- Server & Version: Swoole
- Database Driver & Version: PostgeSQL (not relevant)

### Description:

In order to update the .env file when setting up Octane, the install command tries to resolve the path of the .env file. This is done through the `app()->environmentFile()` function. Only, this function is not defined in the Lumen `Application` class. 

The error message is really clear, but I'm including it anyway:
```
In InstallCommand.php line 63:

  Call to undefined method Laravel\Lumen\Application::environmentFile()

```

The line of code in the install command (in latest 1.x commit): https://github.com/laravel/octane/blob/3ab6e1c221659a2ad0ead019ccbcc151a0e6ae06/src/Commands/InstallCommand.php#L63

### Steps To Reproduce:

* Clone a lumen project
* Install octane
* run `php artisan octane:install`

**Comment by FrontEndCoffee** [comment]
I have manually completed the octane installation, however, I can see that there is more that doesn't work with lumen. Both `StartRoadRunnerCommand` and `StartSwooleCommand` use the `Laravel\Octane\Commands\Concerns\InteractsWithEnvironmentVariables` trait that has the same problem as the piece of code in the `InstallCommand`. 

And thus, running `php artisan octane:start` results in:

```
In InteractsWithEnvironmentVariables.php line 23:

  Call to undefined method Laravel\Lumen\Application::environmentPath()

```

**Comment by nunomaduro** [comment]
Since Lumen is a totally separate framework from Laravel, it does not intentionally offer compatibility with any additional Laravel libraries like Cashier, Octane, Passport, Scout, etc. If your application requires the functionality provided by these libraries, please use the Laravel framework.
