### ISSUE TITLE
Octane with roadrunner unresponsive after benchmark

### ISSUE THREAD

**Issue by dyanakiev** [laravel/octane#289]
- Octane Version: latest
- Laravel Version: latest
- PHP Version: 8.0.6
- Server & Version: Swoole / RoadRunner: rr version 2.2.1 (build time: 2021-05-13T18:00:30+0000, go1.16.4)
- Database Driver & Version: n/a
- Workers: 16 
- OS: MacOS Big Sur

### Description:
Hello, i installed octane on plain laravel setup then i ran `wrk -t12 -c400 -d30s http://localhost:8000/` to test, after it finished the octane/roadruner server become unresponsive and this error thrown in the browser 

```
http_plugin_serve_http: Timeout:
    supervised_exec_with_context: context deadline exceeded
```

There are also more than 20 of this processes
![image](https://user-images.githubusercontent.com/11967079/119231828-65276300-bb2b-11eb-9a9f-03868af35d67.png)

Is this normal behaviour? I hit it really hard but i would expect it to resurrect itself but it's still unresponsive even after few minutes.

### Steps To Reproduce:
1. install laravel
2. install octane with roadrunner
3. run `wrk -t12 -c400 -d30s http://localhost:8000/`

**Comment by dyanakiev** [comment]
Just tested with Swoole and its handling the benchmark with no hassle!

**Comment by nunomaduro** [comment]
That error is coming from the `rr` binary, therefore you may need to report that issue here: https://github.com/spiral/roadrunner-binary.

**Comment by dyanakiev** [comment]
@nunomaduro https://github.com/spiral/roadrunner-binary/issues/62

**Comment by dyanakiev** [comment]
> @dyanakiev is it possible to show the full tree view of the processes being spawned starting with the `php artisan octane:start` process?

I just tested again and i don't see any processes spawned this time, only the main one.  🤨 🤔
![image](https://user-images.githubusercontent.com/11967079/120853804-e1d32c00-c584-11eb-8770-b1d46ba2ed63.png)

But still roadrunner dies  
```
http_plugin_serve_http: Timeout:
	supervised_exec_with_context: context deadline exceeded
```

**Comment by rustatian** [comment]
@driesvints You just oversaturate a RR pipeline with a bunch of requests. RR tries to never lose a single request making a pipeline. My advice is to do the following:
1. Instantiate more workers OR
2. Increase allocate timeout (which is used to get a free worker from the pipeline to handle a request)
Also, hard to say, how many workers are handling your requests, what is the current allocate_timeout because you won't provide a run configuration.

**Comment by Namoshek** [comment]
@rustatian With todays tools, one would normally use horizontal scaling to deal with more requests. Providing some flexibility similar to Horizon workers would be ok for smaller deployments, but not for larger setups. Using request processing times to scale, seems like a good option.

**Comment by rustatian** [comment]
@Namoshek I'm not familiar with the Horizon, but in general, we already had some discussions internally to provide the ability to auto-scale workers based on some metrics. I agree, that processing timers would be a good option here.

**Comment by driesvints** [comment]
@rustatian why did you mention me here?

**Comment by rustatian** [comment]
@driesvints Sorry, misclicked. I wanted to mention @dyanakiev
