### ISSUE TITLE
Wrong user_id in session table

### ISSUE THREAD

**Issue by captenmasin** [laravel/octane#300]
- Octane Version: 1.0.2
- Laravel Version: 8.44.0
- PHP Version: 8.0.5
- Server & Version: Swoole 4.6.4
- Database Driver & Version: Database (MySql 5.7.34)

### Description:
When Swoole is enabled the user_id in the sessions table does not seem to change, i.e I login as user_id 2 which saves fine and then if I logout and log back in as user_id 32 it adds a row to the sessions table with user_id 2

### Steps To Reproduce:
- Install fresh Laravel application with Fortify Auth
- Install Swoole
- Run Swoole via `artisan octane:start --port=8000 --server=swoole --max-requests=500 --workers=auto --no-interaction --watch` 
- Set `SESSION_DRIVER=database`
- Ensure cache is disabled `CACHE_DRIVER=array`
- Login as a user
- Check sessions table
- Logout and login as a different user
- Check new record in sessions table

**Comment by themsaid** [comment]
fixed in https://github.com/laravel/octane/pull/302
