### ISSUE TITLE
Mix asset function keeps data in memory

### ISSUE THREAD

**Issue by Jefemy** [laravel/octane#301]
- Octane Version: 1.0.2
- Laravel Version: 8.44.0
- PHP Version: 8.0.1
- Server & Version:  RoadRunner 2.2.1

### Description:
Mix asset function keeps manifest data in memory causing issues with local development with the function outputting an invalid url

### Steps To Reproduce:
 - Generate a mix-manifest.json file and use the mix function to output it
 - Startup all RR workers to get the manifest in memory
 - Change value in mix-manifest.json
 - Mix will continue to output the old value until restarted

**Comment by sikhlana** [comment]
Does adding the '--watch' switch fix the issue?

**Comment by Jefemy** [comment]
> Does adding the '--watch' switch fix the issue?

Already using it, although I just noticed that there is a watch config that allows me to add mix-manifest to be watched. Perhaps it should be included by default?

**Comment by sikhlana** [comment]
The watch already includes the resources subdirectory. And mix-manifest.json isn't included as it's a generated file which doesn't exist if you never run NPM's build script.

**Comment by driesvints** [comment]
You shouldn't manually edit your `mix-manifest.json`. Like @sikhlana explained, the resources directory is already being watched when you use `npm watch`.

**Comment by Jefemy** [comment]
> You shouldn't manually edit your `mix-manifest.json`. Like @sikhlana explained, the resources directory is already being watched when you use `npm watch`.

Does the config clearly not state that by default only php files are being watched? https://github.com/laravel/octane/blob/54e6677304cf317403ac18f5e3511de864346cc5/config/octane.php#L175

**Comment by sikhlana** [comment]
The Mix Manifest needs to be kept in-memory due to performance issue but I guess in development mode that shouldn't be the case. I'll look at what I can do. In the mean time change `resources/**/*.php` to `resources/**/*` in your config file.
