### ISSUE TITLE
Set custom package max length for Swoole

### ISSUE THREAD

**Issue by VoronovAlexander** [laravel/octane#306]
Hi, I can't set custom package max length because in command it is hardcoded values

<img width="848" alt="image" src="https://user-images.githubusercontent.com/32374709/120528011-6a6e9280-c3f4-11eb-94be-2f841f8ece5f.png">

Pls make params inside config/octane.php for override default values

Thanks

**Comment by sy-records** [comment]
You can add to config/octane.php

```php
    'swoole' => [
        'options' => [
                'package_max_length' => 20 * 1024 *1024,
        ],
    ],
```
