### ISSUE TITLE
Possible memory leak swoole

### ISSUE THREAD

**Issue by dyanakiev** [laravel/octane#308]
- Octane Version: latest
- Laravel Version: latest
- PHP Version: 8
- Server & Version: Swoole
- Database Driver & Version: MySQL

### Description:

When i use `ModelName::create(['something'=>'something'])` and there is unique index in the database when error is thrown i notice that the memory usage is building up when i hit this particular request.

```
500    POST /something/install ....... 15.68 mb 3.33 ms
500    POST /something/install ....... 15.68 mb 3.22 ms
500    POST /something/install ....... 15.68 mb 3.25 ms
500    POST /something/install ....... 15.69 mb 3.07 ms
500    POST /something/install ....... 15.69 mb 3.35 ms
500    POST /something/install ....... 15.69 mb 3.42 ms
500    POST /something/install ....... 15.69 mb 3.25 ms
500    POST /something/install ....... 15.69 mb 3.38 ms
500    POST /something/install ....... 15.69 mb 3.34 ms
500    POST /something/install ....... 15.70 mb 3.17 ms
500    POST /something/install ....... 15.70 mb 3.01 ms
500    POST /something/install ....... 15.70 mb 3.40 ms
500    POST /something/install ....... 15.70 mb 4.17 ms
500    POST /something/install ....... 15.70 mb 3.10 ms
500    POST /something/install ....... 15.70 mb 3.52 ms
500    POST /something/install ....... 15.71 mb 3.29 ms
500    POST /something/install ....... 15.71 mb 3.02 ms
500    POST /something/install ....... 15.71 mb 3.00 ms
500    POST /something/install ....... 15.71 mb 3.04 ms
500    POST /something/install ....... 15.71 mb 3.16 ms
500    POST /something/install ....... 15.71 mb 3.06 ms
500    POST /something/install ....... 15.72 mb 3.11 ms
500    POST /something/install ....... 15.72 mb 3.11 ms
500    POST /something/install ....... 15.72 mb 3.15 ms
500    POST /something/install ....... 15.72 mb 3.02 ms
500    POST /something/install ....... 15.72 mb 3.91 ms
500    POST /something/install ....... 15.72 mb 3.66 ms
500    POST /something/install ....... 15.73 mb 3.36 ms
500    POST /something/install ....... 15.73 mb 3.37 ms
500    POST /something/install ....... 15.73 mb 3.21 ms
500    POST /something/install ....... 15.73 mb 3.37 ms
```

### Steps To Reproduce:
Create table with unique rule, then try to create something with eloquent `ModelName::create(['something'=>'something'])`

**Comment by dyanakiev** [comment]
I fell like this memory reporting thingy is not working as supposed, i noticed the memory going down after some time. It also happens on other requests. So it might not be eloquent issue.

**Comment by tm1000** [comment]
@dyanakiev Do you have telescope enabled?

**Comment by dyanakiev** [comment]
> @dyanakiev Do you have telescope enabled?

No i don't use telescope, this are my only packages

```
    "require": {
        "php": "8.*",
        "ext-pdo": "*",
        "fideloper/proxy": "^4.4",
        "fruitcake/laravel-cors": "^2.0",
        "guzzlehttp/guzzle": "^7.0.1",
        "laravel/framework": "^8.40",
        "laravel/octane": "^1.0"
    },
    "require-dev": {
        "facade/ignition": "^2.5",
        "nunomaduro/collision": "^5.0"
    },
 ```

**Comment by themsaid** [comment]
The leak is in facade/ignition. Fixed https://github.com/facade/ignition/pull/393

**Comment by dyanakiev** [comment]
It looks like the leak is still here even after i removed facade/ignition i don't have any middlewares other than the laravel's default.

**Comment by dyanakiev** [comment]
@themsaid @driesvints sorry to ping you but i think this issue needs to be reopened i discovered the following issue:

I installed fresh laravel and added octane with swoole, when i run it without touching anything its all fine but when i add `return abort(404)` to the routes/web.php default route the memory starts to increase again over time.

**Comment by driesvints** [comment]
ping @themsaid ^

**Comment by tm1000** [comment]
@dyanakiev I dont appear to have the same issue

```
  404    GET / .............................................. 17.63 mb 93.02 ms
  404    GET / ............................................... 17.73 mb 3.48 ms
  404    GET / ............................................... 17.73 mb 3.35 ms
  404    GET / ............................................... 17.73 mb 3.38 ms
  404    GET / ............................................... 17.73 mb 3.36 ms
  404    GET / ............................................... 17.73 mb 3.36 ms
  404    GET / ............................................... 17.73 mb 3.54 ms
  404    GET / ............................................... 17.73 mb 3.37 ms
  404    GET / ............................................... 17.73 mb 3.29 ms
  404    GET / ............................................... 17.73 mb 3.71 ms
  404    GET / ............................................... 17.73 mb 3.62 ms
  404    GET / ............................................... 17.73 mb 3.45 ms
  404    GET / ............................................... 17.73 mb 3.45 ms
  404    GET / ............................................... 17.73 mb 3.45 ms
```

**Comment by dyanakiev** [comment]
> @dyanakiev I dont appear to have the same issue
> 
> ```
>   404    GET / .............................................. 17.63 mb 93.02 ms
>   404    GET / ............................................... 17.73 mb 3.48 ms
>   404    GET / ............................................... 17.73 mb 3.35 ms
>   404    GET / ............................................... 17.73 mb 3.38 ms
>   404    GET / ............................................... 17.73 mb 3.36 ms
>   404    GET / ............................................... 17.73 mb 3.36 ms
>   404    GET / ............................................... 17.73 mb 3.54 ms
>   404    GET / ............................................... 17.73 mb 3.37 ms
>   404    GET / ............................................... 17.73 mb 3.29 ms
>   404    GET / ............................................... 17.73 mb 3.71 ms
>   404    GET / ............................................... 17.73 mb 3.62 ms
>   404    GET / ............................................... 17.73 mb 3.45 ms
>   404    GET / ............................................... 17.73 mb 3.45 ms
>   404    GET / ............................................... 17.73 mb 3.45 ms
> ```

Is this on clean laravel project?

**Comment by themsaid** [comment]
@dyanakiev  with a fresh Laravel app, I can't replicate. Make sure the facade/ignition package is up to date.

**Comment by k2levin** [comment]
using fresh install still having memory leak issue when using `abort()` or `throw()` methods,
(heavy usage inside private sub method),

fresh laravel install with default packages + `laravel/octane` only
besides, checked that is latest `facade/ignition` in composer.lock
