### ISSUE TITLE
Missing Listeners from Octane.php config

### ISSUE THREAD

**Issue by tm1000** [laravel/octane#310]
The default octane config (https://github.com/laravel/octane/blob/1.x/config/octane.php#L61) has several listeners declared so that users can add their own, however it appears that some are missing:

- https://github.com/laravel/octane/blob/1.x/src/Events/TaskTerminated.php
- https://github.com/laravel/octane/blob/1.x/src/Events/TickTerminated.php

**Comment by driesvints** [comment]
If this is a bug report please fill out the issue template. If it's a feature request please send in a pr. Thanks

**Comment by tm1000** [comment]
@driesvints It was more of a "should it be this way". All good I will do the PR! :-)

**Comment by driesvints** [comment]
@tm1000 Thanks. Usually it's better to send in a pr so we can look at actual code.
