### ISSUE TITLE
Customize HTTP request class for server

### ISSUE THREAD

**Issue by digitv** [laravel/octane#318]
Greetings!
Previously I've used PHP-PM to serve application and I was able to change request class `\Illuminate\Http\Request` to application's own (let's say `\App\Http\Request` for some operations within request context). Because extensive usage of added methods macroses are realy slow for this purpose (call overhead through magic PHP methods).
Could you make such possibility here via octane config?

I could make a PR to speed up process :grin:

**Comment by driesvints** [comment]
Heya. It's probably best that you send in an actual PR so we can look at code to evaluate this. Thanks.
