### ISSUE TITLE
Swoole breaks on file-upload

### ISSUE THREAD

**Issue by maher1337** [laravel/octane#321]
- Octane Version: 1.0.3
- Laravel Version: 8.45.1
- PHP Version: 8.0.5
- Server & Version: Swoole / RoadRunner Swoole
- Database Driver & Version: mysql

### Description:
It seems like when a POST request to an API route is sent with files included (array of files) the swoole server breaks and doesn't even show logs of receiving the request.
Then it would timeout.

### Steps To Reproduce:

Create an API route.
Upload files to the route and the the server will break.

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!

**Comment by barryvdh** [comment]
Maybe fixed with https://github.com/laravel/octane/pull/317 already?

**Comment by maher1337** [comment]
Yes thanks @barryvdh it was singleton issues from firebase kreait, they need to update to support Octane.
The solution was to create asynchronous background jobs to finish the uploads on receive to use the regular PHP-FPM
