### ISSUE TITLE
octane with laravel sail

### ISSUE THREAD

**Issue by Corymillz** [laravel/octane#322]
I am kinda new to docker but making good progress working with it and laravel. I have it running and decided to implement laravel octane following the doc.
first 
````
./vendor/bin/sail artisan sail:publish
````
and then editing the created supervisor file in the docker folder of my application with
````
command=/usr/bin/php -d variables_order=EGPCS /var/www/html/artisan octane:start --server=swoole --host=0.0.0.0 --port=8000
````
and then ````sail build````
but getting this error when i run ````sail up````
>   There are no commands defined in the "octane" namespace.

what am i doing wrong?

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by MehdiAghighi** [comment]
@Corymillz did you found a solution ?
i get this error too

**Comment by leitom** [comment]
Running: "sail build" gives me this error:

`#6 48.54 E: Unable to locate package php8.1-cli
#6 48.54 E: Couldn't find any package by glob 'php8.1-cli'
#6 48.54 E: Couldn't find any package by regex 'php8.1-cli'
#6 48.54 E: Unable to locate package php8.1-dev
#6 48.54 E: Couldn't find any package by glob 'php8.1-dev'
#6 48.54 E: Couldn't find any package by regex 'php8.1-dev'
#6 48.54 E: Unable to locate package php8.1-pgsql
#6 48.54 E: Couldn't find any package by glob 'php8.1-pgsql'
#6 48.54 E: Couldn't find any package by regex 'php8.1-pgsql'
#6 48.54 E: Unable to locate package php8.1-sqlite3
#6 48.54 E: Couldn't find any package by glob 'php8.1-sqlite3'
#6 48.54 E: Couldn't find any package by regex 'php8.1-sqlite3'
#6 48.54 E: Unable to locate package php8.1-gd
#6 48.54 E: Couldn't find any package by glob 'php8.1-gd'
#6 48.54 E: Couldn't find any package by regex 'php8.1-gd'
#6 48.54 E: Unable to locate package php8.1-curl
#6 48.54 E: Couldn't find any package by glob 'php8.1-curl'
#6 48.54 E: Couldn't find any package by regex 'php8.1-curl'
#6 48.54 E: Unable to locate package php8.1-imap
#6 48.54 E: Couldn't find any package by glob 'php8.1-imap'
#6 48.54 E: Couldn't find any package by regex 'php8.1-imap'
#6 48.54 E: Unable to locate package php8.1-mysql
#6 48.54 E: Couldn't find any package by glob 'php8.1-mysql'
#6 48.54 E: Couldn't find any package by regex 'php8.1-mysql'
#6 48.54 E: Unable to locate package php8.1-mbstring
#6 48.54 E: Couldn't find any package by glob 'php8.1-mbstring'
#6 48.54 E: Couldn't find any package by regex 'php8.1-mbstring'
#6 48.54 E: Unable to locate package php8.1-xml
#6 48.54 E: Couldn't find any package by glob 'php8.1-xml'
#6 48.54 E: Couldn't find any package by regex 'php8.1-xml'
#6 48.54 E: Unable to locate package php8.1-zip
#6 48.54 E: Couldn't find any package by glob 'php8.1-zip'
#6 48.54 E: Couldn't find any package by regex 'php8.1-zip'
#6 48.54 E: Unable to locate package php8.1-bcmath
#6 48.54 E: Couldn't find any package by glob 'php8.1-bcmath'
#6 48.54 E: Couldn't find any package by regex 'php8.1-bcmath'
#6 48.54 E: Unable to locate package php8.1-soap
#6 48.54 E: Couldn't find any package by glob 'php8.1-soap'
#6 48.54 E: Couldn't find any package by regex 'php8.1-soap'
#6 48.54 E: Unable to locate package php8.1-intl
#6 48.54 E: Couldn't find any package by glob 'php8.1-intl'
#6 48.54 E: Couldn't find any package by regex 'php8.1-intl'
#6 48.54 E: Unable to locate package php8.1-readline
#6 48.54 E: Couldn't find any package by glob 'php8.1-readline'
#6 48.54 E: Couldn't find any package by regex 'php8.1-readline'
#6 48.54 E: Unable to locate package php8.1-ldap
#6 48.54 E: Couldn't find any package by glob 'php8.1-ldap'
#6 48.54 E: Couldn't find any package by regex 'php8.1-ldap'
#6 48.54 E: Unable to locate package php8.1-msgpack
#6 48.54 E: Couldn't find any package by glob 'php8.1-msgpack'
#6 48.54 E: Couldn't find any package by regex 'php8.1-msgpack'
#6 48.54 E: Unable to locate package php8.1-igbinary
#6 48.54 E: Couldn't find any package by glob 'php8.1-igbinary'
#6 48.54 E: Couldn't find any package by regex 'php8.1-igbinary'
#6 48.54 E: Unable to locate package php8.1-redis
#6 48.54 E: Couldn't find any package by glob 'php8.1-redis'
#6 48.54 E: Couldn't find any package by regex 'php8.1-redis'
#6 48.54 E: Unable to locate package php8.1-swoole
#6 48.54 E: Couldn't find any package by glob 'php8.1-swoole'
#6 48.54 E: Couldn't find any package by regex 'php8.1-swoole'
#6 48.54 E: Unable to locate package php8.1-memcached
#6 48.54 E: Couldn't find any package by glob 'php8.1-memcached'
#6 48.54 E: Couldn't find any package by regex 'php8.1-memcached'
#6 48.54 E: Unable to locate package php8.1-pcov
#6 48.54 E: Couldn't find any package by glob 'php8.1-pcov'
#6 48.54 E: Couldn't find any package by regex 'php8.1-pcov'
#6 48.54 E: Unable to locate package php8.1-xdebug
#6 48.54 E: Couldn't find any package by glob 'php8.1-xdebug'
#6 48.54 E: Couldn't find any package by regex 'php8.1-xdebug'
------
executor failed running [/bin/sh -c apt-get update     && apt-get install -y gnupg gosu curl ca-certificates zip unzip git supervisor sqlite3 libcap2-bin libpng-dev python2     && mkdir -p ~/.gnupg     && chmod 600 ~/.gnupg     && echo "disable-ipv6" >> ~/.gnupg/dirmngr.conf     && apt-key adv --homedir ~/.gnupg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys E5267A6C     && apt-key adv --homedir ~/.gnupg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys C300EE8C     && echo "deb http://ppa.launchpad.net/ondrej/php/ubuntu hirsute main" > /etc/apt/sources.list.d/ppa_ondrej_php.list     && apt-get update     && apt-get install -y php8.1-cli php8.1-dev        php8.1-pgsql php8.1-sqlite3 php8.1-gd        php8.1-curl        php8.1-imap php8.1-mysql php8.1-mbstring        php8.1-xml php8.1-zip php8.1-bcmath php8.1-soap        php8.1-intl php8.1-readline        php8.1-ldap        php8.1-msgpack php8.1-igbinary php8.1-redis php8.1-swoole        php8.1-memcached php8.1-pcov php8.1-xdebug     && php -r "readfile('https://getcomposer.org/installer');" | php -- --install-dir=/usr/bin/ --filename=composer     && curl -sL https://deb.nodesource.com/setup_$NODE_VERSION.x | bash -     && apt-get install -y nodejs     && npm install -g npm     && curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -     && echo "deb https://dl.yarnpkg.com/debian/ stable main" > /etc/apt/sources.list.d/yarn.list     && apt-get update     && apt-get install -y yarn     && apt-get install -y mysql-client     && apt-get install -y postgresql-client     && apt-get -y autoremove     && apt-get clean     && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*]: exit code: 100
ERROR: Service 'app.postnord.no.test' failed to build : Build failed`
