### ISSUE TITLE
LARAVEL_START constants not defined and not re-initiate the value on each request

### ISSUE THREAD

**Issue by Afatkharrofiqi** [laravel/octane#328]
- Octane Version: 1.0
- Laravel Version: 8.47
- PHP Version: 8.0.7
- Server & Version: Swoole 4.6.7

### Description:
Undefined constant "LARAVEL_START"

Then i try move to bootstrap/app.php, it works. 
But the value of LARAVEL_START not reset the microtime on each request

`Route::get('/', function () {
    return "Connected successfully ". round((microtime(true) - LARAVEL_START) * 1000) . ' ms';
});`

**Comment by driesvints** [comment]
Octane is a long running process so it's not reset for each request.

**Comment by HDVinnie** [comment]
I know this is old but @Afatkharrofiqi or @driesvints is there a way to get around this so LARAVEL_START can still be used.

**Comment by williamxsp** [comment]
@HDVinnie 
Ive created a Listener class to define, if not defined, LARAVEL_START


```
namespace App\Listeners;

class RequestReceived
{
    public function handle()
    {
        defined('LARAVEL_START') or define('LARAVEL_START', microtime(true));
    }
}
```

Then at config/octane.php

and inside listeners, I added this class

```'listeners' => [
...

        RequestReceived::class => [
            ...Octane::prepareApplicationForNextOperation(),
            ...Octane::prepareApplicationForNextRequest(),
            \App\Listeners\RequestReceived::class
        ],
...
```

**Comment by joe820912boy** [comment]
@HDVinnie 

This day, I find that LARAVEL_START couldn't use in octane when I want to get the time of the request after processing. 

[ref.](https://stackoverflow.com/questions/32839866/log-actions-in-laravel-and-execution-time)

And you could see the error log that LARAVEL_START undefined in terminated function.
