### ISSUE TITLE
php artisan fail to maximize cpu usage

### ISSUE THREAD

**Issue by Afatkharrofiqi** [laravel/octane#329]
- Octane Version: 1.0
- Laravel Version: 8.47.0
- PHP Version: 8.0.7
- Server & Version: Swoole 4.6.7
- Specification Server: cpu 16 core, ram 32 GB, hdd 100 GB

### Description:
I'm trying to benchmark when using php artisan and not, and when not using php artisan, i can get 3000+req/second using wrk.

1. Benchmark using **php artisan octane:start --server=swoole** 
- result in another server to test using wrk
` wrk -t4 -c100 -d10s http://10.200.210.64/`
![image](https://user-images.githubusercontent.com/14047473/122665966-bed78780-d1d4-11eb-8f60-75c9caf09eec.png)
- cpu tree in server octane using htop:
**The root process of swoole_http_server is below php artisan octane:start --server=swoole**
![image](https://user-images.githubusercontent.com/14047473/122665767-5d62e900-d1d3-11eb-8a14-b5140d222432.png)
- **CPU usage** in server octane and **all CPU not maximize, each cpu approximately 30%**:
![image](https://user-images.githubusercontent.com/14047473/122665918-6e602a00-d1d4-11eb-9258-b7ad11eff00f.png)

2. Benchmark **without php artisan**:
- result in another server to test using wrk 
` wrk -t4 -c100 -d10s http://10.200.210.64/`
![image](https://user-images.githubusercontent.com/14047473/122664935-8af96380-d1ce-11eb-8be2-da56d2d15b29.png)
- this cpu tree in server octane using htop:
**This root process swoole_http_server not using php artisan**
![image](https://user-images.githubusercontent.com/14047473/122665312-ae251280-d1d0-11eb-83b3-19fb00a857fa.png)
- **CPU usage** in server octane and **all CPU is push to max usage, each cpu approximately 66%+**:
![image](https://user-images.githubusercontent.com/14047473/122665614-6d2dfd80-d1d2-11eb-9f5e-67309862f87e.png)

3. Conclussion:
When not using php artisan i get 3 times faster than php artisan
### Steps To Reproduce:
How to reproduce running without php artisan,
actually im using php artisan to run this, but this method is tricky
first i run php artisan in background using 
`php artisan octane:start --server=swoole &`
then i close the ssh terminal
and finally i can running octane without using php artisan and maximize cpu usage

is this bug or some feature? i hope i can maximize the cpu usage when using php artisan..
nb: i try adding some flag like `--workers=16 `and `--task-workers=16` the result is same not improve cpu usage.

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!
