### ISSUE TITLE
Support the prometheus metrics in roadrunner

### ISSUE THREAD

**Issue by ohnotnow** [laravel/octane#330]
Hi,

I was interested in Octane to get some of the native [prometheus metrics](https://roadrunner.dev/docs/beep-beep-metrics) roadrunner can serve.  I thought I'd try putting a `.rr.yml` file in the root of my project, but it doesn't seem to get picked up so I guess it's not being used by Octane.

Would there be any chance of allowing us to either customize roadrunner, or some setting in the octane config file to enable the metrics?  They're very handy for monitoring and alerting.

**Comment by driesvints** [comment]
Think this is best to continued in a PR so we can look at the code needed to make this happen. Thanks

**Comment by ohnotnow** [comment]
@pvs9 ah! I had missed that when I was skimming the code - thanks!
