### ISSUE TITLE
Cache store [octane] is not defined.

### ISSUE THREAD

**Issue by jcsoriano** [laravel/octane#334]
- Octane Version: 1.0.6
- Laravel Version: 8.47.0
- PHP Version: 8.0.7
- Server & Version: Swoole 4.6.7
- Database Driver & Version: mysql 8.0.23

### Description:

When I set `CACHE_DRIVER=octane` I get this error:

<img width="694" alt="image" src="https://user-images.githubusercontent.com/5937317/123536731-b47e3600-d75e-11eb-8a92-14e4e7b9b7cd.png">

### Steps To Reproduce:

```
composer require laravel/octane
php artisan octane:install
# Set CACHE_DRIVER=octane in .env
# Do anything (e.g. php artisan tinker) you will now get the error
```

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by thesafaraliyev** [comment]
Put the following code in my cache.php `stores` array

`'octane' => [
      'driver' => 'octane',
  ]`

**Comment by thesafaraliyev** [comment]
Put `'octane' => ['driver' => 'octane', ],` in cache.php `stores` array :)
