### ISSUE TITLE
Auth not working

### ISSUE THREAD

**Issue by Cplatinado** [laravel/octane#336]
- Octane Version: 1,0,6
- Laravel Version:8.48.2
- PHP Version: 8.0.5
- Server & Version: Swoole  
- Database Driver & Version: mysql 8

### Description:

when I use the Auth facede it can't find the logged in user, I give the command octane:reload and then it works, however if I go into another browser it gives the same error, and neither of the two browsers can find the logged user , so I stopped octane and started artisan serve and everything went normally in both browsers

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
