### ISSUE TITLE
octane:reload on symlink strategy, doesn't reflect changes

### ISSUE THREAD

**Issue by kevincobain2000** [laravel/octane#338]
- Octane Version: 1.0
- Laravel Version: 8.12
- PHP Version: 8.0.6
- Server & Version: Swoole
- Database Driver & Version: mysql

### Description:

``php artisan octane:reload`` doesn't reflect new changes for a symbolic link deployment.
This happens for both ``swoole`` and ``roadrunner``. 

*(Still under confirmation) Event with server roadrunner, I suspected that passing the config path directly #335 should have fixed it but now it seems like it will have the same issue.*

Our current deployment uses [deployer PHP](https://deployer.org/) that produces following dir structure.

Dir structure: Before release

```
current -> releases/112
releases
shared
```

Dir structure: After release

```
current -> releases/113 #symblink changed
releases
shared
## octane:reload here...
```

Upon symbolic link change, ``octane::reload`` doesn't have any effect for the new changes. I think it refers to the previous deployment dir still and reload workers from there.

As an alternative, we are doing ``octane::stop`` ▶ symbolic link change ▶ ``octane::start``. This of course is not a hot deployment.
The other work around that we are now considering is ``rsync`` based deployment instead of symbolic link strategy.

**Comment by themsaid** [comment]
Hey. I think for the symlink change to reflect you need to restart the entire process. Terminate the existing one and let Supervisor start a new one with the updated symlink. There will be a down time between stopping Octane and starting a new process.

**Comment by kevincobain2000** [comment]
Thanks @themsaid 
That is kind of a bummer. In that case, I should consider the Rsync strategy instead of the symbolic link for octane apps? We don't want to be restarting the entire process and prefer a hot deployment with a graceful reload. Just like the reload in ``php-fpm``, which works fine after a symbolic release and reloading ``php-fpm`` for the Opcache codes.

**Comment by thyseus** [comment]
Hey folks,

i can confirm that there is a issue with the symbolic link `current/` when using deployer. I have forcefully created a syntax error in `config/octane.php` like:

```php
use Laravel\Octane\Octane;

eturn [
```

but running `php artisan octane:start --rpc-port=6001 --server=roadrunner --host=0.0.0.0 --port=8001` starts without problems. It does not matter if i a inside the `current/` directory or the `releases/60` directory directly. Also restarting octane (via supervisor or without) always ignores the `config/octane.php`.

Bonus: also switching `OCTANE_HTTPS` in `.env` from `false` to `true` has no effect. It seems like octane is _always_ referring to an outdated `.env` and `.config/octane.php` file.

I am still investigation my case...

**Comment by taylorotwell** [comment]
I'm not sure this is something we have control of or could resolve?

**Comment by kevincobain2000** [comment]
Thanks for confirming @thyseus

I have done following 2 confirmations.

1. ``octane::reload`` doesn't work on a symbolic link deployment.
2. For a non symbolic link deployment, ``octane::reload`` doesn't work when opcache is enabled. 

The [swoole doc](https://www.swoole.co.uk/docs/modules/swoole-server-reload) asks to refresh it opcache

>APC/OpCache and hot reloading
>stat in APC/OpCache has to be enabled for code reloading
>Refresh OpCache with apc_clear_cache() or opcache_reset() if necessary

I tried with adding opcache refresh step as ``octane::reload`` -> then -> ``opcache_refresh()`` but that didn't help. As a solution for now, I have disabled the ``opcache.enable_cli => Off => Off``.

I think, ``octane:reload`` cli doesn't need to provide opcache refresh, as this is the responsibility of the deployment strategy.

I don't know for sure if opcache is suggested or will benefit when using Octane. 

To @thyseus 

``'system:restart-supervisor',`` is not a good option as this causes downtime. Instead a simple rsync strategy works better.

```
set('app_path', '/somewhere/app');
task('deploy:rsync', function () {
    run("rsync -a  --exclude 'storage' --delete {{current_path}}/ {{app_path}}");
});

```

**Comment by taylorotwell** [comment]
Just following up - I'm not sure if Octane has anything to do with or can do anything about this issue?

**Comment by kevincobain2000** [comment]
Hi @taylorotwell 
Sorry for the inconvenience. There is nothing that can be done from the Octane side. It is mostly Swoole issue and for alternate fix, it should be handled by the deployment strategy. It is ok to close this issue.

**Comment by gemini133** [comment]
@kevincobain2000 Hi, any chance you work out the symlink re-resolve?

**Comment by kevincobain2000** [comment]
Hi @gemini133 
For centos7
No it doesn’t. I tried with both road runner and swoole. I ended up using octane:stop and octane:start, and before doing that taking server of the load balancer. This is ok, it just adds around an extra minute per server to the deployer.

**Comment by kevincobain2000** [comment]
@gemini133 
Extra note. I also tried with rsync strategy instead of symb link. While this one works fine with the octane:reload. But in this case when there is a change in the .env, the changes are not reflected.

**Comment by madalinignisca** [comment]
You can't reload a process that started in a directory pointing an inode (that is what the symlink id). Full process must stop and start again from the new directory.

PHP-FPM reloads feature works for sure, as php-fpm is a separate process. Identical is for Apache with mod_php on reload.

To have same behaviour, Octane must be a separate process outside the Laravel App, that would start the core part of it required by the app. So somebody must look into splitting octane in two parts. The "manager" that could be packed as phar, and the part needed in the app as a dependency.

Even so, a full restart will be needed when the manager is mandatory to be updated. This is also the case of php-fpm when any php package is updated, including extensions (reload will keep running on same old version).

Ideally Octane should be running either in a docker container (including kubernetes) or by SystemD, which is already in all Linux distributions, avoiding adding another useless supervizor (I mean Supervizor).

**Comment by HassanZahirnia** [comment]
Is there any updates on this ? It seems achieving zero-downtime deployment with Octane is not possible atm.

**Comment by madalinignisca** [comment]
> Is there any updates on this ? It seems achieving zero-downtime deployment with Octane is not possible atm.

You can't reload a process started in a directory, reloading it from another directory. This is not Octane/Swoole limitation.

What updates you would like on this?

This is not a limitation of Laravel, Octane or Swoole, it is a limit any other service faces, in any operating system.

**Comment by HassanZahirnia** [comment]
Yeah I understand the limitations, I was curious if there were any plans to create a workaround for this, or a more elegant way to restart/reload octane with the least impact/downtime possible

**Comment by madalinignisca** [comment]
> Yeah I understand the limitations, I was curious if there were any plans to create a workaround for this, or a more elegant way to restart/reload octane with the least impact/downtime possible

Simply by deploying in another directory you can't reload an application.

I personally do blue-green deployments. Work like charm.

1. setup 2 services to run octane on 2 separate ports.
2. have in your webserver an upstream pointing to them both.
3. on deployment, reconfigure upstream to one of them, upgrade the other, if healthy, change upstream to it, continue with the first one, reconfigure upstream.

Nginx and Apache support reload of configuration with zero downtime.

Personally I scripted this in Ansible, works like a charm and takes like 10s full deployment, with zero downtime.

I suggest similar approach with your favorite automation tool for provisioning.

**Comment by HassanZahirnia** [comment]
@madalinignisca  Thanks for sharing your solution. I actually heard of that blue-green approach, someone shared a gist for that on Twitter but it was tailored toward forge environment but I don't use forge, also they said they didn't really fully tested. So to me it kinda looked hacky and not ideal.

Recently I started using Deployer.org and it's a great tool for zero-downtime deployments.
I never used Ansible though. Would be interested to see how that script would look like.

**Comment by kevincobain2000** [comment]
I can do one up on @madalinignisca's suggested way. In fact, I ended up doing the same since the whole issue was raised.

**Comment by HassanZahirnia** [comment]
Can I ask how you running 2 instances of Octane servers on 2 separate ports?
I get `Server is already running` error when I try to run 2 different Octane servers.
```
php artisan octane:start --port=8000
php artisan octane:start --port=8001
```

**Comment by madalinignisca** [comment]
@HassanZahirnia you won'd be able to escape this on using octane in same host. Reason:

https://github.com/laravel/octane/blob/24ab7f9109bb39ddcd76f51e6df1d4a7578366c3/src/Swoole/ServerProcessInspector.php#L21

Looks like similar to some other Laravel code, the implementation is for only one instance only.

It does work when you do this in separate containers or servers.

I mentioned to create a separate service, and did not encounter the issue as I am using containers (with Podman) and I setup a service unit for each process I run, it is isolated, allows me to scale on many hosts or on same hosts without issues.

I can give you a tip until Octane, and many other Laravel things are refactored to be truly scalable and cloud oriented:

Do 2 deployments for 1 version and your storage files (only for files, as I hope you put sessions in the database, especially if you want to scale horizontally)

The scenario above is possible this way on same host, without containers.

On deployment, start with instance 1, continue with instance 2.
