### ISSUE TITLE
 octane:reload on centos 8 doesn't reflect changes 

### ISSUE THREAD

**Issue by Develgold** [laravel/octane#343]
- Octane Version: 1.0.8
- Laravel Version: 8.49.2
- PHP Version: 8.0.8
- Server & Version: Swoole 4
- Database Driver & Version: PostgreSQL 12

### Description:
On local (Ubuntu 20.04) the reload works well, but on the server (Centos 8) the reload did not reflect the changes. After executing the octane:reload command, it shows `INFO Application change detected. Restarting workers ... `, but the changes were not affected. octane:start --watch with chokidar too did not help

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
