### ISSUE TITLE
Data wrapper not working in Api JsonResource

### ISSUE THREAD

**Issue by eliyas5044** [laravel/octane#347]
- Octane Version: 1.0.6
- Laravel Version: 8.48.2
- PHP Version: 8.0.5
- Server & Version: Swoole in Laravel Forge
- Database Driver & Version:

### Description:
The default behavior of JsonResource is to wrap the response in **data** object. But it's not working properly. When I run `php artisan octane:reload` in server, then this wrap work and after few request, I am getting the same error. You may check on this [link](https://pastebin.com/VeCtPsq1)

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!

**Comment by pristavu** [comment]
I have the same problem, on random intervals the JsonResource data wrapper is missing from octane responses and reappears after a fresh octane:reload

**Comment by ofaws** [comment]
You should check the packages you use if they contain JsonResource::withoutWrapping()
p.s. some of them definitely are

To override you can add a line in 'flush' array in octane.php config:

'flush' => [
        \Illuminate\Http\Resources\Json\JsonResource::class,
    ],
