### ISSUE TITLE
Octane Server (Swoole) error after upgrading facade/ignition (2.11.0 => 2.11.1)

### ISSUE THREAD

**Issue by emaia** [laravel/octane#349]
- Octane Version: 1.0.8
- Laravel Version: 8.50.0
- PHP Version: 8.0.8
- Server & Version: Swoole 4.6.7
- Database Driver & Version: no db

### Description:

After upgrading facade/ignition from 2.11.0 to 2.11.1 laravel octane server stops to work and throw this error loop on terminal:

```
Call to protected method Facade\Ignition\IgnitionServiceProvider::resetFlare() from scope Illuminate\Events\Dispatcher

  at vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php:392
    388▕             if ($wildcard) {
    389▕                 return $listener($event, $payload);
    390▕             }
    391▕
  ➜ 392▕             return $listener(...array_values($payload));
    393▕         };
    394▕     }
    395▕
    396▕     /**

   Error
```
If revert facade/ignition to 2.11.0 it works again.

### Steps To Reproduce:

- laravel new example-swoole
- composer require laravel/octane
- php artisan octane:install (select 1)
- php artisan octane:start
- error...

**Comment by driesvints** [comment]
Best to open up a ticket on the ignition tracker.
