### ISSUE TITLE
octane dose not respond when upload little heavy file

### ISSUE THREAD

**Issue by jun9358** [laravel/octane#350]
- Octane Version: 1.0.4
- Laravel Version: 8.44.0
- PHP Version: 8.0.8
- Server & Version: Swoole
- Database Driver & Version: mariaDB 10.3.23

### Description:
When upload little heavy file, octane not respond and exceed timeout limit.

I tried debugging and found [THE CODE](https://github.com/laravel/octane/blob/v1.0.4/src/Swoole/Actions/ConvertSwooleRequestToIlluminateRequest.php#L33) that load file into memory. So, I tried remove the line temporary and received response correctly.

related issues

[Support of stream in HTTP request instead of swoole_http_request->rawContent(): string](https://github.com/swoole/swoole-src/issues/2373)

**Comment by driesvints** [comment]
Seems like an issue in Swoole and not in Octane. Feel free to follow the issue you linked to.

**Comment by zek** [comment]
I'm also having same issue when I'm uploading binary files. 
This little bug prevents me to use octane :(

**Comment by sammyaxe** [comment]
any resolution on this?
