### ISSUE TITLE
Swoole proccess crashes 

### ISSUE THREAD

**Issue by gotys** [laravel/octane#353]
- Octane Version: 1.0.9
- Laravel Version: 8
- PHP Version: 8

#### Undefined array key "type"
This crashes entire Swoole process:

```shell
Undefined array key "type"
  at vendor/laravel/octane/src/Commands/Concerns/InteractsWithIO.php:229
    225▕      * @return void
    226▕      */
    227▕     public function handleStream($stream, $verbosity = null)
    228▕     {
  ➜ 229▕         match ($stream['type']) {
    230▕             'request' => $this->requestInfo($stream, $verbosity),
    231▕             'throwable' => $this->throwableInfo($stream, $verbosity),
    232▕             'shutdown' => $this->shutdownInfo($stream, $verbosity),
    233▕             default => $this->info(json_encode($stream, $verbosity))
```

### Steps To Reproduce:
```php
// dump an empty array = CRASHes the entire Swoole Process
dump([]);
```

**Comment by nunomaduro** [comment]
@gotys Can you give us more information about the current value of your `$stream` (using a `dd`)? Or maybe a way to reproduce your issue?

**Comment by nunomaduro** [comment]
Using the versions you specified, Swoole, and the following route, I was not able to reproduce your issue. Can you elaborate on the steps to reproduce? 

```php
Route::get('/', function () {
    dd([]);
});
```

**Comment by gotys** [comment]
> Using the versions you specified, Swoole, and the following route, I was not able to reproduce your issue. Can you elaborate on the steps to reproduce?
> 
> ```
> Route::get('/', function () {
>     dd([]);
> });
> ```

hm...try to use "dump" instead of "dd" ?

**Comment by nunomaduro** [comment]
I've just tried with `dump` and it seems to be working as expected.

```php
Route::get('/', function () {
    dump([]);
});
```
