### ISSUE TITLE
unserialize() Error On Octane::concurrentlly when doing unit test.

### ISSUE THREAD

**Issue by maxgaurav** [laravel/octane#354]
- Octane Version: 1.0.7
- Laravel Version: 8.49.1
- PHP Version: 8.0.8
- Server & Version: Swoole  4.7.0
- Database Driver & Version: Mysql, Mysql 8

### Description:
When running a Unit test against a class method that is firing multiple method calls concurrently in unit testing, the test case fails with unserialize error. 

Though when firing the endpoint that has this concurrent call mapped through octane server, it is working as expected.

### Steps To Reproduce:
* Create a class with a method calling other methods concurrently
* Create a PHP unit test through the laravel create test command and attempt to test the sample class method calling concurrent methods

### Following error was received
```
Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()

#0 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()
#1 /home/maxgaurav/projects/project/vendor/laravel/octane/src/Swoole/SwooleHttpTaskDispatcher.php(51): unserialize()
#2 /home/maxgaurav/projects/project/vendor/laravel/octane/src/Concerns/ProvidesConcurrencySupport.php(28): Laravel\\Octane\\Swoole\\SwooleHttpTaskDispatcher->resolve()
#3 /home/maxgaurav/projects/project/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(261): Laravel\\Octane\\Octane->concurrently()
#4 /home/maxgaurav/projects/project/app/Http/Controllers/Api/V1/Sample/SampleController.php(258): Illuminate\\Support\\Facades\\Facade::__callStatic()
...
```
**_Personal information regarding project stripped. Let me know if more information is needed_**

### Point of error Description
On debugging the point of origin of error is unserialze in file **SwooleHttpTaskDispatcher**. The response status is 200 and the response body is having the right data. 

```
    public function resolve(array $tasks, int $waitMilliseconds = 3000): array
    {
        $tasks = collect($tasks)->mapWithKeys(function ($task, $key) {
            return [$key => $task instanceof Closure
                            ? new SerializableClosure($task)
                            : $task, ];
        })->all();

        try {
            $response = Http::timeout(($waitMilliseconds / 1000) + 5)->post("http://{$this->host}:{$this->port}/octane/resolve-tasks", [
                'tasks' => Crypt::encryptString(serialize($tasks)),
                'wait' => $waitMilliseconds,
            ]);

            return match ($response->status()) {
                200 => unserialize($response), /// ----> THE POINT OF PROBLEM. THOUGH RESPOSE BODY IS CORRECT.
                504 => throw TaskTimeoutException::after($waitMilliseconds),
                default => throw TaskExceptionResult::from(
                    new Exception('Invalid response from task server.'),
                )->getOriginal(),
            };
        } catch (ConnectionException) {
            return $this->fallbackDispatcher->resolve($tasks, $waitMilliseconds);
        }
    }
```

**Comment by driesvints** [comment]
Does this also happen on the latest Octane version?

**Comment by maxgaurav** [comment]
Upgraded octane to 1.0.9 and same error.

**Comment by driesvints** [comment]
Heya, thanks for reporting.

We'll need more info and/or code to debug this further. Can you please create a repository with the command below, commit the code that reproduces the issue as separate commits on the main/master branch and share the repository here? Please make sure that you have the [latest version of the Laravel installer](https://github.com/laravel/installer) in order to run this command. Please also make sure you have both Git & [the GitHub CLI tool](https://cli.github.com) properly set up.

```bash
laravel new bug-report --github="--public"
```

Please do not amend and create a separate commit with your custom changes. After you've posted the repository, we'll try to reproduce the issue.

Thanks!

**Comment by maxgaurav** [comment]
Ok. Will link the repository.

**Comment by driesvints** [comment]
Closing this issue because it's inactive, already solved, old or not relevant anymore. Feel to open up a new issue if you're still experiencing this.
