### ISSUE TITLE
Contracts\Validation\Factory is not instantiable while building

### ISSUE THREAD

**Issue by dmouse** [laravel/octane#361]
- Octane Version: 1.0.10
- Laravel Version: 8.53.1
- PHP Version: 8.0.9
- Server & Version: Swoole Stable
- Database Driver & Version: postgres

### Description:
I'm using a combination of tenancy for laravel and lighthouse, when I execute request in more than one domain at the same time I got this error:

```
[2021-08-08 04:33:32] local.ERROR: Target [Illuminate\Contracts\Validation\Factory] is not instantiable while building [Nuwave\Lighthouse\Validation\ValidateDirective]. {"exception":"[object] (Illuminate\\Contracts\\Container\\BindingResolutionException(code: 0): Target [Illuminate\\Contracts\\Validation\\Factory] is not instantiable while building [Nuwave\\Lighthouse\\Validation\\ValidateDirective]. at /var/www/app/vendor/laravel/framework/src/Illuminate/Container/Container.php:1089)
```

[ValidateDirective](https://github.com/nuwave/lighthouse/blob/d6944386e2020dec767f236025e0d80704638ef2/src/Validation/ValidateDirective.php#L21) use `Illuminate\Validation\Factory`, I tried to create a singleton of `Illuminate\Validation\Factory` with the below code but the error persist,

```
use Illuminate\Contracts\Validation\Factory as FactoryContract;
use Illuminate\Validation\Factory;

public function register()
{
       $this->app->singleton(FactoryContract::class, function ($app) {
            return new Factory(
                $app->make(\Illuminate\Contracts\Translation\Translator::class),
                $app
            );
        });
}
```

```
use Illuminate\Validation\Factory;

public function register()
{
       $this->app->singleton(Factory::class, function ($app) {
            return new Factory(
                $app->make(\Illuminate\Contracts\Translation\Translator::class),
                $app
            );
        });
}
```

Any advice or do you think is a bug?

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
