### ISSUE TITLE
Swoole + Nginx File Download 504 Timeout

### ISSUE THREAD

**Issue by gofish543** [laravel/octane#362]
- Octane Version: 1.0.10
- Laravel Version: 8.53.1
- PHP Version: 8.0
- Server & Version: Swoole / RoadRunner 4.6.7
- 
### Description:
I have a file that I'm attempting to download from storage...
```
return response()
        ->download($downloadPath, "{$scenario->name}.pdf")
        ->deleteFileAfterSend();
```
This download results in a 504 Gateway Timeout in production environments using Forge's default configuration for Laravel Octane + Nginx.

I've attempted to fixes like...
```
 'swoole' => [
        'options' => [
            'package_max_length' => 100000000, // For file downloads
            'socket_buffer_size' => 100000000, // For file downloads
            'buffer_output_size' => 100000000, // For file downloads
        ],
    ]
```
and increasing the nginx proxy timeout, buffers, and altered various headers. Nothing works.

The nginx error I get is as follows...
```
2021/08/09 10:00:52 [error] 21683#21683: *2 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 1.1.1.1, server: demo.com, request: "GET /download HTTP/2.0", upstream: "http://127.0.0.1:8000/download", host: "demo.com", referrer: "demo.com"
```

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
