### ISSUE TITLE
Memory keep increasing

### ISSUE THREAD

**Issue by AliAbuArab** [laravel/octane#363]
- Octane Version: 1.0.10
- Laravel Version: 8.12
- PHP Version: 8.0.7
- Server & Version: Swoole 4.7.0
- Database Driver & Version: MySQL 8.0.12

### Description: 
Laravel octane process keep increasing memory usage by each coming request, it arrived to 60 mb !?

![Screen Shot 2021-08-10 at 15 58 45](https://user-images.githubusercontent.com/20545572/128872810-b41bbf2e-de03-4d28-aa31-10eae0035c5b.png)

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by AliAbuArab** [comment]
Hi @driesvints ,

Thank you for fast reply, but keep increasing memory usage you don't think it's a bug ?!
