### ISSUE TITLE
Change tracking (option --watch) does not work correctly when using the swoole server

### ISSUE THREAD

**Issue by another-universe** [laravel/octane#364]
- Octane Version: 1.0.11
- Laravel Version: 8.54.0
- PHP Version: 8.0.9
- Server & Version: Swoole 4.7.0
- Database Driver & Version: pgsql

### Description:
Hello!

When I start the swoole server with the `octane:start` command, the `--watch` option doesn't work for some reason.

My supervisor config file:

```
[program:my-project-serve]
process_name=%(program_name)s
command=/usr/bin/php /var/www/my-project/repo/artisan octane:start --host="127.0.0.1" --port="8081" --workers="4" --task-workers="8" --max-requests="1024" --watch
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=web
numprocs=1
redirect_stderr=false
stdout_logfile=/dev/null
stderr_logfile=/var/www/my-project/repo/storage/logs/octane_server_err.log
stopwaitsecs=0
```

In the .env file:

```
OCTANE_SERVER=swoole
OCTANE_HTTPS=true
```

But when I make changes to the project files, octane for some reason does not see them.

At the same time, after making any changes to the project files, in the file `%storage_path%/logs/swoole_http.log` I see the following entry:

```
[2021-08-17 14:59:22 $2049.0]	INFO	Server is reloading all workers now
```

From which we can conclude that the event itself is triggered.

The `php artisan octane:reload` command has no effect either.
Only forced stop of workers with their subsequent restart helps:  
`php artisan octane:stop`.

At the same time, if you switch to roadrunner, everything works correctly.

In the .env file:

```
OCTANE_SERVER=roadrunner
OCTANE_HTTPS=true
```

Supervisor config file:

```
[program:my-project-serve]
process_name=%(program_name)s
command=/usr/bin/php /var/www/my-project/repo/artisan octane:start --host="127.0.0.1" --port="8081" --rpc-port="6081" --workers="4" --max-requests="1024" --watch
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=web
numprocs=1
redirect_stderr=false
stdout_logfile=/dev/null
stderr_logfile=/var/www/my-project/repo/storage/logs/octane_server_err.log
stopwaitsecs=0
```

What could be the problem? maybe someone came across a similar one.
Is this a error on the Laravel side, or am I doing something wrong?

I would be grateful for any help.

**Comment by nunomaduro** [comment]
The `--watch` flag should only be used for local development only. Are you using supervisor with Laravel Sail?

**Comment by another-universe** [comment]
I know the `--watch` option is for local development only.
I use supervisor solely for the purpose of automating the startup of the Octane server, instead of manually starting it each time.
But even if you run it without using a supervisor, just by running in the terminal:
```
php artisan octane:start --host="127.0.0.1" --port=8081 --workers=auto --task-workers=auto --max-requests=1024 --watch
```
It still doesn't solve the problem.
Also, as I wrote in the first comment, `php artisan octane:reload` has no effect either.

Although in the swoole_http.log file, or in the console if I start the server manually, I see the message `INFO	Server is reloading`, this indicates that the signal to reload workers is still sent.

In addition, as I already noted, the situation is only observed in the case of using Swoole. If you use Roadrunner instead of Swoole, both the `--watch` flag and the` octane:reload` command work correctly.

No, I am not using Laravel Sail. Supervisor does run in a docker container, but without using Laravel Sail.

At the moment, I solved the problem for myself by writing my own script file-watcher.js, which I also run through the supervisor.
If changes are made to the project files, this script actually executes the `php artisan octane:stop` command. After that, the supervisor restarts the Swoole server.

**Comment by nunomaduro** [comment]
Well, since you have found a workaround, we are going to close this issue.

No worries, closing this issue doesn't mean that the problem doesn't exist. Yet, we are going to wait for a few more reports to actually allocate some time to investigate this issue further.
