### ISSUE TITLE
cURL Tasks issued to Octane:Concurrently duplicated in main process

### ISSUE THREAD

**Issue by peterjbassi** [laravel/octane#365]
- Octane Version: 1.0.11
- Laravel Version: 8.54.0
- PHP Version: 8.0.9
- Server & Version: Swoole 4.6.0
- Database Driver & Version: N/A

I'm trying to use `Octane::concurrently()` to make a bunch of cURL requests. I started up Octane with 10 workers and 20 task workers:

`/usr/local/bin/php /var/www/artisan octane:start --watch --host=0.0.0.0 --workers=10 --task-workers=20`

I created a simple Laravel Command that creates an array of 100 cURL "tasks" and passes that array into `Octane::concurrently()`. Each task logs out the PID of the process it's running in to a file. 

```
    public function handle()
    {
        $tasks = [];

        print 'Main Process: ' . getmypid() . "\n";

        for ($i = 0; $i < 100; $i++) {
            $tasks[] = function () {
                $curl = curl_init('http://localhost:8000');
                curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);
                $response = curl_exec($curl);
                curl_close($curl);
                file_put_contents('/var/www/get-localhost.out', 'Child Process ' . getmypid() . "\n", FILE_APPEND);
            };
        }

        Octane::concurrently($tasks);
    }
```

After running the command, the output file contains 100 PIDs from the task workers, and another 100 PIDs matching the main process ID. If I run this without the cURL portion, but leaving the PID file write in place, the output file contains only the 100 PIDs from the task workers. Based on that, the problem seems to be related to cURL.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
