### ISSUE TITLE
Octane Swoole Server Stats

### ISSUE THREAD

**Issue by robertpcontreras-ts** [laravel/octane#366]
Hello,

Looking for a way to expose the underlying swoole server stats for monitoring and alerting. See https://www.swoole.co.uk/docs/modules/swoole-server-stats

I have got this working with the following bodge in `vendor/bin/swoole-server`:
```
$server->on('request', function ($request, $response) use ($server, $workerState, $serverState) {
    if ($request->server['request_uri'] === '/swoole-stats') {
        $response->end(json_encode($server->stats()));
    } else {
        $workerState->lastRequestTime = microtime(true);
        ...
```

Is there currently a way to access the main `$server` variable within a Laravel application allowing me to use laravel routes/middleware etc...

Thanks in advance

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by robertpcontreras-ts** [comment]
Hi Dries,

Thanks for responding. I will check in some other places but this was more of a feature request than support.

I am pretty sure we don't have access to the swoole server instance once in a bootstrapped Laravel app and having the ability to expose metrics like this to monitor the number of available workers would be extremely useful for optimising the setup.
