### ISSUE TITLE
Enhanced request console output - maybe configurable ....

### ISSUE THREAD

**Issue by DeepDiver1975** [laravel/octane#367]
I'd like to see a few more information about a processed request:
- client ip(s)
- user agent
- date
- ...

It could look like this:
![Screenshot from 2021-08-25 00-14-24](https://user-images.githubusercontent.com/1005065/130697168-8069c482-b6f3-47e2-ba27-5e8f66ce0378.png)

Let me know if you are interested in a pull request to implement this

**Comment by DeepDiver1975** [comment]
Just realized that this output is used for local and testing environments only. In this case this is not that of an interest I think.
client ip and user agent are of interest in production environments.

**Comment by driesvints** [comment]
I don't think we have any plans for this right now but you can always attempt a PR. Thanks

**Comment by DeepDiver1975** [comment]
I ended up in an application specific handler for RequestHandled - in case anybody is interested:

```
<?php

namespace App\Octane;

use Illuminate\Http\Request;
use Laravel\Octane\Events\RequestHandled;
use Symfony\Component\Console\Output\ConsoleOutput;
use Symfony\Component\HttpFoundation\Response;

class AccessLog
{
    public function __construct(
        private ConsoleOutput $output)
    {
    }

    public function handle(RequestHandled $event): void
    {
        if (! $event->sandbox->environment('production')) {
            return;
        }

        $this->log($event->request, $event->response);
    }

    public function log(Request $request, Response $response): void
    {
        $method = $request->method();
        $agent = $request->userAgent();
        $status = $response->getStatusCode();
        $ip = implode(', ', $request->ips());
        $path = $request->path();
        $referer = $request->header('referer');

        $this->output->writeln("$ip - - $method $path $status - $referer $agent");
    }
}
```

![Screenshot from 2021-08-25 12-44-28](https://user-images.githubusercontent.com/1005065/130777120-feaa1559-5e3f-4ff2-b1d8-d300ca084987.png)
