### ISSUE TITLE
/tmp files did not auto delete

### ISSUE THREAD

**Issue by zarulizham** [laravel/octane#368]
- Octane Version: 1
- Laravel Version: 8
- PHP Version: 8.0.9
- Server & Version: RoadRunner 2.3.2
- Database Driver & Version: MySQL 8

### Description:

Uploaded attachments that stores temporarily in /tmp folders are not being automatically deleted after script has been finish executed. Attachment is not store in the server, stored in DigitalOcean Spaces.

`Storage::disk('spaces')->putFile($path, $attachment, 'public');`

Snappy pdf also facing the same problem. HTML and PDF generated store in /tmp folder did not automatically deleted.

Before this i'm using PHP-FPM, no such problem existed.

![telegram-cloud-photo-size-5-6150102592315829576-y](https://user-images.githubusercontent.com/10229855/131250921-210faa0c-9656-44d1-b980-fdbaf7e4b422.jpg)

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by rhwilr** [comment]
@zarulizham Did you find a solution to this problem? I'm facing the exact same issue when uploading a file to the server that is then stored on S3. 
Every time I refresh the page after uploading the file, it creates another copy of the file.

**Comment by zarulizham** [comment]
> @zarulizham Did you find a solution to this problem? I'm facing the exact same issue when uploading a file to the server that is then stored on S3.
> Every time I refresh the page after uploading the file, it creates another copy of the file.

Hi, not yet. I ended up stop using octane and back to PHP-FPM.

**Comment by wecraft** [comment]
Hi, 
The issue is closed, but the solution below might be helpful for those, who are still having the issue.
So, by default laravel octane doesn't flush the uploaded files (and their cache), once the request is terminated. The simple solution is to uncomment the related listener in the config **_config/octane.php_** 

`RequestTerminated::class => [
       FlushUploadedFiles::class,
],`
