### ISSUE TITLE
Data is to proper respond 

### ISSUE THREAD

**Issue by RahibHasan** [laravel/octane#369]
- Octane Version: 1.0
- Laravel Version: 8.0
- PHP Version: 8.0.9
- Server & Version: Swoole / RoadRunner RoadRunner , Swoole
- Database Driver & Version:  MySQL InoDB 10.5

### Description:
When i am deleted some data and its deleted successful but when i check my application its here .
i checked this database is empty i refresh my application several times sometimes its show some times is not

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by mtawil** [comment]
@driesvints I believe this is a bug, not just a question that needs to be answered.

Somehow, Octane using RoadRunner keeps and presents the previous states of the application or requests.
Below is a video that demonstrates this exact issue; I've also debugged the code many times, and I've `dd` the requests to check if the response is different or not, and indeed it's different.

https://user-images.githubusercontent.com/700753/132821572-49fb372a-1a36-45f1-af3e-d5b488da8dea.mp4

As you can see, every different response is a different state of application code where `dd` was in different places.

**Comment by hasan689009** [comment]
any update about this issue
