### ISSUE TITLE
Does not detect package routes

### ISSUE THREAD

**Issue by mcolominas** [laravel/octane#370]
- Octane Version: 1.0.11
- Laravel Version: 8.57.0
- PHP Version: 8.0.10
- Server & Version: Swoole 4.7.1
- Database Driver & Version: 

### Description:
I have made a package, where routes are registered, but for some reason, octane does not detect them, but if the routes are cached, octane does detect the routes (I have not tried it with other things, configuration, commands, ...)

### Steps To Reproduce:
composer.json from Package
```json
    "require": {},
    "license": "MIT",
    "autoload": {
        "psr-4": {
            "Campany\\Test\\": "src/"
        }
    },
    "extra": {
        "laravel": {
            "providers": [
                "Campany\\Test\\TestServiceProdiver"
            ]
        }
    },
    "minimum-stability": "dev"
```
Inside of ServiceProvider from Package
```php
public function boot(){
   $this->loadRoutesFrom(__DIR__ . '/../routes/routes.php');
}
```

Inside of routes file
```php
use Illuminate\Support\Facades\Route;

Route::middleware('guest')->group(function () {
    Route::get('/test', [TestController::class, 'test'])->name('test');
});
```

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
