### ISSUE TITLE
Does not detect IP Client

### ISSUE THREAD

**Issue by mcolominas** [laravel/octane#371]
- Octane Version: 1.0.11
- Laravel Version: 8.57.0
- PHP Version: 8.0.10
- Server & Version: Swoole 4.7.1

### Description:
When using Request::ip() and request()->ip() to get the client's ip, it returns the ip 127.0.0.1. I want to clarify, that laravel is running on a server with an associated domain, not on a local machine.

### Steps To Reproduce:

routes/web.php
```php
Route::get('/', function () {
    dd(Request::ip()); // "127.0.0.1"
});
```

**Comment by Namoshek** [comment]
Are you using a reverse proxy like Nginx in front of Laravel Swoole?

**Comment by mcolominas** [comment]
I'm using apache2, this is the configuration
<VirtualHost *:443>
...
ProxyPreserveHost On
    ProxyPass / http://127.0.0.1:8082/
    ProxyPassReverse / http://127.0.0.1:8082/

    RemoteIPHeader X-Forwarded-For
    RemoteIPTrustedProxy 127.0.0.1
...
</VirtualHost>

**Comment by mcolominas** [comment]
Sorry for the inconvenience, I have managed to fix it, I put the solution here in case someone else also happens the same.

The problem was that the proxy ip (127.0.0.1) was not set in the TrustProxies middleware.

This can be a common mistake among newbies who have never used a proxy, as the tutorials do not say anything about this middleware.

**Comment by nogamenofun98** [comment]
![image](https://user-images.githubusercontent.com/9070825/134841713-407fe216-29ec-42d1-b908-a39f8808c9bd.png)

For anyone that want to know where to edit, here is the location, app\Http\Middleware\TrustProxies.php :D

**Comment by iamphonghg** [comment]
For those using Laravel 12, you can fix this by adding the following to the `withMiddleware()` section in `bootstrap/app.php`:
```
->withMiddleware(function (Middleware $middleware): void {
    $middleware->trustProxies(['127.0.0.1']);
})
```
