### ISSUE TITLE
Is there a way to specify hostname

### ISSUE THREAD

**Issue by omarname** [laravel/octane#373]
When i start octane it always use this host http://127.0.0.1:8000, which is usable in local development, but in production environnement i use domain name instead of localhost   
Is there a way to change the hostname like http://domain.com:8000 when we start octane.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by HergenD** [comment]
@omarname  I recommend taking a look at the documentation, especially the [Serving Your Application Via Nginx](https://laravel.com/docs/8.x/octane#serving-your-application-via-nginx) part

**Comment by omarname** [comment]
@HergenD yeah i tried to achieve that but i'm using apache that's why it would be easy if i could specify the hostname.
