### ISSUE TITLE
fn route() does not return domain when using h3 protocol

### ISSUE THREAD

**Issue by mcolominas** [laravel/octane#374]
- Octane Version: 1.0.11
- Laravel Version: 8.58.0
- PHP Version: 8.0.10
- Server & Version: Swoole 4.7.1
- Web Server: nginx 1.21.2 with OpenSSL 1.1.1 (compatible; BoringSSL) (running with BoringSSL)
- SO: Debian GNU/Linux 11 (bullseye)
- Supervisor: 4.2.2

### Description:
I have put this in the discord, but nobody has answered me, therefore I put it here in case you can check it if it is definitely a bug or not.

To clarify, I have done it on a new server, with everything just installed, therefore, the laravel, it is the one that comes after the installation, without modifying controllers, middlewares, etc.

The problem is the following, when I try to obtain a route using route('route_name'), it returns the url without the domain.

Example:
The expected would be: https://www.domain.com/admin/login
But what it returns is: https:/admin/login

I have realized that the parameter "domain" that is inside the Route class is null.

I have also done some tests, without modifying the laravel, just modifying the nginx configuration to enable / disable h3 and switch between php fpm and proxy

As for the nginx configuration, it is the same as shown in the documentation, except for the 4 extra lines to activate h3
https://laravel.com/docs/8.x/deployment#nginx
https://laravel.com/docs/8.x/octane#serving-your-application-via-nginx

Enable h3:
```
listen [::]:443 http3 reuseport ipv6only=on;
listen 443 http3 reuseport;  # UDP listener for QUIC+HTTP/3

add_header Alt-Svc 'h3-27=":443"; ma=86400, h3-28=":443"; ma=86400, h3-29=":443"; ma=86400, h3=":443"; ma=86400';   # Advertise that HTTP/3 is available
add_header QUIC-Status $quic;     # Sent when QUIC was used
```

This is the result:
Laravel with php fpm using protocol h2: It works
Laravel with php fpm using protocol h3: It works
Laravel with octane using protocol h2: It works
Laravel with octane using protocol h3: Not working

What has been modified in laravel, after its installation and the installation of octane is the following:
Add this in TrustProxies
```php
protected $proxies = [
    '127.0.0.1'
];
```

Change routes/web.php to:
```php
Route::get('/', function () {
    dd(route('admin.login'));
    return view('welcome');
});

Route::get('admin/login', function () {
    return view('welcome');
})->name('admin.login');
```

And finally, the .env file
```
APP_URL=www.domain.com
...
OCTANE_SERVER=swoole
OCTANE_HTTPS=true
```

**Comment by driesvints** [comment]
Your app_URL needs to have the protocol before it. Try uncaching and recaching your routes.

**Comment by mcolominas** [comment]
I have already added the https protocol but it still does not work, I remember that what it does not return is the domain only when the HTTP/3 protocol is used.

```
APP_URL=https;//www.domain.com
```

**Comment by mcolominas** [comment]
After reviewing all the laravel code and having a good time to find what the problem is, I have found the problem and request that you update the documentation of laravel octane.

According to the laravel octane documentation, in the nginx configuration you have to put the following for the proxy configuration:
```
...
location @octane {
        set $suffix "";

        if ($uri = /index.php) {
            set $suffix ?$query_string;
        }

        proxy_http_version 1.1;
        proxy_set_header Host $http_host;
        proxy_set_header Scheme $scheme;
        proxy_set_header SERVER_PORT $server_port;
        proxy_set_header REMOTE_ADDR $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;

        proxy_pass http://127.0.0.1:8000$suffix;
    }
```

From what I have found, the variable $http_host works correctly when using the HTTP/1.1 and HTTP/2 protocol, but when using the HTTP/3 protocol, that variable does not pass any information, causing that when laravel performs the following operation `$this->headers->get('HOST') ` returns null.

The solution that I have found to work correctly is replacing $http_host to $host, leaving the configuration as follows:
```
...
location @octane {
        set $suffix "";

        if ($uri = /index.php) {
            set $suffix ?$query_string;
        }

        proxy_http_version 1.1;
        proxy_set_header Host $host; # <-- This line.
        proxy_set_header Scheme $scheme;
        proxy_set_header SERVER_PORT $server_port;
        proxy_set_header REMOTE_ADDR $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;

        proxy_pass http://127.0.0.1:8000$suffix;
    }
```

The variable $host, I have tested it and it works correctly in the 3 protocols (1.1, 2 and 3).
