### ISSUE TITLE
Swoole table memory configuration

### ISSUE THREAD

**Issue by up2top** [laravel/octane#375]
Hello! I am working on a geographic map server based on Laravel Octane with Swoole. The server is created with Forge and DigitalOcean. Everything works fine including Octane routes and Octane Swoole tables. I can easily write and read data from memory. But when I try to prefill the Swoole tables with the complete set of geodata (~1Gb), after successfully filling about 600Mb I always run into issue "unable to allocate memory". However till this point the server has more then 1.5Gb of free memory out of 4Gb. It seems like there is a limit for the Octane Swoole tables which I don't know how to control. Is it? If so, it would be great to add control for this limit to the Octane configuration file.

Production error:

`Swoole\Table::set(): failed to set('z7y71x80'), unable to allocate memory {"exception":"[object] (ErrorException(code: 0): Swoole\\Table::set(): failed to set('z7y71x80'), unable to allocate memory at /home/forge/map.blitztest.ru/app/Console/Commands/CacheMapTiles.php:64)`

Octane Swoole tables configuration:

```
'tables' => [
	'tiles:21844' => [
		'table' => 'int:1',
	],
	'tiles1:9910' => [
		'tile' => 'string:1000',
	],
	'tiles2:1508' => [
		'tile' => 'string:10000',
	],
	'tiles3:888' => [
		'tile' => 'string:30000',
	],
	'tiles4:1149' => [
		'tile' => 'string:50000',
	],
	'tiles5:2219' => [
		'tile' => 'string:70000',
	],
	'tiles6:1758' => [
		'tile' => 'string:90000',
	],
	'tiles7:2100' => [
		'tile' => 'string:110000',
	],
	'tiles8:1631' => [
		'tile' => 'string:130000',
	],
	'tiles9:681' => [
		'tile' => 'string:176906',
	],
],
```

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
