### ISSUE TITLE
php artisan octane:start middleware $request->merge return null

### ISSUE THREAD

**Issue by iehong** [laravel/octane#382]
- Octane Version: latest
- Laravel Version: 8.61.0
- PHP Version: 8.0.9
- Server & Version: Swoole 4.7
- Database Driver & Version: mysql 5

### Description:

https://stackoverflow.com/questions/69279222/laravel-octane-request-merge-request-return-null

**Comment by mcolominas** [comment]
Have you checked the request before the merge? You may be receiving the request when the app starts.
https://laravel.com/docs/8.x/octane#container-injection

I have done a test and it works for me.
```php
Route::get('/', function (Request $request) {
    $request->merge(['merge' => 'new value']);
    dd($request->all());
});
```

**Comment by iehong** [comment]
in a middleware. i have change to another laravel swoole tool (laravels).it works well

**Comment by mcolominas** [comment]
I have done the test and in the middleware it also works without problems, without more information and since you have structured the code to reach the midleware I can not help you anymore.

Class Middleware
```php
namespace App\Http\Middleware;

use Closure;

class Custom
{
    public function handle($request, Closure $next)
    {
        $request->merge(['merge' => 'new value']);
        return $next($request);
    }
}
```
Kernel.php
```php
protected $middlewareGroups = [
    'web' => [
       ...
        \App\Http\Middleware\Custom::class,
    ]
];
```

**Comment by iehong** [comment]
thanks
