### ISSUE TITLE
octane:reload with opcache_reset()

### ISSUE THREAD

**Issue by kevincobain2000** [laravel/octane#384]
Hi,

This is a feature request together with a question.

**Question** When using ``swoole`` or ``rr``, **is it recommended to** **_also_** use ``opcache``?
It is not clear to me yet which is the suggested way. As per my tests, app on ``swoole`` combined with ``opcache`` have better performance and consumes less memory per request, than just ``swoole``.

**Problem**

If the answer to question is **Yes** 
As with ``swoole`` or ``rr``, php cli is used with ``opcache.enable_cli=1``. 

1. **Where is the best place to do ``opcache_reset();``** for all the workers at the time of deployment (``php artisan octane:reload``)? 

If this a feature that can be provided by octane, as ``opcache_reset`` needs to be done for all the workers, and currently, there is only one signal ``SIGUSR1`` that is sent to the master process id and swoole-server independently reloads the servers from there on.

**Comment by sy-records** [comment]
I'm not sure about `rr`, but Swoole can handle it when `onWorkerStart`.

**Comment by kevincobain2000** [comment]
Thanks @sy-records 
Yes right, either if we put ``opcache_reset()`` inside ``onWorkerStart@bootWorker($server)`` or even if we put it inside the Laravel application's ``AppServiceProvider@boot()`` we can reset the opcache.

Like below:

```
<?php

namespace Laravel\Octane\Swoole\Handlers;
...
class OnWorkerStart
{
    ...
    protected function bootWorker($server)
    {
        try {
            // reset opcache
            if (function_exists('opcache_reset')) {
                opcache_reset();
            }
```

But there is one problem with it. 
We only want to be doing ``opcache_reset()`` at the time of deployment and not when the worker's max request limit has reached, which refreshes a new worker.
So not sure, if we should be unnecessarily flushing ``opcache`` per every ``--max-request=`` of the worker is reached.

**Comment by kevincobain2000** [comment]
I am still not sure, if ``opcache`` is really needed at all. Swoole already does the caching. The one benefit of using ``opcache``, could be that re-caching by swoole on worker refresh would be faster.

**Comment by driesvints** [comment]
Let's see how the PR goes. Thanks
