### ISSUE TITLE
add swoole server->addProcess

### ISSUE THREAD

**Issue by fykyx521** [laravel/octane#386]
1.  swooler-server.php add  server.addProcess(fn() => "php artisan queue:work" or "redis subscribe")
放开server添加用户进程权限　执行一些队列或者redis 订阅

2.  schedule:run Is there a memory leak ?
执行schedule:run 是否会内存泄露

```
TickReceived::class => [
            TickQueueListener::class,
            ScheduleRunListener::class
        ],

```

```

<?php

namespace App\Listeners;

use Illuminate\Support\Facades\Artisan;

class ScheduleRunListener
{
    /**
     * Create the event listener.
     *
     * @return void
     */
    public function __construct()
    {
        //
    }

    /**
     * Handle the event.
     *
     * @param  object  $event
     * @return void
     */
    public function handle($event)
    {
        Artisan::call('schedule:run');
    }
}

```

```
<?php

namespace App\Listeners;

use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\Log;

class TickQueueListener
{
    /**
     * Create the event listener.
     *
     * @return void
     */
    public function __construct()
    {
        //
    }

    /**
     * Handle the event.
     *
     * @param  object  $event
     * @return void
     */
    public function handle($event)
    {
        Artisan::call('queue:work', [
            '--once'=>1,
            '--sleep'=>0,
            '--tries'=>0,
            '--timeout'=>30]);
    }
}

```

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
