### ISSUE TITLE
Installation cannot be completed due to missing configuration file

### ISSUE THREAD

**Issue by prodigy7** [laravel/octane#387]
- Octane Version: 1.0.11
- Laravel Version: 8.60.0
- PHP Version: 8.0.9
- Server & Version: RoadRunner 2.4.2

### Description:

Configuration can't fetched

### Steps To Reproduce:

```
sail@854e48a27b0e:/var/www/html$ ./vendor/bin/rr get-binary

 Environment:
   - Version:          2.*
   - Stability:        stable
   - Operating System: linux
   - Architecture:     amd64

  - spiral/roadrunner-binary (2.4.2): Downloading...
RoadRunner (2.4.2) has been installed into /var/www/html/rr

 Do you want create default ".rr.yaml" configuration file? (yes/no) [yes]:
 >


In CommonResponseTrait.php line 181:

  HTTP/2 404  returned for "https://raw.githubusercontent.com/spiral/roadrunner-binary/2.4.2.0/.rr.yaml".


get-binary [-o|--os [OS]] [-a|--arch [ARCH]] [-f|--filter [FILTER]] [-l|--location [LOCATION]] [-s|--stability [STABILITY]]
```

Access url in browser also throws a "404".

**Comment by driesvints** [comment]
See https://github.com/laravel/octane/issues/383

**Comment by prodigy7** [comment]
As answered in the thread https://github.com/spiral/roadrunner/issues/813#issuecomment-928924277, the wrong URL is retrieved. Apparently the octane script is pulling the wrong file here?

**Comment by rustatian** [comment]
Actually, we would use the correct semver 2.0 tag without the initial `v` in the version in the future. At the moment, the correct URL would be as following: https://raw.githubusercontent.com/spiral/roadrunner-binary/v2.4.2/.rr.yaml
But for some reason, I see the `2.4.2.0` (4 digits) in the URL in the ticket.

**Comment by prodigy7** [comment]
I only followed the instructions and did not perform any individual steps or adjustments

**Comment by rustatian** [comment]
@prodigy7 No worries 😃 I guess, @driesvints will help you ) At the moment you may try to download the `.rr.yaml` configuration by the link I provided and put it I guess in the root of your application.

**Comment by driesvints** [comment]
Hmm, I have no idea why this is happening. We don't target that url ourselves. It's inside the Roadrunner CLI library. It could maybe be something in https://github.com/laravel/octane/blob/1.x/src/RoadRunner/Concerns/FindsRoadRunnerBinary.php that it fetches the wrong version?

**Comment by rustatian** [comment]
Sorry @driesvints , I can't help you with the PHP, I'm not a PHP programmer. If you think that this is https://github.com/spiral/roadrunner-cli issue, please, tell me and I'll redirect that case to our PHP devs.

**Comment by driesvints** [comment]
No worries @rustatian, appreciate the help. I'll check with the author of that PR.

**Comment by driesvints** [comment]
The OP of the PR cannot reproduce the problem. I'm stumped myself at this tbh... I'll ask internally if maybe @themsaid or @nunomaduro has any ideas.

**Comment by SerafimArts** [comment]
Done. Requires `roadrunner-cli` package upgrade to version 2.0.9 (https://github.com/spiral/roadrunner-cli/releases/tag/v2.0.9).

**Comment by driesvints** [comment]
Thanks!
