### ISSUE TITLE
bug queue

### ISSUE THREAD

**Issue by ysxpark** [laravel/octane#388]
- Octane Version: 1.0
- Laravel Version: 0.8
- PHP Version: 8.0
- Server & Version: Swoole
- Database Driver & Version: mysql8

### Description:

When the model is pushed to the queue and the queue cannot find the model, http will error and return 404
The queue is driven by synchronization

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
