### ISSUE TITLE
queue bug

### ISSUE THREAD

**Issue by ysxpark** [laravel/octane#389]
Octane Version: 1.0
Laravel Version: 0.8
PHP Version: 8.0
Server & Version: Swoole
Database Driver & Version: mysql8

Description:

When the model is pushed to the queue and the queue cannot find the model, http will error and return 404
The queue is driven by synchronization

origin link https://github.com/laravel/octane/issues/388

**Comment by driesvints** [comment]
Please stop re-opening this and first post on a support channel like I asked.
