### ISSUE TITLE
Request Entity Too Large - client_max_body_size not effect

### ISSUE THREAD

**Issue by aelnemr** [laravel/octane#390]
- Octane Version: 1.0
- Laravel Version: 8.54
- PHP Version: 8.0
- Server & Version: Swoole / RoadRunner 1.x
- Database Driver & Version: none

### Description:
Trying to upload files more than 10M, but get Request Entity Too Large
update Nginx config file added `client_max_body_size 200M;` but sill the same problem,
_____________________________________________

My Nginx config file
```
map $http_upgrade $connection_upgrade {
    default upgrade;
    ''      close;
}

upstream octane {
    server workspace:1215 weight=5 max_fails=3 fail_timeout=30s;
    keepalive 16;
}

server {
    listen 80;
    listen [::]:80;
    server_name demo.test;
    root /var/www/demo/public;
    server_tokens off;

    client_max_body_size 200M;

    index index.php;

    charset utf-8;

    location /index.php {
        try_files /not_exists @octane;
        client_max_body_size 200M;
    }

    location / {
        try_files $uri $uri/ @octane;
        client_max_body_size 200M;
    }

    location = /favicon.ico { access_log off; log_not_found off; }
    location = /robots.txt  { access_log off; log_not_found off; }

    error_page 404 /index.php;

    location @octane {
        client_max_body_size 200M;
        set $suffix "";

        if ($uri = /index.php) {
            set $suffix ?$query_string;
        }

        proxy_http_version 1.1;
        proxy_set_header Host $http_host;
        proxy_set_header Scheme $scheme;
        proxy_set_header SERVER_PORT $server_port;
        proxy_set_header REMOTE_ADDR $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;

        proxy_pass http://octane$suffix;
    }

    error_log  /var/log/nginx/octane_error.log;
    access_log /var/log/nginx/octane_access.log;
}

```
Command line to run octane server `php artisan octane:start --server=swoole --host=0.0.0.0 --port=1215`

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by maher1337** [comment]
first make sure you do `composer dump-autoload -o ` then go to bootstrap/cache folder and delete everything there and restart your octane server and it should work.
