### ISSUE TITLE
Swoole & Octane::concurrently undefined array key on timed out task results

### ISSUE THREAD

**Issue by sybbear** [laravel/octane#395]
- Octane Version: 1.0.12
- Laravel Version: 8.62.0
- PHP Version: 8.0.0
- Server & Version: Swoole 4.7.1
- Database Driver & Version: -

### Description:
Swoole's taskWaitMulti omits returning results, tasks of which have timed out.
Check the information here: https://github.com/swoole/swoole-src/issues/4423

Then a chunk of code in `concurrently` method causes an `ErrorException (undefined array key x)` and technically crashes the whole result fetching process.

https://github.com/laravel/octane/blob/1.x/src/Swoole/SwooleTaskDispatcher.php#L46
```
foreach ($tasks as $key => $task) {
    if ($results[$i] instanceof TaskExceptionResult) { // ErrorException Undefined array key
        throw $results[$i]->getOriginal();
    }
```

### Steps To Reproduce:
Queue a set of tasks with different execution times in such a way, that at least one of them times out.
Not having enough workers could be a reason for timeout.

### Resolution suggestion:
Return check that the key exists and if not, assign `false` as a result array element.

**Comment by driesvints** [comment]
Looks like a straightforward fix. Can you send in a PR?

**Comment by sybbear** [comment]
Added a PR, however cannot delve into the tests and styling as we have priority projects going on right now.
Hopefully this helps to release a fix.

**Comment by driesvints** [comment]
I fixed em for you 👍

**Comment by sybbear** [comment]
Ah, with styling there were a bunch of spaces in front of new line. Got it, thank you 😎
