### ISSUE TITLE
Error when getting response of concurrent http requests with `Octane::concurrently()`

### ISSUE THREAD

**Issue by smortexa** [laravel/octane#399]
- Octane Version: v1.0.13
- Laravel Version: v8.61.0
- PHP Version: 8.0.3
- Server & Version: Swoole v4.6.5 and v4.7.1

### Description:
When trying to get body of concurrent http requests executed by `Octane::concurrently()`, the following error will be thrown:
`TypeError: fseek(): Argument #1 ($stream) must be of type resource, int given in file /var/www/backend/vendor/guzzlehttp/psr7/src/Stream.php on line 210`

### Steps To Reproduce:

try:
```php
$responses = Octane::concurrently([
            fn() => Http::get('https://jsonplaceholder.typicode.com/todos/1'),
            fn() => Http::get('https://jsonplaceholder.typicode.com/todos/2'),
        ]);
        
return collect($responses)->transform(function ($item) {
      return method_exists($item, 'body') ? $item->body() : null;
});
```

**Comment by sikhlana** [comment]
Unfortunately, the concurrent tasks run on different `php` processes and resources cannot be shared to the main process as they point to the child process' internal handler.

One way to bypass this issue would be to save the resource in a temp file which then gets reopened by the main process.

**Comment by caiokawasaki** [comment]
> I noticed the same kind of behaviour and my interpretation is that Stream does not persist over multiple requests. The workaround was to save actual string body in the callback function to the response itself:
> 
> ```
> function () {
>     $response = Http::get('url');
>     $response->body = $response->body(); // Set string property dynamically, then access it later
>     return $response;
> }
> ```
> 
> However this needs to be addressed, as those streams should persist.

Didn't work for me, since I only need the code and the response, my solution was:

```php
public function index(Request $request)
{
    $data = ['message' => $request->message];

    [$response] = Octane::concurrently([
        fn() => cache()->remember('testing-bla', now()->addMinutes(10), function () use ($data) {
            $response = Http::post('https://en6r0ae3pxs8b.x.pipedream.net', $data);

            return json_decode(json_encode([
                'status' => $response->status(),
                'content' => $response->json()
            ]));
        })
    ], 60000);

    if ($response->status >= 200 && $response->status < 300)
        return $response->content;

    abort('400', 'Ooops!');
}
```

**Comment by sybbear** [comment]
@caiokawasaki 
I updated Octane and it stopped working, however this line still worked:

`$response->bodyContents = $response->getBody()->__toString();`
