### ISSUE TITLE
Ram increment with cached routes

### ISSUE THREAD

**Issue by mcolominas** [laravel/octane#401]
Octane Version: 1.0.13
Laravel Version: 8.63.0
PHP Version: 8.0.10
Server & Version: Swoole 4.7.1

### Description:
As I have indicated in the title, when the routes are cached `php artisan route:cache`, for some reason, the ram increments as requests are made, to verify that it is not my error, I have made a new installation of laravel without touching anything and I have the test:

In the first request it has consumed: 14.36 mb 28.74 ms
After 100 requests: 14.53 mb 4.30 ms
After 200 requests: 14.70 mb 5.56 ms

I have not done any more tests, but following these results, every 100 requests increases by about 17MB, therefore after about 6000 requests it would have to consume 1GB of RAM per request.

### Steps To Reproduce:

1. Cache routes `php artisan route:cache`
2. Run the octane service `php octane:start --server=swoole --max-requests=1000 --port=8091 --watch`
3. Make requests to the application.
4. See the log in the console, you will see how the `mb` increase little by little.

**Comment by smortexa** [comment]
I have the same issue.
