### ISSUE TITLE
Swoole & Blackfire profiling - readiness & guidelines

### ISSUE THREAD

**Issue by sybbear** [laravel/octane#405]
Is Octane generally ready for Blackfire profiling and if so, are there any guidelines?

One library provides an integration of Blackfire and Swoole:

https://github.com/upscalesoftware/swoole-blackfire
I wonder if it would be sufficient to create a Middleware and profile requests based on header values.

**Comment by driesvints** [comment]
I think that looks cool @sybbear but probably not something we'll be working on ourselves. If you ever figure out how to make that work we could maybe include a small section in Octane's docs. Otherwise a blog post might be a good idea? Thanks
