### ISSUE TITLE
Swoole\Server::start(): Unexpected end of serialized data

### ISSUE THREAD

**Issue by foremtehan** [laravel/octane#411]
- Octane Version: 10.14
- Laravel Version: 8.*
- PHP Version: 8.*
- Server & Version: Swoole 
- Database Driver & Version:

I find this exception in console :

```
PHP Fatal error:  Uncaught ErrorException: Swoole\Server::start(): Unexpected end of serialized data in /app/vendor/laravel/octane/bin/swoole-server:163
 Stack trace:
 #0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError()
#1 /app/vendor/laravel/octane/bin/swoole-server(163): Swoole\Server->start()
 #2 {main}
 thrown in /app/vendor/laravel/octane/bin/swoole-server on line 163
```

It randomly happens dont know what cause this.

**Comment by fulopattila122** [comment]
I've got the same error in the terminal console where `octane:start` is running, whereas in the browser I've got this error: `Serialization of 'Doctrine\DBAL\Driver\PDOConnection' is not allowed`.

It showed up when I added `Octane::concurrently([...])` to one of the controllers.

Have you figured out something @foremtehan?

**Comment by fulopattila122** [comment]
I've found a solution. In my case, we shouldn't pass a query builder to a co-routine task.

Ie. instead of this:

```php
class SomeController
{
    public function index() {
        // Issue is an Eloquent model
        $issues = Issue::open()->userHasAccessTo(Auth::user())->with('severity')->sort();
        [$issues, $reports] = Octane::concurrently([
            fn () => $issues->with(['project', 'worklogs', 'assignedTo'])->get(),
            fn () => $this->getReports(),
        ]);
    }
}
```

use this:

```php
class SomeController
{
    public function index()
    {
        // Issue is an Eloquent model
        $issues = Issue::open()->userHasAccessTo(Auth::user())->with('severity')->sort();
        if (Preferences::get(AvailablePreferences::DASHBOARD_SHOW_ONLY_MY_ISSUES)) {
            $issues->assignedToUser($authUser);
        }

        [$issues, $reports] = Octane::concurrently([
            fn () => $issues->with(['project', 'worklogs', 'assignedTo'])->get(),
            fn () => $this->getReports(),
        ]);
    }

    private function getOpenIssues(User $authUser)
    {
        $issues = Issue::open()->userHasAccessTo($authUser)->with('severity')->sort();
        if (Preferences::get(AvailablePreferences::DASHBOARD_SHOW_ONLY_MY_ISSUES, $authUser)) {
            $issues->assignedToUser($authUser);
        }

        return $issues->with(['project', 'worklogs', 'assignedTo'])->get();
    }
}
```

This little incident has raised my awareness that those co-routine tasks are running completely without the current context and everything passed over there gets serialized.

Yes, it could be structured better than just a private method on the controller.

**Comment by foremtehan** [comment]
I stop using octane, I encountered so many weird errors from octane codebase, besides of `Unexpected end of serialized data` i got [https://github.com/laravel/serializable-closure/issues/26](Serialization of 'CurlHandle' is not allowed) too.

I was using octane in heroku about 6 month, Last week heroku killed my dyno cuz of heavily memory leak (2GB+ swap memory) I didnt even used swoole table or any static variable, actually i didnt touch my code base in a month and that happended so i give up.

**Comment by foremtehan** [comment]
About memory leak issue on my side, i found out i had a infinite loop query in part of my code, but why it cause the memory leak ? what octane store in memory when it cant stop query ?

**Comment by fulopattila122** [comment]
The whole point of octane/swoole/roadrunner is to keep the application in memory.
Traditional PHP applications boot up the application from scratch at every request.

**Comment by foremtehan** [comment]
i dont think you read my comment

**Comment by fulopattila122** [comment]
I read, but yeah, maybe I didn't understand it correctly.
