### ISSUE TITLE
phpinfo() output missing markup when called from controller/route method

### ISSUE THREAD

**Issue by carestad** [laravel/octane#414]
- Octane Version: 1.0.17
- Laravel Version: 8.69.0
- PHP Version: 8.0.12
- Server & Version: Swoole v4.7.0 / RoadRunner v2.5.3
- Database Driver & Version: mariadb v10.6

### Description:

`phpinfo()` output is missing markup whtn called from a controller method or route closure. `php_sapi_name()` is also `cli` where for `artisan:serve` it would be `cli-server`. This happens with both Swoole and Roadrunner.

### Steps To Reproduce:

Example route:
```php
Route::get('/phpinfo', function() {
	phpinfo();
});
```

When "hosting" with `artisan serve`, navigating to `/phpinfo` will show a colourful output. CTRL+U (view source) reveals a lot of markup and styling involved.

When hosting with `artisan octane:start`, the output is stripped of markup and is the same as when calling `phpinfo()` from CLI, like tinker or a simple script run from the command line. Output of `php_sapi_name()` also says `cli` at this point, which would explain it.

Simple workaround for now to at least get some structure to the page is to rewrite route like this:

```php
Route::get('/phpinfo', function() {
	phpinfo();
	return response('')->withHeaders(['content-type' => 'text/plain']);
});
```

**Comment by nunomaduro** [comment]
Unfortunately, because Octane is started from the "CLI", there is not real way of mutating the SAPI PHP module. So all php core functions, based on that module, including `phpinfo`, will work a little bit differently.

**Comment by manusiakemos** [comment]
for me it works with
```php
ob_start();
phpinfo();
$phpinfo = ob_get_clean();

return response($phpinfo, 200)
    ->header('Content-Type', 'text/html');
```
