### ISSUE TITLE
Exception cant be caught in `concurrently`

### ISSUE THREAD

**Issue by foremtehan** [laravel/octane#418]
- Octane Version: 1.0.18
- PHP Version: 8.*
- Server & Version: Swoole 

### Description:
When some exception thrown in `Octane::concurrently` it terminate the script even though on try/catch

### Steps To Reproduce:
```php
try {
    Octane::concurrently([fn() => throw new \Exception('exception occur')]); // log has this exception
} catch (\Throwable) {
    // 
}
```

**Comment by Namoshek** [comment]
Haven't played with this feature myself yet, but I guess you should add the exception handling to each of the closures you are passing to `Octane::concurrently()` to ensure each closure returns a valid result (or potentially some sort of optional result which can be success/error at the same time).
