### ISSUE TITLE
Model Collection Not Displaying On Blades

### ISSUE THREAD

**Issue by dev-techguy** [laravel/octane#422]
- Octane Version: 1.0.19
- Laravel Version: 8.71.0
- PHP Version: 8.0.12
- Server & Version: Swoole 
- Database Driver & Version: postgres 12

No data is being displayed on the blade.

Return a model collection on a blade and try to loop through via a table.

**Comment by dev-techguy** [comment]
When using with Livewire

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by dev-techguy** [comment]
Thanks, I found the issues.
