### ISSUE TITLE
Add support for ReactPHP

### ISSUE THREAD

**Issue by nazmulpcc** [laravel/octane#425]
Good Day,
Is there any plan to integrate [ReactPHP](https://reactphp.org/http/)? Or is there any specific reason for it not existing?
I've played around with it a bit and seems like basic request/response, static files & file responses work pretty great with Octane & ReactPHP!
I could spend some more time in it & send a PR if needed. 
Thanks

**Comment by driesvints** [comment]
We have no plans for react php atm sorry. Swoole and roadrunner are the only ones well natively support in octane for now. We don't want the maintenance burden of another driver.
