### ISSUE TITLE
Gates do not work in `Octane::concurrently()`

### ISSUE THREAD

**Issue by smortexa** [laravel/octane#431]
- Octane Version: 1.0.21
- Laravel Version: 8.74.0
- PHP Version: 8.0.13
- Server & Version: Swoole 4.8.2
- Database Driver & Version: MariaDB 10.2

### Description:
The Laravel authorization services do not work in `Octane::concurrently()`

### Steps To Reproduce:

Just try:
```php
// FooServiceProvider.php
Gate::define('edit', fn(User $user) => true);

// BarController.php
$permission1 = Gate::allows('edit'));

[$permission2] = Octane::concurrently([
     fn () => Gate::allows('edit'),
]);

dd($permission1, $permission2);  // true, false
```

**Comment by driesvints** [comment]
Octane's concurrent requests are totally separate processed. As such, there's no auth state or any "http" state at all. Please see the docs here: https://laravel.com/docs/8.x/octane#concurrent-tasks

![Screenshot 2021-12-06 at 11 32 20](https://user-images.githubusercontent.com/594614/144830956-5ad2026e-af04-45d5-bcc2-b5dcadec008d.png)

**Comment by marol1210** [comment]
@driesvints 
How  variable  `workerState`  work  in where  `request`  register  callback.   when `$workerState->work` is assign?


1. include WorkerState
```
require_once __DIR__.'/WorkerState.php';

$workerState = new WorkerState;

$workerState->cacheTable = require __DIR__.'/createSwooleCacheTable.php';
$workerState->timerTable = $timerTable;
$workerState->tables = require __DIR__.'/createSwooleTables.php';
```

2. $workerState is instance of WorkerState
```
$server->on('request', function ($request, $response) use ($server, $workerState, $serverState) {
    $workerState->lastRequestTime = microtime(true);

    if ($workerState->timerTable) {
        $workerState->timerTable->set($workerState->workerId, [
            'worker_pid' => $workerState->workerPid,
            'time' => time(),
        ]);
    }

    $workerState->worker->handle(...$workerState->client->marshalRequest(new RequestContext([
        'swooleRequest' => $request,
        'swooleResponse' => $response,
        'publicPath' => $serverState['publicPath'],
        'octaneConfig' => $serverState['octaneConfig'],
    ])));

    if ($workerState->timerTable) {
        $workerState->timerTable->del($workerState->workerId);
    }
});

```
