### ISSUE TITLE
octane:reload command doesn't reflect changes (swoole)

### ISSUE THREAD

**Issue by michael-rubel** [laravel/octane#432]
- Octane Version: v1.0.20
- Laravel Version: v8.73.2
- PHP Version: v8.1.0
- Server & Version: Swoole v4.8.2
- Database Driver & Version: MariaDB v10.6.4

### Description:
`octane:reload` doesn't reflect changes with Swoole.
The issue basically the same as [this one](https://github.com/laravel/octane/issues/364) or [this one](https://stackoverflow.com/questions/68299225/octanereload-on-centos-8-doesnt-reflect-changes).
`octane:stop` works correctly, but creates downtime.

### Steps To Reproduce:
- Set up Octane on CentOS 7 with Nginx and Supervisor:
```
[program:octane]
command=/usr/bin/php -d variables_order=EGPCS /var/www/project/artisan octane:start --server=swoole --host=0.0.0.0 --port=8000 --max-requests=10000
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=youruser
stdout_logfile=/var/www/project/storage/logs/octane-workers.log
stopwaitsecs=60
```
Change something in the project, then run the `octane:reload` command from `youruser`.

**Comment by kevincobain2000** [comment]
Yes, I have also noted the same issue.
It doesn't reflect changes when new route/controller is added.

**Comment by driesvints** [comment]
Since this is about a specific bistro on Linux that we don't use ourselves I'm afraid we can't provide support here. It works well on Ubuntu (the default distro on Forge). We'd very much welcome PR's that would run Octane on CentOS.

**Comment by michael-rubel** [comment]
@driesvints Looks like the issue isn't CentOS-related.
It's something about the configuration cache and Octane's internal behavior.
When I type the following:
```
php artisan optimize:clear
php artisan octane:reload
```
Then it works.
If I add:
```
php artisan optimize:clear
php artisan optimize
php artisan octane:reload
```

Then the changes aren't made.

Perhaps Laravel takes the snapshot of the optimized config cache from an existing Octane instance so we cannot update the cache. Maybe it doesn't make sense at all in the case of using Octane?
