### ISSUE TITLE
Providers are not being reloaded while in development environment using --watch

### ISSUE THREAD

**Issue by p5ych0** [laravel/octane#433]
- Octane Version: 1.0.21
- Laravel Version: 8.75.0
- PHP Version: 8.0.13
- Server & Version: Swoole

### Description:

Changes to routes and service providers cause octane's reloading and I can see this from the logs, however actual changes are not being applied.
Manual stopping of supervisor's process doesn't help as well.

### Steps To Reproduce:
php cli container with supervisord running on behalf of non-root

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
