### ISSUE TITLE
Deny 

### ISSUE THREAD

**Issue by masterjus** [laravel/octane#436]
- Octane Version: all
- Laravel Version: 8.*
- PHP Version: 8.0
- Server & Version: RoadRunner 2.6.4
- Database Driver & Version:

### Description:
There's an option in the roadrunner serve command:

`'-o', 'http.static.dir='.base_path('public'),`

That means that the folder `public` contains static content.

So if we want to use roadrunners without nginx, the index.php file could be called and displayed as a static file.

### Steps To Reproduce:
- Run `php artisan octane:roadrunner`
- Open an url `http://localhost:8000/index.php`

The index.php file is displayed as a static file.

**Comment by masterjus** [comment]
Possible solution is to use an option `forbid`.
```
    # File patterns to forbid
    #
    # Default: empty
    forbid: [ "" ]
```

**Comment by driesvints** [comment]
I don't think we have any plans for this sorry. It's also very unclear what's the issue here. If you want to help improve Octane we're welcoming PR's. Thanks.
