### ISSUE TITLE
package_max_length is hard-coded

### ISSUE THREAD

**Issue by miladrahimi** [laravel/octane#442]
- Octane Version: 1.1.0
- Laravel Version: 8
- PHP Version: 8
- Server & Version: Swoole
- Database Driver & Version: N/A

### Description:
"package_max_length" which is one of Swoole server optiosn is hard-coded (10MB) and not configurabale.

### Steps To Reproduce:
Try to upload a 10 MB or larger file using laravel octane (with Swoole driver)

https://github.com/laravel/octane/blob/1.x/src/Commands/StartSwooleCommand.php#L129

**Comment by maher1337** [comment]
Hello,
That is not correct. its not "hard-coded" instead introduce the following to your octane.php
`'swoole' => [
        'options' => [
            'package_max_length' => 20 * 1024 * 1024,
        ],
    ],`
This will set package_max_length to 20 MB

**Comment by miladrahimi** [comment]
It works, thanks. But it needs to be documented and maybe added to octane config with empty `[]` bracket.
