### ISSUE TITLE
RoadRunner KV support

### ISSUE THREAD

**Issue by masterjus** [laravel/octane#444]
There's the KeyValue plugin for Roadrunner (https://roadrunner.dev/docs/beep-beep-kv).

For now, few very useful features like cache, tables are available for Swoole only. But the same functionality could be implemented by using the KeyValue plugin for Roadrunner.

**Comment by driesvints** [comment]
Heya. We'll take this in our backlog but for now we don't plan on working this ourselves. We would appreciate PR's however. Thanks
