### ISSUE TITLE
PHP Fatal Error on octane:start on fresh Laravel 8 app

### ISSUE THREAD

**Issue by nathan-io** [laravel/octane#446]
- Octane Version: 1.1.0
- Laravel Version: 8.76.2
- PHP Version: 8.0.13
- Server & Version: Swoole 4.8.4
- Database Driver & Version: Postgres 13.5

### Description:

Getting the following output when I run `php artisan octane:start` in a fresh Laravel installation:

```
   INFO  Server running…

  Local: http://127.0.0.1:8000

  Press Ctrl+C to stop the server

PHP Fatal error:  Declaration of Laravel\Octane\Tables\SwooleTable::column($name, $type, $size = 0) must be compatible with Swoole\Table::column(string $name, int $type, int $size = 0): bool in /mnt/c/Users/Nathan/Desktop/dev/platform/vendor/laravel/octane/src/Tables/SwooleTable.php on line 26
Fatal error: Declaration of Laravel\Octane\Tables\SwooleTable::column($name, $type, $size = 0) must be compatible with Swoole\Table::column(string $name, int $type, int $size = 0): bool in /mnt/c/Users/Nathan/Desktop/dev/platform/vendor/laravel/octane/src/Tables/SwooleTable.php on line 26
```

The only other packages installed are: Breeze and Nova.

The Swoole extension is active:

```
$ php -m | grep swoole
swoole
```

I have _not_ yet configured Nginx for this site/project on my local machine (WSL1 with [valet-wsl](https://github.com/valeryan/valet-wsl)), but I doubt that's related to this particular issue. 

### Steps To Reproduce:

1. Create a fresh Laravel project

2. Install Octane and set the `OCTANE_SERVER` env key to "swoole". 

3. Install Swoole server:

```
sudo pecl channel-update pecl.php.net
sudo pecl install swoole
```

4. Add the line `extension=swoole.so` to the end of the active `php.ini`. Restart PHP-FPM. (May want to add this step to the docs [here](https://laravel.com/docs/8.x/octane#swoole).)

5. Run `php artisan octane:start` from the project root folder.

**Comment by nunomaduro** [comment]
Created an issue in their repository: https://github.com/swoole/swoole-src/issues/4545. If they don't address this soon, I will have to adjust Octane code to accommodate potentially breaking changes between versions on the Table class.

**Comment by nathan-io** [comment]
Thank you!

**Comment by sy-records** [comment]
After the Swoole fix, it still needs to be compatible in octane

**Comment by nunomaduro** [comment]
Waiting for the Swoole team to release a new version before closing this issue.

**Comment by maher1337** [comment]
In the mean-time use a lower version of swoole if you want a workaround @nathan-io

**Comment by Sander0542** [comment]
The Swoole team has released a new version which works with the current Octane version.

**Comment by driesvints** [comment]
Closing this because Swoole released a fix.

**Comment by nathan-io** [comment]
Here's what I did to get the fix:

```
sudo pecl channel-update pecl.php.net
sudo pecl upgrade
```
