### ISSUE TITLE
Wrong log level for roadrunner worker

### ISSUE THREAD

**Issue by masterjus** [laravel/octane#450]
- Octane Version: 1.1.1
- Laravel Version: 8.x
- PHP Version: 8.0.13
- Server & Version: RoadRunner 2.6.6

### Description:
Doesn't matter in which mode server was executed, `info` level logs are returned.

I've checked the documentation, there's no log level `warning`. `warn` is correct one.

https://github.com/spiral/roadrunner-binary/blob/master/.rr.yaml#L84  

### Steps To Reproduce:
Run octane in production mode

**Comment by masterjus** [comment]
it's very important to fix because now we have stdout full of info messages

**Comment by masterjus** [comment]
https://github.com/laravel/octane/blob/1.x/src/Commands/StartRoadRunnerCommand.php#L88 here should be `logs.level=warn` instead of `logs.level=warning`

**Comment by driesvints** [comment]
@masterjus We're open to prs

**Comment by masterjus** [comment]
Done
