### ISSUE TITLE
laravel octane 500 Internal Server Error

### ISSUE THREAD

**Issue by ioiofadhil** [laravel/octane#453]
- Octane Version : ^1.0
- Laravel Version : 8.73.2
- PHP Version : 8.0
- Server : Swoole 
- Database Driver : MongoDB

### Description:
im trying to use async for creating records on models. It worked but the postman returned 500 Internal Server error. In this case, the records is created, but the status isnt 200(ok). Why? is there any memory limit on octane which triggered this 500 status?
My code :
```
 public function factory()
    {
        Octane::concurrently([
            function () {
                Model1::factory(50000)->create();
            },
            function () {
                Model2::factory(50000)->create();
            },
        ]);
    }

```

**Comment by ioiofadhil** [comment]
I'm trying to avoid this by using laravel queue. But inside the Queue, it runs synchronously (not async).

**Comment by ioiofadhil** [comment]
Also when i tried to GET more than about 600 records, its not displayed but status was OK (200). 
code : 
```
        $post =
            Octane::concurrently([
                fn () => Model::all(), //500 records
                fn () => Model::all(), //500 records
            ]);
        return $post;

```

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
