### ISSUE TITLE
Swoole not reflecting changes after deployment via Envoyer

### ISSUE THREAD

**Issue by Abhi0725** [laravel/octane#455]
- Octane Version: v1.1.0
- Laravel Version: ^8.65
- PHP Version: 8.1.0
- Server & Version: Swoole / RoadRunner Swoole 4.8.3
- Database Driver & Version: MySql 8.0.26

### Description:
I am deploying Octane project via Envoyer. I have added `octane:reload` command in my deployment hooks but the changes are not getting reflected.

### What have I tried?

I tried a hack to stop octane before the "activate" hook changes symlink and then added another hook to start the octane (hacky, I know) but the deployment then get stuck at octane start command in envoyer (not showing error just stuck). But I can see the changes being reflected.

### Steps To Reproduce:
Just deploy a project via Envoyer.

**Comment by driesvints** [comment]
Heya, can you please contact Envoyer support in-app? Thanks

**Comment by indigoram89** [comment]
@Abhi0725 how did you solve it?

**Comment by robtesch** [comment]
I'm currently facing the same issue. Would it not be prudent to put the solution up here so everyone can see?

**Comment by indigoram89** [comment]
@robtesch I found only the following solution, but it works good:

1. I created the separate Deployment Hook in Envoyer which runs only on servers with Octane.

2. Deployment script for that Hook looks like this:

`cd {{ project }}

git pull origin {{ branch }}

{{ composer }} install --no-interaction --prefer-dist --optimize-autoloader

! {{ php }} artisan octane:status || {{ php }} artisan octane:reload`

3. Also you need to add the following files to gitignore: current, releases.

It is important to understand that Envoyer deployment rollbacks won't work - we need to add separate Hook for it too.

I hope it will help you.

**Comment by robtesch** [comment]
@indigoram89 thanks for taking the time to respond. I have actually gone ahead and disabled Octane for now as there were just too many hickups. I have contacted Envoyer support and if they provide a better solution I will post it here. The solution you've posted above doesn't make too much sense to me because it seems that it's just pulling performing a regular update to the code without actually using the "releases" functionality. If that's what's happening, then perhaps it's best to just use Forge without envoyer.

**Comment by indigoram89** [comment]
@robtesch yes, you are right. I also contacted Envoyer support, but then did not provide a better solution. For now Octane works good in our project and we need Envoyer because we have several servers and we need to deploy (and sync env) between all them.

**Comment by ChrisExP** [comment]
This is the approach I use. It's worked well so far: https://gist.github.com/pascalbaljet/ccc2c3c5b8cda91fa20b0ced588067e4

Basically when deploying you create a second octane service on a different port, switch nginx to point to that port, then gracefully delete the first octane service.

But it does trigger a bunch of Sentry errors when killing the old service but that doesn't impact the user at all so I just ignore them. It would be handy to have a native solution though.
