### ISSUE TITLE
[Feature Request] Implement function to receive swoole server statistics in OpenMetrics format

### ISSUE THREAD

**Issue by Atomzwieback** [laravel/octane#463]
Hi,

i would like to request the feature to utilize the [swoole server statistics](https://openswoole.com/docs/modules/swoole-server-stats) due we cant access the swoole server variable we cant get it directly. We need this feature to export this data via OpenMetrics format to octane

**Comment by driesvints** [comment]
We have no plans for this right now, sorry.
