### ISSUE TITLE
Terminate gracefully on SIGTERM

### ISSUE THREAD

**Issue by spawnia** [laravel/octane#469]
- Octane Version: 1.2.0
- Laravel Version: 8.80.0
- PHP Version: 8.0.9
- Server & Version: Swoole 4.7.0
- Database Driver & Version: None

### Description:

When terminating a running Octane process with `SIGTERM`, it exits with the non-zero exit code `137`.
This indicates a crash or abrupt failure.

I would expect the process to terminate gracefully with exit code `0`.

### Steps To Reproduce:

```sh
root@59d2aec7e8b2:/var/www# php artisan octane:start 

   INFO  Server running…

  Local: http://127.0.0.1:8000 

  Press Ctrl+C to stop the server

root@59d2aec7e8b2:/var/www# echo $?
137
```

In a second terminal, while Octane is running:

```sh
root@59d2aec7e8b2:/var/www# ps aux | grep octane
root       264  0.1  0.2 119612 59224 pts/1    S+   15:34   0:00 php artisan octane:start
root       307  0.0  0.0   3084   820 pts/2    S+   15:36   0:00 grep octane
root@59d2aec7e8b2:/var/www# kill -TERM 264
```

**Comment by driesvints** [comment]
Although not ideal, I don't see this as disruptive or blocking. Feel free to send in a PR if you have a fix 👍
