### ISSUE TITLE
`max_execution_time` config doesn't work

### ISSUE THREAD

**Issue by smortexa** [laravel/octane#470]
- Octane Version: 1.1.1
- Laravel Version: 8.77.1
- PHP Version: 8.1.0
- Server & Version: Swoole 4.8.3

### Description:
When the execution time for requests being handled by Octane exceeded from `max_execution_time` in `octane.php` config file, the Octane wouldn't send any response and the request remains in the pending state.

### Steps To Reproduce:

Set `max_execution_time` to `2` seconds in `octane.php`:

```php
// config/octane.php
return [
    'max_execution_time' => 2,
];
```

and try:
```php
Route::get('/foo', function() {
    sleep(3);
    return 'bar';
});
```

I know this may be a Swoole bug. So if confirmed, I'll open an issue on the Swoole repo.

**Comment by sy-records** [comment]
When the max_execution_time is reached, it is a SIGKILL signal sent directly, so it causes no response.

https://github.com/laravel/octane/blob/722b7567e2817b3f5e4a4ae7b49290f53968a114/src/Swoole/Actions/EnsureRequestsDontExceedMaxExecutionTime.php#L27

This is not a bug, but requires Swoole support.
OpenSwoole adds a [max_request_execution_time](https://openswoole.com/docs/modules/swoole-server/configuration#max_request_execution_time).

**Comment by driesvints** [comment]
Thanks @sy-records

**Comment by smortexa** [comment]
@sy-records The Swoole maintainer [solution](https://github.com/swoole/swoole-src/issues/4594#issuecomment-1099119681) also doesn't work. The following error will be thrown:
```php
PHP Fatal error:  Uncaught ErrorException: Swoole\Http\Response::status(): http response is unavailable (maybe it has been ended or detached)
```
