### ISSUE TITLE
419 Page Expired with Octane, Sail and Dusk

### ISSUE THREAD

**Issue by martio** [laravel/octane#476]
- Octane Version: 1.2.0
- Laravel Version: 8.82.0
- PHP Version: 8.1.1
- Server & Version: Swoole
- Database Driver & Version: MySQL 8

### Description:

After migration to Laravel Octane, the dusk tests fails with 419 Page Expired. Before the migration, everything was fine...

### Steps To Reproduce:

I made the following change to the name file `docker/8.1/supervisord.conf`

```
-command=/usr/bin/php -d variables_order=EGPCS /var/www/html/artisan octane:start --server=swoole --host=0.0.0.0 --port=80
+command=/usr/bin/php -d variables_order=EGPCS /var/www/html/artisan serve --host=0.0.0.0 --port=80
```

**Comment by sy-records** [comment]
see https://github.com/laravel/octane/issues/252#issuecomment-833528977

**Comment by martio** [comment]
@sy-records I changed from

```
SESSION_DRIVER=database
SESSION_LIFETIME=120
SESSION_DOMAIN=laravel.test
```

to

```
SESSION_DRIVER=database
SESSION_LIFETIME=120
SESSION_DOMAIN=null
```

and no effect :(

**Comment by martio** [comment]
The problem only occurs during dusk testing...

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
