### ISSUE TITLE
Memory leak when using Http facade

### ISSUE THREAD

**Issue by Ostojic-96** [laravel/octane#481]
- Octane Version: v1.2.1
- Laravel Version: v9.0.2
- PHP Version: 8.1
- Server & Version: Openswoole 4.9.1
- Sail version: v1.13.2

 When I'm using Http facade memory is going up with every request. My setup is made with Laravel Sail.
```
Route::get('test', function () {
Http::get('https://swapi.dev/api/people/1');

return memory_get_usage();
});
```
![http facade leak](https://user-images.githubusercontent.com/76952170/154912546-e5d17535-680e-479c-8135-16cbd43c5a70.png)

This is not the case with the Guzzle client
```
Route::get('test', function () {
    $client = new \GuzzleHttp\Client();
    $client->get('https://swapi.dev/api/people/1');
    return memory_get_usage();
});  
```
![guzzle](https://user-images.githubusercontent.com/76952170/154912635-0705272d-4c71-49b9-adee-88bf23cae267.png)

I already tried other channels like Discord, Laracasts, Stackoverflow but didn't get any answers.

**Comment by driesvints** [comment]
@Ostojic-96 can you link to the Laracasts and Stackoverflow threads?

**Comment by Ostojic-96** [comment]
> @Ostojic-96 can you link to the Laracasts and Stackoverflow threads?

Sure.
[Laracasts](https://laracasts.com/discuss/channels/laravel/laravel-octane-memory-leak-with-http-facade)
[Stackoverflow](https://stackoverflow.com/questions/71154405/memory-leak-when-using-http-facade-with-laravel-octane)

**Comment by nunomaduro** [comment]
I've tested this exact code with `wrk` and millions of requests, and there is no memory leak here. The fact that you see the memory increasing for a few requests just means that Octane didn't run the `gc_collect_cycles` yet.
