### ISSUE TITLE
octane:start --watch is not watching for modified files

### ISSUE THREAD

**Issue by peibinzhu** [laravel/octane#487]
- Octane Version: 1.2.3
- Laravel Version: 9.2.0
- PHP Version: 8.0.15
- Server & Version: Swoole 4.8.6

### Description:

octane:start --watch does not monitor modified files, I see that there is already the same [problem](https://github.com/laravel/octane/issues/237#issuecomment-842306654), the solution is to add **`usePolling:true`** to the `vendor/laravel/octane/bin/file-watcher.js` file, after adding Changing the file worked. But this destroys the integrity of the component, I hope it can be modified in the configuration file.

### Steps To Reproduce:

Run command.

`php artisan octane:start --watch`

After modifying the file, it is not monitored.

![a5cdcf08a3616558f6c9b6b1d488f4d](https://user-images.githubusercontent.com/26355253/156494505-78a2da11-8542-4843-9424-1cd51e61d23b.png)

This is the file before modification.

![767b262169a22425e377986017aeeaa](https://user-images.githubusercontent.com/26355253/156494526-537e286b-7930-4574-9740-6e8125199358.png)

在 `vendor/laravel/octane/bin/file-watcher.js` 文件中加入 **`usePolling:true`**.

![6aeee3b6f0612ab6037396246bd60c4](https://user-images.githubusercontent.com/26355253/156494672-f67ee1b4-9d32-4d11-9569-01eb95d14feb.png)

Rerun the command:

`php artisan octane:start --watch`

Changed "hello" to "hello world", this time he was watched.

![cc360bf3e14ec57420dc98d33156994](https://user-images.githubusercontent.com/26355253/156494715-ebc38fb9-3f02-43dd-baff-f45781a757ad.png)

**Comment by peibinzhu** [comment]
> @peibinzhu What do you mean by "But this destroys the integrity of the component"?

Sorry, maybe my description is not very clear, what I want to express is that I need to manually modify `vendor/laravel/octane/bin/file-watcher.js` This file, add `usePolling:true` in it to have an effect. But this involves modifying the source code, which I don't want to do.

**Comment by nunomaduro** [comment]
After the next release, you can use `--poll` option to watch files on non-standard environments.

**Comment by peibinzhu** [comment]
> After the next release, you can use `--poll` option to watch files on non-standard environments.

Thanks.
