### ISSUE TITLE
Using queue job after commit under laravel octane does not work

### ISSUE THREAD

**Issue by chendaizhi** [laravel/octane#489]
- Octane Version: 1.2.2
- Laravel Version: 8.83.1
- PHP Version: 8.0
- Server & Version: Swoole / RoadRunner Swoole 4.8.6
- Database Driver & Version: phpredis 5.3.2  redis 6.0.9
- laravel horizon: 5.9.1

### Description:
Using queue job after commit under laravel octane does not work

<img width="858" alt="image" src="https://user-images.githubusercontent.com/45749908/156954431-d763d106-cef8-4f54-b551-186efe1e6ae7.png">

<img width="620" alt="image" src="https://user-images.githubusercontent.com/45749908/156954552-19d09b67-5f4a-4b90-8fc3-7c1307e7b15e.png">

<img width="782" alt="image" src="https://user-images.githubusercontent.com/45749908/156954603-076783bd-f560-43ec-9823-66447c02d673.png">

<img width="1060" alt="image" src="https://user-images.githubusercontent.com/45749908/156954635-38740117-ad03-4a13-abfa-bc041f648ee9.png">

<img width="612" alt="image" src="https://user-images.githubusercontent.com/45749908/156954665-8d2a6b0f-7ce7-4e50-82a7-c7300f9ef05d.png">

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!

**Comment by driesvints** [comment]
Heya, thanks for reporting.

We'll need more info and/or code to debug this further. Can you please create a repository with the command below, commit the code that reproduces the issue as separate commits on the main/master branch and share the repository here? Please make sure that you have the [latest version of the Laravel installer](https://github.com/laravel/installer) in order to run this command. Please also make sure you have both Git & [the GitHub CLI tool](https://cli.github.com) properly set up.

```bash
laravel new bug-report --github="--public"
```

Please do not amend and create a separate commit with your custom changes. After you've posted the repository, we'll try to reproduce the issue.

Thanks!

**Comment by chendaizhi** [comment]
@driesvints https://github.com/chendaizhi/bug-report

**Comment by driesvints** [comment]
You committed everything into a single commit. Please follow the instructions closely.

**Comment by chendaizhi** [comment]
https://github.com/chendaizhi/bug-report/blob/master/app/Http/Controllers/IndexController.php

**Comment by chendaizhi** [comment]
I don't know how to deal with it. I have no experience. I'm sorry,

I wrote it in app/Http/Controllers/Indexcontroller.php In this,

Jobs is in app/Jobs/TestJob.php,

Table indatabase/migrations/2022_03_17_013612_create_test_table.php，

The driver of the queue is redis, and the command is php artisan queue: work redis -- queue = test -- sleep = 0

**Comment by chendaizhi** [comment]
I don't know how to deal with it. I have no experience. I'm sorry,

I wrote it in app/Http/Controllers/Indexcontroller.php In this,

Jobs is in app/Jobs/TestJob.php,

Table indatabase/migrations/2022_03_17_013612_create_test_table.php，

The driver of the queue is redis, and the command is php artisan queue: work redis -- queue = test -- sleep = 0 @driesvints
