### ISSUE TITLE
Octane::route not working on artisan optimize

### ISSUE THREAD

**Issue by ahmadeyamin** [laravel/octane#490]
- Octane Version: 1.2
- Laravel Version: 9.2
- PHP Version: 8.1.3
- Server & Version: Swoole 4.9.1

### Description:

Octane route not working after calling `php artisan optimize`
```php
Octane::route('GET', '/url', function(){
    return new Response('hello world');
});
```

### Steps To Reproduce:

Set route
```php
Octane::route('GET', '/url', function(){
    return new Response('hello world');
});
```

run `php artisan optimize`
run `php artisan octane:start`

hit `/url` route

I don't know is this a problem or features I just noticed this is not working in my application while I was testing.

**Comment by driesvints** [comment]
I don't think `Octane::route` is meant for public usage. Only for inner usage.
