### ISSUE TITLE
Queue afterCommit is not supported

### ISSUE THREAD

**Issue by chendaizhi** [laravel/octane#493]
Queue afterCommit is not supported https://github.com/laravel/octane/issues/489

**Comment by driesvints** [comment]
Please try a support channel first like I asked, thanks.

**Comment by chendaizhi** [comment]
Hello, I've seen it all, and I've tested it many times, and laravel9 has also tested it, but it just doesn't support running queues without committing transactions @driesvints

**Comment by chendaizhi** [comment]
Do you have time to test the problem? Thanks
