### ISSUE TITLE
Octane::concurrently Leaking Open Database Connections 

### ISSUE THREAD

**Issue by foremtehan** [laravel/octane#495]
- Octane Version: v1.2.4
- Laravel Version: 9
- PHP Version: 8.1.2
- Server & Version: Swoole
- Database Driver & Version: PostgreSQL

### Description:
When using `Octane::concurrently` for database query, I noticed octane opens new connections on every requests and wont close it,

So if there are 1000 request comes in we have 1000 open connection until database/server restart

### Steps To Reproduce:
I'm using PostgreSQL on heroku, I checked the number of connections by `heroku pg:info` and it increments on every request:

```php
Octane::concurrently([
    fn() => Title::first(),
    fn() => Post::first(),
    fn() => Thread::first(),
]);

// adds 3 more connection on every request and wont close it
```

**Comment by driesvints** [comment]
That's intended as the concurrently function opens new processes for each call. Therefor new database connections will be started.

**Comment by foremtehan** [comment]
Can you tell how to close connection in laravel? Because when i do `pg_close()` is says:

No PostgreSQL connection opened yet
