### ISSUE TITLE
Laravel Octane does not reset static property values

### ISSUE THREAD

**Issue by mtawil** [laravel/octane#496]
- Octane Version: 1.2.4
- Laravel Version: 9.5.1
- PHP Version: 8.1.2
- Server & Version: Swoole 4.10.0

### Description:
Somehow Laravel Octane doesn't reset static property values between requests, and it's delivering that last value instead of that.

### Steps To Reproduce:
1. Put this snippet to your route:
```php
class Test {
    public static string $foo = 'bar';
}

Route::get('/test-1', function () {
    return Test::$foo;
});

Route::get('/test-2', function () {
    Test::$foo = 'baz';

    return 'Property value changed';
});
```

2. Hit `/test-1`, and the result is `bar`.
3. Hit `/test-2`, the request that is changing the property value to `baz`, you will see the result is `Property value changed`.
4. Get back and refresh `/test-1` again; the result is changed to `baz`, not `bar`.

I've attached the screen video recording:
https://user-images.githubusercontent.com/700753/159297035-11fbc778-4f10-4417-b65b-d13590cd693c.mp4

**Comment by driesvints** [comment]
Octane is a long running process so this is expected. You're responsible for clearing these between requests.
