### ISSUE TITLE
Enabling coroutines and Swoole Hooks leads to a broken container sometimes

### ISSUE THREAD

**Issue by RedChops** [laravel/octane#497]
- Octane Version: 1.2.4
- Laravel Version: 9.5.1
- PHP Version: 8.1.3
- Server & Version: Swoole  4.10.0
- Database Driver & Version: N/A to this bug

### Description:

It seems like just the act of enabling coroutines and the Swoole file command hooks leads to a situation where issuing a number of concurrent requests (see steps below for command I like to use), the possibly last request will sometimes fail with the following stack trace:

```
ReflectionException: Class "events" does not exist in /home/dan/workspace/bug-report/vendor/laravel/framework/src/Illuminate/Container/Container.php:877
Stack trace:
#0 /home/dan/workspace/bug-report/vendor/laravel/framework/src/Illuminate/Container/Container.php(877): ReflectionClass->__construct()
#1 /home/dan/workspace/bug-report/vendor/laravel/framework/src/Illuminate/Container/Container.php(758): Illuminate\Container\Container->build()
#2 /home/dan/workspace/bug-report/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(855): Illuminate\Container\Container->resolve()
#3 /home/dan/workspace/bug-report/vendor/laravel/framework/src/Illuminate/Container/Container.php(694): Illuminate\Foundation\Application->resolve()
#4 /home/dan/workspace/bug-report/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(840): Illuminate\Container\Container->make()
#5 /home/dan/workspace/bug-report/vendor/laravel/framework/src/Illuminate/Container/Container.php(1417): Illuminate\Foundation\Application->make()
#6 /home/dan/workspace/bug-report/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(118): Illuminate\Container\Container->offsetGet()
#7 /home/dan/workspace/bug-report/vendor/laravel/octane/src/ApplicationGateway.php(36): Illuminate\Foundation\Http\Kernel->handle()
#8 /home/dan/workspace/bug-report/vendor/laravel/octane/src/Worker.php(92): Laravel\Octane\ApplicationGateway->handle()
#9 /home/dan/workspace/bug-report/vendor/laravel/octane/bin/swoole-server(117): Laravel\Octane\Worker->handle()
#10 [internal function]: {closure}()
#11 {main}

Next Illuminate\Contracts\Container\BindingResolutionException: Target class [events] does not exist. in /home/dan/workspace/bug-report/vendor/laravel/framework/src/Illuminate/Container/Container.php:879
Stack trace:
#0 /home/dan/workspace/bug-report/vendor/laravel/framework/src/Illuminate/Container/Container.php(758): Illuminate\Container\Container->build()
#1 /home/dan/workspace/bug-report/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(855): Illuminate\Container\Container->resolve()
#2 /home/dan/workspace/bug-report/vendor/laravel/framework/src/Illuminate/Container/Container.php(694): Illuminate\Foundation\Application->resolve()
#3 /home/dan/workspace/bug-report/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(840): Illuminate\Container\Container->make()
#4 /home/dan/workspace/bug-report/vendor/laravel/framework/src/Illuminate/Container/Container.php(1417): Illuminate\Foundation\Application->make()
#5 /home/dan/workspace/bug-report/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(118): Illuminate\Container\Container->offsetGet()
#6 /home/dan/workspace/bug-report/vendor/laravel/octane/src/ApplicationGateway.php(36): Illuminate\Foundation\Http\Kernel->handle()
#7 /home/dan/workspace/bug-report/vendor/laravel/octane/src/Worker.php(92): Laravel\Octane\ApplicationGateway->handle()
#8 /home/dan/workspace/bug-report/vendor/laravel/octane/bin/swoole-server(117): Laravel\Octane\Worker->handle()
#9 [internal function]: {closure}()
#10 {main}%
```

This does not happen with every batch of concurrent requests; if I issue 20 requests, sometimes I get 20 back, sometimes I get 19 back with the above stack trace. Usually it's just one failed request, in large batches sometimes it's two or more. The one thing that seems to be a common denominator is the failure always seems to be the last request to return.

The resolution failure seems to happen in the first middleware that's attempted. Sometimes in my actual application, middleware that has other required parameters will sometimes fail because the parameters are not resolved and passed. I'm assuming that's related to this.

Rarely, I'll also get the following stack trace:

```
PHP Fatal error:  Uncaught Error: Call to a member function handle() on null in /home/dan/workspace/bug-report/vendor/laravel/octane/bin/swoole-server:113
Stack trace:
#0 [internal function]: {closure}()
#1 {main}
  thrown in /home/dan/workspace/bug-report/vendor/laravel/octane/bin/swoole-server on line 113
Fatal error: Uncaught Error: Call to a member function handle() on null in /home/dan/workspace/bug-report/vendor/laravel/octane/bin/swoole-server:113
```

### Steps To Reproduce:

https://github.com/RedChops/bug-report

Note: in my test route, I issue a sleep(1) command. This is handled by Swoole hooks and is non-blocking. It's also not required. If I remove the sleep() statement, I get the errors all the same.

1. Start the server with a single worker: `php artisan octane:start --workers=1`
2. Issue a large number of concurrent requests: `xargs -I % -P 120 curl -s "http://localhost:8000/test" < <(printf '%s\n' {1..120})`

Since this issue seems to be limited to SWOOLE_HOOK_FILE, I can likely work around it in some projects by specifying the exact hooks I'll need, but in other projects I do need file operations to be nonblocking when using Swoole.

**Comment by RedChops** [comment]
My mistake, it seems like the hook that causes the breakage is SWOOLE_HOOK_STDIO. After significant different testing with different bitwise groups of hook flags, it would seem like the following is enough to work around the bug:
`'hook_flags' => SWOOLE_HOOK_ALL ^ SWOOLE_HOOK_STDIO,`

It's interesting, SWOOLE_HOOK_FILE must contain parts of SWOOLE_HOOK_STDIO, as with STDIO disabled, I don't need to also disable FILE.

**Comment by driesvints** [comment]
Coroutines are not supported by Octane atm.
