### ISSUE TITLE
Deprecation warning in SwooleClient when Octane tries to set the SameSite Cookie

### ISSUE THREAD

**Issue by Namoshek** [laravel/octane#498]
- Octane Version: 1.2.4
- Laravel Version: 8.83.5
- PHP Version: 8.1.4
- Server & Version: `ext-swoole:4.8.8`
- Database Driver & Version: `pdo_sqlsrv:5.10.0`

### Description:
During normal execution of (as far as I can see) every request, I find the following warning twice in my logs (using Telescope):
```
Swoole\Http\Response::cookie(): Passing null to parameter #8 ($samesite) of type string is deprecated in /var/www/vendor/laravel/octane/src/Swoole/SwooleClient.php on line 198
```
(Log level is `warning`)

### Steps To Reproduce:
- Run Laravel Octane
- Request any page
- Check logs

**Comment by driesvints** [comment]
This is a deprecation so nothing is really broken here. We'd welcome a PR to solve this. Thanks.
