### ISSUE TITLE
Update resetScope to forgetScopedInstances in Listeners/FlushTemporaryContainerInstances

### ISSUE THREAD

**Issue by coleshirley** [laravel/octane#500]
- Octane Version: ^1.0.5
- Laravel Version: ^8.47.0
- PHP Version: 8.0
- Server & Version: Swoole / RoadRunner Any
- Database Driver & Version: Any

### Description:
In this commit: https://github.com/laravel/framework/commit/2971b64ac29bec9e65afe683ab4fcd461c565fe5 the `resetScope()` method on the container class was changed to `forgetScopedInstances()` but this change was never reflected in Octane in https://github.com/laravel/octane/blob/1.x/src/Listeners/FlushTemporaryContainerInstances.php 

### Solution

```php
<?php

namespace Laravel\Octane\Listeners;

class FlushTemporaryContainerInstances
{
    /**
     * Handle the event.
     *
     * @param  mixed  $event
     * @return void
     */
    public function handle($event): void
    {
        if (method_exists($event->app, 'resetScope')) {
            $event->app->resetScope();
        }
 
        // Add this section
        if (method_exists($event->app, 'forgetScopedInstances')) {
            $event->app->forgetScopedInstances();
        }

        foreach ($event->sandbox->make('config')->get('octane.flush', []) as $binding) {
            $event->app->forgetInstance($binding);
        }
    }
}
```

**Comment by driesvints** [comment]
Thanks for noting this. I sent in a PR: https://github.com/laravel/octane/pull/501
