### ISSUE TITLE
Looking forward to supporting coroutines

### ISSUE THREAD

**Issue by jobsssss** [laravel/octane#503]
There are already many php frameworks that support coroutines, such as hyperf, swoft, etc.

However, these frameworks are obviously inferior to laravel in terms of ecological richness and community appeal. If laravel can support coroutines, it can obviously promote the construction of the entire coroutine ecology

**Comment by driesvints** [comment]
Heya. We are considering this but unfortunately cannot give a time window for it. Thanks for your request.

**Comment by bernardwiesner** [comment]
Just curious if there is any development on this, it would be a really nice feature to have.

**Comment by Spartaques** [comment]
It's the case why all other developers think that php is not serious). For me, it's #1 priority task for laravel team to implement.
