### ISSUE TITLE
The "max_execution_time" setting has no effect with Roadrunner

### ISSUE THREAD

**Issue by Baiquette** [laravel/octane#504]
- Octane Version: 1.2.6
- Laravel Version: 9.7.0
- PHP Version: 8.0.17
- Server & Version:  RoadRunner 2.9.0

### Description

Hello,

I just created a new Laravel application by adding Octane and running it with Roadrunner.
I tried to set the `max_execution_time` settings in the Octane configuration file, but it seems this setting has no effect.

### Steps To Reproduce:
I followed the normal process:
```bash
laravel new octane-timeout
composer require laravel/octane
php artisan octane:install (with Roadrunner)
```

Then, I changed in `config/octane.php` file the `max_execution_time` setting by "3":
```php
    /*
    |--------------------------------------------------------------------------
    | Maximum Execution Time
    |--------------------------------------------------------------------------
    |
    | The following setting configures the maximum execution time for requests
    | being handled by Octane. You may set this value to 0 to indicate that
    | there isn't a specific time limit on Octane request execution time.
    |
    */

    'max_execution_time' => 3,
```

Then, I created a simple code in my `routes/web.php` file:
```php
Route::get('/', function () {
	$i = 0;

	while ($i < 40) {
		$i++;
		sleep(1);
	}
});

```
And I started the server with:
```bash
php artisan octane:start
```

Instead of to get a "Max memory limit" (after 3 seconds), the code has been executed without any timeout.
![image](https://user-images.githubusercontent.com/11754343/162631750-f87a84ff-84f3-4c9d-96d3-ae7dd029c5e3.png)

To  be sure, I cleared the configuration with:
```bash
php artisan config:clear
```

Also tried with:
```bash
php artisan optimize
```

According to the Roadrunner documentation and the file below, this setting should work:
https://github.com/laravel/octane/blob/a6ac540eaa7524042af1355a5cf4e40b3445d60c/src/Commands/StartRoadRunnerCommand.php#L86

Do you have an idea why?

Thank you

**Comment by driesvints** [comment]
Hmm, no I don't actually.. @tarampampam do you might have an idea here?

**Comment by driesvints** [comment]
@Baiquette can you also verify that `$this->maxExecutionTime()` is actually returning `3`?

**Comment by driesvints** [comment]
I do see it uses `s` in the example here: https://github.com/roadrunner-server/roadrunner/blob/master/.rr.yaml#L273-L276

Can you try to set it to `'max_execution_time' => '3s',`?

**Comment by Baiquette** [comment]
@driesvints It seems yes:

```php
dd ('http.pool.supervisor.exec_ttl='.$this->maxExecutionTime());
```

![image](https://user-images.githubusercontent.com/11754343/162686797-72389153-248a-4bfa-a28b-380bdedfdeaf.png)

**Comment by Baiquette** [comment]
> I do see it uses `s` in the example here: [roadrunner-server/roadrunner@`master`/.rr.yaml#L273-L276](https://github.com/roadrunner-server/roadrunner/blob/master/.rr.yaml?rgh-link-date=2022-04-11T07%3A31%3A37Z#L273-L276)
> 
> Can you try to set it to `'max_execution_time' => '3s',`?

It seems the method `maxExecutionTime` already adds the "s":
![image](https://user-images.githubusercontent.com/11754343/162686971-1d39418e-578f-49f1-a387-07dacaa97628.png)

**Comment by driesvints** [comment]
Okay then I'm out of ideas 😅

**Comment by tarampampam** [comment]
@driesvints I suppose that @rustatian will be more relevant for your question 😄

**Comment by driesvints** [comment]
@tarampampam ah thanks for forwarding! 🙂

**Comment by rustatian** [comment]
Hey 👋🏻 There is no such option in the RR 😃 
RR has the `exec_ttl` option -> for example `http.pool.exec_ttl = 10s`.

**Comment by driesvints** [comment]
Hey @rustatian, I think you mistook the Laravel Octane config option name from what we pass to RR? See: 
 https://github.com/laravel/octane/blob/a6ac540eaa7524042af1355a5cf4e40b3445d60c/src/Commands/StartRoadRunnerCommand.php#L86

**Comment by rustatian** [comment]
I'm not a PHP dev :) But yeah, it seems that you mentioned that above. Give me a sec; I'll double-check that.

**Comment by Baiquette** [comment]
@driesvints : Just to be sure it is not an issue due to my PHP config, I manually updated my "php.ini" file by setting:
```
max_execution_time=2
```

**Comment by rustatian** [comment]
I can confirm that this is a RR problem. I found the issue and will release the `v2.9.1` today. Thanks.

**Comment by driesvints** [comment]
Thanks @rustatian!

**Comment by driesvints** [comment]
Cool, thanks @rustatian!
