### ISSUE TITLE
Octane closes due to type error

### ISSUE THREAD

**Issue by juanfelipepipen** [laravel/octane#505]
- Octane Version: 1.2.6
- Laravel Version: 9.7.0
- PHP Version: 8.1.4
- Server & Version: Swoole

### Description:
After some time, approx 5 minutes after starting octane, a type error appears, I attach a screenshot

![Screenshot from 2022-04-10 21-51-48](https://user-images.githubusercontent.com/33106375/162667542-2db999e2-733c-40be-8d22-676b76e9233f.png)

**Comment by sy-records** [comment]
You can start by checking if the `/storage/logs/octane-server-state.json` file exists and is readable, and if the `masterProcessId` exists.

**Comment by driesvints** [comment]
Looks like a fix was sent in. Thanks
