### ISSUE TITLE
How can I tell if my instance is using Octane?

### ISSUE THREAD

**Issue by caiokawasaki** [laravel/octane#508]
Some of my application's services are consumed through the API over Octane and through the queues/jobs.

In some of these services I would like to use the `Octane::concurrently()` method if it is in the API and use the "normal" method if it is in the queue/job, is this possible?

Sample:

```php
public function customServiceAction()
{
    Octane::isRunning() ? // Sample method name
        Octane::concurrently([
            fn() => $this->sendMessage()
        ]) :
        $this->sendMessage();
}

private function sendMessage()
{
    // Magic
}
```

**Comment by smortexa** [comment]
You can define these helper functions:
```php

use Swoole\Http\Server

if (!function_exists('servedByOctane')) {
    function servedByOctane(): bool
    {
        return isset($_SERVER['LARAVEL_OCTANE']) && ((int)$_SERVER['LARAVEL_OCTANE'] === 1);
    }
}

if (!function_exists('onSwooleServer')) {
    function onSwooleServer(): bool
    {
        return (extension_loaded('swoole') || extension_loaded('openswoole')) && app()->bound(Server::class);
    }
}

```

**Comment by Namoshek** [comment]
Have you tried simply using `Octane::concurrently(..)` without any prior checks? I'm not sure, but from the code behind that method, I would assume it falls back to the `SequentialTaskDispatcher` (which executes sequentially in-process):

https://github.com/laravel/octane/blob/85dcacf054bfe9b813b3b9fdbdb1cdd50f5f3bcd/src/Concerns/ProvidesConcurrencySupport.php#L36-L48

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by SimonMacIntyre** [comment]
> Have you tried simply using `Octane::concurrently(..)` without any prior checks? I'm not sure, but from the code behind that method, I would assume it falls back to the `SequentialTaskDispatcher` (which executes sequentially in-process):
> 
> https://github.com/laravel/octane/blob/85dcacf054bfe9b813b3b9fdbdb1cdd50f5f3bcd/src/Concerns/ProvidesConcurrencySupport.php#L36-L48

This also has me confused, I have openswoole installed, and concurrency seems to work, but I also tested in tinker and each of those `match()` checks are false so it would also default to `SequentialTaskDispatcher` 🤔

**Comment by Whallas** [comment]
I don't know if it's correct this way, I'm still testing it. I've implemented this:

**AppServiceProvider.php**
```php
if (!servedByOctane() && !$this->app->bound(DispatchesTasks::class)) {
            $this->app->bind(DispatchesTasks::class, SequentialTaskDispatcher::class);
}
```
Using the function suggested by @smortexa.
