### ISSUE TITLE
shutdown callback

### ISSUE THREAD

**Issue by robberphex** [laravel/octane#512]
I'm using octane as PHP application server, and register to nacos/consul, within `boot` method of one of application's service providers(<https://laravel.com/docs/8.x/octane#ticks-and-intervals>), start a registry-ticker.

But unfortunately, when octan is shutting down, there is no chance to deregister the instance to nacos/consul.

Could we add a mechanism to let registry-ticker know when to deregister?

**Comment by robberphex** [comment]
There could be `unboot` method of service provider.

When octane is shutting down, call `unboot` method firstly.

**Comment by driesvints** [comment]
Hey @robberphex, thanks for your feature request. We consider this to be a responsibility of user land and not Octane to deregister any services you register yourself. 

If you feel there could be a better mechanism in Octane itself you could always attempt a PR, thanks.
