### ISSUE TITLE
I encountered a SwooleExtension error

### ISSUE THREAD

**Issue by daalvand** [laravel/octane#523]
- Octane Version: v1.2.10
- Laravel Version: v9.13.0
- PHP Version: 8.1.5
- Server & Version: Swoole4.8.9
- Database Driver & Version:

### Description:
I wanted to run the `php artisan octane:start` command, but I got the `Swoole\Process::kill(): kill(35, 0) failed, Error: Operation not permitted[1]` error.
And I checked process 35, it's `kdevtmpfs` process.
What should I do?

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
