### ISSUE TITLE
composer require laravel/octane -> no artisan found on the root

### ISSUE THREAD

**Issue by ben74** [laravel/octane#526]
- Octane Version: 1.2.10
- Laravel Version: 9.13.0
- PHP Version: 8.1.3
- Server & Version: Swoole 
- Database Driver & Version:

### Description:
MIssing artisan in order to perform php artisan install

### Steps To Reproduce:
composer require laravel/octane

Using version ^1.2 for laravel/octane
./composer.json has been updated
Running composer update laravel/octane
Loading composer repositories with package information
Updating dependencies
Lock file operations: 60 installs, 0 updates, 0 removals
  - Locking brick/math (0.9.3)
  - Locking dflydev/dot-access-data (v3.0.1)
  - Locking doctrine/inflector (2.0.4)
  - Locking doctrine/lexer (1.2.3)
  - Locking dragonmantank/cron-expression (v3.3.1)
  - Locking egulias/email-validator (3.1.2)
  - Locking fruitcake/php-cors (v1.2.0)
  - Locking graham-campbell/result-type (v1.0.4)
  - Locking laminas/laminas-diactoros (2.11.0)
  - Locking laravel/framework (v9.13.0)
  - Locking laravel/octane (v1.2.10)
  - Locking laravel/serializable-closure (v1.2.0)
  - Locking league/commonmark (2.3.1)
  - Locking league/config (v1.1.1)
  - Locking league/flysystem (3.0.19)
  - Locking league/mime-type-detection (1.11.0)
  - Locking monolog/monolog (2.6.0)
  - Locking nesbot/carbon (2.58.0)
  - Locking nette/schema (v1.2.2)
  - Locking nette/utils (v3.2.7)
  - Locking phpoption/phpoption (1.8.1)
  - Locking psr/container (2.0.2)
  - Locking psr/event-dispatcher (1.0.0)
  - Locking psr/http-factory (1.0.1)
  - Locking psr/http-message (1.0.1)
  - Locking psr/log (3.0.0)
  - Locking psr/simple-cache (3.0.0)
  - Locking ramsey/collection (1.2.2)
  - Locking ramsey/uuid (4.3.1)
  - Locking symfony/console (v6.0.8)
  - Locking symfony/css-selector (v6.0.3)
  - Locking symfony/deprecation-contracts (v3.0.1)
  - Locking symfony/error-handler (v6.0.8)
  - Locking symfony/event-dispatcher (v6.0.3)
  - Locking symfony/event-dispatcher-contracts (v3.0.1)
  - Locking symfony/finder (v6.0.8)
  - Locking symfony/http-foundation (v6.0.8)
  - Locking symfony/http-kernel (v6.0.8)
  - Locking symfony/mailer (v6.0.8)
  - Locking symfony/mime (v6.0.8)
  - Locking symfony/polyfill-ctype (v1.25.0)
  - Locking symfony/polyfill-intl-grapheme (v1.25.0)
  - Locking symfony/polyfill-intl-idn (v1.25.0)
  - Locking symfony/polyfill-intl-normalizer (v1.25.0)
  - Locking symfony/polyfill-mbstring (v1.25.0)
  - Locking symfony/polyfill-php72 (v1.25.0)
  - Locking symfony/polyfill-php80 (v1.25.0)
  - Locking symfony/polyfill-php81 (v1.25.0)
  - Locking symfony/process (v6.0.8)
  - Locking symfony/psr-http-message-bridge (v2.1.2)
  - Locking symfony/routing (v6.0.8)
  - Locking symfony/service-contracts (v3.0.1)
  - Locking symfony/string (v6.0.8)
  - Locking symfony/translation (v6.0.8)
  - Locking symfony/translation-contracts (v3.0.1)
  - Locking symfony/var-dumper (v6.0.8)
  - Locking tijsverkoyen/css-to-inline-styles (2.2.4)
  - Locking vlucas/phpdotenv (v5.4.1)
  - Locking voku/portable-ascii (2.0.1)
  - Locking webmozart/assert (1.10.0)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 60 installs, 0 updates, 0 removals
  - Installing doctrine/inflector (2.0.4): Extracting archive
  - Installing doctrine/lexer (1.2.3): Extracting archive
  - Installing symfony/polyfill-ctype (v1.25.0): Extracting archive
  - Installing webmozart/assert (1.10.0): Extracting archive
  - Installing dragonmantank/cron-expression (v3.3.1): Extracting archive
  - Installing symfony/polyfill-mbstring (v1.25.0): Extracting archive
  - Installing symfony/deprecation-contracts (v3.0.1): Extracting archive
  - Installing symfony/http-foundation (v6.0.8): Extracting archive
  - Installing fruitcake/php-cors (v1.2.0): Extracting archive
  - Installing psr/http-message (1.0.1): Extracting archive
  - Installing symfony/psr-http-message-bridge (v2.1.2): Extracting archive
  - Installing laravel/serializable-closure (v1.2.0): Extracting archive
  - Installing voku/portable-ascii (2.0.1): Extracting archive
  - Installing symfony/polyfill-php80 (v1.25.0): Extracting archive
  - Installing phpoption/phpoption (1.8.1): Extracting archive
  - Installing graham-campbell/result-type (v1.0.4): Extracting archive
  - Installing vlucas/phpdotenv (v5.4.1): Extracting archive
  - Installing symfony/css-selector (v6.0.3): Extracting archive
  - Installing tijsverkoyen/css-to-inline-styles (2.2.4): Extracting archive
  - Installing symfony/var-dumper (v6.0.8): Extracting archive
  - Installing symfony/routing (v6.0.8): Extracting archive
  - Installing symfony/process (v6.0.8): Extracting archive
  - Installing symfony/polyfill-php72 (v1.25.0): Extracting archive
  - Installing symfony/polyfill-intl-normalizer (v1.25.0): Extracting archive
  - Installing symfony/polyfill-intl-idn (v1.25.0): Extracting archive
  - Installing symfony/mime (v6.0.8): Extracting archive
  - Installing psr/container (2.0.2): Extracting archive
  - Installing symfony/service-contracts (v3.0.1): Extracting archive
  - Installing psr/event-dispatcher (1.0.0): Extracting archive
  - Installing symfony/event-dispatcher-contracts (v3.0.1): Extracting archive
  - Installing symfony/event-dispatcher (v6.0.3): Extracting archive
  - Installing psr/log (3.0.0): Extracting archive
  - Installing egulias/email-validator (3.1.2): Extracting archive
  - Installing symfony/mailer (v6.0.8): Extracting archive
  - Installing symfony/error-handler (v6.0.8): Extracting archive
  - Installing symfony/http-kernel (v6.0.8): Extracting archive
  - Installing symfony/finder (v6.0.8): Extracting archive
  - Installing symfony/polyfill-intl-grapheme (v1.25.0): Extracting archive
  - Installing symfony/string (v6.0.8): Extracting archive
  - Installing symfony/console (v6.0.8): Extracting archive
  - Installing symfony/polyfill-php81 (v1.25.0): Extracting archive
  - Installing ramsey/collection (1.2.2): Extracting archive
  - Installing brick/math (0.9.3): Extracting archive
  - Installing ramsey/uuid (4.3.1): Extracting archive
  - Installing psr/simple-cache (3.0.0): Extracting archive
  - Installing symfony/translation-contracts (v3.0.1): Extracting archive
  - Installing symfony/translation (v6.0.8): Extracting archive
  - Installing nesbot/carbon (2.58.0): Extracting archive
  - Installing monolog/monolog (2.6.0): Extracting archive
  - Installing league/mime-type-detection (1.11.0): Extracting archive
  - Installing league/flysystem (3.0.19): Extracting archive
  - Installing nette/utils (v3.2.7): Extracting archive
  - Installing nette/schema (v1.2.2): Extracting archive
  - Installing dflydev/dot-access-data (v3.0.1): Extracting archive
  - Installing league/config (v1.1.1): Extracting archive
  - Installing league/commonmark (2.3.1): Extracting archive
  - Installing laravel/framework (v9.13.0): Extracting archive
  - Installing psr/http-factory (1.0.1): Extracting archive
  - Installing laminas/laminas-diactoros (2.11.0): Extracting archive
  - Installing laravel/octane (v1.2.10): Extracting archive

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by ben74** [comment]
for reference it's needed first to install laravel before octane in order to have artisan .. ( as it isn't specified in any manueal )

composer create-project laravel/laravel octane
cd octane && composer require laravel/octane
