### ISSUE TITLE
php entered FATAL state, too many start retries too quickly when using --watch

### ISSUE THREAD

**Issue by ariaieboy** [laravel/octane#535]
- Octane Version: 1.2.11
- Laravel Version: 9.14.1
- PHP Version: 8.1
- Server & Version: Swoole / RoadRunner swoole 4.8.5
- Database Driver & Version: -

### Description:
i am using phpstorm for development using the autosaving . when i am typing the code phpstorm autosaving the code each 1 sec and since  i use --watch it detect the change and reset the swoole to take the new code. and when the code is not complete it produce an error that is usually syntax error because the line of code is not completed yet. 
it's reload constantly for 3 time and then it return this error :

```
 INFO exited: php (exit status 1; not expected)
 INFO gave up: php entered FATAL state, too many start retries too quickly
```

the big problem is that when we try to reload the octane server it says that ` ERROR  Octane server is not running. `
and since we use laravel sail we need to kill all containers first and then up them using sail to fix the problem or just run the long command that we set in the supervisord config to start octane again in the desired port and etc that is just annoying.

### suggestions:
as a quick fix i tried to add a delay on the phpstorm autosaving but if we set a small delay it reduce the fatal errors but still its happening and if we set a big number for delay u will lose the goodness of autosaving and hot reloading the code.

i tried to increase the interval of chokedir but that didnt helped either.

i think in the development phase octane should not reload the code multiple time when it reach to an error.
the best action i think is that octane show the error and wait for next file change when its in dev enviorment

**Comment by nunomaduro** [comment]
Hi @ariaieboy, I am afraid this is a current limitation of the `--watch` function when combined with modifications of files that make it impossible booting a new server - via parse errors for example.

At this time, we don't have a clean solution for this, but of course, you are free to explore a solution, and pull request it.

**Comment by ariaieboy** [comment]
ok, I've searched about this error and it's generated from the supervisor application, not the laravel octane runtime so a quick turnaround is to set a `startretries=10000` in the supervisord.conf, supervisor default `startretries` value is 3 so after 3 attempts it will return a Fatal Error and stop trying to launch the swoole so by setting a large number it will keep restarting the swoole runtime till it starts correctly.

since it's a development environment it's not that a big problem that the supervisor keeps restarting more than 3 times.

**Comment by Carlwirkus** [comment]
@ariaieboy I'm having the same issue but when I set the `startretries=10000` it's still failing a after three attempts. Is there anything else I would need to do?

```
[supervisord]
nodaemon=true
user=root
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid

[program:php]
command=/usr/bin/php -d variables_order=EGPCS /var/www/html/artisan octane:start --watch --server=swoole --host=0.0.0.0 --port=80
user=sail
environment=LARAVEL_SAIL="1"
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
startretries=1000
```

**Comment by androidacy-user** [comment]
how did anyone get this working? it just endlessly restarts for us even though it starts successfully, supervisord says it doesn't and restarts it for no apparent reason
