### ISSUE TITLE
$_SERVER Can't get it header  and client ip

### ISSUE THREAD

**Issue by JasonSanYe** [laravel/octane#536]
- Octane Version: 1.2.12
- Laravel Version: 9.15.0
- PHP Version: 8.1.5
- Server & Version: Swoole / RoadRunner Swoole 4
- Database Driver & Version:

### Description:

$_SERVER

Why can't you get the client ip

var_dump($_SERVER)  Can't get it header

May I ask how to handle it?

**Comment by JasonSanYe** [comment]
nginx    
   
    location @octane {
        set $suffix "";

        if ($uri = /index.php) {
            set $suffix ?$query_string;
        }
        
        
        proxy_http_version 1.1;
        proxy_set_header Host $http_host;
        proxy_set_header Scheme $scheme;
        proxy_set_header SERVER_PORT $server_port;
        proxy_set_header REMOTE_ADDR $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;


        
        #以下为新增内容
        proxy_set_header X-Real-IP $remote_addr;  #获取客户端真实IP
        proxy_set_header X-Real-PORT $remote_port;
        proxy_set_header REMOTE-HOST $remote_addr;
        proxy_set_header Server-Protocol $server_protocol;
        proxy_set_header Server-Name $server_name;
        proxy_set_header Server-Addr $server_addr;
        proxy_set_header Server-Port $server_port;

        proxy_pass http://127.0.0.1:8000$suffix;
    }


I set it up like this, but it didn't work.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
