### ISSUE TITLE
Monitor / Inspect Octane route in Telescope

### ISSUE THREAD

**Issue by L3o-pold** [laravel/octane#538]
Octane route as `/octane/resolve-tasks` or `/octane/dispatch-tasks` do not appear in Telescope (Requests tab). 

It could be a nice addition for debugging or monitoring purpose to have them in the Telescope Dashboard with the `RequestWatcher`.

**Comment by driesvints** [comment]
Heya. Right now we don't have plans for this but you're always free to see if a PR would be accepted by Taylor. Thanks.
