### ISSUE TITLE
beforeResolving compatible with Octane

### ISSUE THREAD

**Issue by exodusanto** [laravel/octane#542]
- Octane Version: 1.2.12
- Laravel Version: 9.17.0
- PHP Version: 8.0.17
- Server & Version: Swoole / RoadRunner 4.8.8
- Database Driver & Version: Mysql 8.0.28

### Description:
With `lorisleiva/laravel-actions`, Actions registered in `EventServiceProvider` using [asListener](https://laravelactions.com/2.x/as-listener.html#aslistener) works on Laravel but vice versa in Octane will throws an error like this one:

> App\Actions\User\SetupCompleted::handle(): Argument #1 ($user) must be of type App\Models\User, App\Events\UserUpdated given, called in /.../vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php on line 424

This is the related to [issue](https://github.com/lorisleiva/laravel-actions/issues/136) on package github repo.

The problem seems related to `beforeResolving` method in package `ServiceProvider`

### Steps To Reproduce:
This is the [repo](https://github.com/exodusanto/laravel-actions-octane-repro).

To setup the reproduction DB
```bash
php artisan migrate:fresh
php artisan db:seed # this will create an user
```

There are two commits:
1. __Base reproduction__
2. __Octane installed__

### Base reproduction
Route `/` send an event `UserUpdated` and the listener action `UserUpdateTask` writes on logs a message.

### Octane installed
Starting the server with Octane the same flow throws the error

**Comment by nunomaduro** [comment]
You will need to clarify or solve the issue with the original authors of the package. On the Octane side, the `beforeResolving` feature, from the Laravel's service container, is working as expected:

```php
// AppServiceProvider...
$this->app->beforeResolving('foo', function () {
    dd('its working');
});

$this->app->bind('foo', 'bar');

// web.php
Route::get('/', function () {
    return resolve('foo');
});
```

When you visit `/`, you will see `'its working'` on the browser.
