### ISSUE TITLE
Log objects are prepended `INFO` by default

### ISSUE THREAD

**Issue by LauJosefsen** [laravel/octane#544]
Hi.

We are using an ELK stack to gather all our logs, and for that reason we have a custom logger that logs JSON-encoded objects.

However when switching from php-fpm to Octane, we found that all logs are prepended INFO, which makes it invalid JSON. It seems there is no way to disable this currently besides overwriting methods in the `octane:start` command. 

The problem is here: https://github.com/laravel/octane/blob/1.x/src/Commands/Concerns/InteractsWithIO.php#L231-L239
Where the default option is to log the object from a worker as INFO, if the object does not have a known type property. Ideally there would be an option to simply print the JSON_ENCODE result without any label.

I don't know what the best solution could be, but possibly a `--no-labels` option or another configuration method to disable this would be nice. If we can agree on a solution, I would be happy to make a PR with it.

**Comment by Namoshek** [comment]
This issue has been discussed before in #341 and #437. After #438 was opened as alternative to #437, someone realized logging to `stderr` (instead of `stdout`) does not prepend the RoadRunner / Swoole log level. 👍

**Comment by LauJosefsen** [comment]
Thanks for referring me to previous work. I think I must have forgotten to search for previous issues/PR.

However, this still leaves me wondering, is it acceptable that we cannot fully control the output format from a custom logger? I can of course change the logging to stderr, but it just feels like a hack to me. It would also mean that every custom logger needs to have a specific implementation to handle octane (if octane stderr else stdout)?

**Comment by driesvints** [comment]
Right now, I don't think we'll reconsider the above PR. We do, however, would appreciate a PR to the docs to document the usage of `stderr`.
