### ISSUE TITLE
Opcache is not cleared before worker (re)boot

### ISSUE THREAD

**Issue by LauJosefsen** [laravel/octane#546]
- Octane Version: v1.2.12
- Laravel Version: v9.3.1
- PHP Version: 8.1.0
- Server & Version: OpenSwoole 4.11 and also Swoole 4.8.10
- Database Driver & Version: Not relevant

### Description:
The opcache is not cleared before the worker boot, resulting in hot reload not working with all bootstrapped content using at least Swoole and OpenSwoole. (tested with both)

The solution is very simple, and is simply a re-ordering of the boot sequence of a worker, moving the [`clearOpcodeCache()`](https://github.com/laravel/octane/blob/1.x/src/Swoole/Handlers/OnWorkerStart.php#L41) method call before the [`$this->bootWorker()`](https://github.com/laravel/octane/blob/1.x/src/Swoole/Handlers/OnWorkerStart.php#L37) method call fixes the issue on my setup.

### Steps To Reproduce:

1. Enable opcache in php.ini: `opcache.enable_cli=1`
2. With the server running in --watch mode, edit any bootstrapped file, for example a routes file.
3. Observe hot reloading is not having any effect on bootstrapped files, for example that routes do not change untill server restart.

**Comment by driesvints** [comment]
Looks like you sent in a PR so let's see how that goes. Thanks

**Comment by DanjBethel** [comment]
I think this may be happening again. Can anyone else confirm ?
