### ISSUE TITLE
Octane and Swoole doesn't work with Sail

### ISSUE THREAD

**Issue by tndotdev** [laravel/octane#548]
- Octane Version: 1.2.14
- Laravel Version: 9.19.0
- PHP Version: 8.1.7
- Server & Version: Swoole 4.8.5.2
- Database Driver & Version:

### Description:

That's what I get in logs

```
2022-07-01 15:17:04,140 INFO exited: php (exit status 1; not expected)
2022-07-01 15:17:05,142 INFO spawned: 'php' with pid 42

   ErrorException 

  exec(): Unable to fork [stty 2>&1]

  at vendor/symfony/console/Terminal.php:68
     64▕         if (!\function_exists('exec')) {
     65▕             return false;
     66▕         }
     67▕ 
  ➜  68▕         exec('stty 2>&1', $output, $exitcode);
     69▕ 
     70▕         return self::$stty = 0 === $exitcode;
     71▕     }
     72▕

 +6 vendor frames 
  7   artisan:37
      Illuminate\Foundation\Console\Kernel::handle()
```

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
