### ISSUE TITLE
Octane concurrently very slow to resource model

### ISSUE THREAD

**Issue by avlima** [laravel/octane#554]
- Octane Version: 1.2
- Laravel Version: 8.4.0
- PHP Version: 8.1
- Server & Version: Swoole / RoadRunner: OpenSwoole 4.11.1
- Database Driver & Version: pgsql

### Description:

I'm trying to improve the performance of my model resources.
This is a simple test that without Octane corrotine takes 2 seconds.
I tried to divide them and play inside a coroutine but the time that used to be 2 seconds, became 24 seconds, when in fact it should decrease the time and not increase it.

### Steps To Reproduce:

This was the code I tested:

```
public function toArray($request): array
    {
        [$price_table, $products] = Octane::concurrently([
            fn() => [
                'id'                 => $this->id,
                'name'               => $this->name,
                'client_id'          => $this->client_id,
                'price_table_id'     => $this->price_table_id,
                'template'           => $this->template,
                'active_to_contract' => $this->active_to_contract,
                'active'             => $this->active,
                'created_at'         => $this->created_at,
                'updated_at'         => $this->updated_at,
            ],
            fn() => ['products' => ProductResource::collection($this->products)],
        ]);

        return [
            ...$price_table,
            ...$products,
        ];
    }
```

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!

**Comment by avlima** [comment]
Hi,
I posted my issue on these channels:

Laracasts Forums
Laravel.io Forums
StackOverflow
Discord
Larachat
IRC

But so far no one has replied, can't I get help from you guys here?

**Comment by alirzaj** [comment]
I have the same issue! could you find the root cause? or any work arounds?
