### ISSUE TITLE
Uncaught Error: Call to undefined method Swoole\Http\Server::tick

### ISSUE THREAD

**Issue by dhtmdgkr123** [laravel/octane#559]
- Octane Version: 1.2.16
- Laravel Version: 9.22.1
- PHP Version: 8.1.8
- Server & Version: Swoole 5.0.0
- Database Driver & Version:

### Description:
```bash
app-1  | Fatal error: Uncaught Error: Call to undefined method Swoole\Http\Server::tick() in /var/www/vendor/laravel/octane/src/Swoole/Handlers/OnServerStart.php:40
app-1  | Stack trace:
app-1  | #0 /var/www/vendor/laravel/octane/bin/swoole-server(57): Laravel\Octane\Swoole\Handlers\OnServerStart->__invoke(Object(Swoole\Http\Server))
app-1  | #1 [internal function]: {closure}(Object(Swoole\Http\Server))
app-1  | #2 /var/www/vendor/laravel/octane/bin/swoole-server(164): Swoole\Server->start()
app-1  | #3 {main}
app-1  |   thrown in /var/www/vendor/laravel/octane/src/Swoole/Handlers/OnServerStart.php on line 40
```
swool version 5.0.0 raise this error

![image](https://user-images.githubusercontent.com/27611405/182373153-163fd9b5-e749-4312-a0b5-e30a348f2308.png)

### Steps To Reproduce:
1. pecl install swool
2. php artisan octane:start --host=docker.host.internal --port=8000 --workers=4 --task-workers=6 --max-requests=250

**Comment by driesvints** [comment]
Not sure if we already suppport Swoole v5?

**Comment by dhtmdgkr123** [comment]
i alteady downgrade swool 5 to  4 and ot working!!

**Comment by nunomaduro** [comment]
I confirm that Octane currently does not support Swoole 5. I am currently working on getting Octane ready for it.
