### ISSUE TITLE
Changing non-standard HTTP status codes to 200 OK

### ISSUE THREAD

**Issue by saderi** [laravel/octane#562]
- Octane Version: 1.3.0
- Laravel Version: 9.19
- PHP Version: 8.1.9
- Server & Version: Swoole 4.11.1

### Description:
This is so similar to issue #291, just instead of `Illuminate\Session\TokenMismatchException` we used `Symfony\Component\HttpKernel\Exception\HttpException`

When I try to use any non-standard HTTP status codes I always get "200 OK", but in Octane logs its right status code, for example: 

```
Local: http://0.0.0.0:8801 

Press Ctrl+C to stop the server

599    GET /health/ping ................................... 28.99 mb 43.05 ms
```

### Steps To Reproduce:
1. Start the octane 
2. Call the route from Postman
3. Check that the responded status code is 200 instead of 5xx

**Comment by nunomaduro** [comment]
We understand that the status code you are proposing should be respected by Octane. Do you mind making a pull request that addresses that issue?
