### ISSUE TITLE
Installation instructions don't work as expected

### ISSUE THREAD

**Issue by christhomas** [laravel/octane#572]
I'm following the instructions here: https://laravel.com/docs/9.x/octane

I execute the following instructions in an empty folder
```
composer require laravel/octane
```

After that, I attempt to execute
```
php artisan octane:install
```

But there is no artisan command installed. So what do I do in order to install artisan?

**Comment by bumbummen99** [comment]
artisan is a file in your laravel project root folder

**Comment by christhomas** [comment]
I can answer my own question, the installation instructions are not a complete set of instructions from scratch, but first you must install a laravel application into the folder, then on top of that new laravel project, you follow the instructions for octane. It does not say this in the installation instructions, but this appears to be what they expect you to do.
