### ISSUE TITLE
How to configure swoole to output request information like nginx would

### ISSUE THREAD

**Issue by christhomas** [laravel/octane#573]
I'm curious how to configure swoole inside octane so that when a request comes in, it'll output information to the stdout/stderr so I can get some general information about requests hitting the server? The typical information I would like to see, would be something similar to what would happen in the nginx log when I request from it.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by christhomas** [comment]
I kind of solved this problem by writing two middlewares and adding them to the `config/octane.php` file

config/octane.php:
```
[
    'listeners' => [
        RequestReceived::class => [
            \App\Http\Middleware\OctaneStartRequest::class,
        ],

        RequestTerminated::class => [
            \App\Http\Middleware\OctaneStopRequest::class,
        ],
]
```

app/Http/Middleware/OctaneStartRequest.php
```
<?php declare(strict_types=1);

namespace App\Http\Middleware;

use Laravel\Octane\Events\RequestReceived;

class OctaneStartRequest
{
    /**
     * Define this constant for each request
     *
     * @param RequestReceived $event
     * @return void
     */
    public function handle(RequestReceived $event): void
    {
        $event->sandbox->make('config')->set('LARAVEL_START', microtime(true));
    }
}
```

app/Http/Middleware/OctaneFinishRequest.php
```
<?php declare(strict_types=1);

namespace App\Http\Middleware;

use Laravel\Octane\Events\RequestTerminated;

class OctaneFinishRequest
{
    /**
     * Handle Logging each request
     * 
     * @param RequestTerminated $event
     * @return void
     */
    public function handle(RequestTerminated $event): void
    {
        $start = $event->sandbox->make('config')->get('LARAVEL_START');
        $stop = microtime(true);

        \Log::info(implode(' ', [
            $event->request->method(),
            '/' . $event->request->path(),
            $event->response->status(),
            number_format($stop - $start, 4)  . "ms",
            $event->request->userAgent(),
        ]));
    }
}
```

and it outputs lines into the error log which look like this:
```
[2022-09-05 11:06:03] dev.INFO: GET /de/octane-service-template 200 0.4265ms PostmanRuntime/7.29.2
```
