### ISSUE TITLE
Unable to determine the current RoadRunner binary version

### ISSUE THREAD

**Issue by MochamadTegar** [laravel/octane#585]
I use Windows 10

![image](https://user-images.githubusercontent.com/33660856/191407024-925cb080-4af7-4054-86c0-4d78698a5f92.png)

When I use command: php artisan octane:install
![image](https://user-images.githubusercontent.com/33660856/191407263-30d7020b-405a-4784-b0aa-2aa99a707d0c.png)

References: https://developpaper.com/installing-roadrunner-in-laravel-octane/

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by matiasperrone** [comment]
I had the same issue, is not actually a error, it might be a problem with PowerShell?
