### ISSUE TITLE
PHP Swoole Fatal TypeError on octane:start on Laravel 9, PHP 8.1 app

### ISSUE THREAD

**Issue by temmyscope** [laravel/octane#586]
- Octane Version: v1.3.1
- Laravel Version: v9.31.0
- PHP Version: 8.1
- Server & Version: Swoole (or Openswoole) 4.11.1
- Database Driver & Version:

### Description:
The swoole server keeps terminating, throwing a `TypeError: Swoole\Server::__construct(): Argument #2 ($port) must be of type int, string given`.

It shows that the errror is coming from `vendor/laravel/octane/bin/createSwooleServer.php:12`.

I am running my application in a docker container, hence I can't manually edit the specific file where the issue is.

### Steps To Reproduce:
- Create a fresh Laravel project

- Install Octane and set the OCTANE_SERVER env key to "swoole".

- Install Swoole server:
      sudo pecl channel-update pecl.php.net
      sudo pecl install swoole
 
- Run php artisan octane:start from the project root folder.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
