### ISSUE TITLE
Controllers are not dropped per request

### ISSUE THREAD

**Issue by olivernybroe** [laravel/octane#587]
- Octane Version: v1.3.1
- Laravel Version: v9.31.0
- PHP Version: 8.1.10
- Server & Version: Swoole  4.8.7
- Database Driver & Version:

### Description:
A controller will have the same instance throughout the whole lifetime of the application.

This doesn't sounds like a problem when first hearing it, the problem is when you start to do dependency injections via the constructor on a controller.

So we had a controller for handling socialite called `SocialiteController`, which took `Laravel\Socialite\Contracts\Factory` in through the constructor, in our `redirect` method we called `$this->socialite->driver('someDriver')` and did the redirect. 

This would result in a `Target class [request] does not exist.` on the second request to this controller. Reason for this is that the Container instance on the SocialiteManager (the class that implements the factory) would point to the old app, and not the app for the new request, as the instance of the Manager is saved on the controller itself.

This is not a problem with many other dependencies, as they do not depend on `request`, however SocialiteManager passed an instance of Request down to each driver.

It looks like A workaround was created two years ago, in the class named `PrepareSocialiteForNextOperation`, however the following line always returns `false`, so the code for resetting the container and removing the old drivers never happens.
https://github.com/laravel/octane/blob/7ba4282697dd4f3d58704139cf02a5dfaad4e86c/src/Listeners/PrepareSocialiteForNextOperation.php#L17

This issue seems to not be limited to `SocialiteManager`, but is something we also experienced with `AuthManager`, resulting in people being logged in on others accounts.

Our solution for unblocking us was to remove all of these dependencies into each controller method instead of having them shared at the constructor. However I feel that this might make sense to change, so all controllers are not stored in the application, but a new instance of the controller is created on every single request.

**Comment by taylorotwell** [comment]
This should only be the case if your controller is registered as a singleton?

**Comment by olivernybroe** [comment]
The controller is not a singleton and I am just injecting the `Laravel\Socialite\Contracts\Factory`.


However I just tried your idea with a fresh Laravel application, with Octane installed and a simple invokable controller to return the dashboard.

I added a logging into the constructor and the invokable method and this is the result. (the number is the spl object id)
<img width="817" alt="image" src="https://user-images.githubusercontent.com/5870441/193100494-80d7ec78-f9dd-47f9-8323-126f1de5fab6.png">

Here is the example app I created for showcasing it (changed logger to stderr)
https://github.com/olivernybroe/octane-example

**Comment by olivernybroe** [comment]
To show the problem I was talking about with Socialite factory, I have created a branch for replicating that issue.
Here is a screenshot of the object id's which shows that the id of the request object does not change in the github driver.
<img width="831" alt="image" src="https://user-images.githubusercontent.com/5870441/193103934-31a5530c-281b-4b30-a26c-1a4520dc7db8.png">

https://github.com/olivernybroe/octane-example/tree/socialite

**Comment by taylorotwell** [comment]
I don't think dumping the object ID is a good way to determine the same instance is being used. For instance, this will dump the same object ID on every request even without using Octane even though it is obvious a new instance is being used every request:

<img width="654" alt="CleanShot 2022-09-29 at 14 49 41@2x" src="https://user-images.githubusercontent.com/463230/193128275-c9a032f7-7118-4711-9b8c-d2b98f1f956e.png">

**Comment by taylorotwell** [comment]
In this example, a new random string is returned on each request when using Octane + Roadrunner locally. That tells me the controller is not being reused across requests:

<img width="867" alt="CleanShot 2022-09-29 at 15 07 48@2x" src="https://user-images.githubusercontent.com/463230/193131623-99e9d114-98a0-4bd3-8fc1-2f50a9273fef.png">

**Comment by taylorotwell** [comment]
@olivernybroe we were able to recreate this locally - it seems it has always been this way.

However, I am confused about your `AuthManager` comment. How can I recreate locally being logged into other people's accounts?

AuthManager state is flushed on every request.

**Comment by olivernybroe** [comment]
@taylorotwell I see your point about object id as it can in theory get the exact same memory location, however in my examples I posted I also did a log in the constructor and that is only happening once. 

I also just tried the example you shared here and I get the same value every time.

https://user-images.githubusercontent.com/5870441/193206816-bdc9b66a-a7fe-4cd9-a565-836b6a1fd33d.mp4



I did realise one difference and that is you were using RoadRunner, I just retried with RoadRunner and that does not reproduce my issue. So it seems like this is limited to Swoole actually. I just tried upgrading to Swoole 5 also, and the issue is still there.

**Comment by driesvints** [comment]
@olivernybroe Nuno and Taylor came up with a fix already which we're probably gonna tag somewhere today:

https://github.com/laravel/octane/pull/589
https://github.com/laravel/framework/pull/44386

**Comment by olivernybroe** [comment]
@driesvints Ah cool! 

I just tried installing dev laravel and Nuno's branch with the fix for octane and it seems to solve it! 🎉 

Thanks team ❤️

**Comment by driesvints** [comment]
Fixed now, thanks!
