### ISSUE TITLE
Memory leak using Eloquent's dynamic properties with a relationship that have `using` method.

### ISSUE THREAD

**Issue by L3o-pold** [laravel/octane#591]
- Octane Version: 1.3.2
- Laravel Version: 9.32.0
- PHP Version: 8.1.11
- Server & Version: Swoole 4.8.10
- Database Driver & Version: MySQL 8.0

### Description:

https://github.com/L3o-pold/laravel-bug-report / https://github.com/L3o-pold/laravel-bug-report/commits/main

Memory leak using Eloquent's dynamic properties with a relationship that have `using` method.

```php
class User extends Authenticatable
{
    public function teams(): BelongsToMany
    {
        return $this->belongsToMany(Team::class)->using(TeamUser::class);
    }
}

Route::get('/', function () {
    $user = User::firstOrFail();

    return response()->json([
        'user'  => $user,
        'teams' => $user->teams,
    ]);
});
```

### Steps To Reproduce:

```shell
composer i
./vendor/bin/sail build --no-cache
./vendor/bin/sail up -d --remove-orphans
./vendor/bin/sail artisan migrate
./vendor/bin/sail artisan db:seed 
```

In a terminal start querying your app

```shell
while [ true ];
do
    curl http://localhost/
    echo ""
done;
```

In an other terminal check the logs of the Laravel container

```shell
docker logs -f ...

  200    GET / ............................................... 22.77 mb 4.72 ms
  200    GET / ............................................... 22.78 mb 4.28 ms
  200    GET / ............................................... 22.79 mb 4.43 ms
  200    GET / ............................................. 22.80 mb 648.16 ms
  200    GET / ............................................... 22.81 mb 4.40 ms
  200    GET / ............................................... 22.82 mb 4.73 ms
  200    GET / ............................................... 22.83 mb 4.25 ms

```

You will see that the memory is increasing. Without the `->using(TeamUser::class)` in the `User` model their is no memory leak.

**Comment by nunomaduro** [comment]
@L3o-pold Can you fire thousands of requests, to see if there is indeed a memory leak? Having the memory spiking a few megabytes is not necessary a memory leak, but a peak of PHP's memory usage that will be collected once the garbage collector gets used.

You may use the `wrk` tool for firing thousands of requests (wrk -t100 -c100 -d60 http://127.0.0.1:8000). Please re-open the issue if there is indeed a memory leak.
