### ISSUE TITLE
Serving static files with non-ASCII characters naming

### ISSUE THREAD

**Issue by smortexa** [laravel/octane#592]
- Octane Version: 1.3.1
- Laravel Version: 9.29.0
- PHP Version: 8.1.8
- Server & Version: Swoole 4.8.10
- Database Driver & Version: N/A

### Description:
The Laravel Octane Swoole HTTP server can't serve static files with non-ASCII characters naming and returns Laravel 404 page.

### Steps To Reproduce:
 
Put `تست.jpg` or `テスト.jpg` in `public` directory and hit 
`<your-local-server>/تست.jpg` or `<your-local-server>/テスト.jpg`.
You will face with Laravel 404 error page.

**Comment by NathanFreeman** [comment]
Can you please show me you the setting of `document_root` , `enable_static_handler` ?

**Comment by smortexa** [comment]
@NathanFreeman I didn't add any extra configuration to Octane's default configuration, and Octane has no specific config for `document_root` and `enable_static_handler`.

**Comment by sy-records** [comment]
This is a configuration item provided by Swoole, which you can set in `config/octane.php`

```php
    'swoole' => [
        'options' => [
            'document_root' => public_path(),
            'enable_static_handler' => true,
        ],
    ],
```

**Comment by smortexa** [comment]
@sy-records I can confirm that with this configuration the issue was resolved.

**Comment by driesvints** [comment]
Glad you found a solution. Thanks @sy-records
