### ISSUE TITLE
Octane::route not working when using route:cache

### ISSUE THREAD

**Issue by foremtehan** [laravel/octane#596]
- Octane Version: 1.3
- Laravel Version: 9.*
- PHP Version: 8.1
- Server & Version: Swoole 

### Description:
When using `php artisan route:cache` the routes which defined by `Octane::route` become unavailable and we'll get 404 not found.

### Steps To Reproduce:

with Docker:

1. create Dockerfile:
```
FROM phpswoole/swoole:php8.1-alpine

COPY --from=composer /usr/bin/composer /usr/bin/composer

WORKDIR /var/www/html

RUN composer create-project laravel/laravel . --no-dev

RUN mv ./.env.example .env

RUN php artisan key:generate

RUN composer require laravel/octane

RUN php artisan octane:install --server=swoole

RUN echo "<?php \Laravel\Octane\Facades\Octane::route('GET', '/test', fn() => new \Symfony\Component\HttpFoundation\Response('Route from Octane'));" > routes/api.php

RUN php artisan route:cache

CMD php artisan octane:start --server=swoole --host=0.0.0.0 --port=9000
```
2. `docker build -t myswoole .`
3.  `docker run -d -p 9000:9000 myswoole`

hit `http://localhost:9000/test` or `http://localhost:9000/api/test`

Both are 404 not found.

-----

Without docker:

define this route : 

```php
\Laravel\Octane\Facades\Octane::route('GET', '/test', function () {
    return new \Symfony\Component\HttpFoundation\Response('Route from Octane');
});
```
then: `php artisan route:cache`

Note: When you wouldn't use artisan command it works as expected.

**Comment by Namoshek** [comment]
You are caching the routes before you add the route in your example.

**Comment by foremtehan** [comment]
@Namoshek i fixed the order but it still not working.

**Comment by driesvints** [comment]
It's not recommended to add routes dynamically like that. Please use a routes file.

**Comment by CharlesBilbo** [comment]
this still doesnt work jut for anyone curious
