### ISSUE TITLE
Enable explicitly setting Roadrunner logging level

### ISSUE THREAD

**Issue by ejulen** [laravel/octane#597]
Hello, recently ran into a situation at work where it would've been very useful to be able to explicitly set the Roadrunner log level [without manipulating `APP_ENV`](https://github.com/laravel/octane/blob/1.x/src/Commands/StartRoadRunnerCommand.php#L90). Please correct me if there is another way of doing it - setting it in `.rr.yaml` just seems to be overridden due to the `-o` flag usage in `StartRoadRunnerCommand`.

I'd absolutely be willing to make a PR for this should you find it reasonable, with say, a new flag or something - you could still default to the current behaviour to avoid breaking backwards compatibility.

**Comment by driesvints** [comment]
Feel free to attempt a PR 👍
