### ISSUE TITLE
[Feature Request] Add commandline option defaults to the octane config file

### ISSUE THREAD

**Issue by xorinzor** [laravel/octane#608]
Building further on PR #605 and my PR #607 which have added the option to pass the `port` and `host` value via `OCTANE_PORT` and `OCTANE_HOST` environment variables:

Ideally these (and the other commandline values) should be added in the `config/octane.php` config file in a [similar fashion](https://github.com/laravel/octane/blob/1.x/config/octane.php#L39) to how the `server` default value is set too. Doing this would greatly improve usability in containerized deployments where configuration is usually done via environment variables (especially when using provisioning tools such as Terraform).

This would break backwards compatibility however, until existing deployments update their octane config file to contain these newly added properties.

Therefor I'd like to suggest this as a consideration for a possible version 2.0 (whenever this might happen in the future) to make this change and add this to the migration guide.

**Comment by nunomaduro** [comment]
Thank you for your feedback. We will consider it for future (major) versions of this package.
