### ISSUE TITLE
Allow arbitrary number of background tasks or add task limit to docs

### ISSUE THREAD

**Issue by vantezzen** [laravel/octane#609]
It looks like `Octane::concurrently()` internally uses `Swoole->taskWaitMulti` to run the tasks concurrently.

According to the [Swoole Docs](https://openswoole.com/docs/modules/swoole-server-taskWaitMulti), "[the] maximum number of concurrent tasks must not exceed 1024", otherwise an exception is thrown. This is however not documented in the [Octane Docs](https://laravel.com/docs/9.x/octane#concurrent-tasks) which caused the need for some debugging and deep-diving while implementing concurrency.

Of course, such a high task number may be unusual, but the function should still work as expected. From what I can see, improvements could be:

- Add info about the limit to the Octane docs
- Implement a loop into the `concurrently` method that slices the task array into slices of 1023 to allow an arbitrary number of tasks

**Comment by driesvints** [comment]
We'd appreciate a PR to the docs 👍

**Comment by vantezzen** [comment]
Thanks, I'll do that 👍
