### ISSUE TITLE
rr binary has wrong permissions after downloading

### ISSUE THREAD

**Issue by Dylan-Buth** [laravel/octane#610]
- Octane Version: 1.3.5
- Laravel Version: 9.37.0
- PHP Version: 8.1
- Server & Version: RoadRunner 2.11.4
- Database Driver & Version:

### Description:
Just upgraded to Laravel 9 and PHP 8.1, for Laravel 8 and PHP 8.0. We use docker for local development as well as production. When starting the php container after the upgrade it exits immediately. Output in screenshot below.

<img width="1097" alt="image" src="https://user-images.githubusercontent.com/2185074/200640091-53c6b25c-8479-4822-b084-b09562b034a0.png">

The rr binary that gets downloaded has permissions set to `--wxrw--wt`. I know the `downloadRoadRunnerBinary()` method is being ran, but it seems as if the `chmod()` step isn't running successfully. If I manually set the permissions to 755 it works just fine. 

<details>
<summary>Dockerfile for php container is below</summary>

``` 
FROM composer:2.1 as composer

FROM php:8.1-cli-alpine
COPY --from=composer /usr/bin/composer /usr/bin/composer
COPY ./deploy/php/docker-php-entrypoint /usr/local/bin/

RUN apk add --update --no-cache autoconf automake
RUN apk add --update --no-cache build-base
RUN apk add --update --no-cache mysql-client
RUN apk add --update --no-cache openssl
RUN apk add --update --no-cache gmp-dev
RUN apk add --update --no-cache zlib-dev
RUN apk add --update --no-cache libzip-dev
RUN docker-php-ext-install gmp
RUN docker-php-ext-install pdo_mysql
RUN docker-php-ext-install zip
RUN CFLAGS="$CFLAGS -D_GNU_SOURCE" docker-php-ext-install sockets
RUN docker-php-ext-install pcntl

RUN pecl install -o -f redis \
    &&  rm -rf /tmp/pear \
    &&  docker-php-ext-enable redis

WORKDIR /var/www

# OPcache defaults
ENV PHP_OPCACHE_ENABLE="1"
ENV PHP_OPCACHE_MEMORY_CONSUMPTION="128"
ENV PHP_OPCACHE_MAX_ACCELERATED_FILES="10000"
ENV PHP_OPCACHE_REVALIDATE_FREQUENCY="0"
ENV PHP_OPCACHE_VALIDATE_TIMESTAMPS="0"

RUN docker-php-ext-install opcache
COPY ./deploy/php/opcache.ini "$PHP_INI_DIR/conf.d/opcache.ini"

RUN \
	curl -L https://download.newrelic.com/php_agent/release/newrelic-php5-10.3.0.315-linux-musl.tar.gz | tar -C /tmp -zx && \
    export NR_INSTALL_USE_CP_NOT_LN=1 && \
    export NR_INSTALL_SILENT=1 && \
    /tmp/newrelic-php5-*/newrelic-install install && \
    rm -rf /tmp/newrelic-php5-* /tmp/nrinstall* && \
    sed -i \
    -e 's/"REPLACE_WITH_REAL_KEY"/"real-key"/' \
    -e 's/newrelic.appname = "PHP Application"/newrelic.appname = "app-name"/' \
    -e 's/;newrelic.daemon.app_connect_timeout =.*/newrelic.daemon.app_connect_timeout=15s/' \
    -e 's/;newrelic.daemon.start_timeout =.*/newrelic.daemon.start_timeout=5s/' \
    /usr/local/etc/php/conf.d/newrelic.ini

COPY . /var/www
RUN chown -R www-data /var/www
COPY ./deploy/php/newrelic.ini /usr/local/etc/php/conf.d/newrelic.ini
RUN composer install --no-dev -o

CMD ["php", "-d", "variables_order=EGPCS", "/var/www/artisan", "octane:start", "--server=roadrunner", "--host=0.0.0.0", "--rpc-port=6001", "--port=8000"]
```
</details>

### Steps To Reproduce:
I guess these would be the steps to reproduce it?
- Create docker container with dockerfile above
- See error when starting the container

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by Dylan-Buth** [comment]
@driesvints I can post on a support forum but it seemed like it was a bug with the library itself. Nothing on my end changed other than the version of the package and php. 

How do I know if it's a bug with the library or an issue with my container? Should I post again here if no one is able to help me on other sites?

**Comment by Dylan-Buth** [comment]
@driesvints I found the issue and have confirmed it's working locally. I have a branch with the fix but don't have permission to push.

Essentially the `755` permissions just needed a `0` prefix to specify it as an octal value, per the [chmod docs](https://www.php.net/manual/en/function.chmod.php).

When I update line 174 of `InstallsRoadRunnerDependencies.php` to the following, then delete the rr binary and restart the container, it downloads it and sets the permissions successfully. 

```
        chmod(base_path('rr'), 0755);
```

Not sure why/how this would be working for everyone else and just failing for me and my team. Maybe something in the most recent version of php made it more strict?

**Comment by Dylan-Buth** [comment]
Only thing I could find from the php changelog that references octal values. https://www.php.net/releases/8.1/en.php#explicit_octal_numeral_notation

**Comment by driesvints** [comment]
hmm that could be maybe yeah. Can you send in a PR?
