### ISSUE TITLE
memory leak on welcome page (laravel new app - swoole)

### ISSUE THREAD

**Issue by kocoten1992** [laravel/octane#620]
Hi, I've notice a wierd phenomenon about octane (swoole), it greatly reduce it performance if let run for a while.

- Octane Version: v1.3.8
- Laravel Version: v9.40.1
- PHP Version: 8.1.11
- Server & Version: Swoole / RoadRunner: swoole-4.8.10
- Database Driver & Version: not relevant

### Description:
Octane run much lower than it capacity when let it run for a while, I've a synthetically script below to demonstrate:

### Steps To Reproduce:
```
cd /tmp/
composer create-project laravel/laravel example-app
cd example-app
composer require laravel/octane
php artisan octane:install --server=swoole
php artisan octane:start --workers=4 --server=swoole --host=0.0.0.0 --max-requests=25000 -q
```

Using `ab` tool to test req/sec:
```
ab -t 5 -c 4 http://0.0.0.0:8000/
```

Keep re-running `ab -t 5 -c 4 http://0.0.0.0:8000/`, after just 5 runs, you start to see performance suffer considerably, after 10 or 15 runs, can't see advantage octane over php-fpm anymore. 

(apology in advance if this the way conducting this test is bad)

**Comment by sy-records** [comment]
Have you done any testing after removing `max-requests`?

**Comment by kocoten1992** [comment]
> Have you done any testing after removing `max-requests`?

I've not actually. In local testing it does seem stabilized, suggesting this is a memory leak scenario. Then I go ahead and remove `-q`, memory does indeed increasing.

early request:
`15.09 mb`

latter request:
`22.04 mb`

Guess it leaking somewhere in my app, and coincidentally homepage on laravel newly app also leak...

**Comment by kocoten1992** [comment]
@driesvints, you can replicate it with the following script:

```
cd /tmp/
composer create-project laravel/laravel example-app
cd example-app
composer require laravel/octane
php artisan octane:install --server=swoole
php artisan octane:start --workers=4 --server=swoole --host=0.0.0.0 --max-requests=25000
```
(Notice I remove `-q` to see memory increase)

Then keep rerun `ab`
```
ab -t 5 -c 4 http://0.0.0.0:8000/
```

On my computer, at first it take 16.32mb to finish a request:
```
200    GET / ................................................................................... 16.32 mb 2.65 ms
```

But later on it keep on increasing:

```
200    GET / ................................................................................... 21.82 mb 6.00 ms
```

That is the leak, I'm sure that a while ago it doesn't have leak (it would be a constant 16.32mb across thousand of thousand of requests). I will try find a non-leak commit this weekend.

**Comment by driesvints** [comment]
No idea about that. Would appreciate a PR that resolves this.

**Comment by kocoten1992** [comment]
Will open PR if I find time to do it.
