### ISSUE TITLE
Problem with static variables in service provider

### ISSUE THREAD

**Issue by roDRYgo0** [laravel/octane#621]
- Octane Version: 1.3
- Laravel Version: 9.19
- PHP Version: 8.1.9
- Server & Version: Swoole  4.11.1

I am currently using Laravel Nova in conjunction with Octane. Within the service provider I am declaring de nova I am declaring the following:
```php
Nova::$resourcesByModel = [
  \App\Models\Order::class => \App\Nova\Resources\Order::class,
  \App\Models\Payment::class => \App\Nova\Resources\Payment::class,
];
```

Which is used for Nova to resolve the resource with the model that I tell it.

The problem is that when I'm running Octane completely ignores it. And the static variable `$resourcesByModel` is an empty array.

The same thing also happened to me with Inertia Shared data.
```php
Inertia::share('appName', config('app.name'));
```

But I could solve that with another alternative that Inertia gives me.

**Comment by crynobone** [comment]
This is not a bug on Octane or Nova as Service Providers only loaded once. `App\Providers\NovaServiceProvider` already has `resources()` method to handle registration properly for Octane.

**Comment by roDRYgo0** [comment]
Ok I understand. So is there any way I could use this feature with octane?

**Comment by crynobone** [comment]
I already answered that.

**Comment by roDRYgo0** [comment]
I already managed to solve, thank you
