### ISSUE TITLE
reload - code not reloaded

### ISSUE THREAD

**Issue by cccdz** [laravel/octane#622]
- Octane Version: 1.3.9
- Laravel Version: 9.41.0
- PHP Version: 8.0.2
- Server & Version: Swoole / RoadRunner Swoole:any
- Database Driver & Version:

### Steps To Reproduce:

![image](https://user-images.githubusercontent.com/45749908/205290911-7ce60c0d-6317-444d-8ef6-e13788dc6c32.png)
![image](https://user-images.githubusercontent.com/45749908/205290999-a9bdd078-bdf6-4c0b-8b5e-9325d48695b9.png)
![image](https://user-images.githubusercontent.com/45749908/205291232-66b53162-81a8-498d-bc23-aa3701dd122b.png)
![image](https://user-images.githubusercontent.com/45749908/205291044-aa58ad4e-7f53-406e-bf1f-e6bb30400828.png)

### The following modifications are required for reload to be effective：

<img width="1063" alt="image" src="https://user-images.githubusercontent.com/45749908/205291677-70f7adb1-4209-40c8-a260-ff0f7555926d.png">

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
