### ISSUE TITLE
reload - code not reloaded

### ISSUE THREAD

**Issue by cccdz** [laravel/octane#623]
I'm sure this is a problem
https://github.com/laravel/octane/issues/622

**Comment by driesvints** [comment]
Please try some support channels first like I asked.

**Comment by cccdz** [comment]
> 
I can't find a solution through those channels
I have tested this problem many times
Could you test it according to my screenshot

**Comment by cccdz** [comment]
> Please try some support channels first like I asked.

I can't find a solution through those channels
I have tested this problem many times
Could you test it according to my screenshot
Thank you very much

**Comment by cccdz** [comment]
> > Please try some support channels first like I asked.

@driesvints

**Comment by cccdz** [comment]
> Please try some support channels first like I asked.

@driesvints 
I can't find a solution through those channels
I have tested this problem many times
Could you test it according to my screenshot
Thank you very much

**Comment by driesvints** [comment]
Please share links to the channels where you've tried asking for help.

**Comment by cccdz** [comment]
@driesvints 
I also raised the issue of the `aftercommit` last time, but I will not raise the issue. You closed my issue, and someone raised the issue later, It is a bug. so I hope you can test my issue

**Comment by driesvints** [comment]
These aren't the support channels I linked to. Please try the support channels which I pointed to.
