### ISSUE TITLE
mpdf library output result strange characters

### ISSUE THREAD

**Issue by adeiming** [laravel/octane#627]
- Octane Version: 1.3.9
- Laravel Version: 9.43.0
- PHP Version: 8.1
- Server & Version: Swoole
- Database Driver & Version: MySql 8

### Description:
I am trying to create a pdf document with mpdf, but when using octane it becomes strange characters.

### Steps To Reproduce:
1. composer require carlos-meneses/laravel-mpdf
2. in controller:

$pdf = PDF::loadView('pdf.document'); // document content with free characters
return $pdf->stream('document.pdf')

3. the result is
<img width="958" alt="image" src="https://user-images.githubusercontent.com/13284072/209747768-55236efc-c635-4d38-b4e0-d646465364fd.png">

**Comment by driesvints** [comment]
I'm sorry but we don't maintain this library. Please try a support channel:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)
