### ISSUE TITLE
Is octane:reload will loading new installed package?

### ISSUE THREAD

**Issue by joe820912boy** [laravel/octane#632]
- Laravel Version: 8
- PHP Version: 8.1.5
- Server & Version: Swoole 
- Database Driver & Version: Mysql

### Description:
Is octane:reload will loading new installed package?

### Steps To Reproduce:
Today I face some problem, that in octane active circumstances, if we add some new package to laravel, 
and reload the octane server, the new package seems not be installed to octane server.

My solution is stop and start the octane, and the package will be loaded, 
otherwise it will occur that class not found error.

So this in my opinion that today we install the package and we need restart the server, is right?

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by indigoram89** [comment]
@joe820912boy how did you solve this problem?

**Comment by cccdz** [comment]
@driesvints @indigoram89 @joe820912boy 
https://github.com/laravel/octane/issues/622

**Comment by indigoram89** [comment]
@driesvints why you don't look at this problem? After install any package via composer and run octane:reload then Octane crashes.

**Comment by driesvints** [comment]
We currently have no knowledge of a widespread issue when installing new package on Octane enabled Laravel apps. If that was the case we'd probably get a large influx of new issues which isn't the case.

In general I believe it's the correct wtg to stop and restart Octane when installing new packages.

**Comment by indigoram89** [comment]
@driesvints maybe you need to say about it in documentation? Because it is a bad surprise that after install a new package we get an error, Octane stops and we need to start it again. And I don't understand how to do a deploy of my application? We discussed it in Laravel Discord Channel and not to find a solution.

**Comment by driesvints** [comment]
But are you installing new packages using `composer update` on the server? You'd only run `composer install` on the server to install the new packages right?

**Comment by indigoram89** [comment]
Sure, here is an example deploy script in forge

git pull ...
composer install ...
artisan octane:reload

After octane:reload you will have class not found error and octane will stop (it is downtime).

<img width="605" alt="Screenshot 2023-01-30 at 12 59 40" src="https://user-images.githubusercontent.com/85135210/215446431-8c2dd486-72b4-4bd1-ad86-a1bc934bdb06.png">

**Comment by driesvints** [comment]
What package are you trying to update?

**Comment by indigoram89** [comment]
@driesvints not update but install a new package.

Package [spatie/laravel-data](https://github.com/spatie/laravel-data) for example.

**Comment by joe820912boy** [comment]
@indigoram89 I restart the octane and the problem could be solved, 

but it will trigger another problem that the nginx server will not receive any request when the octane is stopped

**Comment by indigoram89** [comment]
@joe820912boy  I think we have several problems here.

- Octane crashes with error and stops after we install a new package and run octane:reload after it.
- In some cases of it I could not restart octane because like "Address in use 127.0.0.1:8000" error (I will need to kill processes manually).
- If we need to stop and start Octane again, so we have downtime and our users get server errors.
- And how can automate my deployments? Because now I need to stop and run Octane only when I have a new package installed in the deployment. Otherwise it enough to run octane:reload to fresh my code (without a new package installed).

Sorry for my english guys. I record videos about Laravel and Octane and I sad about this problem of installation a packages.

**Comment by joe820912boy** [comment]
@indigoram89 Yes, maybe another solution is when in developed period, we need avoid to use the octane, 

after installing needed packages and start the octane, because octane reload will not reload the package installed

**Comment by driesvints** [comment]
Re-opening this for @nunomaduro to review.

**Comment by indigoram89** [comment]
@nunomaduro How to reproduce the error:
1. Create a new application (curl "https://laravel.build/octane" | bash)
2. Install octane package (sail composer install laravel/octane)
3. Choose swoole server (sail artisan octane:install + swoole)
4. Start octane to handle requests (sail artisan octane:start --host 0.0.0.0)
5. Install any package (sail composer require spatie/laravel-data)
6. Try to reload octane workers (sail artisan octane:reload)

You will see an error like "class not found" and octane stopped.

**Comment by taylorotwell** [comment]
Hi @indigoram89 - can you contribute a fix via PR? Thanks!

**Comment by cccdz** [comment]
![image](https://user-images.githubusercontent.com/45749908/215505146-da4850dc-e09e-4cda-a660-5a55490c51b3.png)
@taylorotwell Is this OK？

**Comment by indigoram89** [comment]
> Hi @indigoram89 - can you contribute a fix via PR? Thanks!

I don't know how does Octane work under hood and why it doesn't see a new package installed.

**Comment by sy-records** [comment]
Hi, there.
The Reload operation can only reload PHP files that were loaded after the Worker process was started. Use the `get_included_files` function to list which PHP files were loaded before WorkerStart, and PHP files in this list cannot be reloaded even after the reload operation. You have to shut down and restart the server for this to take effect.

```
$serv->on('WorkerStart', function(Swoole\Server $server, int $workerId) {
    var_dump(get_included_files());
});
```

**Comment by joe820912boy** [comment]
@sy-records 
One more thing I wanna confirm the autoload_static.php file I could see the new installed package path was added in it,

so the reload will not reload the file with it, or it will not reload the vendor directory?

**Comment by taylorotwell** [comment]
So - @sy-records or anyone else, is there really specific action we can take on the Octane side to help with this?

**Comment by sy-records** [comment]
Smooth restarts are only available for PHP files that are `included/required` in the worker process such as onWorkerStart or onReceive.
PHP files that were `included/required` before the Server was started cannot be reloaded by a smooth restart.

**Comment by joe820912boy** [comment]
@sy-records 

OK, I got it, thanks!

**Comment by indigoram89** [comment]
@sy-records so we can't work without full restart octane server?

**Comment by sy-records** [comment]
yeah, should use stop, start.

**Comment by cccdz** [comment]
@sy-records Is this OK？
![image](https://user-images.githubusercontent.com/45749908/216265505-b4c57aea-7605-4fa5-8b67-5d2fd8d40b48.png)

**Comment by sy-records** [comment]
I'm not sure, you can run a test.

**Comment by taylorotwell** [comment]
Fix: https://github.com/laravel/octane/pull/644

**Comment by indigoram89** [comment]
@taylorotwell thank you so much!

**Comment by joe820912boy** [comment]
Does it fix error by updating laravel/octane?

Or just add the fixed code to file and re-autoload.

**Comment by driesvints** [comment]
I've just done a new patch release for this. Thanks everyone.

**Comment by joe820912boy** [comment]
OK, it is updated
