### ISSUE TITLE
Continuation HTTP client wrapper for Laravel Http?

### ISSUE THREAD

**Issue by i386** [laravel/octane#634]
Would there be any appetite to make the Laravel Http client back onto the Swoole continuation http client if that is available? 

Would prevent developer experience fails like https://github.com/laravel/serializable-closure/issues/26

**Comment by taylorotwell** [comment]
I don't really want to tie the Laravel Http client to Swoole at this time I don't think.

**Comment by taylorotwell** [comment]
Of course, everything depends on the complexity of the code in the PR. 😅
