### ISSUE TITLE
Undefined function tick()

### ISSUE THREAD

**Issue by douglashb** [laravel/octane#635]
- Octane Version: 1.2.12
- Laravel Version: 9.17.0
- PHP Version: 8.0.27
- Server & Version: Swoole 5.0.1
- Database Driver & Version: MariaDB 10.8.6

### Description:
Undefined function tick()
vendor/laravel/octane/src/Swoole/Handlers/OnServerStart.php - line 40, 44

**File OnServerStart.php**

if ($this->shouldTick) { 
    $server->tick(1000, function () use ($server) {       --> Line 40
        $server->task('octane-tick');
    });
}

$server->tick(1000, function () use ($server) {       --> Line 44
    (new EnsureRequestsDontExceedMaxExecutionTime(
        $this->extension, $this->timerTable, $this->maxExecutionTime, $server
    ))();
});

### Steps To Reproduce:

Install the latest version of swoole or install swoole 5.0.0 because that version remove that function from package
https://pecl.php.net/package-changelog.php?package=swoole

### Temporal Solve(Wait official fix):

Only the lines where the tick() function is used should be commented out.

**Comment by sy-records** [comment]
Fixed via #560, please upgrade laravel/octane.

**Comment by driesvints** [comment]
Thanks @sy-records

**Comment by douglashb** [comment]
Thank you @sy-records
