### ISSUE TITLE
Undefined array key "line" error

### ISSUE THREAD

**Issue by alecpl** [laravel/octane#637]
- Laravel Version: 9.47
- Octane Version: 1.4.0
- PHP 8.1

Undefined array key "line" {"exception":"[object] (ErrorException(code: 0): Undefined array key \"line\" at /.../vendor/laravel/octane/src/Commands/Concerns/InteractsWithIO.php:186)

I got it when OpenSwoole\Http\Response throws an exception (for a reason related to my faulty code). So, sounds like the line is not always specified.

**Comment by nunomaduro** [comment]
It will be fixed next week, on the next release of Octane.
