### ISSUE TITLE
Larvel Octane failed to create a session identifier based on Swoole startup. Session Cookie Name?

### ISSUE THREAD

**Issue by pro911** [laravel/octane#638]
- Octane Version: 1.3.10
- Laravel Version: 8.83.27
- PHP Version: 8.1.14
- Server & Version: Swoole 5.0.1
- Database Driver & Version:

### Description:
After the traditional mode is started, there will be a cookie generated based on Session Cookie Name after opening the view page. However, Octane based on Swoole has no information about this session after it is started. The project used to rely on this as a simple password, but now it wants to use acceleration, but it is found that the basis of this session cannot be obtained.

### Steps To Reproduce:
config/session.php 
` 'cookie' => env(
        'SESSION_COOKIE',
        Str::slug(env('APP_NAME', 'laravel'), '_').'_session'
    ),`

routes/web.php

* octane start:
 ```php
Route::get('/api/online', function (\Illuminate\Http\Request $request){
    $cookieKey = Str::slug(env('APP_NAME', 'laravel'), '_') . '_session';//laravel_session
    $sessionId = $request->cookie($cookieKey);
    dd($sessionId); //null
});
```
* no octane start:
```php
Route::get('/api/online', function (\Illuminate\Http\Request $request){
    $cookieKey = Str::slug(env('APP_NAME', 'laravel'), '_') . '_session';//laravel_session
    $sessionId = $request->cookie($cookieKey);
    dd($sessionId);  //JDDl56X9X7xfXPpMMOLZOIxqfUAtgr1IrCh5QXNZ
});
```

**Comment by nunomaduro** [comment]
Octane (with Swoole) is able to capture the cookies from a request. So, this must be an issue in your application. Please try to get help from the community:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)
