### ISSUE TITLE
Ocatne doesn't compatible for the newly released version 5.0

### ISSUE THREAD

**Issue by linsining-1** [laravel/octane#645]
Ocatne doesn't compatible for the newly released version 5.0

**Comment by nunomaduro** [comment]
What Laravel and Octane version are you using? What "released version 5.0" are you talking about exactly?

**Comment by linsining-1** [comment]
swoole 5

**Comment by alecpl** [comment]
It works for me with Swoole 5.0.1. So, we'll need more details.

**Comment by driesvints** [comment]
I also remember this issue being posted in the past with people responding that it worked for them. If you're experiencing issues please open a much more detailed issue, thanks.
