### ISSUE TITLE
Using Octane::concurrently in artisan commands?

### ISSUE THREAD

**Issue by i386** [laravel/octane#647]
Hi there,

Curious if there is any way to use ``Octane::concurrently`` in artisan commands. I think without a Octane server running, the `concurrently` just executes in serial. My workload involves a bit of number crunching and then yielding back the result from the `concurrently` call. 

Any advice here?

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
