### ISSUE TITLE
Terminated process/502 on syscall timeouts

### ISSUE THREAD

**Issue by oprypkhantc** [laravel/octane#651]
- Octane Version: 1.4.2
- Laravel Version: 9.52.4
- PHP Version: 8.1.9
- Server & Version: Swoole 5.0.1

### Description:
When a request is timed out due to a syscall (`curl`, for example), response is not returned, causing a 502. Worst of all, master process gets restarted for whatever reason, causing a downtime before Octane restarts.

The exit code is 139 (segfault), meaning it is a bug in Swoole allowing Octane to do something wrong. Yet, it's very likely Octane is doing something wrong here, given it's relation to `max_execution_time`.

### Steps To Reproduce:

Set `max_execution_time` in `config/octane.php` to `5`; add this route:
```php
Route::get('test', function () {
	Http::timeout(40)->connectTimeout(40)->get('https://hub.dummyapis.com/delay?seconds=10');
});
```
start Octane and navigate to `your_domain/test`. You will get a 502 if you're using a reverse proxy, or just a cut-off response if you're hitting Octane directly. You'll also see that the Octane process has terminated with an exit code of 139.

**Comment by oprypkhantc** [comment]
It's possible to debug this down to C++ Swoole code; the segfault is happening somewhere in [there](https://github.com/swoole/swoole-src/blob/master/ext-src/swoole_http_server.cc#L355) based on the coredump I got from production. I don't know the specific line number, only the function.

I can try debugging it more to get a line number if that's needed, but I'm not very familiar with neither C++ nor debugging it :)

**Comment by smortexa** [comment]
@sy-records #510 doesn't work anymore.

**Comment by sy-records** [comment]
I will test it, I also found before that it causes the main process to exit, probably because of the Swoole5 modification.

**Comment by sy-records** [comment]
@oprypkhantc You are right, a coredump has occurred and I will give feedback to Swoole Team.
![image](https://user-images.githubusercontent.com/33931153/222958139-53394974-b584-4564-b84a-0a95a1754593.png)

**Comment by sy-records** [comment]
Swoole is fixed, please test it with master branch. @oprypkhantc

**Comment by driesvints** [comment]
Thanks @sy-records

**Comment by joe820912boy** [comment]
I got the timeout error in the following

"2023/04/08 03:12:14 [error] 801885#801885: *46084951 upstream timed out (110: Connection timed out) while reading response header from upstream, client: x.x.x.x, server: server_nam, request: "POST /path/to/url", upstream: "http://127.0.0.1:8000/path/to/url", host: "host.name""

Have someone that faced this before? 

I search that it seems occurs between proxy and server. 

Is it solvable that we extend "proxy_read_timeout"?

Or there are any solutions?

**Comment by kolaente** [comment]
I'm still hitting this with swoole 5.0.3 and octane 2.0.0.

**Comment by NathanFreeman** [comment]
@NargesHajiani Hi.
I can not reproduce it.
Please show me your swoole version `php --ri swoole` and error information.

**Comment by NargesHajiani** [comment]
@NathanFreeman 
```
swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 5.0.3
Built => Jun 11 2023 11:06:37
coroutine => enabled with boost asm context
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
http2 => enabled
json => enabled
zlib => 1.2.11
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 8388608 => 8388608
```
Octane command log error after finishing `max_execution_time`:
```
2023-06-11 10:55:58,653 INFO exited: php (exit status 139; not expected)
2023-06-11 10:55:58,654 INFO reaped unknown pid 1552 (terminated by SIGKILL)
2023-06-11 10:55:58,654 INFO reaped unknown pid 1565 (terminated by SIGKILL)
2023-06-11 10:55:58,654 INFO reaped unknown pid 1566 (terminated by SIGKILL)
2023-06-11 10:55:58,654 INFO reaped unknown pid 1567 (terminated by SIGKILL)
2023-06-11 10:55:58,654 INFO reaped unknown pid 1568 (terminated by SIGKILL)
2023-06-11 10:55:58,654 INFO reaped unknown pid 1569 (terminated by SIGKILL)
2023-06-11 10:55:58,654 INFO reaped unknown pid 1570 (terminated by SIGKILL)
2023-06-11 10:55:58,654 INFO reaped unknown pid 1571 (terminated by SIGKILL)
2023-06-11 10:55:58,654 INFO reaped unknown pid 1572 (terminated by SIGKILL)
2023-06-11 10:55:58,654 INFO reaped unknown pid 1573 (terminated by SIGKILL)
2023-06-11 10:55:58,654 INFO reaped unknown pid 1574 (terminated by SIGKILL)
2023-06-11 10:55:58,654 INFO reaped unknown pid 1575 (terminated by SIGKILL)
2023-06-11 10:55:58,654 INFO reaped unknown pid 1576 (terminated by SIGKILL)
2023-06-11 10:55:58,654 INFO reaped unknown pid 1578 (exit status 0)
2023-06-11 10:55:58,654 INFO reaped unknown pid 1579 (exit status 0)
2023-06-11 10:55:58,654 INFO reaped unknown pid 1580 (exit status 0)
2023-06-11 10:55:58,655 INFO reaped unknown pid 1581 (exit status 0)
2023-06-11 10:55:58,655 INFO reaped unknown pid 1582 (exit status 0)
2023-06-11 10:55:58,655 INFO reaped unknown pid 1583 (exit status 0)
2023-06-11 10:55:58,655 INFO reaped unknown pid 1584 (exit status 0)
2023-06-11 10:55:58,655 INFO reaped unknown pid 1585 (exit status 0)
2023-06-11 10:55:58,655 INFO reaped unknown pid 1586 (exit status 0)
2023-06-11 10:55:58,655 INFO reaped unknown pid 1587 (exit status 0)
2023-06-11 10:55:58,655 INFO reaped unknown pid 1588 (exit status 0)
2023-06-11 10:55:58,655 INFO reaped unknown pid 1589 (terminated by SIGKILL)
```

**Comment by NargesHajiani** [comment]
It's maybe related to the following warning printed by PHP: 
```
Warning: Swoole\Http\Response::create(): parameter $2 must be valid connection session id in /var/www/html/vendor/laravel/octane/src/Swoole/Actions/EnsureRequestsDontExceedMaxExecutionTime.php on line 33
```

**Comment by NathanFreeman** [comment]
@NargesHajiani Hi.
What is your swoole mode? `SWOOLE_BASE` or `SWOOLE_PROCESS`?
If it's `SWOOLE_BASE`, you can try changing it to `SWOOLE_ PROCESS`. 

```shell
Warning: Swoole\Http\Response::create(): parameter $2 must be valid connection session id in /var/www/html/vendor/laravel/octane/src/Swoole/Actions/EnsureRequestsDontExceedMaxExecutionTime.php on line 33
```

Laravel octane will delete `fd` from the `swoole table` after the function is executed,  and it will throw this warning if the timer starts before this step.

It seems like we need to make some code adjustments 
```php
public function __invoke()
    {
        foreach ($this->timerTable as $workerId => $row) {
            if ((time() - $row['time']) > $this->maxExecutionTime) {
                if (!$server->exists($row['fd'])) {
                    $this->timerTable->del($workerId);
                    continue;
                }
                
                $this->timerTable->del($workerId);

                $this->extension->dispatchProcessSignal($row['worker_pid'], SIGKILL);

                if ($this->server instanceof Server) {
                    $response = Response::create($this->server, $row['fd']);

                    if ($response) {
                        $response->status(408);
                        $response->end();
                    }
                }
            }
        }
    }
```

**Comment by yusifk88** [comment]
adding this to the octane config file fixed it for me 
'swoole' => [
    'options' => [
        'log_file' => storage_path('logs/swoole_http.log'),
        'package_max_length' => 10 * 1024 * 1024,
    ],
],
as per the [laravel](https://laravel.com/docs/10.x/octane) documentation.
to test after this make a route with a lengthy sleep function and make a request to see if it will kill swoole
