### ISSUE TITLE
Call to undefined method Swoole\Http\Server::tick()

### ISSUE THREAD

**Issue by huangjinbing** [laravel/octane#656]
- Octane Version: 1.2
- Laravel Version: 9.19
- PHP Version: v8.0.21
- Server & Version: Swoole 5.0.2
- Database Driver & Version:  mysql5.8

### Description:
![image](https://user-images.githubusercontent.com/13633806/223083796-3c1b6054-8106-415d-9442-5f81e52f7d17.png)

PHP Fatal error:  Uncaught Error: Call to undefined method Swoole\Http\Server::tick() in /data/web/aibaowei/ttq-simulation/vendor/laravel/octane/src/Swoole/Handlers/OnServerStart.php:40

**Comment by sy-records** [comment]
Fixed via https://github.com/laravel/octane/pull/560, please upgrade laravel/octane.

**Comment by driesvints** [comment]
Thanks @sy-records

**Comment by huangjinbing** [comment]
Thanks @sy-records
