### ISSUE TITLE
Emergency Logger Issue in Laravel using Octane

### ISSUE THREAD

**Issue by erfanmola** [laravel/octane#657]
- Octane Version: 1.4.3
- Laravel Version: 9.52.4
- PHP Version: 8.2.3
- Server & Version: OpenSwoole 22.0.0

I keep getting this error being logged in my laravel.log file lately, it's a bug introduced in latest versions :

```
[2023-03-07 01:33:03] laravel.EMERGENCY: Unable to create configured logger. Using emergency logger. {"exception":"[object] (InvalidArgumentException(code: 0): Log [none] is not defined. at /PATH/vendor/laravel/framework/src/Illuminate/Log/LogManager.php:210)
[stacktrace]
#0 /PATH/vendor/laravel/framework/src/Illuminate/Log/LogManager.php(135): Illuminate\\Log\\LogManager->resolve()
#1 /PATH/vendor/laravel/framework/src/Illuminate/Log/LogManager.php(122): Illuminate\\Log\\LogManager->get()
#2 /PATH/vendor/laravel/octane/src/Listeners/FlushLogContext.php(23): Illuminate\\Log\\LogManager->driver()
#3 /PATH/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(441): Laravel\\Octane\\Listeners\\FlushLogContext->handle()
#4 /PATH/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(249): Illuminate\\Events\\Dispatcher->Illuminate\\Events\\{closure}()
#5 /PATH/vendor/laravel/octane/src/DispatchesEvents.php(20): Illuminate\\Events\\Dispatcher->dispatch()
#6 /PATH/vendor/laravel/octane/src/Worker.php(177): Laravel\\Octane\\Worker->dispatchEvent()
#7 /PATH/vendor/laravel/octane/bin/swoole-server(145): Laravel\\Octane\\Worker->handleTick()
#8 [internal function]: {closure}()
#9 /PATH/vendor/laravel/octane/bin/swoole-server(170): OpenSwoole\\Server->start()
#10 {main}
"} 
```

It is urgent, fix it please, it generates 5GB log each day!

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!

**Comment by erfanmola** [comment]
I tried all the methods, got no answers, I had no issues until I ran composer update, and octane got updated last week
