### ISSUE TITLE
Route cache command causes octane routes to 404

### ISSUE THREAD

**Issue by CharlesBilbo** [laravel/octane#658]
- Octane Version: 1.3.1
- Laravel Version: 9.31.0
- PHP Version: 8.1.15
- Server & Version: Swoole / RoadRunne (swoole: 5.0.2)

I know this was already asked before but it was never answered. 

If you run the `php artisan route:cache` then octane routes will 404 while the non octane routes still work. 

```
<?php
use Illuminate\Support\Facades\Route;
use Laravel\Octane\Facades\Octane;
use Symfony\Component\HttpFoundation\Response;

Route::get('/', fn() => response('root'));

\Laravel\Octane\Facades\Octane::route('POST', '/example', function($request) {
    return new Response(content: 'example', status: 200);
});
```

is this the desired behavior or should I open a pr for a bug ?

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!

**Comment by michael-rubel** [comment]
@CharlesBilbo I managed to workaround this by clearing the route cache. But the question lasts for non-Octane routes: shouldn't it be cached if we use Octane routes in our projects?

**Comment by CharlesBilbo** [comment]
@michael-rubel I found the issue its because the routes are being excluded from the cache file but in my own personal finding caching the routes rendered a negative memory performance since it seems the cache file takes up more memory than it resolving the routes from the file.

here is the PR if you want to take a look.

https://github.com/laravel/framework/pull/46448/files
