### ISSUE TITLE
RoadRunner: execute php artisan octane:stop then throw exception

### ISSUE THREAD

**Issue by ahkui** [laravel/octane#664]
- Octane Version: 1.4.2
- Laravel Version: 9.51.0
- PHP Version: 8.1.4
- Server & Version: Swoole / RoadRunner 2.12.2
- Database Driver & Version:

### Description:

```
>> Exception Message:
Uncaught Error: Call to undefined method Illuminate\Support\Facades\Config::get() in /var/www/current/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:1261
```
```
>> Exception Message:
Unable to read frame header: Incorrect header size


Symfony\Component\ErrorHandler\Error\FatalError -> 10
```
```
>> Exception Message:
Uncaught Error: Call to undefined method Illuminate\Support\Facades\Config::get() in /var/www/current/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:1261

```

![image](https://user-images.githubusercontent.com/14049597/226797871-60feee51-2e1a-48bd-a6ba-ef595d363cee.png)

### Steps To Reproduce:
1. Start server with roadrunner
2. make some request
3. run php artisan octane:stop when processing request (sometime throw exception)

**Comment by ahkui** [comment]
maybe issue with `Laravel\Octane\Listeners\FlushLocaleState`

**Comment by nunomaduro** [comment]
Unfortunately, I am unable to reproduce the issue you reported locally. Could you kindly re-open this pull request and provide me with precise instructions on how to reproduce the issue locally? If possible, creating a demo repository on GitHub would also be helpful. Thank you.

**Comment by ahkui** [comment]
1. composer create-project --prefer-dist laravel/laravel laravel-octane-test
2. composer require laravel/octane
3. php artisan octane:start
4. use wrk simulate workload `wrk -t4 -c8 -d30m http://127.0.0.1:8000/api/test`
5. php artisan octane:stop
6. some exception is throw
```json
{
  "exception": {
    "class": "Spiral\\Goridge\\Exception\\HeaderException",
    "code": 0,
    "file": "/var/www/service/vendor/spiral/goridge/src/StreamRelay.php:78",
    "trace": [
      "/var/www/service/vendor/spiral/roadrunner-worker/src/Worker.php:83",
      "/var/www/service/vendor/spiral/roadrunner-http/src/HttpWorker.php:69",
      "/var/www/service/vendor/spiral/roadrunner-http/src/PSR7Worker.php:102",
      "/var/www/service/vendor/laravel/octane/bin/roadrunner-worker:39",
      "/var/www/service/vendor/bin/roadrunner-worker:120"
    ],
    "message": "Unable to read frame header: Incorrect header size"
  }
}
```

**Comment by ahkui** [comment]
@nunomaduro do you have make some workload and stop octane?

**Comment by michael-rubel** [comment]
@nunomaduro I face the same issue in my application.
