### ISSUE TITLE
Add Max-Age Argument in the Set-Cookie Header with Swoole

### ISSUE THREAD

**Issue by nifi7801** [laravel/octane#680]
When a cookie is set, only an absolute expire date is sent to the client. 
It should also send a Max-Age argument with relative timestamp as implemented in Symfony and Laravel.

Tested with OpenSwoole

I know that Swoole is not supporting Max-Age with the cookie and rawCookie function, but it is possible to send the Cookies via the header function.

**Comment by driesvints** [comment]
Heya, can you send in a PR for us to look at? Thanks
