### ISSUE TITLE
Version conflict

### ISSUE THREAD

**Issue by x12311231** [laravel/octane#683]
### Octane Version

1.x-dev

### Laravel Version

Laravel Framework 10.6.2

### PHP Version

8.2.0

### What server type are you using?

Swoole

### Server Version

ubuntu desktop22.04

### Description

composer require laravel/octane:1.x-dev                                                                                   2 ↵  1008  23:23:02
./composer.json has been updated
Running composer update laravel/octane
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires laravel/octane 1.x-dev -> satisfiable by laravel/octane[1.x-dev].
    - laravel/octane 1.x-dev requires laravel/framework ^8.83.26|^9.38.0|^10.0 -> found laravel/framework[v8.83.26, v8.83.27, 8.x-dev, v9.38.0, ..., 9.x-dev, v10.0.0, ..., 10.x-dev] but it conflicts with your root composer.json require (^11.0).
`
`

### Steps To Reproduce

`
composer require laravel/octane:1.x-dev
`
It's require laravel/framework ^8.83.26|^9.38.0|^10.0 but latest version of laravel/framework is ^11.0 now

**Comment by driesvints** [comment]
Laravel v11 isn't released yet.
