### ISSUE TITLE
Uncaught ReflectionException: Class "config" does not exist

### ISSUE THREAD

**Issue by dhtmdgkr123** [laravel/octane#684]
### Octane Version

1.5.3

### Laravel Version

10.8.0

### PHP Version

8.2.5

### What server type are you using?

Open Swoole

### Server Version

22.0.0

### Database Driver & Version

AWS-RDS MySQL 5.7.12-log

### Description

try many time (maybe 3 or over thane) to request it and throw error

Test.php
```php
<?php

declare(strict_types=1);

namespace App\SomeNamespace;

class Test
{
    public function debug(array $chunk, SomeVo $validateData)
    {
        $rlt = $validateData->user->shops()
                                 ->createMany(
                                    collect($chunk)->map(fn (string $data): array => (
                                        [
                                            'test' => $data,
                                            'test2' => 'ok'
                                        ]
                                    ))
                                );

        return $rlt;
    }
}
```

and call it like this

```php
<?php

declare(strict_types=1);

namespace App\AnotherNamespace;

use App\SomeNamespace\Test;
use Laravel\Octane\Facades\Octane;

class AnotherTest
{
    public function debug(SupportCollection $chunk, SomeVo $validateData)
    {
        $sendBuffers = collect(
            Octane::concurrently(
                $datas->map(function ($item) use ($instance) {
                    return fn() => $instance->debug($item[0], $item[1]);
                })->toArray()
            )
        )
        ->flatten();
    }
}
```

ang i got error

PHP Fatal error:  Uncaught ReflectionException: Class "config" does not exist in /code/vendor/laravel/framework/src/Illuminate/Container/Container.php:914
Stack trace:
#0 /code/vendor/laravel/framework/src/Illuminate/Container/Container.php(914): ReflectionClass->__construct('config')
#1 /code/vendor/laravel/framework/src/Illuminate/Container/Container.php(795): Illuminate\Container\Container->build('config')
#2 /code/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(933): Illuminate\Container\Container->resolve('config', Array, true)
#3 /code/vendor/laravel/framework/src/Illuminate/Container/Container.php(731): Illuminate\Foundation\Application->resolve('config', Array)
#4 /code/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(918): Illuminate\Container\Container->make('config', Array)
#5 /code/vendor/laravel/framework/src/Illuminate/Container/Container.php(1456): Illuminate\Foundation\Application->make('config')
#6 /code/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php(170): Illuminate\Container\Container->offsetGet('config')
#7 /code/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php(136): Illuminate\Database\DatabaseManager->configuration('travel')
#8 /code/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php(101): Illuminate\Database\DatabaseManager->makeConnection('travel')
#9 /code/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1820): Illuminate\Database\DatabaseManager->connection('travel')
#10 /code/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1786): Illuminate\Database\Eloquent\Model::resolveConnection('travel')
#11 /code/vendor/lunasoft/leo/src/Leo/Models/Travel/HasOwnerUser.php(13): Illuminate\Database\Eloquent\Model->getConnection()
#12 /code/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(324): Lunasoft\Leo\Models\Travel\Alimtalk\Shop\Shop->initializeHasOwnerUser()
#13 /code/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(2399): Illuminate\Database\Eloquent\Model->initializeTraits()
#14 [internal function]: Illuminate\Database\Eloquent\Model->__wakeup()
#15 /code/vendor/laravel/serializable-closure/src/Serializers/Signed.php(87): unserialize('O:46:"Laravel\\S...')
#16 [internal function]: Laravel\SerializableClosure\Serializers\Signed->__unserialize(Array)
#17 /code/vendor/laravel/octane/bin/swoole-server(170): OpenSwoole\Server->start()
#18 {main}

Next Illuminate\Contracts\Container\BindingResolutionException: Target class [config] does not exist. in /code/vendor/laravel/framework/src/Illuminate/Container/Container.php:916
#0 /code/vendor/laravel/framework/src/Illuminate/Container/Container.php(795): Illuminate\Container\Container->build('config')
#1 /code/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(933): Illuminate\Container\Container->resolve('config', Array, true)
#2 /code/vendor/laravel/framework/src/Illuminate/Container/Container.php(731): Illuminate\Foundation\Application->resolve('config', Array)
#3 /code/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(918): Illuminate\Container\Container->make('config', Array)
#4 /code/vendor/laravel/framework/src/Illuminate/Container/Container.php(1456): Illuminate\Foundation\Application->make('config')
#5 /code/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php(170): Illuminate\Container\Container->offsetGet('config')
#6 /code/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php(136): Illuminate\Database\DatabaseManager->configuration('travel')
#7 /code/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php(101): Illuminate\Database\DatabaseManager->makeConnection('travel')
#8 /code/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1820): Illuminate\Database\DatabaseManager->connection('travel')
#9 /code/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1786): Illuminate\Database\Eloquent\Model::resolveConnection('travel')
#10 /code/vendor/lunasoft/leo/src/Leo/Models/Travel/HasOwnerUser.php(13): Illuminate\Database\Eloquent\Model->getConnection()
#11 /code/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(324): Lunasoft\Leo\Models\Travel\Alimtalk\Shop\Shop->initializeHasOwnerUser()
#12 /code/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(2399): Illuminate\Database\Eloquent\Model->initializeTraits()
#13 [internal function]: Illuminate\Database\Eloquent\Model->__wakeup()
#14 /code/vendor/laravel/serializable-closure/src/Serializers/Signed.php(87): unserialize('O:46:"Laravel\\S...')
#15 [internal function]: Laravel\SerializableClosure\Serializers\Signed->__unserialize(Array)
#16 /code/vendor/laravel/octane/bin/swoole-server(170): OpenSwoole\Server->start()
#17 {main}
  thrown in /code/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 916

### Steps To Reproduce

```bash
php artisan octane:start --port=9874
```

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
