### ISSUE TITLE
Octane fails to detect Roadrunner or start properly

### ISSUE THREAD

**Issue by alexc-hollywood** [laravel/octane#687]
### Octane Version

1.5.4

### Laravel Version

9.52.3

### PHP Version

8.1.12

### What server type are you using?

Roadrunner

### Server Version

2.12.3

### Description

When attempting to use Octane in a simple PHP docker container, starting the server produces the following error:

```
ERROR  RoadRunner not installed. Please execute the `octane:install` Artisan command.
```

composer.json

```json
    "require": {
        "php": "^8.1.2",
        "guzzlehttp/guzzle": "^7.2",
        "hedii/laravel-gelf-logger": "^7.1",
        "laravel/framework": "^v9.52.3",
        "laravel/octane": "^1.5",
        "laravel/sanctum": "^3.0",
        "laravel/tinker": "^2.7",
        "opekunov/laravel-centrifugo-broadcaster": "^2.0",
        "spatie/fractalistic": "^2.9",
        "spiral/roadrunner": "^2.8"
    },
```

Dockerfile: using a parallel folder named "laravel-src" with a pre-existing application with fresh install and little/no modification (no changes to default config file):

```Dockerfile
FROM php:8.1.12-cli-alpine3.16

    # this is mounted as a volume from the laravel-src folder within docker-compose.yml
    WORKDIR /srv/laravel 

    COPY --from=composer:latest /usr/bin/composer /usr/bin/composer
    COPY --from=spiralscout/roadrunner:2.12.3 /usr/bin/rr /usr/bin/rr

    ENV ROADRUNNER_MAX_REQUESTS "500"
    ENV ROADRUNNER_WATCH $false
    ENV ROADRUNNER_WORKERS "auto"

    # Copy the Laravel project into the container. This is relative to the build context (the local host dir) set in docker-compose.yml
    COPY ./laravel-src ./

    RUN apk add libzip-dev zip unzip wget curl && \
        docker-php-ext-install bcmath ctype pcntl sockets zip

    RUN apk add nodejs npm && \
        mkdir "/home/www-data/.npm-global/" && \
        npm config set prefix "/home/www-data/.npm-global/" && \
        npm install -g chokidar      # Used for file-watching

    # Do Laravel setup here
    RUN chmod -R 777 bootstrap/cache && chmod -R 777 storage/logs
    RUN composer install --ignore-platform-reqs && composer update --ignore-platform-reqs
    RUN touch .rr.yaml && chmod 777 .rr.yaml
    RUN yes | php artisan octane:install --server="roadrunner"

    # Expose the ports that Octane is using.
    EXPOSE 8000

    # Run RoadRunner
    CMD if [[ -z $ROADRUNNER_WATCH ]] ; then \
        php ./artisan octane:start --server="roadrunner" --host="0.0.0.0" --workers=${ROADRUNNER_WORKERS} --max-requests=${ROADRUNNER_MAX_REQUESTS} ; \
    else \
        php ./artisan octane:start --server="roadrunner" --host="0.0.0.0" --workers=${ROADRUNNER_WORKERS} --max-requests=${ROADRUNNER_MAX_REQUESTS} --watch ; \
    fi

    # Check the health status using the Octane status command.
    HEALTHCHECK CMD php ./artisan octane:status --server="roadrunner"
```

Configuration of Docker service named "laravel":

```yml
  laravel:
    build:
      context: .
      dockerfile: ./docker/laravel.Dockerfile
    restart: unless-stopped
    ports:
      - '127.0.0.1:8000:8000' # run on port 8000 localhost only, port 8000 on the container
    environment:
      ROADRUNNER_MAX_REQUESTS: 250
      ROADRUNNER_WATCH: "yes"
      ROADRUNNER_WORKERS: 6
    volumes:
      - ./laravel-src:/srv/laravel
 ```

Output of docker-compose up ---build laravel

```
Step 15/18 : RUN yes | php artisan octane:install --server="roadrunner"
 ---> Running in b20b0d3544fe

   INFO  Octane installed successfully.
Removing intermediate container b20b0d3544fe
 ---> 45d9069952bc
Step 16/18 : EXPOSE 8000
 ---> Running in de843aa9caa8
Removing intermediate container de843aa9caa8
 ---> b7fbc30d3c9b
Step 17/18 : CMD if [[ -z $ROADRUNNER_WATCH ]] ; then         php ./artisan octane:start --server="roadrunner" --host="0.0.0.0" --workers=${ROADRUNNER_WORKERS} --max-requests=${ROADRUNNER_MAX_REQUESTS} ;     else         php ./artisan octane:start --server="roadrunner" --host="0.0.0.0" --workers=${ROADRUNNER_WORKERS} --max-requests=${ROADRUNNER_MAX_REQUESTS} --watch ;     fi
 ---> Running in d01cf424e661
Removing intermediate container d01cf424e661
 ---> dd49cd81b98e
Step 18/18 : HEALTHCHECK CMD php ./artisan octane:status --server="roadrunner"
 ---> Running in 66bcde3850be
Removing intermediate container 66bcde3850be
 ---> 4983aa7ffe4c
Successfully built 4983aa7ffe4c
Successfully tagged atmo_laravel:latest
Recreating laravel_1 ... done
Attaching to laravel_1
laravel_1           | 
laravel_1           |    ERROR  RoadRunner not installed. Please execute the `octane:install` Artisan command.

```

### Steps To Reproduce

Current version of Roadrunner is **2023.1.1**, which is effective v3. 

1. Create new folder;
2. Create fresh install of Laravel in laravel-src/ subfolder and compose.json deps;
3. Use code above to create Dockerfile in docker/laravel.Dockerfile;
4. Use code above to create  docker-compose.yml;
5. Run docker-compose up --build laravel, watch output.

Alternatively:

1. Use any PHP docker image and attempt to run Octane from it.

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!

**Comment by alexc-hollywood** [comment]
@driesvints Respectfully, this angers me about the official Laravel ecosystem support, as i've seen it as a repetitive complaint. No, i don't want to post it on forums, Discord, or IRC. The package claims it's installed, but then claims it's not (it's looking for the presence of a PS7 class). It's not a configuration issue where i need a tutorial; i'm using it as intended with a simple setup.

How do we class that, exactly? A feature?

**Comment by driesvints** [comment]
> No, i don't want to post it on forums, Discord, or IRC.

This isn't free support, this is open source. Right now, this is the only report we've gotten about this so we have nothing to assume there's a widespread issue. That's why I want you to try a support channel first to see if there's someone who can help you. If you can confirm the bug that way it'll help us figure it out.

**Comment by Namoshek** [comment]
You might be successful by copying or symlinking the `rr` binary in the project root:
https://github.com/laravel/octane/blob/f3ae57e230eef23df39d4d307ec9097482e9dd9e/src/RoadRunner/Concerns/FindsRoadRunnerBinary.php#L15-L28
