### ISSUE TITLE
Installation conflict with laminas/laminas-diactoros

### ISSUE THREAD

**Issue by anonym-uz** [laravel/octane#689]
### Octane Version

1.5.4

### Laravel Version

10.9.0

### PHP Version

php 8.1.4

### What server type are you using?

Roadrunner

### Server Version

-

### Database Driver & Version

MySQL 8

### Description

> composer require laravel/octane

./composer.json has been updated
Running composer update laravel/octane
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - laravel/octane[v1.4.0, ..., v1.5.4] require laminas/laminas-diactoros ^2.5 -> satisfiable by laminas/laminas-diactoros[2.5.0, ..., 2.25.2].
    - laravel/octane[v0.1.0, ..., v0.1.1] require laravel/framework ^8.35 -> found laravel/framework[v8.35.0, ..., v8.83.27] but it conflicts with your root composer.json require (^10.8).
    - laravel/octane[v0.2.0, ..., v0.5.0, v1.0.0, ..., v1.0.12] require laravel/framework ^8.37 -> found laravel/framework[v8.37.0, ..., v8.83.27] but it conflicts with your root composer.json require (^10.8).
    - laravel/octane[v1.0.13, ..., v1.0.17] require laravel/framework ^8.62 -> found laravel/framework[v8.62.0, ..., v8.83.27] but it conflicts with your root composer.json require (^10.8).
    - laravel/octane[v1.0.18, ..., v1.1.3] require laravel/framework ^8.70 -> found laravel/framework[v8.70.0, ..., v8.83.27] but it conflicts with your root composer.json require (^10.8).
    - laravel/octane v1.2.0 requires laravel/framework ^8.77|^9.0 -> found laravel/framework[v8.77.0, ..., v8.83.27, v9.0.0, ..., v9.52.7] but it conflicts with your root composer.json require (^10.8).
    - laravel/octane[v1.2.1, ..., v1.3.1] require laravel/framework ^8.81|^9.0 -> found laravel/framework[v8.81.0, ..., v8.83.27, v9.0.0, ..., v9.52.7] but it conflicts with your root composer.json require (^10.8).
    - laravel/octane[v1.3.2, ..., v1.3.5] require laravel/framework ^8.83.25|^9.33 -> found laravel/framework[v8.83.25, v8.83.26, v8.83.27, v9.33.0, ..., v9.52.7] but it conflicts with your root composer.json require (^10.8).
    - laravel/octane[v1.3.6, ..., v1.3.10] require laravel/framework ^8.83.26|^9.38.0 -> found laravel/framework[v8.83.26, v8.83.27, v9.38.0, ..., v9.52.7] but it conflicts with your root composer.json require (^10.8).
    - laminas/laminas-diactoros[2.5.0, ..., 2.6.0] require php ^7.3 || ~8.0.0 -> your php version (8.1.14) does not satisfy that requirement.
    - laminas/laminas-diactoros[2.7.0, ..., 2.24.2] require psr/http-message ^1.0 -> found psr/http-message[1.0, 1.0.1, 1.1] but the package is fixed to 2.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - laminas/laminas-diactoros[2.25.0, ..., 2.25.2] require psr/http-message ^1.1 -> found psr/http-message[1.1] but the package is fixed to 2.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - Root composer.json requires laravel/octane * -> satisfiable by laravel/octane[v0.1.0, ..., v0.5.0, v1.0.0, ..., v1.5.4].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
You can also try re-running composer require with an explicit version constraint, e.g. "composer require laravel/octane:*" to figure out if any version is installable, or "composer require laravel/octane:^2.1" if you know which you need.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

### Steps To Reproduce
>composer create-project --prefer-dist laravel/laravel octane-project
>composer require laravel/octane

**Comment by godruoyi** [comment]
when we install Laravel, we will get `psr/http-message: ^2.0` as the default version, but `laminas/laminas-diactoros` only include `^1.0`, you can see [here](https://github.com/laminas/laminas-diactoros/blob/2.26.x/composer.json#L39), may we should post a PR in laminas/laminas-diactoros to resolve this problem first.

**Comment by godruoyi** [comment]
https://github.com/laminas/laminas-diactoros/pull/144
https://github.com/laminas/laminas-diactoros/pull/145

**Comment by driesvints** [comment]
We'll have to wait to see how https://github.com/laminas/laminas-diactoros/pull/136 goes. Thanks
