### ISSUE TITLE
Unable to run Octane in development mode with --watch after adding 'type: module' to Laravel boilerplate

### ISSUE THREAD

**Issue by faytekin** [laravel/octane#695]
### Octane Version

1.5.5

### Laravel Version

10.10.1

### PHP Version

8.1.18

### What server type are you using?

Swoole

### Server Version

5.0.0

### Database Driver & Version

PostgreSQL 14.7 ARM64 homebrew

### Description

Hello, we are having an issue running Octane in development mode with `--watch` after adding `"type": "module"` to the Laravel boilerplate (https://github.com/laravel/laravel/commit/d3b2eada8618f8608c755137acc1741ec74771dc). It's throwing the following error.

```
Watcher process has terminated. Please ensure Node and chokidar are installed.
file:///Users/.../vendor/laravel/octane/bin/file-watcher.js:1
const chokidar = require('chokidar');
                 ^

ReferenceError: require is not defined in ES module scope, you can use import instead
This file is being treated as an ES module because it has a '.js' file extension and '/Users/.../package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.
    at file:///Users/.../vendor/laravel/octane/bin/file-watcher.js:1:18
    at ModuleJob.run (node:internal/modules/esm/module_job:192:25)
```

### Steps To Reproduce

`php artisan octane:start --watch`

**Comment by mmarkalas** [comment]
I'm getting the same error on fresh Laravel installation with Octane. Just to add, I'm not using Sail for this and in my composer.json, the type is set to "project".

PHP: v8.2.6
Laravel: v10.10.1
Octane: v1.5.5

**Comment by timacdonald** [comment]
We've just put up a PR to fix this one. Thanks for reporting it.
