### ISSUE TITLE
Disable swoole header name formatting

### ISSUE THREAD

**Issue by NiroDeveloper** [laravel/octane#697]
### Octane Version

1.5.6

### Laravel Version

10.9.0

### PHP Version

8.1.18

### What server type are you using?

Swoole

### Server Version

5.0.3

### Description

Swoole and Open Swoole are formatting headers by default, but it can be disabled.
https://openswoole.com/docs/modules/swoole-http-response-header

In the SwooleClient class, the header will be read with the original formatting.
$headers = $response->headers->allPreserveCase();

But if you give these headers to 
$swooleResponse->header($name, $value);
Swoole will format the header because the third parameter $format is not set.

The swoole formatting should be disabled or adjustable by config.
(I know I should use rfc compliant headers, but i can not update old weird clients)

### Steps To Reproduce

1. Create new route
2. Respond with a not RFC conform header name (like "myHeader")
3. Check response header name: "Myheader"

**Comment by nunomaduro** [comment]
Thank you for proposing that feature request. Would be willing to write a pull request, with tests, so we can analyse the amount of code involved? Thank you!
