### ISSUE TITLE
[Swoole] Header names are broken

### ISSUE THREAD

**Issue by NiroDeveloper** [laravel/octane#709]
### Octane Version

2.0.1

### Laravel Version

10.9.0

### PHP Version

8.1.18

### What server type are you using?

Swoole

### Server Version

5.0.3

### Description

Unfortunately i already created a pull request 3 weeks ago, but all further pings were ignored.
https://github.com/laravel/octane/pull/702

Swoole and Open Swoole are formatting headers by default.
https://openswoole.com/docs/modules/swoole-http-response-header

It seems odd that you specifically called ResponseHeaderBag's allPreserveCase presumably to preserve the casing.
https://github.com/laravel/octane/blob/d962806a79c5ac97ddd1e371bd232d00c855c0d9/src/Swoole/SwooleClient.php#L156

... but are suggesting it's fine for Swoole to override the casing few lines later? 
https://github.com/laravel/octane/blob/d962806a79c5ac97ddd1e371bd232d00c855c0d9/src/Swoole/SwooleClient.php#L164

### Steps To Reproduce

1. Create new route
2. Respond with a not RFC conform header name (like "myHeader")
3. Check response header name: "Myheader"

**Comment by driesvints** [comment]
Thanks @NiroDeveloper. @sy-records do you know if it might be useful in this case to set `$format` to `false` by default for the `->header(` call?

**Comment by sy-records** [comment]
Normally, we should do the formatting. But we should provide options and let the user make choices.
For compatibility, the default should still be `true`
