### ISSUE TITLE
Support KV from RR

### ISSUE THREAD

**Issue by farti22** [laravel/octane#711]
Hi.

In Octane there is support for swoole tables. But what to do with RR. Is there any way to support the ability to connect KV from RR via Octane?
Or maybe I'm misunderstanding, and the performance of the connection from PHP will not be very different from the connection from the RR server.

**Comment by asanikovich** [comment]
Hello. You can try the package https://github.com/asanikovich/laravel-roadrunner-cache

**Comment by asanikovich** [comment]
@farti22 
Hello. You can try the package https://github.com/asanikovich/laravel-roadrunner-cache

**Comment by asanikovich** [comment]
Please note, that swoole in-memory or table cache works only inside HTTP workers.

If you want a cache that works from all parts of PHP (HTTP or CLI) - our [package](https://github.com/asanikovich/laravel-roadrunner-cache) and RoadRunner KV will help you.

**Comment by driesvints** [comment]
Thank you. Right now we don't have plans to work on this ourselves. If someone could attempt a PR we could look at the code that's required for this. Thanks
