### ISSUE TITLE
Incompatibility Issue with Firestore Leading to Mutex Error and Invalid Connection Session ID

### ISSUE THREAD

**Issue by Jakoffe** [laravel/octane#712]
### Octane Version

2.0.1

### Laravel Version

10.14.0

### PHP Version

8.2.4

### What server type are you using?

Swoole

### Server Version

5.0.3

### Database Driver & Version

MySQL 8.0.31 on both amd64 and arm64

### Description

Hello Maintainers and Contributors,

First, I would like to extend my gratitude for all the effort put into Laravel Octane. I have encountered an issue while using Laravel Octane with Swoole and Google's Firestore package for in-app messaging. I would like to know if anyone can provide insights or solutions to this problem. The problem occurs in our development, staging, and production environments.

**We use the following Firestore related packages:**
- "google/cloud-firestore": "1.35.0"
- "grpc/grpc": "1.52.0"
- "kreait/laravel-firebase": "5.2.0"

**Issue**
When attempting to utilize the chat functionality in our applications (flutter app and admin-panel), which are built using Firestore, we receive the following error message in the logs:

`[mutex.cc : 2417] RAW: Check w->waitp->cond == nullptr failed: Mutex::Fer while waiting on Condition`

This error seems to originate from a low-level C++ library, possibly the underlying gRPC library used by Firestore. Shortly after this error, we also receive the following warning message:

`Warning: Swoole\Http\Response::create(): parameter $2 must be valid connection session id in /var/www/vendor/laravel/octane/src/Swoole/Actions/EnsureRequestsDontExceedMaxExecutionTime.php on line 33`

This error appears to be a side effect of the first error, indicating that the connection might have gotten into a bad state due to the underlying library issue.

Every other aspect of our backend works great with Octane (Swoole).

**What was tried:**
- I have tried updating all dependencies to the latest versions.
- I have checked the configuration of both Firestore and Laravel Octane.
- I have attempted to isolate the issue by using Firestore without Octane/Swoole and vice versa (Before moving to Octane we have been running the backend using php-fpm for 12+ months without any issues).

### Steps To Reproduce

```php
namespace App\Models\Firestore;

use App\Models\Staff;
use App\Models\User;
use Exception;
use Google\Cloud\Core\Timestamp;
use Google\Cloud\Firestore\CollectionReference;
use Google\Cloud\Firestore\DocumentReference;
use Google\Cloud\Firestore\FieldValue;
use Google\Cloud\Firestore\FieldValue\ArrayUnionValue;
use Illuminate\Support\Facades\Log;
use Kreait\Laravel\Firebase\Facades\Firebase;

class Channel extends FirestoreModel
{
    private static CollectionReference $collection;
    private CollectionReference $messageCollection;

    private function __construct(DocumentReference $document)
    {
        parent::__construct($document);
        $this->messageCollection = $document->collection('messages');
    }

    public static function getByID(string $id): self
    {
        return new self(self::collection()->document($id));
    }
    
    .
    .
    .
}
```

```php
namespace App\Models\Firestore;

use Google\Cloud\Firestore\DocumentReference;

class FirestoreModel
{
    protected DocumentReference $document;
    protected array $data;

    public function __construct(DocumentReference $document)
    {
        $this->document = $document;
    }

    public function load(): FirestoreModel
    {
        $snapshot = $this->document->snapshot();
        $data = $snapshot->data();
        if (isset($data)) {
            $this->data = $data;
        } else {
            $this->data = [];
        }
        return $this;
    }

    public function __get($name): DocumentReference|null|array|string
    {
        if ($name == 'data') {
            return $this->getData();
        }
        if ($name == 'document') {
            return $this->document;
        }
        if ($name == 'id') {
            return $this->id();
        }
        return null;
    }

    public function getData(): array
    {
        if (!isset($this->data)) {
            $this->load();
        }
        return $this->data;
    }

    protected function fieldUpdate(string $name, mixed $value): array
    {
        return ['path' => $name, 'value' => $value];
    }

    public function document(): DocumentReference
    {
        return $this->document;
    }

    public function id(): string
    {
        return $this->document->id();
    }
}
```

With the above code one can run the following function and get the errors:
```php
Channel::getByID('anyFirestoreChannelID')->getData();
```

**Comment by NathanFreeman** [comment]
I will test it later.

**Comment by driesvints** [comment]
Thank you for this issue. However, we don't use firestore ourselves so unfortunately we cannot be of help here. You can maybe get help from one of these support channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

**Comment by jihadismail8** [comment]
I think the issue is integration of Grpc , try to use roadrunner instead of swoole . It might work

**Comment by BSN4** [comment]
For anyone hitting this with Firestore + Swoole — [grpc-php-rs](https://github.com/BSN4/grpc-php-rs) is a drop-in replacement for ext-grpc with a different connection management design that doesn't have the mutex/stale session issues in long-lived worker processes.

```
pie install bsn4/grpc
```

Same `Grpc\` namespace API, no code changes needed. Pre-built binaries for PHP 8.2–8.5.
