### ISSUE TITLE
gRPC support 

### ISSUE THREAD

**Issue by dominikhalvonik** [laravel/octane#714]
Hi guys, first of all I would like to say that I really love Octane. I am a hardcore Lumen user so Octane is the only reason why I was able to migrate from Lumen(best framework ever!!! 😋) to regular Laravel. And now the feature request. It is possible to add gRPC server support? All platforms: RoadRunner, Swoole, OpenSwoole supports this feature(example https://openswoole.com/docs/modules/grpc-server). It is really important when you want to use Laravel for microservice architecture project. Today we are hacking it by using Nest.js, but I would love to stick only to Laravel ecosystem. Thank you for considering this feature.

**Comment by dominikhalvonik** [comment]
@michael-rubel no, we are using OpenSwoole.

**Comment by driesvints** [comment]
I *think* we could provide support for this but it would depend on the code complexity. If you could send in a PR for us to look at that'd be great. Please make sure all three drivers work.
