### ISSUE TITLE
[Swoole] Non blocking task support

### ISSUE THREAD

**Issue by atymic** [laravel/octane#716]
Would you accept a PR for non blocking task support? Ie, instead of using `concurrently` to wait for all tasks to complete you would call a method like`background`, which would return immediately. Can optionally pass a callback to be executed once the task completes.

**Comment by driesvints** [comment]
Everything depends on the complexity of the PR. If you could send in the PR we can have a look. thanks

**Comment by borys-p** [comment]
@atymic there already is `SwooleTaskDispatcher::dispatch()` that does exactly this. Not sure why it isn't exposed in the `Octane` facade, though. Maybe because it can't be easily replaced with something like `SequentialTaskDispatcher`?
