### ISSUE TITLE
Looking forward to supporting coroutines

### ISSUE THREAD

**Issue by cccdz** [laravel/octane#720]
Looking forward to supporting coroutines

**Comment by leonvd6** [comment]
@driesvints Any update on supporting coroutines? 

At the moment If I understand it correctly: If I have 4 Swoole workers and I `sleep(1000)` on them the 5 request will hang. So to solve this problem I need to increase the amount of workers.

E.g If all my requests take exactly 1 second, and I want guaranteed 40 requests per second I'll need a mininum of 40 Swoole workers.
