### ISSUE TITLE
SSL can't be enabled on OpenSwoole

### ISSUE THREAD

**Issue by borys-p** [laravel/octane#721]
### Octane Version

2.0.1

### Laravel Version

10.14.1

### PHP Version

8.2.7

### What server type are you using?

Open Swoole

### Server Version

22.0.0

### Description

I'm trying to enable HTTP/2 on OpenSwoole and it seems that it requires SSL/TLS to function. However, Octane implements that in the following way in `createSwooleServer.php`:

```
    $server = new Swoole\Http\Server(
        $serverState['host'] ?? '127.0.0.1',
        $serverState['port'] ?? 8080,
        $serverState['mode'] ?? SWOOLE_PROCESS,
        ($config['swoole']['ssl'] ?? false)
            ? SWOOLE_SOCK_TCP | SWOOLE_SSL
            : SWOOLE_SOCK_TCP,
    );
```
Note that this requires having `ssl` defined in Swoole-specific configuration and that's not a valid configuration option, as:
```
	'swoole' => [
		'options' => [
			'ssl' => true,
		],
	],
```
ends up with:
```
Fatal error: OpenSwoole\Server\Port::set(): Invalid server option: ssl in /application/vendor/laravel/octane/bin/createSwooleServer.php on line 20
```

Note that I don't want to terminate SSL on nginx, just use Swoole directly.

### Steps To Reproduce

As above, just putting that configuration option there results in a fatal error.

**Comment by sy-records** [comment]
```php
    'swoole' => [
        'ssl' => true,
        'options' => []
    ],
```

**Comment by borys-p** [comment]
Ha, you're right! Thanks!
