### ISSUE TITLE
Specifying a specific .env file path for the Octane server

### ISSUE THREAD

**Issue by negartarh** [laravel/octane#727]
Hi Laravel Octane Team,

I am writing to request an option to be added to the Command Line Interface (CLI) that allows users to specify a specific .env file path for the Octane server.

Currently, there is no way to use a specific .env file for the Octane server. this can be problematic, especially if you want to use multiple environments.

For example, you may want to use a development environment to develop your application and a production environment to run your application. Currently, there is no way to make changes in same time. This can be problematic and increase the likelihood of error.

I suggest adding an option to the CLI that allows users to specify a specific .env file path for the Octane server. This would allow users to use multiple environments without having to copy the .env file or make changes to the .env file.

This would also make it possible to consider different settings for the Octane server that are widely used.

In addition, this option makes the octane package more compatible with packages such as [gecche/laravel-multidomain](https://github.com/gecche/laravel-multidomain) that supports multiple .env files.

I believe that this feature would be useful and I hope you will consider it for the upcoming version of Laravel Octane.

Thank you for your time and attention.

Sincerely,
Negar Tarh Giti (PJSC)

**Comment by crynobone** [comment]
Laravel already supports https://laravel.com/docs/10.x/configuration#additional-environment-files for using `.env` on multiple environments which made auto-deployment a breeze. No plan for this at the moment.
