### ISSUE TITLE
Why not implement a WebSocket Server?

### ISSUE THREAD

**Issue by twomiao** [laravel/octane#732]
Why not implement a WebSocket Server so that PHP can also enable long-connection application development? Such as instant messaging applications, online customer service systems, etc.

**OpenSwoole**:
   WebSocket Server Library: **https://openswoole.com/docs/modules/swoole-websocket-server**

**Comment by twomiao** [comment]
The laravel framework can develop message push, IM online chat software.****

**Comment by driesvints** [comment]
I'm not sure tbh, sorry. If you're willing to work on a PR you could send one in for us to look at. Depending on how complicated the PR is we could consider merging it in.

**Comment by twomiao** [comment]
> I'm not sure tbh, sorry. If you're willing to work on a PR you could send one in for us to look at. Depending on how complicated the PR is we could consider merging it in.

It has already been implemented, and I hope that the official will also support it: https://github.com/swooletw/laravel-swoole

**Comment by killjin** [comment]
https://github.com/laravel/framework/discussions/43468
