### ISSUE TITLE
Why  workerId  is same  in request callback , Should be random, isn't it?  

### ISSUE THREAD

**Issue by marol1210** [laravel/octane#744]
### Octane Version

1.5.6

### Laravel Version

8.83.27

### PHP Version

8.1.18

### What server type are you using?

Swoole

### Server Version

5.0.3

### Description

swoole starts  dozen of  request workers .   when user's request coming in where the workerId is same in request callback.

It feels like the same worker process is processing, but if it can't handle it, restart another worker process to handle it.

i add echo for debug;

```
$server->on('request', function ($request, $response) use ($server, $workerState, $serverState) {
    $workerState->lastRequestTime = microtime(true);

    echo $workerState->workerId;  // whether id is random.

    if ($workerState->timerTable) {
        $workerState->timerTable->set($workerState->workerId, [
            'worker_pid' => $workerState->workerPid,
            'time' => time(),
            'fd' => $request->fd,
        ]);
    }

    $workerState->worker->handle(...$workerState->client->marshalRequest(new RequestContext([
        'swooleRequest' => $request,
        'swooleResponse' => $response,
        'publicPath' => $serverState['publicPath'],
        'octaneConfig' => $serverState['octaneConfig'],
    ])));

    if ($workerState->timerTable) {
        $workerState->timerTable->del($workerState->workerId);
    }
});
```

### Steps To Reproduce

1.  just add echo  for print.  in request callback  and the result of print  always  same . (show in snapshot) 
2.  use Apache ab for concurrent .  

![image](https://github.com/laravel/octane/assets/7519301/d1ffc174-5ea1-4bff-b0cb-2b3ddeeec376)

**Comment by sy-records** [comment]
The URL you visit should be the same, and you can increase the random number test.

You can also try the configuration item of swoole: dispatch_mode. Fixed mode is used by default.

**Comment by marol1210** [comment]
i see.   big thks for you

> The URL you visit should be the same, and you can increase the random number test.
> 
> You can also try the configuration item of swoole: dispatch_mode. Fixed mode is used by default.
