### ISSUE TITLE
When and How ,  the value of variable $workerState which in request callback is set ?

### ISSUE THREAD

**Issue by marol1210** [laravel/octane#745]
### Octane Version

1.5.6

### Laravel Version

8.83.27

### PHP Version

8.1.18

### What server type are you using?

Swoole

### Server Version

5.0.3

### Description

When and How the value of variable $workerState which in request callback is set ?

### Steps To Reproduce

swoole create a number of worker processes.  

questions are:

1. Did the request callback  execute  when those events `start`、 `workerstart` 、`managerstart` had finished?  or  Request callback always execute after those workers started?
```

$server->on('start', fn (Server $server, $workerId) =>  something...)
$server->on('workerstart', fn (Server $server, $workerId) =>  something...)
$server->on('managerstart', fn (Server $server, $workerId) =>  something...)

$server->on('request', something...)

```

2.  When and How ,  the value of variable $workerState which in request callback to set ?

    It's the most incomprehensible part of me.  The $workerState is global , but , in callback context , what value is it ?

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so, please open up a new issue and we'll help you out.

Thanks!
