### ISSUE TITLE
Error occurs with Octane::concurrently when referencing serialized models

### ISSUE THREAD

**Issue by pslxx** [laravel/octane#746]
### Octane Version

2.0.5

### Laravel Version

10

### PHP Version

8.1

### What server type are you using?

Swoole

### Server Version

xx

### Database Driver & Version

8.0

### Description

<img width="884" alt="image" src="https://github.com/laravel/octane/assets/8417207/b7c0d505-36e8-4113-81fc-776daf851419">
is OK,,print tasks like this
<img width="728" alt="image" src="https://github.com/laravel/octane/assets/8417207/3dc0c260-2980-4fd7-a693-492bd08f0368">

 when i use like this 
<img width="838" alt="image" src="https://github.com/laravel/octane/assets/8417207/d1af2864-6cde-4166-acd6-54298097560c">
 and print tasks like this   and result is false
<img width="697" alt="image" src="https://github.com/laravel/octane/assets/8417207/6e231792-7860-4b72-9757-89e8761b0430">

### Steps To Reproduce

Octane::concurrently Reference ORM Model

**Comment by driesvints** [comment]
Looks like this isn't supported but it already seems like you have an easy workaround so my suggestion is to just use that 👍
