### ISSUE TITLE
`UrlGenerator` warming up issue

### ISSUE THREAD

**Issue by michael-rubel** [laravel/octane#748]
### Octane Version

2.0.6

### Laravel Version

10.23.1

### PHP Version

8.2.3

### What server type are you using?

Roadrunner

### Server Version

v2023.2.2

### Description

When using `Route::bind()` and `URL::defaults()` with Octane, it seems that `UrlGenerator` keeps the same instance of `RouteUrlGenerator`, and so the defaults are cached between requests.

#### Example use case is identifying the company context:
\
Route:
```php
Route::get('dashboard/{company}', ShowDashboardController::class)->name('dashboard');
```

Route binding:
```php
Route::bind('company', function (string $uuid) {
    $company = Company::firstWhere('uuid', $uuid);

    URL::defaults(['company' => $company->uuid]);
});
```

Now everywhere in the app, without passing the UUID each time:
```php
redirect()->route('dashboard');
```

---

#### Workarounds I found

1. To always return a new instance of `RouteUrlGenerator` in the `routeUrl()` method. This way seems to be a BC because the instance is used in other places.
2. To avoid warming of `url` service in `defaultServicesToWarm`. Not sure it would introduce a BC, but doesn't seem to be the right solution.

Note: adding `url` to the `flush` array in the `octane` config leads to the process crash.

Should it be somewhat patched on the Octane level or we can just remove the `url` from the warming process?

**Comment by nunomaduro** [comment]
I was unable to create an test that reproduces this issue. Do you mind of creating a pull request, that introduces a test that reproduces your issue please? Maybe call the test `UrlGeneratorStateTest`.

**Comment by michael-rubel** [comment]
@nunomaduro I was trying to write the test for this too, but everything is working fine in tests.
It seems that the application is loaded differently in tests than in real-world apps.

**Comment by gazzoy** [comment]
+1
