### ISSUE TITLE
Feature: Bun support

### ISSUE THREAD

**Issue by RVxLab** [laravel/octane#749]
Hi Laravel crew, would you accept a PR to add Bun support?

With Bun gaining traction and it supporting tons of Node's APIs, I feel adding Bun support may be beneficial.

The way I see this being implemented is creating a new method in [src/Commands/Concerns/InteractsWithServers](https://github.com/laravel/octane/blob/master/src/Commands/Concerns/InteractsWithServers.php) named `determineJavaScriptRuntime`, checking for `node` and `bun` in that order (to maintain backwards compatibility) or otherwise specified by the developer (`--bun` flag, config option, env variable, you name it).

This will in turn return a nullable string, this being the same signature as Symfony's [`ExecutableFinder::find`](https://github.com/symfony/symfony/blob/93afb42e99e555d3b0a30ebc214298cbbc1227ad/src/Symfony/Component/Process/ExecutableFinder.php#L51C21-L51C21) method.

In theory, no changes should be needed to the `file-watcher.cjs` script, though I would need to test that.

**Comment by driesvints** [comment]
Yeah I think if you could whip up a PR we can have a look, thanks 👍
