### ISSUE TITLE
Binding to unix sockets

### ISSUE THREAD

**Issue by artiommocrenco** [laravel/octane#754]
Nice library!

Could you please consider adding support/documentation for Unix socket binding? This could help Octane perform even better, especially when running behind a reverse proxy on the same host.

**Comment by artiommocrenco** [comment]
Additionally, support for using unix sockets between Octane and RoadRunner/Swoole may further improve Octane latency/throughput.

**Comment by driesvints** [comment]
Heya. Feel free to send in a PR so we can have a look 👍

**Comment by benascbr** [comment]
@artiommocrenco did you had any luck writing PR :) ?
