### ISSUE TITLE
Unable to read frame header: Incorrect header size

### ISSUE THREAD

**Issue by gytissakalis** [laravel/octane#756]
### Octane Version

2.0.6

### Laravel Version

10.26.2

### PHP Version

^8.2

### What server type are you using?

Roadrunner

### Server Version

2023.2.2

### Description

When kubernetes try kill pod (with default kubernetes signals) it shutdown processes not gracefully.

As far as I understand, signals being sent to `octane:start` command and underlying workers are killed forcefully (instant shutdown, it does not matter if incoming request is being processed), thus response for client (browser) is not sent (gives 502 response), and exception is thrown.

Whole stack trace:
```
#0 /workspace/application/vendor/spiral/roadrunner-worker/src/Worker.php(58): Spiral\Goridge\StreamRelay->waitFrame()
#1 /workspace/application/vendor/spiral/roadrunner-http/src/HttpWorker.php(51): Spiral\RoadRunner\Worker->waitPayload()
#2 /workspace/application/vendor/spiral/roadrunner-http/src/PSR7Worker.php(62): Spiral\RoadRunner\Http\HttpWorker->waitRequest()
#3 /workspace/application/vendor/laravel/octane/bin/roadrunner-worker(41): Spiral\RoadRunner\Http\PSR7Worker->waitRequest()
#4 /workspace/application/vendor/bin/roadrunner-worker(119): include()
#5 {main}
```

If i register sleep function on sigterm (basically blocking sigterm for giving room to finish request) it shut downs correctly

```
bootstrap/app.php


function testSigterm() {
    Log::info('testSigterm');
    sleep(15);
    Log::error("after testSigterm");
}
//

pcntl_signal(SIGTERM, 'testSigterm');

```

### Steps To Reproduce

1. Deploy octane to kubernetes
2. Make route with sleep
 ```
   Route::get('/_/ping', static function () {
    \Illuminate\Support\Facades\Log::error('ping');
    sleep(10);

    return 1;
});
```
3. ping route, and while running execute next step
4. Kill octane running pod
5. It is shut down instantly, browser gives 502 response

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
