### ISSUE TITLE
Unable to read frame header: Incorrect header size

### ISSUE THREAD

**Issue by gytissakalis** [laravel/octane#757]
### Octane Version

2.0.6

### Laravel Version

10.26.2

### PHP Version

^8.2

### What server type are you using?

Roadrunner

### Server Version

2023.2.2

### Description

Since I am using octane in kubernetes environment, a lot of errors comes through when pods are being killed of autoscaler.

Issue is still relevant, and bugging not only me.

Can you guys take a look?

https://github.com/laravel/octane/issues/756
https://github.com/laravel/octane/issues/664

### Steps To Reproduce

https://github.com/laravel/octane/issues/756
https://github.com/laravel/octane/issues/664

**Comment by gytissakalis** [comment]
Also, found out debugging with minikube that:

If I send SIGTERM directly to octane main process, it fails to handle properly request and response is broken, thus errors appear.

If I send SIGTERM to roadrunner directly, server stops correctly and pods shutdown properly

**Comment by nunomaduro** [comment]
Can you try to come up with a pull request - and understand why the `SIGTERM` on Octane's main process is not terminating properly the underlying roadrunner master process?

**Comment by gytissakalis** [comment]
I am not sure about solution, since I would need to invest a lot of time for understanding how it works. But it seems that its just because 
```\Laravel\Octane\RoadRunner\ServerProcessInspector``` just sends ```posix_kill($processId, $signal)``` without anyhow confirming that child processes actually finished. This means main process (octane:start) finishes faster than child (because main process not waiting, it just sends signal and exit). This leads to 503 error code if request is in progress

**Comment by rustatian** [comment]
Hey everyone, Roadrunner is here 👋🏻😄 
Just saw this issue. And yes, killing without waiting is the reason for this issue.

Some info:
The parent process (Octane) should use [wait4](https://linux.die.net/man/2/wait4)-like system calls (or `waitid`/`waitpid`) to wait child process. Moreover, if Octane kills RR (or basically any process) incorrectly, and then restart it – the previous one might become a [zombie](https://en.wikipedia.org/wiki/Zombie_process) if the state of the previous process wasn't read via `wait`-like system call.

So, basically, you have 2 options here:
1. Use [this](https://github.com/roadrunner-server/roadrunner/blob/master/.rr.yaml#L2205) option to set the shutdown timeout and then use `wait` system call to wait for the RR process to exit. RR will gracefully close all the incoming connections and stop workers correctly until the specified time.
2. Use sleep to wait for the number of seconds, specified in the `endure.grace_period` + 1–2 seconds. In this case, RR will stop itself after the graceful timeout is expired (or earlier). This option is hacky from my POV 😃

**Comment by driesvints** [comment]
Thanks all. Would love a PR for this.

**Comment by driesvints** [comment]
Hi all, we'd still accept a PR for this so feel free to send one in so we can continue the discussion there.
