### ISSUE TITLE
I'm facing issues when the Octane and Swoole configure with Behind AWS LoadBalancer

### ISSUE THREAD

**Issue by rahmanuk** [laravel/octane#760]
### Octane Version

* v1.5.6

### Laravel Version

8.83.27

### PHP Version

8.2

### What server type are you using?

Open Swoole

### Server Version

ubuntu22

### Database Driver & Version

mysql  aurora

### Description

Hello Team,

I'd like to seek assistance from the expert team. I have successfully configured Octane and Swoole for a single-server Ubuntu EC2 machine. However, when I attempted to set up Octane and Swoole behind a load balancer with an EFS file system for sharing data for Both EC2 machines, they were not functioning. This issue persists even after trying configurations both with and without a supervisor.

I'm seeking guidance on how to troubleshoot and resolve this problem. Any insights or suggestions would be greatly appreciated.

Thank you!
Supervisor configuration is given below

[program:octane_app]
process_name=%(program_name)s
command=sudo php /var/www/html/artisan octane:start --server=swoole --watch --max-requests=1000
autostart=true
autorestart=true
user=ubuntu
redirect_stderr=true
stdout_logfile=/tmp/octane_app.log
stopwaitsecs=3600

### Steps To Reproduce

Hello Team,

I'd like to seek assistance from the expert team. I have successfully configured Octane and Swoole for a single-server Ubuntu EC2 machine. However, when I attempted to set up Octane and Swoole behind a load balancer with an EFS file system for sharing data for Both EC2 machines, they were not functioning. This issue persists even after trying configurations both with and without a supervisor.

I'm seeking guidance on how to troubleshoot and resolve this problem. Any insights or suggestions would be greatly appreciated.

Thank you!
Supervisor configuration is given below

[program:octane_app]
process_name=%(program_name)s
command=sudo php /var/www/html/artisan octane:start --server=swoole --watch --max-requests=1000
autostart=true
autorestart=true
user=ubuntu
redirect_stderr=true
stdout_logfile=/tmp/octane_app.log
stopwaitsecs=3600

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
