### ISSUE TITLE
HTPP 425 returns as HTTP 200

### ISSUE THREAD

**Issue by anotherglitchinthematrix** [laravel/octane#767]
### Octane Version

2.1

### Laravel Version

10.10

### PHP Version

8.2.12

### What server type are you using?

Swoole

### Server Version

5.1.1

### Description

Hello, I've found this incosistency when trying to move my project to octane, I'm using **HTTP 425 Too Early** to inform the client about the setup process, it returns 425 when it's processing, 500 if it fails and 200 upon success. But for some reason, when using octane (with swoole) it returns 200 for 425, I haven't found any other misbehaving. I haven't tested yet with open-swoole or roadrunner.

### Steps To Reproduce

1. `composer create-project laravel/laravel octane-swoole-425`
2. `composer require laravel/octane`
3. `php artisan octane:install`
4. write a rest route to web.php
```php 
// routes/web.php

Route::get("test", function() {
  return response(null, 425);
});
```
5. visit http//127.0.0.1:8000/test
6. see 200 instead 425

**Comment by driesvints** [comment]
Thanks @anotherglitchinthematrix. Seems @sy-records already sent in a PR so we'll hopefully get this fixed soon.
