### ISSUE TITLE
Running empty tasks throws TaskTimeoutException

### ISSUE THREAD

**Issue by zhiyingxu** [laravel/octane#769]
### Octane Version

2.1.2

### Laravel Version

10.34.2

### PHP Version

8.3.0

### What server type are you using?

Swoole

### Server Version

5.1.1

### Description

When running empty tasks, Laravel will throw `Laravel\Octane\Exceptions\TaskTimeoutException`.

### Steps To Reproduce

```php
use Laravel\Octane\Facades\Octane;

$tasks = [];

Octane::concurrently($tasks);
```

<img width="416" alt="screenshot" src="https://github.com/laravel/octane/assets/118196628/ceef973b-de0e-4696-b043-f4f4f477cd9a">

**Comment by driesvints** [comment]
You can add a simple if statement around the concurrently task to prevent this.
