### ISSUE TITLE
Your FrankenPHP binary version may be incompatible with Octane.

### ISSUE THREAD

**Issue by riasvdv** [laravel/octane#771]
### Octane Version

2.2.0

### Laravel Version

10.37.3

### PHP Version

8.2.12

### What server type are you using?

FrankenPHP

### Server Version

1.0.1

### Description

1. The issue template didn't let me select Frankenphp as the server type.

2. When letting Octane download the Frankenphp binary on an Ubuntu server, the returned version by Frankenphp (`b2e92a673a8a5e1c285b6ef10bacc9e67651a43d`) is not `>= 1.0.0` and Octane outputs this warning:

> WARN  Your FrankenPHP binary version (b2e92a673a8a5e1c285b6ef10bacc9e67651a43d) may be incompatible with Octane.
> 
>  Should Octane download the latest FrankenPHP binary version for your operating system? (yes/no) [yes]:

This makes it so Octane cannot be started by a supervisor process, even when using non-interactive or quiet flags (the default is `yes`, which keeps re-downloading the binary)

### Steps To Reproduce

1. Install a Laravel project with Octane on an Ubuntu server
2. Run `octane:install` and choose `frankenphp`
3. Let Octane download the binary
4. Try to run `octane:start`

**Comment by nunomaduro** [comment]
Waiting for @dunglas to tag an Linux Build that displays the version like so:

```
FrankenPHP 1.0.1 PHP 8.3.0 Caddy v2.7.6 h1:w0NymbG2m9PcvKWsrXO6EEkY9Ru4FJK8uQbYcev1p3A=
```

**Comment by nunomaduro** [comment]
Fixed.

**Comment by tebbbb** [comment]
Using the latest laravel version as of today.

WARN  Your FrankenPHP binary version (1.0.3) may be incompatible with Octane.
