### ISSUE TITLE
Unable to determine the current FrankenPHP binary version \ unable to get instance ID; storage clean stamps will be incomplete

### ISSUE THREAD

**Issue by HDVinnie** [laravel/octane#774]
### Octane Version

^2.2

### Laravel Version

10.37.3

### PHP Version

8.3.0

### What server type are you using?

FrankenPHP

### Server Version

Ubuntu 22.04.1

### Database Driver & Version

MySQL 8.0.35

### Description

php artisan octane:install

 Which application server you would like to use?:
  [0] roadrunner
  [1] swoole
  [2] frankenphp
 > 2

 FrankenPHP's Octane integration is in beta and should be used with caution in production. Do you wish to continue? (yes/no) [no]:
 > yes

 Unable to locate FrankenPHP binary. Should Octane download the binary for your operating system? (yes/no) [yes]:
 > yes

 116990064/116990064 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%

   INFO  Octane installed successfully.

Then upon starting octane.

php artisan octane:start

   WARN  Unable to determine the current FrankenPHP binary version. Please report this issue: https://github.com/laravel/octane/issues/new.

   INFO  Server running…

  Local: http://127.0.0.1:8000 

  Press Ctrl+C to stop the server

   WARN  unable to get instance ID; storage clean stamps will be incomplete

### Steps To Reproduce

Install octane, select frakenphp, configure config and nginx, start octane.

**Comment by HDVinnie** [comment]
I should note that the site is accessible and does seem to be working fine regardless of the two WARN messages.

**Comment by cbpatel17** [comment]
And it's also crashing without any information

**Comment by phh** [comment]
Did the same thing today in Laravel Sail.

Also how to reproduce on a fresh install:

```
curl -s https://laravel.build/octane-frankenphp | bash
cd octane-frankenphp && ./vendor/bin/sail up -d
./vendor/bin/sail composer require laravel/octane
./vendor/bin/sail artisan octane:install --server=frankenphp

yes
yes

./vendor/bin/sail artisan octane:start
```

**Comment by binaryfire** [comment]
Hi @HDVinnie. Did this solve the `unable to get instance ID; storage clean stamps will be incomplete` part of the issue for you? I'm still seeing that on startup (as are others: https://github.com/laravel/octane/issues/810).

**Comment by HDVinnie** [comment]
> Hi @HDVinnie. Did this solve the `unable to get instance ID; storage clean stamps will be incomplete` part of the issue for you? I'm still seeing that on startup (as are others: https://github.com/laravel/octane/issues/810).
> 
> 

I uninstalled and reinstalled the new release and haven't had issues since.

**Comment by asanikovich** [comment]
The problem is related that caddy need writable access to next paths in your `$HOME` directory:
```
.config/caddy
.local
```
