### ISSUE TITLE
FrankenPHP with laravel sail

### ISSUE THREAD

**Issue by nprasath002** [laravel/octane#783]
Hi there, I am not able to set up frankenphp with my apple M1 chip.

<img width="1255" alt="Screenshot 2023-12-21 at 12 19 01 pm" src="https://github.com/laravel/octane/assets/581008/353a06c4-9d45-4103-930e-a08a78b76f33">

Is there any instructions i can follow to setup FrankenPHP in laravel sail environment?

**Comment by nunomaduro** [comment]
Asked @dunglas if we get builds compiled for Sail too.

**Comment by nunomaduro** [comment]
Dunglas just reported to me that this will be fixed beginning of next week.

**Comment by dunglas** [comment]
Related: https://github.com/dunglas/frankenphp/issues/418

**Comment by dunglas** [comment]
ARM builds are now available: https://github.com/dunglas/frankenphp/releases/tag/v1.0.2

It should be possible to close this issue.
