### ISSUE TITLE
Reopening #748: UrlGenerator warming up issue

### ISSUE THREAD

**Issue by gazzoy** [laravel/octane#784]
### Octane Version

2.2.3

### Laravel Version

10.38.1

### PHP Version

8.2.13

### What server type are you using?

Swoole

### Server Version

v2023.2.2

### Description

See #748.

In addition to that, I'm trying to reproduce this issue on the test as below but I can't. As for some reason `$app['router']->bind()` doesn't work. Could you tell me where I should change please?

```
    public function test_url_generator_creates_correct_urls_across_subsequent_with_bind()
    {
        [$app, $worker, $client] = $this->createOctaneContext([
            Request::create('/dashboard/foo', 'GET'),
            Request::create('/dashboard/bar', 'GET'),
        ]);

        $app['router']->bind('param', function (string $value)
        {
            return URL::defaults(['param' => strtoupper($value)]);
        });

        $app['router']->get('dashboard/{param}', function (Application $app)
        {
            return URL::getDefaultParameters()['param'];
        })->name('dashboard');

        $worker->run();

        $this->assertEquals('FOO', $client->responses[0]->getContent());
        $this->assertEquals('BAR', $client->responses[1]->getContent());
    }
```

### Steps To Reproduce

See #748.

**Comment by gazzoy** [comment]
> I was trying to write the test for this too, but everything is working fine in tests.
> It seems that the application is loaded differently in tests than in real-world apps.

Hi @michael-rubel, Would it be possible to you to share the test code you mentiond like above on #748 ?

Just wondering what kind of test you had as I've been stucking to reproduce the issue.

**Comment by michael-rubel** [comment]
Hi @gazzoy 

I removed the branch already. I was applying similar code as in other Octane tests, but this issue cannot be covered because of the way the instance is bootstrapped. Octane needs an integration test suite. The one that will boot the real Swoole/Roadrunner/FrankenPHP instance.

**Comment by gazzoy** [comment]
@michael-rubel Thank you! I see, seems a bit complicated to reproduce the issue then.

Actually my problem was I couldn't even write a  successful test case for this, but most likely I'm doing something wrong so will have another look at my work.

**Comment by gazzoy** [comment]
Hi @nunomaduro 

As @michael-rubel suggested, most likely we need to set up an integration test suite to reproduce this issue. However, I'm not too sure how to do it in octane repository. Do you happen to have any ideas? Using sail or testbench-dusk doesn't seem a good option.

**Comment by nunomaduro** [comment]
@gazzoy, could you confirm if the scenario described in https://github.com/laravel/octane/pull/807 is the one causing issues in your application?  Meaning that the `URL::defaults` state is being shared between requests?

**Comment by gazzoy** [comment]
Thank you @nunomaduro. Correct me if I'm wrong, but I don't believe #807 is the case I've been facing, as in my case I define `Router::bind` with calling `URL::defaults` along with `Router::get`.

To be more specific, my case is as follows. I believe the original issue https://github.com/laravel/octane/issues/748 was too:
https://github.com/gazzoy/octane/blob/fix/url-same-instance/tests/UrlGeneratorStateTest.php

The problem here is in above test both requests returns BAR and WIBBLE as expected, but in the real world Octane always returns BAR which seems `URL::defaults` keeps its state.

Please let me know if you have any questions.

**Comment by nunomaduro** [comment]
Got it! In that case, please provide an open-source repository with a fresh Laravel installation with Octane, including one or two routes that face this issue. I need something I can clone locally to reproduce your problem. Thank you for your patience with this matter. Once you've set it up, create a new issue and include the repository link and instructions.

**Comment by gazzoy** [comment]
> Got it! In that case, please provide an open-source repository with a fresh Laravel installation with Octane, including one or two routes that face this issue. I need something I can clone locally to reproduce your problem. Thank you for your patience with this matter. Once you've set it up, create a new issue and include the repository link and instructions.

No worries. Will do!
