### ISSUE TITLE
FrankenPHP crashes when Redis compression and serializer options are set

### ISSUE THREAD

**Issue by binaryfire** [laravel/octane#789]
### Octane Version

2.2.3

### Laravel Version

10.3.0

### PHP Version

8.2

### What server type are you using?

FrankenPHP

### Server Version

2.7.6

### Description

Hi @dunglas. First of all thanks for adding FrankenPHP to Octane!

The server is crashing with `Undefined constant Redis::COMPRESSION_LZ4` and `Undefined constant Redis::SERIALIZER_IGBINARY` when either of these options are used in the Redis config:

```
// database.php

    'redis' => [

        'client' => env('REDIS_CLIENT', 'phpredis'),

        'options' => [
            'cluster' => env('REDIS_CLUSTER', 'redis'),
            'prefix' => env('REDIS_PREFIX'),
            'compression' => Redis::COMPRESSION_LZ4,
            'serializer' => Redis::SERIALIZER_IGBINARY,
        ],
        //

```

Everything works fine with Swoole and Roadrunner.

### Steps To Reproduce

Use this Redis configuration in `database.php`:

```
    'redis' => [

        'client' => env('REDIS_CLIENT', 'phpredis'),

        'options' => [
            'cluster' => env('REDIS_CLUSTER', 'redis'),
            'prefix' => env('REDIS_PREFIX'),
            'compression' => Redis::COMPRESSION_LZ4,
            'serializer' => Redis::SERIALIZER_IGBINARY,
        ],
        .........
```

**Comment by dunglas** [comment]
These features seem to not be enabled by [static-php-cli](https://github.com/crazywhalecc/static-php-cli) (the tool we use to create the static PHP library embedded in the static builds for FrankenPHP)  when compiling ext-redis.

Could you open a feature request upstream?

Thank you.

**Comment by driesvints** [comment]
Thanks @dunglas.

@binaryfire feel free to open up a feature request on the library @dunglas linked to.

**Comment by binaryfire** [comment]
@driesvints Will do, but shouldn’t this stay open since it’s a confirmed bug? Octane w/
FrankenPHP currently doesn’t work properly when Redis options are set.

**Comment by driesvints** [comment]
Since this isn't a bug in Octane we won't keep this open. Feel free to attempt a PR to the docs, thanks 👍

**Comment by dunglas** [comment]
In the meantime, using a non-static build of FrankenPHP (such as the one in the Docker image) should allow to do what you want.

**Comment by binaryfire** [comment]
@dunglas Thanks for the suggestion. We use custom images so we'd need to add a fair bit of complexity to the build to add and configure Caddy (as per https://github.com/dunglas/frankenphp/blob/main/Dockerfile). It's easier for us to switch back to Swoole for now.

I've opened an issue in static-php-cli repo: https://github.com/crazywhalecc/static-php-cli/issues/293. Will test again once it's fixed.

**Comment by dunglas** [comment]
This should now work as expected: https://github.com/dunglas/frankenphp/releases/tag/v1.0.2

**Comment by binaryfire** [comment]
@dunglas Thanks! Would it be possible to add an `octane:upgrade-frankenphp` command or something similar? Currently it looks like we need to manually download the binary from GitHub to upgrade (unless I'm missing something).

**Comment by binaryfire** [comment]
Never mind, Octane does this automatically. v2.2.6 bumped the minimum FrankenPHP version to v1.0.2 👍
