### ISSUE TITLE
Laravel Octane Swoole Sync function or Sync route

### ISSUE THREAD

**Issue by mstfaslanntr** [laravel/octane#794]
### Octane Version

2.2.5

### Laravel Version

9.41.0

### PHP Version

8.1.18

### What server type are you using?

Swoole

### Server Version

2023.2.2

### Description

I am using Laravel Octane but I have a problem. I have a payment callback page, and when requests come at the same time, some payments are confirmed twice because the transactions are async. Is there a feature in Octane where I can specify a route or function so that transactions can be synchronized?

### Steps To Reproduce

I am using Laravel Octane but I have a problem. I have a payment callback page, and when requests come at the same time, some payments are confirmed twice because the transactions are async. Is there a feature in Octane where I can specify a route or function so that transactions can be synchronized?

**Comment by nunomaduro** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
