### ISSUE TITLE
Laravel Octane Swoole Sync function or Sync route

### ISSUE THREAD

**Issue by mstfaslanntr** [laravel/octane#795]
I am using Laravel Octane but I have a problem. I have a payment callback page, and when requests come at the same time, some payments are confirmed twice because the transactions are async. Is there a feature in Octane where I can specify a route or function so that transactions can be synchronized?

Closed Issue : https://github.com/laravel/octane/issues/794

Even though I searched all forums and channels, I could not find an explanation or answer on this issue. Can you help me please?

**Comment by nunomaduro** [comment]
I understand that you have searched for an explanation. However, in this case, it's better if you post the question on those forums instead.
