### ISSUE TITLE
FrakenPHP crashes randomly

### ISSUE THREAD

**Issue by abishekrsrikaanth** [laravel/octane#801]
### Octane Version

2.2.6

### Laravel Version

10.39.0

### PHP Version

8.2

### What server type are you using?

FrankenPHP

### Server Version

1.0.2

### Database Driver & Version

MySQL 8

### Description

Started using Laravel Octane with FrankenPHP on a new Laravel Project. The server keeps abruptly crashing automatically. Not quite sure why this is happening. I started using the debug parameter after going through another issue on this repo and started capturing the debug logs.

Sometimes the server crashes when I make code changes. What I have noticed is sometimes it crashes if I make changes to `.env` file or add a new file to the project. But there are times the server crashes abruptly when I am browsing the app on the browser.

Here is the recent log when I started the server and it crashed as soon as it started.

```
php artisan octane:start --port=8011 --log-level=debug --watch

{"level":"info","ts":1703863912.924263,"msg":"using provided configuration","config_file":"/Users/abisheksrikaanth/projects/client_name/v2/app_name/vendor/laravel/octane/src/Commands/stubs/Caddyfile","config_adapter":""}
{"level":"info","ts":1703863912.92533,"logger":"admin","msg":"admin endpoint started","address":"localhost:2030","enforce_origin":false,"origins":["//localhost:2030","//[::1]:2030","//127.0.0.1:2030"]}
{"level":"info","ts":1703863912.925426,"logger":"tls.cache.maintenance","msg":"started background certificate maintenance","cache":"0x14000419e80"}
```

Please let me know if you need any additional information that can help debug the issue. I will keep adding more logs here everytime the server crashes for your help.

### Steps To Reproduce

```bash
php artisan octane:start --port=8011 --log-level=debug --watch
```

**Comment by nunomaduro** [comment]
Duplicated of https://github.com/laravel/octane/issues/791.

**Comment by abishekrsrikaanth** [comment]
@nunomaduro the linked issue was only specific to high loads, thats why I created this issue. Do I report the logs on the other one?
