### ISSUE TITLE
A Question About Data Persistence

### ISSUE THREAD

**Issue by qingye5786** [laravel/octane#808]
Hello,

I have a question regarding data persistence in Laravel Octane. How long does it take for the in-memory data managed by Octane to be actually written to the database? 

I've noticed that when I use the `octane:reload` command, some in-memory data seems to be lost. However, if I use `octane:stop` followed by `octane:start`, the in-memory data is not lost. This observation has led to a concern: if I don't stop Octane, how long will it take for these data to be written to the database? What is the underlying mechanism for this process? 

Is there any specific documentation that explains how data persistence is handled in Laravel Octane?

Thank you for your assistance.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by qingye5786** [comment]
OK，thanks

**Comment by indigoram89** [comment]
> OK，thanks

Hello, did you solve this problem? Or where did you continue this discussion? Thank you!
