### ISSUE TITLE
WARN  unable to get instance ID; storage clean stamps will be incomplete, how to solve it?

### ISSUE THREAD

**Issue by fdjrr** [laravel/octane#810]
### Octane Version

2.2.7

### Laravel Version

10.40.0

### PHP Version

8.3.1

### What server type are you using?

FrankenPHP

### Server Version

1.0.3

### Description

I tried to install Laravel Octane from watching videos on the Laravel channel. Then I tried it on WSL2 but I got the error message "WARN unable to get instance ID; storage clean stamps will be incomplete". How to solve it?

### Steps To Reproduce

```bash
$ laravel new laravel
$ cd laravel
$ composer require laravel/octane
$ php artisan octane:install
$ php artisan octane:start
```

**Comment by gazzoy** [comment]
I don't think Octane has `octane:serve` option. Have you checked the docs?
https://laravel.com/docs/10.x/octane

**Comment by fdjrr** [comment]
> I don't think Octane has `octane:serve` option. Have you checked the docs? https://laravel.com/docs/10.x/octane

Sorry i mean, `octane:start`

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!

**Comment by asanikovich** [comment]
The problem is related that caddy need writable access to next paths in your `$HOME` directory:
```
.config/caddy
.local
```

**Comment by fdjrr** [comment]
> The problem is related that caddy need writable access to next paths in your user root:
> 
> ```
> .config/caddy
> .local
> ```

Thanks for the answer @asanikovich , where is the folder you mentioned? in the laravel project or in $HOME?

**Comment by asanikovich** [comment]
@fdjrr $HOME directory
