### ISSUE TITLE
Connection refused error when streaming OpenAI responses

### ISSUE THREAD

**Issue by benbjurstrom** [laravel/octane#820]
### Octane Version

2.3.0

### Laravel Version

10.41.0

### PHP Version

8.3.1

### What server type are you using?

FrankenPHP

### Server Version

FrankenPHP 1.0.3 | Caddy v2.7.6

### Database Driver & Version

N/A

### Description

Ran into an issue streaming responses with the [openai-php/client](https://github.com/openai-php/client) package. Calling the createStreamed method in a FrankenPHP Octane environment throws a connection refused error.

I've isolated it to an Octane FrankenPHP issue since streaming works fine using FrankenPHP alone. It also seems to work fine using Octane Swoole.

<img width="1127" alt="image" src="https://github.com/openai-php/client/assets/12499093/a16baa83-5ddf-42df-a6d0-e22920bdd354">

### Steps To Reproduce

I created a minimal reproduction of the issue here: https://github.com/benbjurstrom/octane-streaming-bug-report.

**Comment by benbjurstrom** [comment]
Had a chance to look at this again and confirmed it's not an issue with the openai-php package. Instead this error occurs anytime you pass the `stream => true` flag to guzzle in a FrankenPHP Octane environment.

```php
    // use GuzzleHttp\Client;

    $client = new Client();
    $response = $client->get('https://api.openai.com/v1/chat/completions', [
        'stream' => true
    ]);
```

**Comment by driesvints** [comment]
@dunglas is it okay if I assign these FrankenPHP issues to you?

**Comment by dunglas** [comment]
@driesvints Sure

**Comment by LukeAbell** [comment]
@dunglas Any update on this? We're having this issue too. We'd like to use streaming responses for our AI features and recently moved to FrankenPHP.

**Comment by dunglas** [comment]
I wonder if it's not the same issue as https://github.com/dunglas/frankenphp/issues/582?

**Comment by LukeAbell** [comment]
@dunglas Not sure but we're having another issue related to streaming that might be related. [Streaming an excel file](https://github.com/spatie/simple-excel#streaming-an-excel-file-to-the-browser) downloads an empty file. It works correctly with valet, but breaks when using frankenphp. Switching to download instead of using a stream fixes the issue.

**Comment by dunglas** [comment]
Would you be able to provide a simple/small reproducer?

**Comment by dunglas** [comment]
This is being fixed by https://github.com/dunglas/frankenphp/pull/692.

**Comment by driesvints** [comment]
Thanks @dunglas. Gonna close this already if it's a Frankenphp thing.

**Comment by niknir** [comment]
I am using this code to stream the response:


  $prompt = [
                'model' => $model,
                'messages' => [
                    ['role' => 'system', 'content' => 'You must ONLY use these component types, their variants, and their container status: Component Types List (100 total)'],
                    ['role' => 'user', 'content' => str_replace(['{conceptName}'],[$conceptName],$conceptPrompt)]
                ],
                'temperature' => (int)$temperature,
                'response_format' => [ "type" => "json_object"],
                'stream' => true,
                'stream_options' => ['include_usage' => true]
            ]

 $stream = OpenAI::chat()->createStreamed($prompt);



Still getting this error:
Connection refused for URI https://api.openai.com/v1/chat/completions
Can anyone help me out on this?

**Comment by tandasima** [comment]
Happening with Laravel AI too. Same issue as of today.
