### ISSUE TITLE
Frankenphp installation fails in no-interaction mode

### ISSUE THREAD

**Issue by hotrush** [laravel/octane#827]
### Octane Version

2.3.2

### Laravel Version

10.43.0

### PHP Version

8.3

### What server type are you using?

FrankenPHP

### Server Version

no idea, it's not installed

### Description

```
failed to solve: process "/bin/sh -c php artisan octane:install --server=frankenphp --no-interaction" did not complete successfully: exit code: 1
```

It works if remove `--no-interaction` flag.

### Steps To Reproduce

`php artisan octane:install --server=frankenphp --no-interaction`

**Comment by driesvints** [comment]
@dunglas

**Comment by brn-solutions** [comment]
I created a pull request to fix that https://github.com/laravel/octane/pull/830

**Comment by driesvints** [comment]
Thanks all
