### ISSUE TITLE
Using Swoole as the driver to install Octane for pressure testing, if the level exceeds, the entire positive sequence cannot run normally

### ISSUE THREAD

**Issue by liangguifeng** [laravel/octane#831]
![image](https://github.com/laravel/octane/assets/37197772/45a2a598-2b4c-4377-9cd7-a66fb09d842c)
![image](https://github.com/laravel/octane/assets/37197772/9429f14a-a344-40c6-bd56-7c263647cb9c)

My local machine is Mac Os Sonoma 14.1.1, The following is the complete reproduction step
`laravel new laravel-test`
`composer require laravel/octane`
`php artisan octane:install` Choose swoole driver
`php artisan octane:start`

My pressure test command is：
`wrk -c 1024 -t 8 http://127.0.0.1:8000/hello`

After the command above is executed, the actual request is very successful, and then the entire Laravel program cannot accept any request, as if it is stuck, and then start again.

The same command, I tried the Hyperf framework, it is normal. After the hyperf framework is completed, the program can still be accessed normally

**Comment by liangguifeng** [comment]
If I need me to provide a parameter to reproduce you, I am happy to provide it ~

**Comment by driesvints** [comment]
Please recreate this issue with the filled out issue template. Thanks
