### ISSUE TITLE
FrankenPHP in octane-server-state.json not showing? Is it running?

### ISSUE THREAD

**Issue by sts-ryan-holton** [laravel/octane#832]
### Octane Version

2.3.2

### Laravel Version

10.43.0

### PHP Version

8.2.15

### What server type are you using?

FrankenPHP

### Server Version

Latest (1.1.0)

### Database Driver & Version

MySQL

### Description

On my Windows 10 machine, running WSL and Docker Desktop I'm using Laravel Sail. I recently installed Octane with Swoole as per the docs and got everything up and running, I then went to install FrankenPHP as per the Octane docs which downloaded the latest binary, presumably 1.1.0 as I tried this yesterday.

### Steps To Reproduce

After changing my Octane config file and setting `OCTANE_SERVER` to **frankenphp** and setting the `--server` flag to **frankenphp** as well, rebuilding Docker with `sail build --no-cache` and launching, `octane-server-state.json` `state.octaneConfig.server` still says "swoole", what's more, there's no performance difference between Swoole and FrankenPHP, is it even running?

**Comment by driesvints** [comment]
I think you can expect things to go a bit awry when you're switching drivers like that. Try manually removing that file and letting Octane recreate it. From a fresh install this shouldn't be happening.
