### ISSUE TITLE
FrankenPHP starting server fails

### ISSUE THREAD

**Issue by smortexa** [laravel/octane#833]
### Octane Version

2.3.2

### Laravel Version

10.43.0

### PHP Version

8.3.2

### What server type are you using?

FrankenPHP

### Server Version

1.1.0

### Database Driver & Version

N/A

### Description

When attempting to start the Octane server in a containerized environment using this [Dockerfile](https://github.com/exaco/laravel-octane-dockerfile/blob/frankenphp-version/FrankenPHP.Dockerfile), the following logs are generated and, the server fails to start:

(This [Dockerfile](https://github.com/exaco/laravel-octane-dockerfile/blob/main/FrankenPHP.Dockerfile) works.)

```php
2024-02-05 12:57:35,092 INFO Set uid to user 1000 succeeded
2024-02-05 12:57:35,094 INFO supervisord started with pid 1
2024-02-05 12:57:36,097 INFO spawned: 'octane_00' with pid 28

>>>>>>>>>>>>>>>>>>>>>  WARN  Unable to determine the current FrankenPHP binary version. Please report this issue: https://github.com/laravel/octane/issues/new.

   INFO  Server running…

  Local: http://0.0.0.0:80 

  Press Ctrl+C to stop the server


 >>>>>>>>>>>>>>>>>>>>>>  INFO  /var/www/html/frankenphp: symbol lookup error: /var/www/html/frankenphp: undefined symbol: core_globals_offset
2024-02-05 12:57:36,938 WARN exited: octane_00 (exit status 127; not expected)
2024-02-05 12:57:37,942 INFO spawned: 'octane_00' with pid 35

   WARN  Unable to determine the current FrankenPHP binary version. Please report this issue: https://github.com/laravel/octane/issues/new.

   INFO  Server running…

  Local: http://0.0.0.0:80 

  Press Ctrl+C to stop the server


   INFO  /var/www/html/frankenphp: symbol lookup error: /var/www/html/frankenphp: undefined symbol: core_globals_offset
2024-02-05 12:57:38,794 WARN exited: octane_00 (exit status 127; not expected)
2024-02-05 12:57:40,798 INFO spawned: 'octane_00' with pid 60

   WARN  Unable to determine the current FrankenPHP binary version. Please report this issue: https://github.com/laravel/octane/issues/new.

   INFO  Server running…

  Local: http://0.0.0.0:80 

  Press Ctrl+C to stop the server


   INFO  /var/www/html/frankenphp: symbol lookup error: /var/www/html/frankenphp: undefined symbol: core_globals_offset
2024-02-05 12:57:41,615 WARN exited: octane_00 (exit status 127; not expected)
2024-02-05 12:57:44,621 INFO spawned: 'octane_00' with pid 76
```

### Steps To Reproduce

see exaco/laravel-octane-dockerfile#59

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
