### ISSUE TITLE
Undefined constant "LARAVEL_START" in health-up.blade

### ISSUE THREAD

**Issue by codebarista** [laravel/octane#836]
### Octane Version

v2.3.2

### Laravel Version

11.x-dev

### PHP Version

8.3.2

### What server type are you using?

FrankenPHP

### Server Version

1.1.0

### Description

Possibly a general issue, but in my test installation of the new Laravel 11 (dev), the "`health`" route throws an exception. The reason is that the constant `LARAVEL_START` is used in `health-up.blade.php`. The constant is not present, at least with `FrankenPHP`. The default artisan serve works.

https://github.com/laravel/framework/blob/fa1e70a74c202d15db8a856eca1d3d17a93350d6/src/Illuminate/Foundation/resources/health-up.blade.php#L41

### Steps To Reproduce

- install Laravel 11 (with laravel installer)
- install Octane with option frankenphp
- run php artisan octane:start
- go to http://127.0.0.1:8000/up

**Comment by driesvints** [comment]
Would appreciate a PR here!

**Comment by driesvints** [comment]
Fixed!

**Comment by codebarista** [comment]
> Would appreciate a PR here!

Sorry, you're right. We use the awesome Laravel a lot for our projects. I have now forked the repositories and will try my hand at PRs in the future. Thanks for your fix. 👍

**Comment by KLiniksentosajkt** [comment]
Good Article, thanks for sharing


Klinik Utama Sentosa merupakan salah satu klinik kesehatan yang fokus terhadap spesialis penyakit kelamin di Jakarta dengan didukung oleh peralatan medis modern dan terbaru.

 visit our website

https://kliniksentosajakarta.com

https://blog.sentosaklinik.com

https://sentosaklinik.com

https://klinikutamasentosa.net
