### ISSUE TITLE
Roadrunner upload limit setting

### ISSUE THREAD

**Issue by barisyild** [laravel/octane#837]
Roadrunner gives error "413 (payload too large)" when I try to upload a file.

Is there a section in the config where I can set this value?
If not, what is the way to increase this limit?

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by barisyild** [comment]
The original config has a 256 mb limit but octane doesn't even allow uploading 9 mb files.

https://github.com/roadrunner-server/roadrunner/blob/master/.rr.yaml#L643

**Comment by barisyild** [comment]
> Merhaba,
> 
> Raporladığınız için teşekkürler, ancak bu bir destek kanalında sorulabilecek bir soru gibi görünüyor. Lütfen bu sorun izleyiciyi hataları kitaplığın kendisiyle bildirmek için kullanın. Bu repo tarafından sağlanan işlevselliği nasıl kullanacağınız hakkında bir sorunuz varsa, aşağıdaki kanallardan birini deneyebilirsiniz:
> 
> * [Laracasts Forumları](https://laracasts.com/discuss)
> * [Laravel.io Forumları](https://laravel.io/forum)
> * [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
> * [anlaşmazlık](https://discordapp.com/invite/KxwQuKb)
> * [Larachat](https://larachat.co)
> * [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)
> 
> Ancak, bu sorun kilitlenmeyecek ve herkes hala sorununuza yönelik çözümleri tartışmakta özgür!
> 
> Teşekkürler.

Why can't this be a feature suggestion?
Swoole upload limit can be set in config.
Why not the roadrunner too?

package_max_length

https://laravel.com/docs/10.x/octane#swoole-configuration
