### ISSUE TITLE
Error PHP 8.3.3 10.46.0 Undefined constant "FTP_BINARY"

### ISSUE THREAD

**Issue by JuanObiJuan** [laravel/octane#845]
### Octane Version

2.3.4

### Laravel Version

10.10

### PHP Version

8.2.15

### What server type are you using?

FrankenPHP

### Server Version

Ubuntu 22 LTS

### Database Driver & Version

MySql

### Description

Im totally lost here, and have no idea how to dig deeper. Any help?

- The project works normally with php artisan serve
- I have a FTP disk in Laravel filesystem.php to store media files

![image](https://github.com/laravel/octane/assets/1729541/1f2b8057-2895-4269-bf14-85e4aafeb217)

![image](https://github.com/laravel/octane/assets/1729541/d13c4847-7f1e-4b79-9076-ad15f17386be)

- Is this missing binary sometihing I can isntall or build?
- Is just a constant missing?
- How can I tell frankenphp/octane to bring/update all the neccesary binaries for my project?

### Steps To Reproduce

- Create a FTP driver with Laravel
- Check that it works accesing the disk with "php artisan serve"
- install octane/frankenphp
- Serve project with octane:start
- Try to access ftp disk

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by JuanObiJuan** [comment]
Thankyou. I will do.
