### ISSUE TITLE
gmp and imagick and other extensions not loaded

### ISSUE THREAD

**Issue by Issa-projects** [laravel/octane#846]
### Octane Version

2.3.4

### Laravel Version

10.46

### PHP Version

8.3

### What server type are you using?

FrankenPHP

### Server Version

1.1.0

### Database Driver & Version

Mysql latest

### Description

I have an issue with laravel octane that i reported as an issue on frankenphp, but it may be a laravel octane issue:

https://github.com/dunglas/frankenphp/issues/623

### Steps To Reproduce

Fresh laravel app with laravel octane frankenphp. Try to call gmp_sign or any other funkctions of gmp or imagick extensions

**Comment by driesvints** [comment]
We haven't had any other reports about this so far so I doubt this is an Octane issue. Let's see what the frankenphp ticket says first.
