### ISSUE TITLE
Using Octane cause an issue with repeater fields from Laravel Nova

### ISSUE THREAD

**Issue by msucevan** [laravel/octane#847]
### Octane Version

2.3.4

### Laravel Version

10.47

### PHP Version

8.2

### What server type are you using?

Not know I'm using Laravel Vapor

### Server Version

not know

### Description

All the issue details can be found here:
https://github.com/laravel/nova-issues/issues/6229

I spent over 2 days to find out that octane was invalided my Repeater field, somehow the data are parsed differently.

To be honest, I don't have any clue at this moment if is an octane or a nova issue. 

Any help will be appreciate.

### Steps To Reproduce

Fork my repo in order to reproduce the error:
https://github.com/msucevan/nova-issue

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
