### ISSUE TITLE
Error Too few arguments to function Illuminate\Cache\CacheManager::repository()

### ISSUE THREAD

**Issue by metasanjaya** [laravel/octane#849]
### Octane Version

2.3.5

### Laravel Version

11.0

### PHP Version

8.2.14

### What server type are you using?

Swoole

### Server Version

5.1.1

### Description

Error when using Octane Cache

`Too few arguments to function Illuminate\Cache\CacheManager::repository(), 1 passed in /app/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php on line 357 and exactly 2 expected`

### Steps To Reproduce

1. Install laravel with `laravel new app`
2. Add laravel octane using  `composer require laravel/octane`
3. Install octane using `php artisan octane:install --server=swoole`
4. Add this script to web.php before view
`cache()->store('octane')->put('time', now()->format('U'));`
5. Run octane using `php artisan octane:start`
6. open http://127.0.0.1:8000

**Comment by nunomaduro** [comment]
This is fixed: https://github.com/laravel/framework/pull/50510. Can you test again?

**Comment by metasanjaya** [comment]
It works now. Thank you very much !
