### ISSUE TITLE
Undefined array key "assets"

### ISSUE THREAD

**Issue by phpmac** [laravel/octane#863]
### Octane Version

latest

### Laravel Version

11

### PHP Version

8.3

### What server type are you using?

FrankenPHP

### Server Version

latest

### Description

```
php artisan octane:install --server=frankenphp -vvv


 FrankenPHP's Octane integration is in beta and should be used with caution in production. Do you wish to continue? (yes/no) [yes]:
 > 

 Unable to locate FrankenPHP binary. Should Octane download the binary for your operating system? (yes/no) [yes]:
 > 



   ERROR  Undefined array key "assets"
```

### Steps To Reproduce

When I quickly confirm everything and cancel, and then run again it always prompts these

**Comment by sy-records** [comment]
Please check your network to the GitHub API. https://api.github.com/repos/dunglas/frankenphp/releases/latest

**Comment by phpmac** [comment]
> Please check your network to the GitHub API. https://api.github.com/repos/dunglas/frankenphp/releases/latest

是的，就是这个问题

```
{
"message": "API rate limit exceeded for 103.116.72.46. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)",
"documentation_url": "https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting"
}
```

**Comment by phpmac** [comment]
The solution is to switch ip

**Comment by driesvints** [comment]
Thanks. @sy-records sent in a PR so let's see how it goes. Thanks for the PR @sy-records!
