### ISSUE TITLE
No documentation for custom HTTP headers?

### ISSUE THREAD

**Issue by 200-0K** [laravel/octane#881]
I've been exploring options to include CORS headers for static files, but haven't had any success. During my search, I came across PR #653, where I noticed documentation within the Octane config regarding static file headers. However, it seems that this documentation was removed at some stage. I'm wondering whether this feature is deprecated or simply forgotten. Can it still be utilized? If now then what is the alternative.

I use it like this for now, and it works:
```php
'static_file_headers' => [
    '*' => [
        'Access-Control-Allow-Origin' => '*'
    ]
]
```

**Comment by driesvints** [comment]
Hi there. We wouldn't ever remove functionality in a minor/patch release just like that so if the code is still present, you can still use it. I guess Taylor doesn't wants to expose this publicly because it'd probably isn't a widely used feature.
