### ISSUE TITLE
Thread support from Swoole

### ISSUE THREAD

**Issue by ticherdev** [laravel/octane#885]
Hey! It seems Swoole will release an update with threads support soon. Laravel somehow tracks these updates, maybe there are plans to implement this in Octane?

https://wiki.swoole.com/en/#/thread/thread

**Comment by driesvints** [comment]
Hi there. Right now we don't have plans to implement this ourselves. If you want, you can always attempt a PR so we can look at some code to see how this could fit into Octane. Thanks
