### ISSUE TITLE
Swoole - Access logs for non local/testing environments

### ISSUE THREAD

**Issue by tania-pets** [laravel/octane#893]
When using `swoole` server, the access logs are logged for local/testing environments only, see [here](https://github.com/laravel/octane/blob/2.x/src/Swoole/Handlers/OnWorkerStart.php#L97), and I can't find a way to override that.

It's important to see those access logs for production environments and it would be great to have a config variable to toggle the access logs.

Thank you

**Comment by driesvints** [comment]
Thanks. It seems you already sent in a PR so let's see how it goes.

**Comment by tania-pets** [comment]
> Thanks. It seems you already sent in a PR so let's see how it goes.

@driesvints Can we reopen this one, since my pr didn't go through, but didn't get any feedback for future plans?

**Comment by driesvints** [comment]
@tania-pets it seems Taylor doesn't wants to change the behaviour for this one right now sorry so we're going to leave this one be.
