### ISSUE TITLE
Swoole Call to undefined function Laravel\Octane\Swoole\swoole_cpu_num()

### ISSUE THREAD

**Issue by matystu** [laravel/octane#90]
- Octane Version: 0.1.0
- Laravel Version: 8.36.0
- PHP Version: 8.0.3
- Database Driver & Version: Mysql 8

### Description:
Hey, just installed octane for testing and when set in octane config server to swoole, it return that `swoole_cpu_num()` function is undefined. 
![image](https://user-images.githubusercontent.com/68393567/113751302-1acd5c80-970c-11eb-8d81-a0da5ffd8bac.png)

**Comment by nuernbergerA** [comment]
Hey @matystu,

have you [installed swoole](https://www.swoole.co.uk/docs/get-started/installation)?

**Comment by matystu** [comment]
Hey @nuernbergerA, yes I have installed swoole.

**Comment by nuernbergerA** [comment]
Which version?

**Comment by Namoshek** [comment]
@matystu Please ensure the swoole extension is also configured to be loaded, e.g. using `php -m`.

**Comment by nunomaduro** [comment]
Please ensure that the `swoole` PHP extension is installed and enabled.

**Comment by matystu** [comment]
@nunomaduro yeah, It was problem with install, I've just reinstalled it and it's working fine. Thanks :-)
