### ISSUE TITLE
Some time Database Transaction Failed with Laravel Octane & swoole.

### ISSUE THREAD

**Issue by emrancu** [laravel/octane#901]
### Octane Version

^2.3

### Laravel Version

10.48

### PHP Version

8.3

### What server type are you using?

Swoole

### Server Version

latest

### Database Driver & Version

MYSQL 8

### Description

Hello,

I am running a Laravel app with a load balancer on two servers, connecting to a database on a separate server with a private IP. Occasionally, when I create a project and get redirected to the edit page, I encounter a 404 error because the project is not found in the database. This happens due to the load balancer's round-robin method, which sends the edit project request to the second server that doesn't find the project in the database.

The issue is that no data is inserted into the database, but the first server returns success and redirects to the edit page with the inserted ID. 

Thank you in advance for any help.

### Steps To Reproduce

no idea

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb) or [InertiaJS Discord](https://discord.gg/inertiajs) for Inertia questions
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
