### ISSUE TITLE
Octane cannot detect changes in code deployed with deployer

### ISSUE THREAD

**Issue by yusifk88** [laravel/octane#904]
### Octane Version

1.5.6

### Laravel Version

8.83.27

### PHP Version

8.2.11

### What server type are you using?

Open Swoole

### Server Version

1.4.2

### Database Driver & Version

MySQL 8

### Description

When code is deployed using deployer([deployer.org](https://deployer.org)) it is almost impossible to get octane to detect the changes.
this is because the current directory where the lates deployment is, is symlinked to a version number.

octane:reload does not have any effect
restarting the server does not also have any effect but it appears changes turn to reflect after some minutes(about 30minutes but it is not consistent)

### Steps To Reproduce

Make a laravel 8.2 project for a REST API
Deploy with [deployer](https://deployer.org)
Deploy a change and deploy
Reload octane and check for changes.

Please Note that deployer fixed this issue for PHP-FPM and nginx deployment but has no documentation for swoole or octane as much as i know

**Comment by crynobone** [comment]
Hey there,

Unfortunately we don't support this version of the library anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so, please open up a new issue and we'll help you out.

Thanks!
