### ISSUE TITLE
Xdebug is not working in Laravel Octane & FrankenPHP

### ISSUE THREAD

**Issue by cgranados16** [laravel/octane#905]
### Octane Version

2.4.0

### Laravel Version

11.10.0

### PHP Version

8.3.8

### What server type are you using?

FrankenPHP

### Server Version

FrankenPHP v1.2.0 PHP Caddy v2.8.4

### Description

I can't get Xdebug to work using the Frankenphp server option in Laravel Octane. 

A fresh Laravel install shows this in the`phpinfo()`:
![Screenshot 2024-06-09 at 23 37 02](https://github.com/laravel/octane/assets/18092598/44ad26aa-3953-411a-98bc-38ccde58214c)

But after following this guide to install Laravel Octane with FrankenPHP: https://laravel.com/docs/11.x/octane#server-prerequisites the Xdebug section is missing from the `phpinfo()`. It is being caused by this command in the `docker-compose.yml` file:
```zsh
SUPERVISOR_PHP_COMMAND: "/usr/bin/php -d variables_order=EGPCS /var/www/html/artisan octane:start --server=frankenphp --host=0.0.0.0 --admin-port=2019 --port=80" 
```

Removing it causes the Xdebug section to appear again but that also stops Laravel Octane from running.

I don't know if the docs are missing some information but the current latests suggests this should work out of the box. Also FrankenPHP claims to natively support Xdebug.

### Steps To Reproduce

I have created a new Laravel Sail repo using this guide https://laravel.com/docs/11.x/installation#sail-on-macos
```zsh
curl -s "https://laravel.build/example-app" | bash
cd example-app
./vendor/bin/sail up
./vendor/bin/sail artisan migrate
```

Installed Laravel Octane and FrankenPHP integration following https://laravel.com/docs/11.x/octane#server-prerequisites.
```zsh
sail up
sail composer require laravel/octane
sail artisan octane:install --server=frankenphp
```
and added the following to the `docker-compose.yml`:
```zsh
services:
  laravel.test:
    environment:
      SUPERVISOR_PHP_COMMAND: "/usr/bin/php -d variables_order=EGPCS /var/www/html/artisan octane:start --server=frankenphp --host=0.0.0.0 --admin-port=2019 --port=80" 
      XDG_CONFIG_HOME:  /var/www/html/config 
      XDG_DATA_HOME:  /var/www/html/data 
```

finally rebuild and start the container
```
docker compose down -v
 
sail build --no-cache

sail up
```

**Comment by crynobone** [comment]
https://laravel.com/docs/11.x/octane#frankenphp-via-docker

Static installation doesn't contain Xdebug: https://github.com/laravel/octane/issues/829#issuecomment-1929960004

**Comment by driesvints** [comment]
@cgranados16 did that solve your issue?

**Comment by cgranados16** [comment]
I see, so the idea is to create a Dockerfile and install the xdebug extension there. 
Thanks guys :)
