### ISSUE TITLE
CORS ERROR after server reloaded for few requests

### ISSUE THREAD

**Issue by GhostvOne** [laravel/octane#908]
### Octane Version

2.4.0

### Laravel Version

11

### PHP Version

8.3

### What server type are you using?

FrankenPHP

### Server Version

1.2.0

### Database Driver & Version

mariadb

### Description

When I'm using --watch for automaticly restart my server, i'm getting a CORS error for the first and the second request.
I'm using 1 worker on my developement environement and laravel sanctum with cors policy.

Here you can see on the preflight request, there is no cors policy causing cors error just after server restart. (response time ~300ms)
![image](https://github.com/laravel/octane/assets/798011/bd156e4d-0abe-49d6-9537-bb051ce5a075)

It's look like when the worker is not in memory yet it doesn't send cors policy. 
![image](https://github.com/laravel/octane/assets/798011/91e6eea6-b84a-4fac-bb30-a1cc63a622e9)

after 2 requests : it's fine (response time ~8ms)
![image](https://github.com/laravel/octane/assets/798011/f7da9b80-ff97-4035-8e6d-e56028eb7f70)

How is that possible ? Maybe a bug ??
Thanks for help

### Steps To Reproduce

1. Installing fresh server using octane and franken php with --watch --workers=1
2. Automatic server restart by changing a file
3. Send a preflight request. The first and the second response are not sending Cors rules (see images)

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
