### ISSUE TITLE
A way to set execution time limit for a current request

### ISSUE THREAD

**Issue by alecpl** [laravel/octane#916]
Normally I would `set_time_limit(0)` for a specific type of request, and let others be limited. However, `set_time_limit()` does not work under Octane (Swoole) and  `octane.max_execution_time` is enforced on all processes. It's done by the server and set when the server starts.

I'd like to implement this possibility, but I'd need some help with that. I've found `EnsureRequestsDontExceedMaxExecutionTime` that uses `timerTable` created in `bin/createSwooleTimerTable.php`. So, I suppose I could modify (move forward) the 'time' property in that table or introduce another column with max_execution_time. Would that work?

- How do I get 'worker_pid' from outside of Octane?
- How do I access the table from outside of Octane?
- How do I access the current worker?
- Would you be interested in a public API for that? Where would I put it?

**Comment by driesvints** [comment]
Thank you. Right now we don't have plans to contribute to this feature ourselves. Should you need help with trying to build a PR for this it's best that you try a support channel:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb) or [InertiaJS Discord](https://discord.gg/inertiajs) for Inertia questions
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)
