### ISSUE TITLE
Operation not permitted after server OOM

### ISSUE THREAD

**Issue by Pluuk** [laravel/octane#919]
### Octane Version

2.3.4

### Laravel Version

10.46.0

### PHP Version

8.2.20

### What server type are you using?

Swoole

### Server Version

5.1.1

### Description

When the server runs out of memory, swoole is restarted after a restart of the server. Swoole thinks that the process should still be active because the PID is still in the octane-server-state.json, but this process ID doesn't exist anymore. Then in line 22-24 of src/Swoole/SwooleExtension.php it tries to kill a PID which doesn't exist anymore, receives a Operation not permitted[1] error and crashes the process, which is not started anymore.

### Steps To Reproduce

1. Create a laravel octane instance.
2. Start up the server
3. Trigger an OOM error on the server
4. Try to restart the octane instance

**Comment by driesvints** [comment]
Thanks @Pluuk. Would appreciate help here in handling this gracefully. Most likely we'll need to somehow check if the PID still exists first?

**Comment by Pluuk** [comment]
Yes, but it could also be the case that the PID exists, but is not owned by octane anymore, thus we're not allowed to kill it. I'm not familiar enough with this, so I'm not able to create a PR for this unfortunately.

**Comment by paramientos** [comment]
Hey! Try `chown -R www-data:www-data .` on the root folder of Laravel if you are using Nginx as a web server

**Comment by crynobone** [comment]
Hey there,

We're closing this issue because it's inactive, already solved, old, or not relevant anymore. Feel free to open up a new issue if you're still experiencing this problem.
