### ISSUE TITLE
Laravel Nova Navigation is duplicating itself

### ISSUE THREAD

**Issue by richardkeep** [laravel/octane#92]
- Octane Version: 0.1.0
- Laravel Version: 8.36.0
- Laravel Nova 3.22.0
- PHP Version: 8.0.3
- Ubuntu 20.10

### Description:
The navigation panel gets duplicated on page refresh.

### Steps To Reproduce:
Please see the video below

https://user-images.githubusercontent.com/3874381/113756492-1d36b300-971a-11eb-81a7-63d2a811e447.mp4

**Comment by nunomaduro** [comment]
@richardkeep Can you update to Laravel Nova v3.23.0 and try again?

**Comment by richardkeep** [comment]
Let me try. I had not updated it

**Comment by taylorotwell** [comment]
@richardkeep any feedback?

**Comment by crynobone** [comment]
@richardkeep Octane compatibility with Laravel Nova does require changes made to 3.23.0, however we are experiencing a separate issue with the release itself, described in https://github.com/laravel/nova-issues/issues/3328#issuecomment-814576678

**Comment by richardkeep** [comment]
@taylorotwell I'm waiting for Laravel Nova 3.23.1 so that I can test it.

**Comment by richardkeep** [comment]
I have download the repo (3.23.0) and require it as a local repo. Everything seems to be okay now.
