### ISSUE TITLE
Frankenphp : Failed upload file size more than 2 MB

### ISSUE THREAD

**Issue by ikhsank6** [laravel/octane#926]
Octane Version: 2.2
Laravel Version: 10.10
PHP Version: 8.1
Server & Version: Frankenphp

**Description:**

i have a problem when uploading file in size >2MB failed upload. Is there a way to set the upload limit in octane?

**Comment by x8Haider** [comment]
Hi,

You may create php.ini in Laravel root with following:

```
; Maximum size of POST data that PHP will accept
post_max_size = 50M

; Maximum allowed size for uploaded files
upload_max_filesize = 50M

```

Optionally you can add any php setting:

```
; Maximum execution time of each script, in seconds
max_execution_time = 300

; Maximum amount of time each script may spend parsing request data
max_input_time = 300
```


Hope this help!

**Comment by ikhsank6** [comment]
@x8Haider  i have config ```php.ini``` following below

```
[PHP]
memory_limit=100M
post_max_size = 100M
upload_max_filesize = 100M
max_execution_time = 300
max_input_time = 300
expose_php = 0
variables_order = "EGPCS"
realpath_cache_size = 16M
realpath_cache_ttl = 360
```

and i still failed to upload

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb) or [InertiaJS Discord](https://discord.gg/inertiajs) for Inertia questions
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
