### ISSUE TITLE
Monitor octane worker status

### ISSUE THREAD

**Issue by sts-ryan-holton** [laravel/octane#929]
Hi 👋 

I'd like to suggest a new feature.

I'd like a way of being able to show the status of workers that Octane creates. `octane:status` just tells me a little about the overall status of Octane, but I'd like to know the status as to how many workers have been created with what status.

**Comment by Cluster2a** [comment]
That is a good idea. For projects running on php-fpm we use https://github.com/hipages/php-fpm_exporter to export the metrics to prometheus and scale by the amount of free workers.

We could use the information from this command to scale by worker resources.

**Comment by VincentBean** [comment]
We've done this by extending [spatie/laravel-prometheus](https://github.com/spatie/laravel-prometheus) and hooking into the events that Octane dispatches.

**Comment by driesvints** [comment]
We'd recommend a PR for any feature you want to add. Thanks

**Comment by CheesyTech** [comment]
Up
