### ISSUE TITLE
The InstallCommand currently updates the .env file but it doesn't update the .env.example

### ISSUE THREAD

**Issue by jhonatanhulse** [laravel/octane#935]
After installing Laravel Octane with the following steps:
```
composer require laravel/octane
php artisan octane:install --server=frankenphp
```
we can see that the `.env` file is changed and the following line is appended:
```bash
OCTANE_SERVER=frankenphp
```
It would be nice if the same line was appended to the `.env.example` file.

**Comment by driesvints** [comment]
There's no need for that imo.
