### ISSUE TITLE
BinaryFileResponse deleteFileAfterSend is not implemented in the Swoole Client

### ISSUE THREAD

**Issue by NiroDeveloper** [laravel/octane#940]
### Octane Version

2.5.2

### Laravel Version

11.19.0

### PHP Version

8.3

### What server type are you using?

Swoole

### Server Version

5.1.3

### Description

If you sent files via a BinaryFileResponse and call deleteFileAfterSend(), then octane will not delete the file after sending.

### Steps To Reproduce

1. Send a file via `return response()->file($tempFile)->deleteFileAfterSend();`
2. See that the file still exists after the download

**Comment by driesvints** [comment]
`deleteFileAfterSend` isn't a documented Laravel method and can't ever work with Octane because Octane uses long running requests.
