### ISSUE TITLE
Undefined constant "SWOOLE_SOCK_TCP"

### ISSUE THREAD

**Issue by IVoyt** [laravel/octane#942]
### Octane Version

2.5.3

### Laravel Version

11.20

### PHP Version

8.2.21

### What server type are you using?

Swoole

### Server Version

5.1.3

### Database Driver & Version

MySQL 8.4 (standalone, macOS)

### Description

I'm trying to start new project with laravel octane and I decided to use swoole as server.
I've successfully installed swoole extension with pecl and included it in php.ini. But for some reason it does not work in Octane. If I var_dump this particular constant in cli or anywhere in php code, I can see it's value. But in the `vendor/laravel/octane/bin/createSwooleServer.php` file the constant suddenly becomes undefined. I can't understand how is it possible...

More information in this [thread](https://github.com/swoole/swoole-src/issues/5442)

### Steps To Reproduce

```shell
pecl install swoole
php artisan octane:install
php artisan octane:start
```

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb) or [InertiaJS Discord](https://discord.gg/inertiajs) for Inertia questions
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
