### ISSUE TITLE
StartFrankenPhpCommand and StartRoadRunnerCommand should use $this->getHost() instead of $this->option('host')

### ISSUE THREAD

**Issue by jhonatanhulse** [laravel/octane#943]
In `InteractsWithServers`, a trait that is used by both `StartFrankenPhpCommand` and `StartRoadRunnerCommand`, we have the following method:

![image](https://github.com/user-attachments/assets/284a5e26-3445-421f-aad6-ec16808bdde8)

This method allow us to configure the server by using Laravel config files, environment variables or by just passing the `host` option to the command.

Currently `StartFrankenPhpCommand` and `StartRoadRunnerCommand` are not using the `$this->getHost()` method, they are accessing the option directly with `$this->option('host')`, which means we can only configure the server by passing the `host` option.

![image](https://github.com/user-attachments/assets/0dd580af-18da-41fc-bd7a-e19ae33e4228)

![image](https://github.com/user-attachments/assets/6ea671cf-2b0f-4988-905a-a88379158880)

Both commands should be using the `$this->getHost()` to give the user more flexibility.

**Comment by driesvints** [comment]
Feel free to send in a PR 👍
