### ISSUE TITLE
Log [deprecations] is not defined "laravel.EMERGENCY" error when using Laravel Octane

### ISSUE THREAD

**Issue by vincemammoliti** [laravel/octane#944]
### Octane Version

2.5.4

### Laravel Version

11.21.0

### PHP Version

8.3

### What server type are you using?

FrankenPHP

### Server Version

1.2.5

### Description

When using Laravel Octane with FrankenPHP on a new Laravel project, a "laravel.EMERGENCY" error is logged to the default laravel.log file when a deprecation warning is hit.

The error message is:
laravel.EMERGENCY: Unable to create configured logger. Using emergency logger. {"exception":"[object] (InvalidArgumentException(code: 0): Log [deprecations] is not defined. at /var/www/html/vendor/laravel/framework/src/Illuminate/Log/LogManager.php:231)

Without Laravel Octane installed, there is no such error.

### Steps To Reproduce

1. Install new Laravel project following "Sail on Linux" documented instructions:
```
curl -s "https://laravel.build/example-app" | bash
cd example-app
./vendor/bin/sail up
```

2. Force a deprecation warning, for example:
```
Route::get('/', function () {
    // Expected deprecation on "subject" being null.
    preg_match('/test/i', null);

    return view('welcome');
});
```

3. Visit http://localhost and notice no error logged to `laravel.log`.
4. Now, install Laravel Octane with FrankenPHP following documented instructions:
```
./vendor/bin/sail composer require laravel/octane
./vendor/bin/sail artisan octane:install --server=frankenphp

// Add environment variables to docker-compose.yml:
services:
  laravel.test:
    environment:
      SUPERVISOR_PHP_COMMAND: "/usr/bin/php -d variables_order=EGPCS /var/www/html/artisan octane:start --server=frankenphp --host=0.0.0.0 --admin-port=2019 --port=80" 
      XDG_CONFIG_HOME:  /var/www/html/config 
      XDG_DATA_HOME:  /var/www/html/data
```
5. Visit http://localhost and notice the `laravel.EMERGENCY` error logged to `laravel.log`.

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb) or [InertiaJS Discord](https://discord.gg/inertiajs) for Inertia questions
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!

**Comment by HDVinnie** [comment]
@driesvints this shouldnt be closed. It is a valid issue with frakenphp driver when it tries to report deprecations. It should be noted in docs that you cannot use default NULL here. https://github.com/laravel/laravel/blob/61fec7b8981c8d4dec3351574a902701f2489d3c/config/logging.php#L34-L36

@vincemammoliti if you set your `LOG_DEPRECATIONS_CHANNEL` to same as your used `LOG_CHANNEL` you will be good to go.

**Comment by vincemammoliti** [comment]
> @driesvints this shouldnt be closed. It is a valid issue with frakenphp driver when it tries to report deprecations. It should be noted in docs that you cannot use default NULL here. https://github.com/laravel/laravel/blob/61fec7b8981c8d4dec3351574a902701f2489d3c/config/logging.php#L34-L36
> 
> @vincemammoliti if you set your `LOG_DEPRECATIONS_CHANNEL` to same as your used `LOG_CHANNEL` you will be good to go.

Thanks for confirming the issue @HDVinnie. The resolution I ended up coming to was to define a log channel named `deprecations` as detailed in the Laravel docs https://laravel.com/docs/11.x/logging#logging-deprecation-warnings

**Comment by HDVinnie** [comment]
> > @driesvints this shouldnt be closed. It is a valid issue with frakenphp driver when it tries to report deprecations. It should be noted in docs that you cannot use default NULL here. https://github.com/laravel/laravel/blob/61fec7b8981c8d4dec3351574a902701f2489d3c/config/logging.php#L34-L36
> 
> > 
> 
> > @vincemammoliti if you set your `LOG_DEPRECATIONS_CHANNEL` to same as your used `LOG_CHANNEL` you will be good to go.
> 
> 
> 
> Thanks for confirming the issue @HDVinnie. The resolution I ended up coming to was to define a log channel named `deprecations` as detailed in the Laravel docs https://laravel.com/docs/11.x/logging#logging-deprecation-warnings

No worries as I ran into it myself. I do think it should still be noted in octane docs directly but just my two cents.

**Comment by FrancisMawn** [comment]
This does not seem to be related to the FrankenPHP driver as we're getting the same error using Octane + Swool.

**Comment by flightsupport** [comment]
I ran into this too with frankenphp.
Should definitely be documented.
