### ISSUE TITLE
SQL Server connection fails when serving app using octane under frankenPHP

### ISSUE THREAD

**Issue by YAZZYD** [laravel/octane#947]
### Octane Version

2.5.4

### Laravel Version

11.22.0

### PHP Version

8.3.11

### What server type are you using?

FrankenPHP

### Server Version

x.x.x.x

### Database Driver & Version

Microsoft SQL Azure (RTM) - 12.0.2000.8

### Description

When running laravel app with octane on frankenphp i got the same below error no matter how i change environment from continerd to VM.
 "message": "could not find driver (Connection: sqlsrv, SQL: (SOME QUERY) )",

Consider that all requiired php extension are installed and checked, also the app works fine when runing on php artisan:serve or serving under nginx.

when following the error stack it starts from frankenphp worker
{ "file": "/pathi/to/project/public/frankenphp-worker.php", "line": 3, "function": "require" }

### Steps To Reproduce

install octane with --server=frankenphp
configure the database to use sql server
run the octane server and send requests

**Comment by YAZZYD** [comment]
I took a look to frankenphp codebase, the build-static.sh doesn't include php extensions for sqlsrv, i guess sqlserver isn't supported yet

**Comment by spector32** [comment]
@YAZZYD You can build your own binary with Docker with all the needed extensions: https://frankenphp.dev/docs/static/

**Comment by LemiLu** [comment]
When you run Laravel in a Laravel Sail enviorment this can be a bit tricky....

**Comment by crynobone** [comment]
I believe @spector32 suggestion is there right way to go. You could also make a request from FrankenPHP project directly to cover this use case.
