### ISSUE TITLE
Fresh install with Roadrunner throws `chmod(): No such file or directory` on MacOS M1

### ISSUE THREAD

**Issue by shahlin** [laravel/octane#95]
- Octane Version: v0.1.0
- Laravel Version: 8.36.0
- PHP Version: 8.0.2
- Database Driver & Version: _No database configured_

### Description:
I'm trying to install Laravel Octane with Roadrunner. I've not had Roadrunner before. I tried installing the binaries via Octane installation helper itself. It seems to throw the following error:

```
Fatal error: Uncaught OutOfRangeException: Current architecture (arm64) may not be supported in /Users/shahlinibrahim/Projects/Test/OctaneTest/vendor/spiral/roadrunner-cli/src/Environment/Architecture/Factory.php:56
Stack trace:
#0 /Users/shahlinibrahim/Projects/Test/OctaneTest/vendor/spiral/roadrunner-cli/src/Environment/Architecture.php(33): Spiral\RoadRunner\Console\Environment\Architecture\Factory->createFromGlobals()
#1 /Users/shahlinibrahim/Projects/Test/OctaneTest/vendor/spiral/roadrunner-cli/src/Command/ArchitectureOption.php(44): Spiral\RoadRunner\Console\Environment\Architecture::createFromGlobals()
#2 /Users/shahlinibrahim/Projects/Test/OctaneTest/vendor/spiral/roadrunner-cli/src/Command/Option.php(56): Spiral\RoadRunner\Console\Command\ArchitectureOption->default()
#3 /Users/shahlinibrahim/Projects/Test/OctaneTest/vendor/spiral/roadrunner-cli/src/Command/Option.php(38): Spiral\RoadRunner\Console\Command\Option->register(Object(Spiral\RoadRunner\Console\GetBinaryCommand), 'arch', 'a')
#4 /Users/shahlinibrahim/Projects/Test/OctaneTest/vendor/spiral/roadrunner-cli/src/Command/ArchitectureOption.php(28): Spiral\RoadRunner\Console\Command\Option->__construct(Object(Spiral\RoadRunner\Console\GetBinaryCommand), 'arch', 'a')
#5 /Users/shahlinibrahim/Projects/Test/OctaneTest/vendor/spiral/roadrunner-cli/src/GetBinaryCommand.php(72): Spiral\RoadRunner\Console\Command\ArchitectureOption->__construct(Object(Spiral\RoadRunner\Console\GetBinaryCommand))
#6 /Users/shahlinibrahim/Projects/Test/OctaneTest/vendor/spiral/roadrunner-cli/bin/rr(69): Spiral\RoadRunner\Console\GetBinaryCommand->__construct()
#7 {main}
  thrown in /Users/shahlinibrahim/Projects/Test/OctaneTest/vendor/spiral/roadrunner-cli/src/Environment/Architecture/Factory.php on line 56


 ErrorException 

 chmod(): No such file or directory
```

### Steps To Reproduce:
1. Set `roadrunner` as the server in `config/octane.php`
2. Run `php artisan octane:start`
3. When it prompts you to install Roadrunner, type yes.
4. It prompts you to install the binaries, type yes.
5. Above error shows up

**Comment by Namoshek** [comment]
Have you tried running `./vendor/bin/rr get-binary` directly, to rule out an issue with the base library?

**Comment by shahlin** [comment]
> Have you tried running `./vendor/bin/rr get-binary` directly, to rule out an issue with the base library?

Same error

**Comment by taylorotwell** [comment]
Doesn't appear to be supported? Maybe follow up with RoadRunner maintainers?

**Comment by Namoshek** [comment]
Should be supported [by this issue](https://github.com/spiral/roadrunner-binary/issues/16). The [releases of `spiral/roadrunner-binary`](https://github.com/spiral/roadrunner-binary/releases) also contain a `darwin-arm64` version. Seems to be an issue with their `get-binary` command.

**Comment by shahlin** [comment]
> Should be supported [by this issue](https://github.com/spiral/roadrunner-binary/issues/16). The [releases of `spiral/roadrunner-binary`](https://github.com/spiral/roadrunner-binary/releases) also contain a `darwin-arm64` version. Seems to be an issue with their `get-binary` command.

Thanks @Namoshek, will try this!

**Comment by mugabo-shafi-danny** [comment]
updates
