### ISSUE TITLE
unlink(/app/storage/logs/octane-server-state.json): No such file or directory during kubernetes scaling

### ISSUE THREAD

**Issue by Cluster2a** [laravel/octane#950]
### Octane Version

2.5.5

### Laravel Version

11.2.0

### PHP Version

8.3

### What server type are you using?

Swoole

### Server Version

5.1.4

### Database Driver & Version

MySQL 9.0.1

### Description

We are running Laravel on swoole on a kubernetes cluster.
Depending on the load the autoscaler starts and stops additionaly instances.

Sometimes we are getting this error:
![image](https://github.com/user-attachments/assets/642aab0e-e255-4c7b-bbc8-e81a4d21cfb2)
![image](https://github.com/user-attachments/assets/f146bfe0-7a84-4d40-8012-abce2ac01bec)

We are not mounting any storage within the container - so every container should have it's own octane-server-state.json file.

### Steps To Reproduce

Currently this seems to happen randomly - especially if the application scales up and down.

**Comment by sy-records** [comment]
Is `/app/` the root directory of your project?

**Comment by crynobone** [comment]
Hey there,

We're closing this issue because it's inactive, already solved, old, or not relevant anymore. Feel free to open up a new issue if you're still experiencing this problem.
