### ISSUE TITLE
Memory Exhaustion in ConvertSwooleRequestToIlluminateRequest.php

### ISSUE THREAD

**Issue by jbidad** [laravel/octane#952]
### Octane Version

2.5.5

### Laravel Version

11.23.5

### PHP Version

8.3.11

### What server type are you using?

Swoole

### Server Version

Ubuntu 24.04 LTS

### Database Driver & Version

MySQL 8.0.31

### Description

We are experiencing a memory exhaustion issue while using Laravel Octane with the Swoole server. The error occurs when a request is processed in the `ConvertSwooleRequestToIlluminateRequest.php` file, causing a fatal error due to memory allocation limits being exceeded.

## Error Details:
The error message is as follows:

`PHP Fatal error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 84106280 bytes) in /var/www/html/vendor/laravel/octane/src/Swoole/Actions/ConvertSwooleRequestToIlluminateRequest.php on line 31`

## Additional error context:

```
{
   "message": "Allowed memory size of 268435456 bytes exhausted (tried to allocate 84106280 bytes)",
   "exception": "Symfony\\Component\\ErrorHandler\\Error\\FatalError",
   "file": "vendor/laravel/octane/src/Swoole/Actions/ConvertSwooleRequestToIlluminateRequest.php",
   "line": 31,
   "trace": []
}
```

### Steps To Reproduce

1. Configure `php.ini` Limits: Ensure that all relevant size limitations, such as `post_max_size`, `upload_max_filesize`, and `memory_limit`, are set correctly in the `cli/php.ini` configuration.
2. Adjust Swoole Settings: Following guidance from [#442](https://github.com/laravel/octane/issues/442), set the socket_buffer_size and package_max_length options in config/octane.php appropriately.
3. Running Laravel Octane with the Swoole driver.
4. Processing a specific request that involves file uploads and complex request data.
5. The server fails with a fatal memory exhaustion error during the request-to-response cycle.

**Comment by crynobone** [comment]
PR #953 has been merged
