### ISSUE TITLE
[OpenSwoole] Task handler has wrong params when enabling task coroutines

### ISSUE THREAD

**Issue by Manueljlin** [laravel/octane#955]
### Octane Version

2.5.4

### Laravel Version

11.21.0

### PHP Version

8.3.6

### What server type are you using?

Open Swoole

### Server Version

22.1.5

### Description

When setting
```php
    'swoole' => [
        'options' => [
            'task_enable_coroutine' => true
        ]
    ],
```
in a project's `config/octane.php`, the function inside `vendor/laravel/octane/bin/swoole-server > $server->on('task', fn (...))` receives a different data shape, and thus the application never instantiates correctly, resulting in an immediate (and cyclic) crash. This prints the error page to the shell over and over.

This is the data shape that it receives once the option in question is enabled (see https://github.com/openswoole/openswoole/blob/master/ide-helper/src/OpenSwoole/Server/Task.php):
```
[2024-09-25 19:44:07] development.INFO: Task: OpenSwoole\Server\Task Object
(
    [data] => octane-tick
    [dispatch_time] => 1727286247.8368
    [id] => 16
    [worker_id] => 0
    [flags] => 132
)
```
so this would fix it:
```php
$server->on('task', fn (Server $server, mixed $task) =>
    $task->data === 'octane-tick'
                  ? $workerState->worker->handleTick()
                  : $workerState->worker->handleTask($task->data)
);
```
but it would break for everyone else who doesn't explicitly enable it. 

### Steps To Reproduce

1. Create new Octane + OpenSwoole project
2. Set the config like I did in the description above
3. Run `php artisan octane:start`

**Comment by clemask** [comment]
Do not support coroutine.

**Comment by crynobone** [comment]
Yes, Laravel Octane currently doesn't support Swoole Coroutine.
