### ISSUE TITLE
Swoole: Doubled memory use of request input data

### ISSUE THREAD

**Issue by alecpl** [laravel/octane#959]
### Octane Version

2.5.6

### Laravel Version

10.48.22

### PHP Version

8.1.29

### What server type are you using?

Swoole

### Server Version

5.1.4

### Description

I noticed that octane+swoole consumes much more memory than standard `artisan serve`. For example I'm testing file uploads (using raw POST request) with files of different sizes. Results:
```
File size             | Laravel | Octane |
----------------------------------------------------------------
10 B                  |   8 MB  |  23 MB |
20 MB                 |  22 MB  |  64 MB |
50 MB                 |  53 MB  | 125 MB |
```
So, looks like with swoole the file is copied twice in memory.

### Steps To Reproduce

Create a POST route that does nothing but logs/returns `memory_get_peak_usage()` and run `curl -k --data-binary "@file" -H "Expect:" -H "Content-Type: text/plain" https://host/path/to/route`. Make the file "./file" of appropriate size.

Swoole configuration from `config/octane.php`:
```
  'swoole' => [
        'options' => [
            'log_file' => storage_path('logs/swoole_http.log'),
            'package_max_length' => env('SWOOLE_PACKAGE_MAX_LENGTH', 50 * 1024 * 1024),
            'enable_coroutine' => false,
            'send_yield' => true,
            'socket_buffer_size' => 10 * 1024 * 1024,
        ],
    ],
```

**Comment by NathanFreeman** [comment]
Hello, your meaning is that after uploading the file, there is a memory leak?

**Comment by alecpl** [comment]
I don't think it's a leak, but it is an excessive memory usage. With Octane a request needs twice as much memory as for Laravel without Octane.

I can only guess that swoole server keeps the input in memory and Laravel Request keeps another copy of the input. It should not create a copy if that's possible.

EDIT: BTW, this is not peak usage, `memory_get_usage()` returns the same values, which means it's still allocated.

**Comment by NathanFreeman** [comment]
Swoole will keeps a copy of the request data in memory, allowing you to get the raw http message through `Swoole\Http\Request->getData()`.

**Comment by NathanFreeman** [comment]
You can try setting the `upload_max_filesize` configuration. As long as the content-length header of the http message is greater than `package_max_length`, swoole will write the uploaded file content directly to a temporary file instead of keeping it in memory.

```php
  'swoole' => [
        'options' => [
            'package_max_length' => 1 * 1024 * 1024,
            'upload_max_filesize' => 5 * 1024 * 1024
        ],
    ],
```

Because `upload_max_filesize` is set to a value greater than 0, the client can upload files larger than `package_max_length` without encountering an error. When `upload_max_filesize` is not 0, Swoole will write the uploaded file, which means the request body, to disk instead of keeping it in memory. Of course, the request headers will still be transmitted in memory.

**Comment by alecpl** [comment]
Thank you. I confirm that what you suggested works with files uploaded using `multipart/form-data` method. It does not if the payload is POSTed in an unstructured request body. For this case `package_max_length` limits the input size and it is handled in memory.

**Comment by crynobone** [comment]
Hey there,

We're closing this issue because it's inactive, already solved, old, or not relevant anymore. Feel free to open up a new issue if you're still experiencing this problem.
