### ISSUE TITLE
Memory leak?

### ISSUE THREAD

**Issue by Cluster2a** [laravel/octane#963]
### Octane Version

2.5.9

### Laravel Version

11.32.0

### PHP Version

8.3

### What server type are you using?

Swoole

### Server Version

5.1.5

### Database Driver & Version

MySQL 9.1.0

### Description

Today, we noticed an increase in memory usage in our app following the latest release. The recent update included some logic adjustments and dependency updates, including Octane and the Laravel framework. We regularly update all dependencies to keep them current.

I tried to identify the source of the memory leak but couldn't pinpoint any specific changes in our logic that might be causing it.

To troubleshoot, I pulled a fresh Laravel codebase (https://github.com/laravel/laravel), added Octane, and checked the memory consumption.

```php
Route::get('/', function () {
    $memoryConsumptionInMB = memory_get_usage() / 1024 / 1024;
    $memoryPeakInMB = memory_get_peak_usage() / 1024 / 1024;
    $memoryLimitInMB = ini_get('memory_limit');
    $memoryLimitInMB = (int) $memoryLimitInMB;

    dd([
        'memory_get_usage' => $memoryConsumptionInMB,
        'memory_get_peak_usage' => $memoryPeakInMB,
        'memory_limit' => $memoryLimitInMB,
    ]);


    return view('welcome');
});
````
Request number 1:
![image](https://github.com/user-attachments/assets/c556e71a-770a-4a8c-9780-effc661a6244)

Request number 100:
![image](https://github.com/user-attachments/assets/94d03eb6-4016-4ecd-a95b-dd7f70d906bc)

Even with the standard laravel code base the memory seems to increase on every request, which seems odd to me.

I tired to downgrade to swoole 5.1.4, laravel/framework to 11.27.0 and octane 2.5.5 without any luck.

Shouldn't the memory stay the same between two calls (if the same endpoint is being called)?

edit: I now uncommented `CollectGarbage`and set `garbage` to `1`. Now the memory stays exactly the same.
Do we have an issue here, or is this happening by design?

Best - Alex

### Steps To Reproduce

- setup laravel (default)
- install octane
- run server
- call base endpoint multiple times

**Comment by crynobone** [comment]
Wouldn't `dd()` cause the worker to die and new worker need to be spawned? Would this contribute to additional memory usage?

**Comment by Cluster2a** [comment]
I just tested it with a normal response and the memory stays the same - so indeed dd() seems to have an impact.
