### ISSUE TITLE
sync_worker_exec_payload: TypeError: fwrite(): Argument #2 ($data) must be of type string, null given

### ISSUE THREAD

**Issue by 675076143** [laravel/octane#972]
### Octane Version

1.5.6

### Laravel Version

8.83.29

### PHP Version

8.1.3

### What server type are you using?

Roadrunner

### Server Version

2.12.3

### Description

Just `response()->noContent()` I will get status 500, and worker stop.

`sync_worker_exec_payload: TypeError: fwrite(): Argument #2 ($data) must be of type string, null given in vendor/laminas/laminas-diactoros/src/Stream.php:234`

This is because the use of **`declare(strict_types=1);`** in `laminas/laminas-diactoros/src/Stream.php`

So `fwrite($stream, null)` throw error.

And In `symfony/http-foundation`

When the response status is 204, the content will be set to null..😭
```php

public function isEmpty(): bool
{
    // L1259
    return \in_array($this->statusCode, [204, 304]);
}


public function prepare(Request $request): static
{
    $headers = $this->headers;
  
    if ($this->isInformational() || $this->isEmpty()) {
        // L247
        $this->setContent(null);
   }
}
```

https://github.com/symfony/http-foundation/blob/7.2/Response.php#L1259

https://github.com/symfony/http-foundation/blob/7.2/Response.php#L247

### Steps To Reproduce

```php
class ExampleController extends Controller
{
    public function index()
    {
        return response()->noContent();
    }
}
```

**Comment by 675076143** [comment]
I realized I had written it wrong.

setContent has been overwritted

https://github.com/laravel/framework/blob/11.x/src/Illuminate/Http/Response.php#L51

Maybe we can copy symfony?

https://github.com/symfony/http-foundation/blob/7.2/Response.php#L420

```php
  public function setContent($content)
  {
      // $this->original = $content;
      $this->original = $content ?? '';
 }
```

**Comment by 675076143** [comment]
Update

I also found dingo overwrite the response

'$this->original' is nullable

https://github.com/dingo/api/blob/master/src/Http/Response.php#L206

https://github.com/laravel/framework/blob/11.x/src/Illuminate/Http/ResponseTrait.php#L60

```php
public function setContent($content)
    {
        if (! empty($content) && is_object($content) && ! $this->shouldBeJson($content)) {
           $this->original = $content; // <-----nullable

            return $this;
        }

        try {
            return parent::setContent($content); // <------do $this->content = $content ?? '';
        } catch (UnexpectedValueException $exception) {
            $this->original = $content;

            return $this;
        }
    }
```

**Comment by crynobone** [comment]
I believe we should update [Illuminate/Http/Response.php#L51](https://github.com/laravel/framework/blob/11.x/src/Illuminate/Http/Response.php#L51) but you need to report the issue to `dingo/api` as we don't maintain that package.

**Comment by crynobone** [comment]
@675076143 Can you test if https://github.com/laravel/framework/pull/53872 worked for you?

**Comment by 675076143** [comment]
> @675076143 Can you test if [laravel/framework#53872](https://github.com/laravel/framework/pull/53872) worked for you?

It works 😊
