### ISSUE TITLE
FrankenPHP asset not found.

### ISSUE THREAD

**Issue by parth391** [laravel/octane#975]
### Octane Version

2.6.0

### Laravel Version

11.36.1

### PHP Version

8.4.1

### What server type are you using?

FrankenPHP

### Server Version

-

### Database Driver & Version

mysql  Ver 8.0.40-0ubuntu0.24.04.1 for Linux on x86_64 ((Ubuntu))

### Description

ubuntu version: Ubuntu 24.04.1 LTS
architecture: x86_64

### Steps To Reproduce

`php artisan octane:install`

![Screenshot from 2024-12-21 09-50-10](https://github.com/user-attachments/assets/29aca376-77e3-43d6-b60d-2483b59f440a)

**Comment by bensherred** [comment]
I started running into a similar issue yesterday as well and this appears to be more of a FrankenPHP issue. The latest release (v1.3.4) doesn’t have a `frankenphp-linux-x86_64` or `frankenphp-linux-aarch54` asset attached to it.

**Comment by pushpak1300** [comment]
Related to https://github.com/laravel/octane/pull/976 https://github.com/dunglas/frankenphp/issues/1276

**Comment by crynobone** [comment]
Thanks @pushpak1300 

Best to continue here: https://github.com/dunglas/frankenphp/issues/1276
