### ISSUE TITLE
Unable to serve static resources from a symink folder.

### ISSUE THREAD

**Issue by aftabnaveed** [laravel/octane#99]
- Octane Version: beta
- Laravel Version: 8.35.1
- PHP Version: 8.0.3

### Description:
Octane is unable to serve static resources configured through a symlink.  I have a separate node project where I keep my static resource (js & css files) I then use a symlink to reference these from the laravel's public folder
`/home/naveed/laravel/public/assets` -> `/home/naveed/ui/build/assets/`  

Octane is using `realpath` which resolves the symlink thus making it incomptible to render static resources. `http://127.0.0.1:8000/assets/main.css`  that results in a 404 Not Found.

```php
  public function canServeRequestAsStaticFile(Request $request, RequestContext $context): bool
    {
        if (! ($context->publicPath ?? false) ||
            $request->path() === '/') {
            return false;
        }

        $publicPath = $context->publicPath;

        return $this->fileIsServable(
            $publicPath,
            realpath($publicPath.'/'.$request->path()),
        );
    }
```
Removing the `realpath` solves the problem but I am not sure if it has any security implications.

**Comment by riseno** [comment]
i have the same issue with that as well.

**Comment by taylorotwell** [comment]
PRs welcome.

**Comment by ahmedash95** [comment]
I made a PR but it's really tricky to know if the file lives in a symlink or not. I'm waiting for the feedback on the PR to know how to proceed. but as a side note, this happens with Swoole only. the roadrunner would work fine (FYI @aftabnaveed)

**Comment by aftabnaveed** [comment]
@ahmedash95  I don't think dropping `realpath` is a better idea. In my opinion it needs to be handled differently. I will look into an alternate solution and let you know here.

**Comment by aftabnaveed** [comment]
@ahmedash95  `realpath` is needed to pass the `fileIsServable` check and as per php documentation:

> realpath() expands all symbolic links and resolves references to /./, /../ and extra / characters in the input path and returns the canonicalized absolute pathname.


```php
  protected function fileIsServable(string $publicPath, string $pathToFile): bool
    {
        return $pathToFile &&
               ! in_array(pathinfo($pathToFile, PATHINFO_EXTENSION), ['php', 'htaccess', 'config']) &&
               substr($pathToFile, 0, strlen($publicPath)) === $publicPath &&
               is_file($pathToFile) && filesize($pathToFile);
    }
```

Checking if a file being served is a bit tricky here,  the folder itself could be a symlink but `is_link` would return false for the file.

**Comment by ahmedash95** [comment]
> @ahmedash95 `realpath` is needed to pass the `fileIsServable` check and it is there for security. As per php documentation:
> 
> > realpath() expands all symbolic links and resolves references to /./, /../ and extra / characters in the input path and returns the canonicalized absolute pathname.
> 
> ```
>   protected function fileIsServable(string $publicPath, string $pathToFile): bool
>     {
>         return $pathToFile &&
>                ! in_array(pathinfo($pathToFile, PATHINFO_EXTENSION), ['php', 'htaccess', 'config']) &&
>                substr($pathToFile, 0, strlen($publicPath)) === $publicPath &&
>                is_file($pathToFile) && filesize($pathToFile);
>     }
> ```
> 
> Checking the file being served is a link is a bit tricky here, the folder itself could be a symlink but `is_link` would return false for the file.

I did another PR trying to tweak your cause. it would be good if you can test it with your project. Thank you!

**Comment by aftabnaveed** [comment]
@ahmedash95 I don't see any other PR except for the old one which was similar to what I originaly proposed.

**Comment by ahmedash95** [comment]
> @ahmedash95 I don't see any other PR except for the old one which was similar to what I originaly proposed. 

Weird. I see it linked but here is a link :)

https://github.com/laravel/octane/pull/144

**Comment by aftabnaveed** [comment]
@ahmedash95  This works now thanks! However, the security concern of this should be dealt with cautiously.
